### ISSUE TITLE
Can we use SFT trainer for casual language modelling or next word prediction ? 

### ISSUE THREAD

**Issue by shamanez** [huggingface/trl#1001]
I am thinking of conducting continual pre-training. Although the SFT trainer is there for fine-tuning instruction, it's fundamentally performing next-word prediction or casual language modeling. So, can I use the same trainer for the continual pre-training task? Am I missing something?

**Comment by younesbelkada** [comment]
Hi @shamanez 
In essence it should be the same thing right? SFT does next word prediction but `SFTTrainer` can take care of properly formatting the input prompts which are important for instruction fine-tuning. If you use the `SFTTrainer` as is e.g.

```python
from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("imdb", split="train")

trainer = SFTTrainer(
    "facebook/opt-350m",
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)
trainer.train()
```

It should lead to the same behaviour as training a model for next word prediction

**Comment by shamanez** [comment]
@younesbelkada  Thanks ! Exactly this is what I was thinking as well :).

**Comment by younesbelkada** [comment]
Awesome @shamanez , thanks a lot !

**Comment by abhishek-bairagi** [comment]
@shamanez ,did it work. what was your experience with it
