### ISSUE TITLE
[Doc Bugs] `min_length` in generation strategies

### ISSUE THREAD

**Issue by halfrot** [huggingface/trl#1002]
https://github.com/huggingface/trl/blob/28bdb6a3736b09f8bad7961f16852d052c74ae04/docs/source/how_to_train.md?plain=1#L32
I think it should be the opposite? **Low** log prob for EOS token and **high** log probs for others until min_length is reached

**Comment by younesbelkada** [comment]
I think that you are right, would you be happy to address the fix through a PR? 🙏 
cc @lvwerra @vwxyzjn in case I am mistaken

**Comment by halfrot** [comment]
#1003 just opened a pr here

**Comment by younesbelkada** [comment]
Thanks! Requested other TRL maintainers for review 🙏

**Comment by lvwerra** [comment]
no this is correct: the EOS token is ignored during decoding with the `min_length` kwarg, so the model can concentrate all probability distribution on that token and it still won't be chosen. thus all other tokens have a very low probability and when compared to the reference model you will get negative KL-div.
