### ISSUE TITLE
Guidance on how to fix the scheduler and ConstantLengthDataset

### ISSUE THREAD

**Issue by tcapelle** [huggingface/trl#1004]
Hello,

I want to fix the issue related to the `ConstantLengthDataset` not knowing the dataset's length in advance.

Besides having a broken progressbar and a wrong epoch count, the only problem I see is related to the scheduler, as most of us are training using cosine with warmup; if we want a complete cycle, the scheduler needs the total number of steps to adjust the ratios accordingly.

One solution would be to "guess" how many batches/iteration of packed data we will see by grabbing some samples and estimating the total length. A function tries to do something like this by computing a char/tok ratio.

Do you have any advice so I can draft a PR?

Ohh I just saw that @lvwerra has a [PR](https://github.com/huggingface/trl/pull/979) in the works, but only for "finite" dataset.

**Comment by lvwerra** [comment]
Yes, I think if you don't precompute there is no way to really know unfortunately. If feel an approximation will also not be a great user experience as it can still be off.

**Comment by tcapelle** [comment]
I think so, anyway, then direction on doing stuff like:
```python
TOTAL_PACKED_SAMPLES = 10_000
batch_size = 16
gradient_accumulation_steps = 2
num_train_epochs = 3
total_num_steps = num_train_epochs * TOTAL_PACKED_SAMPLES // (batch_size * gradient_accumulation_steps)
config.eval_steps = total_num_steps // num_train_epochs
```
I perform this before instantiating the Trainer these days...

**Comment by younesbelkada** [comment]
Per my understanding the issue should be fixed by this PR: https://github.com/huggingface/trl/pull/1027

**Comment by tcapelle** [comment]
do you think that API change being merged?

**Comment by younesbelkada** [comment]
Should be fixed by https://github.com/huggingface/trl/pull/979
Can you try to install TRL from source?
