### ISSUE TITLE
State definition in PPOTrainer

### ISSUE THREAD

**Issue by harrison4ride** [huggingface/trl#1009]
From my understanding, reinforcement learning needs to define state, agent, and reward. In PPOTrainer, it's easy to understand the agent is a reward model, and the reward is computed scores. But I didn't see where it defines the state. In PPOtrainer.step, it takes three inputs(query_tensors, response_tensors, rewards), is the query_tensors a state? and if I want to define my own state, how should I use ppotrainer?

**Comment by harrison4ride** [comment]
I am using generated text as test cases for another program, and I can get a bitmap indicating the code coverage. I want to use that bitmap as the state. Does it make sense? and how should I modify it?

**Comment by lvwerra** [comment]
It sounds like the bitmap is more like extra information that's already encoded in the generated text. The state has to be the thing that goes into the model when the action/tokens are generated. Maybe you want to rather encode it in the reward?

**Comment by harrison4ride** [comment]
Yes. So one solution can be vectorize that bitmap and use tokenizer to encode it?

**Comment by lvwerra** [comment]
Sure, that could work, assuming you use that information also for generation.
