### ISSUE TITLE
DPO: Multi-GPU training does not start, but works on single GPU

### ISSUE THREAD

**Issue by AndersGiovanni** [huggingface/trl#1011]
I have a DPO training script very similar to [`stack_llama_2/scripts/dpo_llama2.py`](https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py). The script works perfectly fine when I run on a single A100 GPU. However, when I use 2 A100, the script is just stuck in 0'th iteration of the training and does not continue. 

```bash
  0%|          | 0/11264 [00:00<?, ?it/s]
```

My model and reference model are defined like this:
```python
model = AutoPeftModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float32,
        load_in_4bit=True,
        is_trainable=True,
        device_map={"": Accelerator().local_process_index},
    )

model_ref = AutoPeftModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float32,
        load_in_4bit=True,
        device_map={"": Accelerator().local_process_index},
    )
```

My `accelerate config` is like this:
```bash
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

The versions of `trl`, `peft`, `transformers`, and `accelerate` are:
```bash
transformers==4.34.0
peft==0.5.0
trl==0.7.2
accelerate==0.22.0
```

My issues is sort of a mix of #151, #226 and #958. 

Anyone who could help me out here?

Thanks!

**Comment by younesbelkada** [comment]
cc @kashif

**Comment by AndersGiovanni** [comment]
I guess with merging #885 this issue can be closed. Thanks @kashif @lvwerra @younesbelkada @lewtun 😊🙌🏼
