### ISSUE TITLE
model produces multiple responses in one after training with conservation datasets using sft

### ISSUE THREAD

**Issue by kangqi-ni** [huggingface/trl#1015]
I am using sft trainer to fine-tune mistral 7b on a multi-round conversation dataset. 

I format the conversation as such:
###Human: ...
###Assistant: ...
###Human: ...
###Assistant: ...

Within the prompt, I ask the model to produce the results in a json format: { key:value }

However, after training, the model would produce multiple { key:value } within a single response. Each instance of value 
would be slightly different.

I am not sure what the issue issue is. Does anyone have a solution?

**Comment by lvwerra** [comment]
It's a bit hard to know without seeing the dataset. Is it possible that maybe the EOS tokens are missing during training and thus the model keeps on generating?

**Comment by younesbelkada** [comment]
That is most likely the issue, you can mitigate that by making sure the EOS token is different from the PAD token. Before training you can do `tokenizer.pad_token = tokenizer.unk_token` and make sure the values of `tokenizer.pad_token` is different from `tokenizer.eos_token`
