### ISSUE TITLE
Model Performance Degradation When Training Llama-2-7b-chat-hf with DPO on Anthropic Dataset

### ISSUE THREAD

**Issue by IkhlasAlhussien** [huggingface/trl#1023]
Hello,

I am currently facing a challenge while training a **fine-tuned** `NousResearch/Llama-2-7b-chat-hf` model using the (DPO) method.  The training dataset I'm utilizing is the https://huggingface.co/datasets/Anthropic/hh-rlhf, and the script I'm using is from the Hugging Face TRL repository examples: [dpo_llama2.py](https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py).

```
Training Arguments:
{
    "beta": 0.5, // Also tried with 0.1
    "learning_rate": 0.0005,
    "lr_scheduler_type": "cosine",
    "warmup_steps": 100,
    "weight_decay": 0.05,
    "optimizer_type": "paged_adamw_32bit",
    "per_device_train_batch_size": 1,
    "per_device_eval_batch_size": 1,
    "gradient_accumulation_steps": 16,
    "gradient_checkpointing": true,
    "lora_alpha": 32,
    "lora_dropout": 0.05,
    "lora_r": 16,
    "max_prompt_length": 512,
    "max_length": 1536,
    "num_train_epochs": 2,
    "logging_steps": 10,
    "ignore_bias_buffers": false
}
```

**Issue:**
Before the DPO training,  the fine-tuned model is out-performing the base `NousResearch/Llama-2-7b-chat-hf` on the alpaca_eval dataset.
After training, contrary to expectations, the model's performance deteriorates instead of improving. This is perplexing as I anticipated an enhancement in performance post-training.

**Questions and Assistance Needed:**

1. What could be causing the degradation in model performance?
2. Are there any specific parameters or configurations in the training setup that might be contributing to this issue?
3. Is there any additional information or diagnostic data that would be helpful to share for troubleshooting this problem?

Any insights or suggestions would be greatly appreciated.

**Comment by lvwerra** [comment]
From what I heard is the HH dataset not super high quality, but I defer to @lewtun and @edbeeching who did a lot of experiments with the DPO and different datasets.

**Comment by zztMermory** [comment]
I also met the situation when using dpo based llama2-13b-SFT.
![ME1701867806393](https://github.com/huggingface/trl/assets/49942637/1c80d28a-3775-40a7-97c7-ccf1ec7dd496)

**Comment by zztMermory** [comment]
why endless repetitions？
