### ISSUE TITLE
gradient clipping V.S. max_grad_norm

### ISSUE THREAD

**Issue by lzy37ld** [huggingface/trl#1026]
I notice that there is a parameter max_grad_norm in PPOConfig
Also there is a potential parameter in accelerate config named gradient_clipping.

So should I use the same value for both or not?

Best regards.

**Comment by lzy37ld** [comment]
Any clarification here?

**Comment by vwxyzjn** [comment]
https://github.com/huggingface/trl/blob/23bf9d4b58bd7640f2f2964bc2638a8afa02a21e/trl/trainer/ppo_trainer.py#L1065 you should use the `max_grad_norm in PPOConfig`

https://huggingface.co/docs/accelerate/v0.25.0/en/package_reference/accelerator#accelerate.Accelerator.clip_grad_norm_
