### ISSUE TITLE
In DataCollatorForCompletionOnlyLM Does it include an issue?

### ISSUE THREAD

**Issue by zhaoxjmail** [huggingface/trl#1028]
IN class DataCollatorForCompletionOnlyLM method torch_call()  row 145:
batch["labels"][i, start:end] = self.ignore_index

Why  batch["labels"][i, start:end]  instead of  batch["labels"][i][start:end]?

trl version:v0.5.0

**Comment by lvwerra** [comment]
Because `batch["labels"]` is a tensor/array so we can slice across two dimensions simultaneously :)

**Comment by zhaoxjmail** [comment]
I see ,thank you!
