### ISSUE TITLE
Default value for compute_metrics in SFTTrainer

### ISSUE THREAD

**Issue by albertauyeung** [huggingface/trl#1030]
The docstring says:
```
compute_metrics (`Callable[[transformers.EvalPrediction], Dict]`, *optional* defaults to `compute_accuracy`):
```
in https://github.com/huggingface/trl/blob/3719f7a92901afc2b6b82b8016119a99ee58b031/trl/trainer/sft_trainer.py#L74.
However, it seems that if nothing is provided for this argument, no metric computing function will be used. So it seems the description is not correct here. Is my understanding correct?
Thanks.

**Comment by younesbelkada** [comment]
hi @albertauyeung 
Correct, thanks for noticing ! Would you be happy opening a PR to fix it?

**Comment by albertauyeung** [comment]
@younesbelkada Thanks for your reply.
Yes, just created a simple PR for this: https://github.com/huggingface/trl/pull/1062
