### ISSUE TITLE
Example for finetuning a trained controlnet model by using dpo with human feedback data?

### ISSUE THREAD

**Issue by universewill** [huggingface/trl#1040]
Hi, i have a trained controlnet model to generate images，︀and i want to finetune the model with human feedback data by using DPO

How to do that with trl?

**Comment by lvwerra** [comment]
Hi there, currently we only have DDPO integrated in TRL for images, unfortunately DPO is not integrated, yet.

**Comment by universewill** [comment]
> Hi there, currently we only have DDPO integrated in TRL for images, unfortunately DPO is not integrated, yet.

Is there any plan for that?

**Comment by lvwerra** [comment]
Yes, we are looking into it! cc @kashif @sayakpaul
