### ISSUE TITLE
Does DPOTrainer loss mask the prompts?

### ISSUE THREAD

**Issue by tokestermw** [huggingface/trl#1041]
Hi quick question, so DataCollatorForCompletionOnlyLM will train only on the responses by loss masking the prompts.

Does it work this way with DPOTrainer (DPODataCollatorWithPadding) as well? Looking at the code, it does look like it trains on the prompts. But maybe it doesn't matter with the DPO loss.

The reason I ask is my dataset has long prompts, but short responses. And the resulting model trained by DPO is barely different from the reference model (even with accuracy 90+%). So loss masking the prompts may help focus the learning, just a guess.

Thanks!

**Comment by rpowalski** [comment]
I am having the same problem with the DPO training not improving the baseline model

Nevertheless, DPODataCollatorWithPadding seems to put an ignore index for label indexes corresponding to prompt so probably the reason is elsewhere
Here is the relevant piece of code that does that:
https://github.com/huggingface/trl/blob/baa8f09cb35057c03b33d898f90c7e8ff958ed9b/trl/trainer/utils.py#L384

**Comment by tokestermw** [comment]
ah thanks! @rpowalski

**Comment by sadaisystems** [comment]
Gentlemen, If I understood your discussion correctly, DPOTrainer does in fact mask out the prompt tokens by default? Were you able to figure out why your models didnot improve? 

@rpowalski @tokestermw

**Comment by A-Mahla** [comment]
> I am having the same problem with the DPO training not improving the baseline model
> 
> Nevertheless, DPODataCollatorWithPadding seems to put an ignore index for label indexes corresponding to prompt so probably the reason is elsewhere Here is the relevant piece of code that does that:
> 
> https://github.com/huggingface/trl/blob/baa8f09cb35057c03b33d898f90c7e8ff958ed9b/trl/trainer/utils.py#L384

The code mentioned in the comment is not in the main branch. In fact, the [DPODataCollatorWithPadding](https://github.com/huggingface/trl/blob/2d244f8acb204cb2ddb83a4ef017ca4b1f2d366a/trl/trainer/utils.py#L340) from the main branch does not assign an ignore index for label indices corresponding to the prompt. Can this commit be included in the next release?

**Comment by A-Mahla** [comment]
> I am having the same problem with the DPO training not improving the baseline model
> 
> Nevertheless, DPODataCollatorWithPadding seems to put an ignore index for label indexes corresponding to prompt so probably the reason is elsewhere Here is the relevant piece of code that does that:
> 
> https://github.com/huggingface/trl/blob/baa8f09cb35057c03b33d898f90c7e8ff958ed9b/trl/trainer/utils.py#L384

The code referenced in this comment does not appear in the latest [release](https://github.com/huggingface/trl/releases/tag/v0.9.4). Specifically, the [DPODataCollatorWithPadding](https://github.com/huggingface/trl/blob/974b0d380f12c357b70265c5f2dd2c8cb39a6a3e/trl/trainer/utils.py#L340) from the main branch **does not assign an ignore index for label indices corresponding to the prompt.** Could this commit be included in the upcoming release?

**Comment by shansiliu95** [comment]
https://github.com/huggingface/trl/blob/b6a084c46e17ad3439557b2c75703671eb4db151/trl/trainer/dpo_trainer.py#L1138

**Comment by HERIUN** [comment]
https://github.com/huggingface/trl/blob/d625c5533a6b1c84d3565c8080857f6bb81c538a/trl/trainer/dpo_trainer.py#L1145-L1149
