### ISSUE TITLE
Deprecated option `optimize_cuda_cache` warning on import of trl

### ISSUE THREAD

**Issue by ChanderG** [huggingface/trl#1044]
When you just import trl, we get the following warning:
```
$ python3
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trl
/opt/conda/lib/python3.10/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
```

Unless this is left on purpose, I believe that this line https://github.com/huggingface/trl/blob/main/trl/trainer/ppo_config.py#L107, should be changed from:
```
optimize_cuda_cache: bool = False
```
to:
```
optimize_cuda_cache: Optional[bool] = None
```
to get rid of the warning.

I can open a PR if this warning is not needed on default config creation.

**Comment by lvwerra** [comment]
Indeed, that's correct! A PR would be great, thank you!
