### ISSUE TITLE
the issues in dpo_trainer.py

### ISSUE THREAD

**Issue by Moyhub** [huggingface/trl#1068]
In the dpo_llama2.py I explored the differences between two loading methods.  AutoModelForCausalLM and AutoPeftModelForCausalLM, 
<img width="251" alt="image" src="https://github.com/huggingface/trl/assets/44131880/4608a59d-d3a2-419a-9600-6c50a67ee437">
I found the following error when loading using the first method.
<img width="627" alt="image" src="https://github.com/huggingface/trl/assets/44131880/70c7b616-17b2-4b68-9f3d-a03e60649595">

I think it is the first loading method（AutoModelForCausalLM ）. When recording the Lora model, the model obtained contains the Lora structure (which I have verified). In dpo_trainer.py, the  get_peft_model function will be called again.

**Comment by Moyhub** [comment]
![image](https://github.com/huggingface/trl/assets/44131880/6c279928-ea3d-4cc6-93fc-e32c1fb71780)

**Comment by lvwerra** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi @Moyhub 
Thanks for the issue, I think i did not 100% get the problem, can you please elaborate again? 🙏
