### ISSUE TITLE
Model Performance Degradation When Training Llama-2-13b-chat-hf with DPO +  deepspeed stage3

### ISSUE THREAD

**Issue by zztMermory** [huggingface/trl#1069]

**Comment by zztMermory** [comment]
Hello, did you meet model Performance Degradation When Training Llama-2-13b-chat-hf with DPO +  deepspeed stage3?
I can fintune with Lora.
But using deepspeed stage3 , model performance degrades. 
![Screenshot from 2023-12-07 20-21-29](https://github.com/huggingface/trl/assets/49942637/3bdf3afb-af8b-4a92-a366-a0725aa3b36e)

**Comment by lvwerra** [comment]
Could you provide a reproducible example and maybe some logs so we can track down the issue? cc @kashif
