### ISSUE TITLE
PPO for conversation datasets

### ISSUE THREAD

**Issue by Reason-Wang** [huggingface/trl#1102]
It seems that all the examples used alpaca-like datasets, where the actor model are given an instruction and generate a response. However, I want to know if there is a way to do PPO in ShareGPT-like conversational datasets, where the actor is updated based on assistant's response (assume we know the reward of each assistant's response). Should I do some masking to mask all user's content.

**Comment by younesbelkada** [comment]
I am not sure custom masks are supported for PPO, only full padding right / left are support if I am not mistaken, meaning this would be currently not possible to do with PPOTrainer cc @lvwerra

**Comment by lvwerra** [comment]
Yes masking is supported since the addition of #424. Note that it is even necessary as training on tokens that don't come from the model distribution can have severe side effects!
