### ISSUE TITLE
reward model training output file

### ISSUE THREAD

**Issue by ycYiwei** [huggingface/trl#1105]
What is the output file after training a reward model and how do I test the performance of a trained reward model or use it in PPO? Thanks for answering!

**Comment by younesbelkada** [comment]
Hi @ycYiwei 
After training a RM, you should get a full standalone transformers model or PEFT adapters (in case you used PEFT). The performance of your RM can be only tested through the testing set of the dataset you used for training your RM, and empirically across your experiences you will do with PPO + that RM
