### ISSUE TITLE
Difference between RewardTrainer and DPOTrainer? when to use each over the other?

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/trl#1106]
What is the difference between RewardTrainer and DPOTrainer? when to use each over the other?

**Comment by lvwerra** [comment]
They serve completely different purposes:
- The RewardTrainer is trained on preference data and can then be used e.g. as a reward signal to train a model using PPO
- The DPOTrainer directly optimized the model on preference data without the need for a reward model and PPO

Hope this helps.

**Comment by pradeepdev-1995** [comment]
but in both trainers, we are passing the accepted and rejected data pairs. so both using RL right?

**Comment by lvwerra** [comment]
No the RewardModel is just a classifier, so it does not generate text, whereas the DPOTrainer directly trains the language model.

**Comment by pradeepdev-1995** [comment]
@lvwerra
In the official huggingface documentation
The rewardtrainer dataset is given as below

https://huggingface.co/datasets/Anthropic/hh-rlhf?row=8

Its a text generation dataset rather than a classification dataset.

**Comment by lvwerra** [comment]
It is a preference dataset with chosen and rejected samples. The RewardModel is trained to _classify_ the samples into these two classes.
