### ISSUE TITLE
Does the hidden states need detached when training a LLama ?

### ISSUE THREAD

**Issue by wangxg666** [huggingface/trl#1108]
https://github.com/huggingface/trl/blob/d708ec272f292ded00a4d0f14b5bd214741b87f3/trl/models/modeling_value_head.py#L50C40-L50C40

If not detached from the Llama, the Critic will seriously affect the generation when the first PPO step that the pg_loss is nearly zero.

**Comment by lvwerra** [comment]
We haven't observed any issues thus far, but if you have some experiments showing performance degradation we would be happy to consider adding it as an option.
