### ISSUE TITLE
Cannot save models in ppo.py when using deepspeed

### ISSUE THREAD

**Issue by viethoangtranduong** [huggingface/trl#1121]
Script: 

```
accelerate launch --config_file examples/accelerate_configs/deepspeed_zero2.yaml scripts/ppo_with_save_cmd.py --ppo_config.exp_name ppo_v1 --ppo_config.batch_size 32  --ppo_config.mini_batch_size 8 --ppo_config.log_with wandb --ppo_config.model_name models/zephyr-7b-sft-full --ppo_config.reward_model none:none
```

However, **I cannot find ways to safely save the model at certain checkpoints/ after some epochs/ at the end** in `ppo.py`.

The file does not provide a direct way to save models after certain epochs, so I manually try to save the model. 

When I added either `ppo_trainer._save_pretrained(path_name)` or `ppo_trainer.save_pretrained(path_name)` to save the model (at the end of the file or after X epoch), it seemed to save only a subset of layers. For instance, the output indicates that shared tensors like 'model.layers.9.mlp.up_proj.weight', 'model.layers.10.post_attention_layernorm.weight', and several others are removed during the save process. The message displayed is:

```
Removed shared tensor {'model.layers.9.mlp.up_proj.weight' .... q_proj.weight', 'model.layers.10.post_attention_layernorm.weight', 'model.layers.24.mlp.down_proj.weight', 'model.layers.1.self_attn.k_proj.weight', 'model.layers.4.self_attn.q_proj.weight', 'model.layers.13.mlp.up_proj.weight'} while saving. This should be OK, but check by verifying that you don't receive any warning while reloading
```

Subsequently, when I attempt to reload that saved model using `AutoModelForCausalLM.from_pretrained`, it results in a warning message:

```
Some weights of MistralForCausalLM were not initialized from the model checkpoint at my_save_path and are newly initialized [those layers above]
```

This suggests that the model is not being saved correctly. And the generation, is of course, very bad (like the newly initialized weights are random). Could you provide any guidance on how to ensure the entire model is saved and can be properly reloaded? My code for saving the model to a local directory is as straightforward as the commands mentioned above.

The accelerate script I ran is exactly like the above, and I modified `examples/accelerate_configs/deepspeed_zero2.yaml` to be compatible with 4 GPUs instead of the default 8. I'm running on 4xA100 80GB. I modified `ppo.py` to save `ppo_traianer` after `X` epochs.  I tried both saving at every GPU or conditioning to only save `ppo_trainer` if `device==0`, and neither of them worked.

Thank you for your guidance.

```
transformers.__version__, accelerate.__version__, deepspeed.__version__
>> ('4.35.1', '0.24.1', '0.12.5')
```

Also tried with 4.36.0, 4.34.0, 4.35.0, none works.

Thank you! 

Once someone can help me, happy to put up a PR to add to existing codes (in case others need this)!
Thank you!

**Comment by lvwerra** [comment]
Maybe @vwxyzjn or @lewtun can help who used DeepSpeed quite a bit for training Mistral models.

**Comment by lewtun** [comment]
Hello @viethoangtranduong can you share the code snippet you're using to save the model? One thing to be aware of is to save the model on the main process (assuming you have a shared disk), e.g. with something like:

```python
if accelerator.is_main_process:
    ppo_trainer.save_pretrained("my-ppo-model")
```

**Comment by viethoangtranduong** [comment]
Hi @lewtun 
At the end of each epoch, I did: (I attach at the end of [ppo.py](https://github.com/huggingface/trl/blob/main/examples/scripts/ppo.py))
```
if args.save_freq and epoch % args.save_freq == 0:
        if ppo_trainer.accelerator.is_main_process:
            ppo_trainer.save_pretrained("models_ppo/" + args.ppo_config.exp_name + f"_step_{epoch}")
            print(f"Saved checkpoint at epoch {epoch}.")
```

It does save the model, but the `.bin` file is very small - i.e., it doesn't seem to save the whole model

The command I ran was 
```
accelerate launch  --config_file recipes/accelerate_configs/deepspeed_zero3.yaml scripts/my_ppo.py --ppo_config.exp_name ppo_model_v1 --ppo_config.batch_size 16  --ppo_config.mini_batch_size 4 --ppo_config.model_name models/zephyr-7b-sft-full --ppo_config.gradient_accumulation_steps 4
```

I am running on 4xA100 GPUs.

The code runs and does everything properly (including `ppo_trainer.step`), and only the save_pretrained is not saving the full model.

Thank you!
