### ISSUE TITLE
SFT - AutoGPTQ Quantization Issues

### ISSUE THREAD

**Issue by ChrisCates** [huggingface/trl#1138]
Hello HuggingFace friends,

I've been dealing with some difficult to debug quantization issues with AutoGPTQ Quantization.
The vanilla base model quantizes perfectly fine with AutoGPTQ scripts.

However, when I run SFT using the TRL SFT script. I get a `lingalg.cholesky` error.

You will notice that on the AutoGPTQ Github, there are several related issues related to this error. Unfortunately, with the TRL trained model. Upping `damp_percent` and `group_size` or `desc_act` had no impact on quantization. With or without `triton`.

The following is the error I experience while running AutoGPTQ quantization. Hopefully you guys could give some feedback:

```console
Traceback (most recent call last):
  File "/root/my-model/workflow/process/gptq.py", line 55, in <module>
    converter(model_path, output_path)
  File "/root/my-model/workflow/process/gptq.py", line 25, in converter
    model.quantize(examples)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/modeling/_base.py", line 368, in quantize
    scale, zero, g_idx = gptq[name].fasterquant(
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/quantization/gptq.py", line 110, in fasterquant
    H = torch.linalg.cholesky(H)
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 1 is not positive-definite).
```

**Comment by ChrisCates** [comment]
Okay, figured it out.
You need to update the SFT example script a bit.

### Update to feed Tokenizer into `SFT Training`

```python
tokenizer = AutoTokenizer.from_pretrained(script_args.model_name, use_fast=True)

# Step 5: Define the Trainer
trainer = SFTTrainer(
    model=model,
    args=training_args,
    max_seq_length=script_args.seq_length,
    train_dataset=dataset,
    dataset_text_field=script_args.dataset_text_field,
    peft_config=peft_config,
    tokenizer=tokenizer
)
...

### Lower Gradient Accumulation Steps

Set it to 4 when running SFT.

Hope this helps future people who have issues.

**Comment by younesbelkada** [comment]
Nice finding @ChrisCates would you be happy to point that out in the documentation? 🙏

**Comment by ChrisCates** [comment]
@younesbelkada, I've added the fix in the PR mentioned above.
A few things that may helpful.

1. For the example scripts. We should create shell scripts for people to run and test SFT -> Reward -> PPO/DPO pipeline. We should maybe create a micro dataset that can be trained quickly. Also, the parameters passed into the trainers should be low VRAM and work on a RTX 3080.

2. I use TRL a lot. And, am open to working on a full CLI suite (ie: `trl sft --params`) etc. Maybe future discussion once we streamline example scripts and make it super easy to ramp up on TRL.

**Comment by ChrisCates** [comment]
My ideal workflow with a CLI suite would generate config files and templates.

```bash
# Train with configuration.json
trl sft --config [/path/to/config.json]

# Generate a template
trl sft template --vram 8gb --gpus 1
```

Regardless, let's save that for a later discussion. Hopefully what I've suggested looks like a good time saver and productivity workflow.

**Comment by lvwerra** [comment]
Hi @ChrisCates

1. Generally sounds good to me to streamline the process a bit. In our experiments, the SFT -> Reward -> PPO/DPO pipeline was usually not quite stable enough to do it fully hands off (e.g. the SFT step would require a bit of tuning/manual inspection to get right). Maybe @lewtun has some ideas too. 

2. Having a CLI on top of the scripts sounds good to me. As long as it is tightly coupled to the scripts it should only cause minor overhead to maintain on top of the scripts!

Feel free to either open a draft PR or an issue to discuss this further!

**Comment by ChrisCates** [comment]
@lvwerra, oh definitely agree in regards to the streamlined examples. The demo or "quick start"/"tour" example would just be on a micro dataset to demonstrate results. Definitely not meant to demonstrate actual production usage.

The core goal is to reduce ramp up time into TRL. They can reference the shell scripts in the `examples` folder and also see how to prepare datasets for each step of the pipeline. I think seeing this nuance is especially important for PPO. Where you need to fine tune the sentiment model to train the main model.

Would probably have a micro dataset on something trivial like Batman Factoids. And they can test the before and after on a 3B llama model using the transformers library for inference.

Regardless, I'll send a PR later next week showcasing a first draft. And we can figure out next steps.

**Comment by lewtun** [comment]
A CLI for launching the training examples is a neat idea! FWIW we opted for a YAML config system in the `alignment-handbook` repo (https://github.com/huggingface/alignment-handbook) and that worked out pretty well using the `HfArgumentParser` from `transformers`
