### ISSUE TITLE
How to additional finetune with new data from previous adapter ?

### ISSUE THREAD

**Issue by SiraHaruethaipree** [huggingface/trl#1140]
Hi All, I have question about finetune. Currently I use SFTtrainer for finetuning Llama2-7b-chat model and save it in adapter format. The question is, In case of I want to additional finetune with new data from previous adapter, How I could to do. Normally I additional finetune by merge adapter with base model before finetune it. I'm not sure my method that i do is correct or not. Or have any other method that easily more than this.
Thank

**Comment by younesbelkada** [comment]
Hi @SiraHaruethaipree 
Your solution seems correct, currently the best way to perform this is to merge the trained adapter into the base model, save/push it then attach new adapters on top of it again.
