### ISSUE TITLE
Suggestion (DPO): throw an error/warn if `tokenizer.pad_token` is `None`

### ISSUE THREAD

**Issue by yumemio** [huggingface/trl#1149]
## Description

trl/trainer/utils.py uses `tokenizer.pad_token` to pad the input sequence. 

This is problematic when `tokenizer.pad_token` is `None`, which results in a rather cryptic `TypeError`:

https://github.com/huggingface/trl/blob/911d3658e23786740c29b8042474bc05ce20b466/trl/trainer/utils.py#L314-L315

https://github.com/huggingface/trl/blob/911d3658e23786740c29b8042474bc05ce20b466/trl/trainer/utils.py#L323

```
...

[/usr/local/lib/python3.10/dist-packages/trl/trainer/utils.py](https://localhost:8080/#) in __call__(self, features)
    320                         raise ValueError(f"Unexpected key in batch '{k}'")
    321 
--> 322                     padded_batch[k] = pad_sequence(to_pad, batch_first=True, padding_value=padding_value)
    323                     # for the prompt, flip back so padding is on left side
    324                     if "prompt" in k:

[/usr/local/lib/python3.10/dist-packages/torch/nn/utils/rnn.py](https://localhost:8080/#) in pad_sequence(sequences, batch_first, padding_value)
    398     # assuming trailing dimensions and type of all the Tensors
    399     # in sequences are same and fetching those from sequences[0]
--> 400     return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
    401 
    402

TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
```

Perhaps checking whether `tokenizer.pad_token == None` beforehand and raising an error would help users debug the issue.

Any thoughts on this suggestion? Thanks!

**Comment by lvwerra** [comment]
Sounds good to me, feel free to open a PR! :)
