### ISSUE TITLE
Negative KL warning even if KL='abs' and KL='full'

### ISSUE THREAD

**Issue by mgerstgrasser** [huggingface/trl#1161]
I'm using PPOTrainer to RLHF a llama2 model, and I sometimes get negative KL in my experiments. I've noticed that PPOTrainer prints a warning about that, even if I set `kl_penalty="abs"` or `kl_penalty="full"`, even though (by my understanding) it should be impossible to get negative KL in those cases.

Two questions:
* Checking the code, it looks like the KL divergence that's reported to wandb, and that is also used to determine whether the "negative KL" warning is printed, is calculated separately from the KL that is used for training; and the reported KL is always using the standard estimate. Did I understand that correctly, and does that mean I can ignore the "negative KL" warning if I'm using "abs" or "full" KL? (I can see that the non-score reward is non-positive if I use abs or full KL, and if I'm reading the code correctly the does indicate that the KL used in training is likely positive.)
* Conceptually, is there any issue or drawback with using "abs" or "full" instead of "kl"?

Thank you so much!

**Comment by lvwerra** [comment]
Indeed, that might be a bug, would you like to open a PR to fix it? In general `full` should be fine but we have observed some issues with the KL becoming negative and then `abs` is safer.

**Comment by mgerstgrasser** [comment]
> Indeed, that might be a bug, would you like to open a PR to fix it? In general `full` should be fine but we have observed some issues with the KL becoming negative and then `abs` is safer.

Yes, happy to open a PR! Give me a few days.

And just to make sure my understanding of everything is correct: 
- With `kl` and negative KL, the real issue is that the negative KL leads to a positive non-score reward, and that opens up a loophole where the algorithm can get almost arbitrarily good returns just by driving down the KL into large-magnitude negative numbers.
- Negative KL with `kl` means that the log-prob of the chosen tokens were on average less than the log-probs of those same tokens in the reference model.
- That in itself (log-probs of chosen tokens being less than in the ref model) isn't necessarily an issue. It probably just means that the 'peak' of the token probability distribution decreased, i.e. the probability weight was spread out more across tokens, i.e. entropy increased. That could be indicative of an issue depending on what you're trying to do, but it doesn't *have* to be a problem. Is my intuition here roughly in line with how you are thinking about this?

And as an aside, can you get negative `full` KL? I thought KL by definition is non-negative; or is `full` still just an estimate pf the real KL?

Thank you so much!

**Comment by lvwerra** [comment]
All above points are correct. For the last point:

> That in itself (log-probs of chosen tokens being less than in the ref model) isn't necessarily an issue. It probably just means that the 'peak' of the token probability distribution decreased, i.e. the probability weight was spread out more across tokens, i.e. entropy increased. That could be indicative of an issue depending on what you're trying to do, but it doesn't have to be a problem. Is my intuition here roughly in line with how you are thinking about this?

Since we average over a large sample it should still be mostly positive (the expected value is strictly positive but here we sample). In our experiment it usually meant you screwed something up with the generation and you are not sampling from the natural distribution of the model output. There is a full section in the [docs](https://huggingface.co/docs/trl/how_to_train#what-is-the-concern-with-negative-kl-divergence).

This can all be quite subtle so the `abs` strategy was to see if you can avoid this edge cases.

**Comment by mgerstgrasser** [comment]
> All above points are correct. For the last point:
> 
> > That in itself (log-probs of chosen tokens being less than in the ref model) isn't necessarily an issue. It probably just means that the 'peak' of the token probability distribution decreased, i.e. the probability weight was spread out more across tokens, i.e. entropy increased. That could be indicative of an issue depending on what you're trying to do, but it doesn't have to be a problem. Is my intuition here roughly in line with how you are thinking about this?
> 
> Since we average over a large sample it should still be mostly positive (the expected value is strictly positive but here we sample). In our experiment it usually meant you screwed something up with the generation and you are not sampling from the natural distribution of the model output. There is a full section in the [docs](https://huggingface.co/docs/trl/how_to_train#what-is-the-concern-with-negative-kl-divergence).
> 
> This can all be quite subtle so the `abs` strategy was to see if you can avoid this edge cases.

Ah, yes, I've seen that discussion in the documentation. I meant, assuming the generation is working correctly, then negative estimated KL itself isn't an issue. I.e. if the `kl` case leads to negative KL, then assuming one has verified that generation is working correctly, simply switching to `abs` or `full` would be OK to do in general?

In any case, I've opened a PR! Thanks so much for your explanations.

**Comment by lvwerra** [comment]
Yes that's correct!
