### ISSUE TITLE
ValueError: You passed a `DataCollatorForCompletionOnlyLM` to the SFTTrainer. This is not compatible with the `packing` argument.

### ISSUE THREAD

**Issue by palash04** [huggingface/trl#1163]
I am using SFTTrainer having following structure

```
trainer = SFTTrainer(
    model,
    args=training_arguments,
    train_dataset=dataset,
    # eval_dataset=dataset,
    formatting_func=formatting_prompts_func,
    data_collator=collator,
    peft_config=peft_config,
    max_seq_length=4096,
    packing=True,
)
```

```
collator = DataCollatorForCompletionOnlyLM(response_template, tokenizer=tokenizer, mlm=False, return_tensors="pt", pad_to_multiple_of=8)
```

I want to make use of packing=True, since, max_seq_length=4096 gives CUDA OOM. I cannot afford to loose out on data.

But, if I use packing then I get
```
ValueError: You passed a `DataCollatorForCompletionOnlyLM` to the SFTTrainer. This is not compatible with the `packing` argument.
```

So, which datacollator to use where I want the functionality of response_template, and also I want to use packing=True?

**Comment by palash04** [comment]
Thanks @lvwerra 

> Currently masking out the instructions when using `packing` is not supported, as it would require complex attention mask patterns. So if you remove the data collator it should work.

I tried removing data collator and it worked, but, then the loss would be calculated for the entire sequence. 
Does it makes sense to compute loss for entire sequence (prompt + response) in sft instead of computing loss only on response?


> In general I don't think this solves your issue of data being lost: if your samples are longer than the window they will still be cut into multiple samples which might not be useful for training. Have you tried PEFT and made sure you use FlashAttention2?

I am making sure that my samples in dataset has seq_len <= max_seq_len.
Yes, I am using peft, but not flashattn as there is a tensor size mismatch error while training if I load the model using flash attn.
I am using MPT with GQA, the 'Wqkv' block has (in_features=4608, out_features=6144), but when using flash attn that becomes (in_features=4608, out_features=13824), then, while training gives tensor size error. Any idea on this?


Does the SFTtrainer freezes weights other than target modules?

**Comment by xkszltl** [comment]
> Does it makes sense to compute loss for entire sequence (prompt + response) in sft instead of computing loss only on response?

Depends on your use case, whether you need to learn more about language modeling or just generation.
