### ISSUE TITLE
Add multiple formats in SFTrainer, DataCollatorForCompletionOnlyLM only allows for one format.

### ISSUE THREAD

**Issue by XueTianci** [huggingface/trl#1166]
**Normally, we can specify the starting point of loss calculation through DataCollatorForCompletionOnlyLM. However, if the task contains data in multiple formats, the place where loss calculation starts may be different.**

For example：
Task 1 (want to calculate loss from answer):
Question: xxx
Answer: xxx

Task 2 (want to calculate loss from the explanation)
Question: xxx
Explanation: xxx
Answer: xxx

**Comment by lvwerra** [comment]
I think in this case it's best to write your own data collator that integrates your custom logic.
