### ISSUE TITLE
Nan loss when training llama2

### ISSUE THREAD

**Issue by ahmedkotb98** [huggingface/trl#1173]
I’m trying to train llama2 on 400000 steps when the training reaches 23000 steps the loss is 0.0 in train and nan in eval 
My hardware :
4 16Gp v100

**Comment by younesbelkada** [comment]
hi @ahmedkotb98 
what is the training precision? Can you try with bf16?

**Comment by ahmedkotb98** [comment]
> hi @ahmedkotb98 what is the training precision? Can you try with bf16?

My gpu is v100 not supported for bf16
