### ISSUE TITLE
7B model OOM with 4x4096(96GB)

### ISSUE THREAD

**Issue by vegasvv** [huggingface/trl#1187]
Hi

I try to train a full 7B model with the DPO script on 4x4096(96Gb), without using Lora or quantization (it is a full model training). But I did train with fp16. Hosting 7b model takes 50GB (Adam optimizer), so my 4x4096 setup should be fine.

I used the dpo script from your example https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py, and I only change the Lora and remove the quantization part.

But if I used 1xA100(80GB), it works fine. Do you know what is the issue with the 4x4096 setup?

**Comment by younesbelkada** [comment]
Hi @vegasvv 
thanks for the issue!
I believe you need to split up your model across all available GPUs, can you load both the reference and active models using `device_map="auto"` ?

**Comment by vegasvv** [comment]
Thanks @younesbelkada i did try with auto for device_map, but it won't let me. It was I can't use auto in distributed model

**Comment by younesbelkada** [comment]
ah yes , correct, in that case you need to load the training protocol with the technique mentioned here: https://github.com/huggingface/accelerate/issues/1840#issuecomment-1683105994 
instead of using `Accelerator().process_index` you can use `PartialState().process_index`. please refer to that comment for the explanation on why this hack is needed for distributed training

**Comment by candygocandy** [comment]
> ah yes , correct, in that case you need to load the training protocol with the technique mentioned here: [huggingface/accelerate#1840 (comment)](https://github.com/huggingface/accelerate/issues/1840#issuecomment-1683105994) instead of using `Accelerator().process_index` you can use `PartialState().process_index`. please refer to that comment for the explanation on why this hack is needed for distributed training

I see, so, I basically do this?

`If the model does not fit entirely into a single GPU, you can continue using device_map="auto" but instead of running the script with accelerate launch xxx or python -m torch.distributed.run xxx run it simply with python xxx.py.` ?

Or I use `device_map=PartialState().process_index` but still use `accelerate launch xxx`?

**Comment by vegasvv** [comment]
> ah yes , correct, in that case you need to load the training protocol with the technique mentioned here: [huggingface/accelerate#1840 (comment)](https://github.com/huggingface/accelerate/issues/1840#issuecomment-1683105994) instead of using `Accelerator().process_index` you can use `PartialState().process_index`. please refer to that comment for the explanation on why this hack is needed for distributed training

I see, so, I basically do this?

`If the model does not fit entirely into a single GPU, you can continue using device_map="auto" but instead of running the script with accelerate launch xxx or python -m torch.distributed.run xxx run it simply with python xxx.py.` ?

Or I use `device_map=PartialState().process_index` but still use `accelerate launch xxx`? > ah yes , correct, in that case you need to load the training protocol with the technique mentioned here: [huggingface/accelerate#1840 (comment)](https://github.com/huggingface/accelerate/issues/1840#issuecomment-1683105994) instead of using `Accelerator().process_index` you can use `PartialState().process_index`. please refer to that comment for the explanation on why this hack is needed for distributed training

I see, so, I basically do this?

`If the model does not fit entirely into a single GPU, you can continue using device_map="auto" but instead of running the script with accelerate launch xxx or python -m torch.distributed.run xxx run it simply with python xxx.py.` ?

Or I use `device_map=PartialState().process_index` but still use `accelerate launch xxx`?

@younesbelkada

**Comment by younesbelkada** [comment]
Hi @vegasvv , can you please try method 2

**Comment by vegasvv** [comment]
I try, it is still OOM unfortunately..

**Comment by younesbelkada** [comment]
Hmm, can you make sure gradient checkpointing is set to `True` ?

**Comment by zhongshsh** [comment]
If I use method 1, how to start multi-machine @younesbelkada

**Comment by younesbelkada** [comment]
Hi @zhongshsh, just run it with `python xxx.py`, for method 2, first run `accelerate config`, make sure to select multi-GPU and run `accelerate run xxx.py`

**Comment by zhongshsh** [comment]
@younesbelkada I try Method 1, `python xxx.py` when running in multi-machine env, but got error message:

```
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
```

**Comment by younesbelkada** [comment]
Hmmm are you sure you ran with `python xxx.py` ? Are you using `python -m torch.distributed.run` ?

**Comment by zhongshsh** [comment]
not sure. I ran with `python xxx.py`, but in my case of multi node, maybe `python xxx.py` would be implicitly changed to `python -m torch.distributed.run`
