### ISSUE TITLE
AutoModelForCausalLMWithValueHead.generate() incompatibility with DeepSpeed ZeRO-3 

### ISSUE THREAD

**Issue by liu-zichen** [huggingface/trl#1192]
When using deepspeed zero3, some hook functions are attached to AutoModelForCausalLMWithValueHead.forward. These hooks are essential for the correct functioning. However, the AutoModelForCausalLMWithValueHead.generate directly calls self.pretrained_model.generate which will not call self.forward so those hooks would not be activated. 

AutoModelForCausalLMWithValueHead.generate: 
https://github.com/huggingface/trl/blob/dbcb2f00217a24f23d13bedf1ca495ea6af672a7/trl/models/modeling_value_head.py#L190-L202

The problem seems to be similar to the one described in issue https://github.com/huggingface/trl/issues/1051

**Comment by lvwerra** [comment]
@lewtun have you encountered similar issues in your experiments?
