### ISSUE TITLE
`TypeError`: `__init__()` got an unexpected keyword argument 'save_safetensors'

### ISSUE THREAD

**Issue by wasertech** [huggingface/trl#1210]
Comon! I can't use safetensors if I want to quantize my merge with AWQ.

https://github.com/huggingface/transformers/blob/976189a6df796a2ff442dd81b022626c840d8c27/src/transformers/training_args.py#L835

https://github.com/huggingface/trl/blob/7a95cc86966ec5e59a9347384ba572f93e931827/trl/trainer/sft_trainer.py#L120-L146

Need to add `**kwargs` at the end of parameters to pass keyword arguments to transformers' Trainer.

**Comment by wasertech** [comment]
Nevermind. If you face this issue (or a similar one), set `save_safetensors` (or the argument you want) as parameter when you initialize `TrainingAguments`...

```python
from transformers import AutoModelForCausalLM, TrainingArguments
from trl import SFTTrainer

training_args = TrainingArguments(
    save_safetensors=False,
)

trainer = SFTTrainer(
    args=training_args,
)
```

**Comment by lvwerra** [comment]
Maybe we should fix this in general, what do you think @younesbelkada?

**Comment by wasertech** [comment]
> Maybe we should fix this in general
@lvwerra What do you mean?

From my POV, its my lack of understanding of the code's behavior that lead to this error. To be honest I was hyper focused on exporting my checkpoints in the correct format to later quantize my FP merge with AWQ when looking at the trl docs that I didn't even thought about the dedicated way to pass arguments to the trainer. Plus the fact I thought SFTTainer was a subclass of Trainer didn't helped me either...

Something that can be improved is the docs of trl. Like I said in my PR's review, it would be nice to have a small section dedicated to saving your checkpoint in supported formats with trl trainers. That way it's easy to find when you are looking for it. Because atm, without prior knowledge, you would have to piece it from a few different projects docs, the code and a lot of trial and error.
