### ISSUE TITLE
Padding side incorrect for Mistral DPO

### ISSUE THREAD

**Issue by hengjiUSTC** [huggingface/trl#1217]
For code here: https://github.com/huggingface/trl/blob/main/trl/trainer/utils.py#L538C4-L550 Does it always padding to right?

I get error when run dpo for mixtral 7b.

I am still seeing this error after set `tokenizer.padding_side  = 'left'`
This is my demo notebook: https://colab.research.google.com/drive/1sVqbYEOqjJYl7CzNzXzviEBB6A984cMq?usp=sharing

**Tokenizer already set with left padding**
![截屏2024-01-10 下午10 53 07](https://github.com/huggingface/transformers/assets/25971665/0ce9f431-8a8f-4236-8c71-846f183f455e)

**Train**
![截屏2024-01-11 上午10 28 53](https://github.com/huggingface/trl/assets/25971665/e8f0a944-9f22-4cba-88a6-a1712ba02f2c)

**Still have**: `ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to  call `tokenizer.padding_side  = 'left'` before tokenizing the input.`

![截屏2024-01-10 下午10 54 31](https://github.com/huggingface/transformers/assets/25971665/f031de6c-6b25-4be8-8b4a-7075e70785a5)

Seems https://github.com/huggingface/trl/blob/main/trl/trainer/utils.py#L538C4-L550 or other part of code might lead to bug?

transformers             4.36.2
trl                      0.7.7
peft                     0.6.0

**Comment by hengjiUSTC** [comment]
Did some debugging, quiet confirmed that https://github.com/huggingface/trl/blob/main/trl/trainer/utils.py#L538C4-L550 gives incorrect padding side and lead to crash in transformers.

```
File ~/learn-llm/venv/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py:899, in MistralModel.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, return_dict)
    897     is_padding_right = attention_mask[:, -1].sum().item() != batch_size
    898     if is_padding_right:
--> 899         raise ValueError(
    900             "You are attempting to perform batched generation with padding_side='right'"
    901             " this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to "
    902             " call `tokenizer.padding_side  = 'left'` before tokenizing the input. "
    903         )
    905 if self._use_flash_attention_2:
    906     # 2d mask is passed through the layers
    907     attention_mask = attention_mask if (attention_mask is not None and 0 in attention_mask) else None

ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to  call `tokenizer.padding_side  = 'left'` before tokenizing the input. 
```

**Comment by gchhablani** [comment]
Can I take this up @vwxyzjn?

**Comment by arkapal3** [comment]
I had the same issue and went down a debugging rabbit hole, but realised in the end I had forgotten to set `use_cache` to False for my reference model.

Remember you need to set `use_cache = False` for both the main and reference model. If you do so the check on `is_padding_right` above won't trigger (which it shouldn't, because we are using the forward to compute log probs, not do generation).

**Comment by hengjiUSTC** [comment]
> I had the same issue and went down a debugging rabbit hole, but realised in the end I had forgotten to set `use_cache` to False for my reference model.
> 
> Remember you need to set `use_cache = False` for both the main and reference model. If you do so the check on `is_padding_right` above won't trigger (which it shouldn't, because we are using the forward to compute log probs, not do generation).

Checked this solution work.

**Comment by hengjiUSTC** [comment]
Any reason that training should be right? For most of dpo scripts I have seen, they all set mistral tokenizer padding to left.

> Hi thanks for the issue. Maybe during training the tokenizer.padding_side should be set to right?

**Comment by vwxyzjn** [comment]
For both our and DPO's original repo, we all do right padding. Out of curiosity, which DPO scripts have you seen use the pad left? Pad left is primarily used for generation such as in PPO but in DPO it's unnecessary because DPO does not do generation. 

<img width="1714" alt="image" src="https://github.com/huggingface/trl/assets/5555347/30280b0a-2fa7-4c32-8a34-82a40ef8a280">

<img width="1629" alt="image" src="https://github.com/huggingface/trl/assets/5555347/cb952cfb-60b3-4443-a85b-88be73824023">

**Comment by hengjiUSTC** [comment]
https://towardsdatascience.com/fine-tune-a-mistral-7b-model-with-direct-preference-optimization-708042745aac
https://colab.research.google.com/drive/15iFBr1xWgztXvhrj5I9fBv20c7CFOPBE?usp=sharing

Does setting pad_size to left impact DPO result? What is the correct settings we should use?

**Comment by younesbelkada** [comment]
This should be now fixed on TRL main !

**Comment by TeFurie** [comment]
I also encounter this problem, I use trl for GRPOTrainer using DeepSeek-R1-Distill-Qwen-7B, any way to solve it?

**Comment by ZejunCao** [comment]
https://blog.csdn.net/qq_41496421/article/details/136654890?spm=1001.2014.3001.5502
这里有解决办法，欢迎讨论

**Comment by singhalarchit** [comment]
@TeFurie having the same issue with Qwen2.5-7B/3B and phi4-mini-instruct. Did you find a solution?
