### ISSUE TITLE
Multi-GPU Training with DPO

### ISSUE THREAD

**Issue by QiyaoWei** [huggingface/trl#1220]
I am trying to RLHF a Llama-7B using DPO, closely following [this example](https://github.com/huggingface/trl/blob/main/examples/scripts/dpo.py). I also try to use both of my GPUs, with a config file that looks like [this one](https://github.com/huggingface/trl/blob/main/examples/accelerate_configs/multi_gpu.yaml). However, my GPU usage looks like the following
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           Off | 00000001:00:00.0 Off |                    0 |
| N/A   31C    P0              36W / 250W |  10924MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE-16GB           Off | 00000002:00:00.0 Off |                  Off |
| N/A   31C    P0              36W / 250W |    310MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     11149      C   /home/azureuser/miniconda/bin/python       5460MiB |
|    0   N/A  N/A     11150      C   /home/azureuser/miniconda/bin/python       5460MiB |
|    1   N/A  N/A     11150      C   /home/azureuser/miniconda/bin/python        306MiB |
+---------------------------------------------------------------------------------------+
```
At which point there is a CUDA out of memory error, presumably because the remaining VRAM on GPU0 is not enough to hold the DPO network and train them at the same time. So my question is---is it possible to load the trained model and the reference model separately (one on GPU0 and the other on GPU1)? Looking at the nvidia-smi output it seems like OOM happened because both models are loaded on GPU0, hence overloading the memory of that GPU. Am I misunderstanding something?

**Comment by younesbelkada** [comment]
Hi @QiyaoWei 
Thanks for the issue! I think if you load the active and reference model on different devices it will work out of the box
Can you try to load the active model with passing `device_map={"": 0}` and the reference model with `device_map={"": 1}` ? Make sure to use the latest TRL version from pypi as it includes a fix for multi-gpu
Moreover you can use a single model to get both the reference and active logits and speed up your training, you need to pass a peft_config to `DPOTrainer` and load your model with `device_map={"": PartialState().process_index}` and run your script with `accelerate launch xxx.py` after selecting `"multi-gpu"` when calling `accelerate config` from your terminal.
Let me know if anything is unclear.

**Comment by QiyaoWei** [comment]
@younesbelkada Many thanks for your help, and everything is super clear! I tried exactly `device_map={"": PartialState().process_index}` and the code worked out of the box, I didn't even have to use `accelerate`, just a normal python run was enough :)

**Comment by younesbelkada** [comment]
Awesome, glad to hear that! Thanks and enjoy using TRL !

**Comment by u1vi** [comment]
> device_map={"": PartialState().process_index}

`from accelerate import PartialState`
