### ISSUE TITLE
ADAM_32bit optimizer with PPO trainer

### ISSUE THREAD

**Issue by candygocandy** [huggingface/trl#1231]
Hello

How do I use  `ADAM_32bit`

https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L139-L157

with the [PPO Trainer (TRL)](https://huggingface.co/docs/trl/main/en/ppo_trainer)?

I know I can specify optimizer by:

    optimizer = Adafactor(
        filter(lambda p: p.requires_grad, model.parameters()),
        scale_parameter=False,
        relative_step=False,
        warmup_init=False,
        lr=config.learning_rate,
    )

How do I do it with `ADAM_32bit`?

**Comment by lvwerra** [comment]
Which optimizer class are you referring to with `ADAM_32bit`? As long as the `optimizer` is a torch optimizer it should be fine.
