### ISSUE TITLE
prompt_len_input_ids is never used and assigned by min len of chosen,rejected immediately

### ISSUE THREAD

**Issue by maliozer** [huggingface/trl#1232]
Because there is a caution in comment lines, is there anything to missed here to validate ?

https://github.com/huggingface/trl/blob/baf3c1c2939986b08660cb023da12310ee293da6/trl/trainer/dpo_trainer.py#L610C13-L610C33

**Comment by lvwerra** [comment]
True, let's see what @kashif thinks!
