### ISSUE TITLE
SFTTrainer: Can we make tokenization in the trainer optional?

### ISSUE THREAD

**Issue by mgerstgrasser** [huggingface/trl#1237]
Currently the SFTTrainer seems to insist on tokenizing the dataset when it prepares the dataloader (see [here](https://github.com/huggingface/trl/blob/7a95cc86966ec5e59a9347384ba572f93e931827/trl/trainer/sft_trainer.py#L423)). I think it would be nice to make that optional. The main use case I have in mind is conversational data, where you can't always tokenize an example as a whole, but you might have to tokenize turn-by-turn. 

In my own such use case, I end up tokenizing in the DataCollator, but I still have to pass a `text` column inside the dataset just to make the SFTTrainer data loader prep work.

I'd be happy to make a PR, but just wanted to check if there are any objections?

**Comment by younesbelkada** [comment]
There is no objection on my end @mgerstgrasser would you be happy to make a PR for this enhancement?

**Comment by mgerstgrasser** [comment]
I'd be happy to, but just to check beforehand, what do you think is the best way of passing that configuration option? Right now `SFTTrainer` uses standard `transformers` `TrainingArguments`, which don't include a configuration option for tokenization. I assume the best way of doing it is to pass it to `SFTTrainer.__init__()` as a new argument? There are already arguments for the number of processes to use for tokenization there, so I guess that makes the most sense?

**Comment by younesbelkada** [comment]
hi @mgerstgrasser - that's great!
I think having an arg in the sfttrainer's init sounds good, but I think we don't even need an argument as this can be detected already under the hood by inspecting the dataset's column (if it contains `input_ids` only for instance), if that's properly documented in the SFTTrainer docs this shouldn't be an issue. What do you think?

**Comment by amew0** [comment]
Any plans to implement this? How are we handling to avoid the auto tokenizing on data preparation under the hood?

**Comment by rchen4-snap** [comment]
Is this implemented in the latest version?
