### ISSUE TITLE
When reference_free the ref_logratios is zero int, but int type has no attribute .to for set device causes AttributeError

### ISSUE THREAD

**Issue by maliozer** [huggingface/trl#1238]
https://github.com/huggingface/trl/blob/baf3c1c2939986b08660cb023da12310ee293da6/trl/trainer/dpo_trainer.py#L846C9-L846C22

reference_free case causes AttributeError

```python
ref_logratios = 0
ref_logratios = ref_logratios.to(self.accelerator.device)

AttributeError: 'int' object has no attribute 'to'
```

**Comment by younesbelkada** [comment]
Indeed, nice catch @maliozer would you be happy to open a PR to fix it?

**Comment by maliozer** [comment]
ok let me check for it

**Comment by younesbelkada** [comment]
Thanks for your contribution and fix @maliozer !
