### ISSUE TITLE
Understanding v_head training

### ISSUE THREAD

**Issue by MassimilianoT** [huggingface/trl#1240]
I was analyling how SFTrainer works on finetuning a LLM and i was trying to understand how the value head is trained. Is only the PPOTrainer that modifies the weights? Where can i find the code where the Trainer updates the weights of the v_head? 
I was also wondering if the SFTrainer can be used to train a model from scratch.
Thank you

**Comment by vwxyzjn** [comment]
SFT trainer does not have a value head. Only PPOTrainer does. See https://github.com/huggingface/trl/blob/29d439a2043edf4455b05cae5a1e2ade69d22794/trl/models/modeling_value_head.py#L113
