### ISSUE TITLE
Role of Alpha parameter in LORA configuration while finetuned model inferencing time

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/trl#1243]
Is there any role of the Alpha parameter in LORA configuration while model inferencing time?
Does the alpha parameter control the inference speed of the finetuned model?

**Comment by younesbelkada** [comment]
Hi @pradeepdev-1995 
I believe inference time is proportional to alpha, for higher alphas it might take longer inference time. For inferring lora models, I would suggest to merge the lora weights into the base model

https://huggingface.co/docs/peft/conceptual_guides/lora#merge-lora-weights-into-the-base-model

You can just call `model.merge_and_unload()` on your `PeftModel`

**Comment by pradeepdev-1995** [comment]
@younesbelkada 
But after merging also the alpha parameter plays the role while inferencing time?
Will the inference time of the finetuned merged model increase as the alpha value used while its training time, increases?

**Comment by younesbelkada** [comment]
If you merge the LoRA weights, the alpha will not have any influence on the inference speed as the LoRA weights will be unloaded from the model

**Comment by pradeepdev-1995** [comment]
Thanks for the clarification @younesbelkada

**Comment by pradeepdev-1995** [comment]
so other than alpha is there any other Lora parameters which regulate the model inference time in the merged model?

**Comment by younesbelkada** [comment]
Thanks @pradeepdev-1995 ! Once you merge the lora adapters in the model there shouldn't be anything that influences the merged model's inference speed
