### ISSUE TITLE
Dataloading speed significantly slower in multi GPU setting

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/trl#1249]
Hi, I am trying to launch a fine-tuning job using a slightly modified version of `sft.py` with accelerate, looks something like:

```bash
accelerate launch \
    --config_file="./conf/accelerate/multi_gpu.yaml" \
    --num_processes 8 \
    examples/sft.py \
    --other_args
```

Within the script is a `formatting_func` and `DataCollatorForCompletionOnlyLM` data collator that are both passed to `SFTTrainer`, mostly following the [documentation](https://huggingface.co/docs/trl/main/en/sft_trainer).

At some point before training, the `SFTTrainer._prepare_non_packed_dataloader()` method is called. My issue is that the __time it takes to preprocess the dataset is significantl longer in the multi GPU setting, compared to a single GPU__. I might expect a little overhead to go distributed, but this is a significant difference (>10X):

```bash
# Single GPU setting, processes my dataset in about 20 minutes
accelerate launch \
    --config_file="./conf/accelerate/single_gpu.yaml" \
    --num_processes 1 \
    examples/sft.py \
    --other_args
 
# Multi GPU setting, reporting almost 5 hours to preprocess my data, a ~15X slowdown
accelerate launch \
    --config_file="./conf/accelerate/multi_gpu.yaml" \
    --num_processes 8 \
    examples/sft.py \
    --other_args
```
 
I got the accelerate configs right from the TRL repo [here](https://github.com/huggingface/trl/tree/main/examples/accelerate_configs). I figured the dataset was being loaded once per node and then batches dispatched to each GPU, so not really sure why I am seeing the slow-down before training even begins. I am not even sure this is a TRL issue but I figured it would be worth asking. Is there any kind of obvious gotcha that would lead to a slowdown like this? Anything one should take into account when moving to the multi-GPU setting with `accelerate + SFTTrainer`?

__Update__:

I confirmed this is not due to any changes in my script. Running the raw [`sft.py`](https://github.com/huggingface/trl/blob/main/examples/scripts/sft.py) script with default arguments and I get the following numbers:

```bash
# Single GPU
accelerate launch \
    --config_file="./conf/accelerate/single_gpu.yaml" \
    --num_processes 1 \
    examples/sft.py
# => data loading reports: 9846/9846 [00:07<00:00, 1340.85 examples/s]

# Multi GPU
accelerate launch \
    --config_file="./conf/accelerate/multi_gpu.yaml" \
    --num_processes 8 \
    examples/sft.py
# => data loading reports: 9846/9846 [01:03<00:00, 155.30 examples/s]
```

Which is a 9X slowdown (again, this is _before_ training even begins)

**Comment by younesbelkada** [comment]
Thanks for reporting @JohnGiorgi 
I think the issue is that we call `prepare_xxx_dataloader` on all processes, can you try to modify the source code of SFTTrainer to make sure to call data processing steps only on the main process? You can import `PartialState` from accelerate and guard that call with `if PartialState().is_main_process:`. If that works, would you be happy to submit a PR with the fix? 🙏

**Comment by JohnGiorgi** [comment]
Sure! Will open a PR and continue the discussion there

**Comment by younesbelkada** [comment]
Thanks @JohnGiorgi , let me know how it goes!
