### ISSUE TITLE
DPOTrainer dataset preprocessing is slow

### ISSUE THREAD

**Issue by normster** [huggingface/trl#1251]
The DPOTrainer dataset preprocessing step does not make use of multiprocessing: https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L356. Is it possible to set `num_proc` to a reasonable default, or enable specifying it via an argument?

**Comment by younesbelkada** [comment]
cc @kashif that would make sense I would say - would you be happy to submit a PR to add `num_proc` to a reasonable value and make it configurable?

**Comment by kashif** [comment]
ah yes sure! i can do it or do you want to try @normster

**Comment by lvwerra** [comment]
Actually it is recommended to pass batches to the tokenizer rather than parallelize, since the tokenizer is implemented in rust and handles multiprocessing in the background.

**Comment by younesbelkada** [comment]
FYI there is an ongoing work to support mulit-processing in DPOTrainer tokenization: https://github.com/huggingface/trl/pull/1286

**Comment by younesbelkada** [comment]
Closing as https://github.com/huggingface/trl/pull/1286 being merged
