### ISSUE TITLE
`RewardTrainer` hits NaN output with quantized pretrained model

### ISSUE THREAD

**Issue by chenmoneygithub** [huggingface/trl#1258]
Hi team,

I am trying to tune my reward model (`opt-350m`) via `RewardTrainer`, while it works fine without applying quantization, using int4 + lora hit the NaN problem after <10 steps. Here is the reproducible code: [github gist](https://colab.research.google.com/gist/chenmoneygithub/a2e0895b0dba6e49b440686cda5ed01b/reproduce-reward-model-nan-issue.ipynb?authuser=1#scrollTo=FFTBZa0iTkwf), tested on A100 environment. Could anyone provide any insight? I am also wondering how people debug quantization-related issue when using HuggingFace trainer, is it possible to print out the gradients, and outputs of certain layers inside the model? Thanks a lot!

**Comment by lvwerra** [comment]
cc @younesbelkada

**Comment by chenmoneygithub** [comment]
Hi team, any suggestion on this? It looks like a mixed precision issue, but i don't know how to debug it...

**Comment by Joe-Hall-Lee** [comment]
Hi, I have the same problem. Have you solved it?
