### ISSUE TITLE
could share parameter between model(lora) and ref model?

### ISSUE THREAD

**Issue by dhcode-cpp** [huggingface/trl#1263]
when use dpo, i read the code, need to load 2 model. I want load my sft model as ref model, and use lora+sft model as my dpo train target.

i want to train DPO model in low-memory GPU, how could i run this method?

thanks for your reply.

**Comment by younesbelkada** [comment]
Yes you can run DPO in a memory efficient manner by using QLoRA and load a single model and adapters. 
You can use our `dpo.py` script and run this command to do so: https://github.com/huggingface/trl/blob/main/commands/run_dpo.sh
Note this works on single & multi-GPU envs

**Comment by dhcode-cpp** [comment]
thanks, it works

I set model with `peft`, and set `dpo_trainer` ref model is `None`

```
    trainer = DPOTrainer(
        model,
        None,
        args=training_args,
        beta=beta,
        train_dataset=train_datasets,
        eval_dataset=test_datasets,
        tokenizer=tokenizer,
        peft_config=peft_config,
        max_prompt_length= output_max_length,
        max_length= seq_length,
    )
```

**Comment by younesbelkada** [comment]
Awesome, thanks @dhcode-cpp !
