### ISSUE TITLE
DPO: dpo_trainer.train() 

### ISSUE THREAD

**Issue by JasonTaoY** [huggingface/trl#1267]
error:
ValueError: Can only automatically infer lengths for datasets whose items are dictionaries with an 'input_ids' key.

The dpo_trainer.train_dataset:
Dataset({
    features: ['prompt', 'chosen', 'rejected', 'chosen_input_ids', 'chosen_attention_mask', 'chosen_labels', 'rejected_input_ids', 'rejected_attention_mask', 'rejected_labels', 'prompt_input_ids', 'prompt_attention_mask'],
    num_rows: 51818
})

**Comment by lvwerra** [comment]
Hi @JasonTaoY could you provide a minimal reproducible example?
