### ISSUE TITLE
DDPO training stuck after 14 step with 4 gpus in a single machine

### ISSUE THREAD

**Issue by EYcab** [huggingface/trl#1270]
![1706000025863](https://github.com/huggingface/trl/assets/11568206/0e076072-51f5-4ae3-8539-63c0e6266562)
I have been running the code following 2 steps:
accelerate config
accelerate launch examples/scripts/ddpo.py --hf-user-access-token **********************************

![1706000242816](https://github.com/huggingface/trl/assets/11568206/ad858eb2-0271-4444-acd8-b61ef598564f)
No idea where runs wrong at all

**Comment by lvwerra** [comment]
Does it work as expected if you run it on a single GPU?
