### ISSUE TITLE
DPOTrainer arguments: max_length and max_prompt_length

### ISSUE THREAD

**Issue by filippo82** [huggingface/trl#1271]
Hi all :wave: , I have questions about the `DPOTrainer` [docs](https://huggingface.co/docs/trl/main/en/dpo_trainer#trl.DPOTrainer):

- What is a good value for the [max_length](https://huggingface.co/docs/trl/main/en/dpo_trainer#trl.DPOTrainer.max_length) parameter? Would it be the same one used for the SFT training?
- What is a good value for the [max_prompt_length](https://huggingface.co/docs/trl/main/en/dpo_trainer#trl.DPOTrainer.max_prompt_length)

Moving the question here from Discord as suggested by @osanseviero 🙏

**Comment by filippo82** [comment]
Also please let me know if there exists any resource which already discuss this!

**Comment by younesbelkada** [comment]
Thanks @filippo82 for the issue!
cc @kashif @edbeeching @lewtun who have more experience than I do about DPO - feel free also to look into the alignment handbook: https://github.com/huggingface/alignment-handbook that gathers the best practices around RLHF

**Comment by filippo82** [comment]
Hi @younesbelkada, thanks for your reply. That is a good tip. I'll dive in to the alignment handbook repo to see if I can find additional info about that 🙏🏻

**Comment by anakin87** [comment]
In case someone (like me 😄)  still needs this information, it is well explained in this blog post: https://www.philschmid.de/dpo-align-llms-in-2024-with-trl

**Comment by qgallouedec** [comment]
From https://www.philschmid.de/dpo-align-llms-in-2024-with-trl

> Compared to the `SFTTrainer` the `DPOTrainer` has two parameter related to dataset sizing with `max_prompt_length` and `max_length`. The `max_prompt_length` is the maximum length of the prompt and the `max_length` is the maximum length of the prompt + chosen or rejected response. Those are used for tokenization, padding and trunctation. This means if we set those wrongly our data will be potentially cut off, but if we set them too high we will waste memory and time.

**Comment by filippo82** [comment]
> In case someone (like me 😄) still needs this information, it is well explained in this blog post: https://www.philschmid.de/dpo-align-llms-in-2024-with-trl

Grazie Stefano 🙏🏻
