### ISSUE TITLE
Regarding dataset used for lvwerra/gpt2-imdb

### ISSUE THREAD

**Issue by SapanaChaudhary** [huggingface/trl#1272]
Hello! 

Is the lvwerra:gpt2-imdb model used in controlled sentiment generation examples [https://github.com/huggingface/trl/blob/main/examples/notebooks/gpt2-sentiment-control.ipynb](url) trained on the entire IMDB dataset (train+test) or just train?

**Comment by younesbelkada** [comment]
Hi @SapanaChaudhary 
I think just on the train set, @lvwerra can perhaps confirm
