### ISSUE TITLE
DPO and Packing?

### ISSUE THREAD

**Issue by kostum123** [huggingface/trl#1274]
Is there an incompatibility issue between dpo and the 'packing true' setting? My dataset mostly single turn.

**Comment by younesbelkada** [comment]
I don't think it is possible to implement packing for DPO as you need a paired dataset for preferred and rejected responses; not sure how we can implement this in practice. cc @kashif to confirm but we can leave this as an open question

**Comment by kostum123** [comment]
> I don't think it is possible to implement packing for DPO as you need a paired dataset for preferred and rejected responses; not sure how we can implement this in practice. cc @kashif to confirm but we can leave this as an open question

I tried DPO with packing in a llama factory, but I don't know if it automatically falls back to false. The results were not good for a large number of samples, but they were good for 50 samples.
