### ISSUE TITLE
Question: eos_token while fine-tuning Mistral

### ISSUE THREAD

**Issue by ymoslem** [huggingface/trl#1283]
Hello! 

I am fine-tuning Mistral. When I create the tokenizer with `add_eos_token = False`,  SFTTrainer adds `</s>` by default. When I create the tokenizer with `add_eos_token = True` SFTTrainer adds `</s>` _**twice**_. 

I can see this when I print:
```python
trainer.train_dataset["input_ids"][0]
```

In this case, should `add_eos_token` be set to False as it is not needed, or should I set it to True, nevertheless? Thanks!

```python
tokenizer = AutoTokenizer.from_pretrained(model_name,
                                          add_bos_token = True,
                                          add_eos_token = True
                                          )
```

```python
trainer = SFTTrainer(
                    model=model,
                    peft_config=peft_config,
                    max_seq_length=max_seq_length,
                    tokenizer=tokenizer,
                    packing=True,
                    dataset_text_field="text",
                    args=training_args,
                    train_dataset=dataset["train"],
                    eval_dataset=dataset["validation"],
                  )
```

**Comment by younesbelkada** [comment]
HI @ymoslem 
Thanks for the issue ! 
I think this is because for packing the collator already separates each sample with a EOS token, can you try to pass `dataset_kwargs={"add_special_tokens": False}` in the SFTTrainer's init?

**Comment by younesbelkada** [comment]
Also in general it should be avoided to call `add_eos_token = True` on the tokenizer while using the packed dataset as this is handled under the hood by the trainer

**Comment by ymoslem** [comment]
Thanks! @younesbelkada 

Yes, if `packing=False` it does not add `</s>`
If `dataset_kwargs={"add_special_tokens": False}` it does not add `<s>` or `</s>`

So, as you suggested, I will set `add_eos_token=False` if both of the aforementioned options are set to True. Thanks!
