### ISSUE TITLE
Question about conversation format in SFT Trainer

### ISSUE THREAD

**Issue by luffycodes** [huggingface/trl#1285]
hello, i was wondering how to preprocess the conversations into the new conversation format supported by trl.
The docs recommend the following [format](https://huggingface.co/docs/trl/sft_trainer#dataset-format-support):

`{"messages": [{"role": "system", "content": "You are helpful"}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "It is Zurich"}]}`

**the question is for multiple rounds in a conversation, let's say two, does the message json look like this?**
`{"messages": [{"role": "system", "content": "You are helpful"}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "It is Zurich" }, {"role": "user", "content": Are you sure?"}, {"role": "assistant", "content": "Yes"}]}`

Or do i need to append the system prompt for each round like this?
the question is for multiple rounds in a conversation let's say two, does the message json look like this?
`{"messages": [{"role": "system", "content": "You are helpful"}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "It is Zurich" }, {"role": "system", "content": "You are helpful"},{"role": "user", "content": Are you sure?"}, {"role": "assistant", "content": "Yes"}]}`

**Comment by vk-maurya** [comment]
It appears that your goal is to develop a dataset for training conversations. In order to accomplish this, it is essential to comprehend the inference aspect of the process. Specifically, you must transmit the system message only once throughout the entire conversation. Consequently, the second option is the appropriate choice.

Here is an example JSON for a two-round conversation(dataset row1):

```
{"messages": [
    {"role": "system", "content": "You are helpful"},
    {"role": "user", "content": "What's the capital of France?"},
    {"role": "assistant", "content": "It is Zurich" },
    {"role": "user", "content": "Are you sure?"},
    {"role": "assistant", "content": "Yes"}
]}
```
Here is an example JSON for a three-round conversation(dataset row2):

```
{"messages": [
    {"role": "system", "content": "You are helpful"},
    {"role": "user", "content": "What's the capital of France?"},
    {"role": "assistant", "content": "It is Zurich" },
    {"role": "user", "content": "Are you sure?"},
    {"role": "assistant", "content": "Yes"},
    {"role": "user", "content": "Tell me more."},
    {"role": "assistant", "content": "Paris is the largest city and the capital of France."}
]}
```

So your dataset will be created accordingly.
