### ISSUE TITLE
The Dpo_trainer.py and trainer_pt_utils.py in the transformers package are not compatible.

### ISSUE THREAD

**Issue by jiahe7ay** [huggingface/trl#1288]
### 1.Error
ValueError(
                    "Can only automatically infer lengths for datasets whose items are dictionaries with an input_ids key."

### 2. Package version
My version of TRL is 0.7.10 and transformers is 4.36.2

### 3. My code

````

from dataclasses import dataclass, field
from typing import List, Optional, Dict

from datasets import load_dataset
from transformers import PreTrainedTokenizerFast, PhiForCausalLM, TrainingArguments, TrainerCallback
import pandas as pd
import time
import torch 
from trl import DPOTrainer



dpo_file = './data/dpo_train_data.json'
tokenizer_dir = './model_save/tokenizer/'
sft_from_checkpoint_file = './model_save/sft/'
model_save_dir = './model_save/dpo/'
max_seq_len = 320


tokenizer = PreTrainedTokenizerFast.from_pretrained(tokenizer_dir)
print(f"vicab size: {len(tokenizer)}")

dataset = load_dataset(path='json', data_files=dpo_file, split='train', cache_dir='.cache')

def split_prompt_and_responses(samples: dict[str, str]) -> Dict[str, str]:
        prompts, chosens, rejects = [], [], []
        batch_size = len(samples['prompt'])
        for i in range(batch_size):
            # add an eos token for signal that end of sentence, using in generate.
            prompts.append(f"[BOS]{samples['prompt'][i]}[EOS]")
            chosens.append(f"[BOS]{samples['chosen'][i]}[EOS]")
            rejects.append(f"[BOS]{samples['rejected'][i]}[EOS]")

        return {
              'prompt': prompts,
              'chosen': chosens,
              'rejected':rejects,
        }

dataset = dataset.map(split_prompt_and_responses, batched=True,).shuffle(2333)

model = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)
model_ref = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)

model_size = sum(t.numel() for t in model.parameters())
print(f"Phi-2 size: {model_size / 1000**2:.1f}M parameters")


class EmptyCudaCacheCallback(TrainerCallback):
    log_cnt = 0
    def on_log(self, args, state, control, logs=None, **kwargs):
        self.log_cnt += 1
        if self.log_cnt % 5 == 0:
            torch.cuda.empty_cache()
            
empty_cuda_cahce = EmptyCudaCacheCallback()


args = TrainingArguments(
    output_dir=model_save_dir,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=16,
    num_train_epochs=4,
    weight_decay=0.1,
    warmup_steps=1000,
    learning_rate=2e-5,
    save_steps=2000,
    save_total_limit=3,
    report_to='tensorboard',
    bf16=True,
    logging_steps=10,
    log_level='info',
    logging_first_step=True,
    optim="adafactor",
    remove_unused_columns=False,
    group_by_length=True,
)

trainer = DPOTrainer(
    model,
    model_ref,
    args=args,
    beta=0.1,
    train_dataset=dataset,
    tokenizer=tokenizer,
    callbacks=[empty_cuda_cahce],
    max_length=max_seq_len * 2 + 16, # 16 for eos bos
    max_prompt_length=max_seq_len,
)


trainer.train()

loss_log = pd.DataFrame(trainer.state.log_history)
loss_log.to_csv(f"./logs/dpo_train_log_{time.strftime('%Y%m%d-%H%M')}.csv")


trainer.save_model(model_save_dir)

````

### Solution

This is not a problem with my code, as I encounter the same error even when following the official DPO tutorial.

So I delved into the source code and discovered the root of the problem.

In the LengthGroupedSampler class within trainer_pt_utils.py of the transformers library:
````
model_input_name = model_input_name if model_input_name is not None else "input_ids"
lengths = [len(feature[model_input_name]) for feature in dataset]
````
These two lines of code are responsible for obtaining the lengths to be used for sampling. Specifically, they retrieve the length of the **'input_ids'** feature  in the dataset. If model_input_name has a specified value, it will use that as the key to access the relevant feature; otherwise, it defaults to using "input_ids". The list comprehension then calculates the lengths based on these features across the entire dataset.

In the **Dpo_trainer.py** at line **692,** I found that the **'input_ids'** key in the batch was missing after printing out the batch. 

However, the 'input_ids' key was present in the chosen_sequence_tokens above. Therefore, I reassigned the 'input_ids' value to the batch: **batch['input_ids'] = chosen_sequence_tokens['input_ids'].** This resolved the issue.

So, the crux of this issue lies in the construction of the batch where the 'input_ids' key was inadvertently dropped. It's unclear whether this is due to an incorrect usage on my part or if it's indeed a bug within the system itself.

**Comment by younesbelkada** [comment]
cc @kashif

**Comment by Minami-su** [comment]
> ### 1.Error
> ValueError( "Can only automatically infer lengths for datasets whose items are dictionaries with an input_ids key."
> 
> ### 2. Package version
> My version of TRL is 0.7.10 and transformers is 4.36.2
> 
> ### 3. My code
> ```
> 
> from dataclasses import dataclass, field
> from typing import List, Optional, Dict
> 
> from datasets import load_dataset
> from transformers import PreTrainedTokenizerFast, PhiForCausalLM, TrainingArguments, TrainerCallback
> import pandas as pd
> import time
> import torch 
> from trl import DPOTrainer
> 
> 
> 
> dpo_file = './data/dpo_train_data.json'
> tokenizer_dir = './model_save/tokenizer/'
> sft_from_checkpoint_file = './model_save/sft/'
> model_save_dir = './model_save/dpo/'
> max_seq_len = 320
> 
> 
> tokenizer = PreTrainedTokenizerFast.from_pretrained(tokenizer_dir)
> print(f"vicab size: {len(tokenizer)}")
> 
> dataset = load_dataset(path='json', data_files=dpo_file, split='train', cache_dir='.cache')
> 
> def split_prompt_and_responses(samples: dict[str, str]) -> Dict[str, str]:
>         prompts, chosens, rejects = [], [], []
>         batch_size = len(samples['prompt'])
>         for i in range(batch_size):
>             # add an eos token for signal that end of sentence, using in generate.
>             prompts.append(f"[BOS]{samples['prompt'][i]}[EOS]")
>             chosens.append(f"[BOS]{samples['chosen'][i]}[EOS]")
>             rejects.append(f"[BOS]{samples['rejected'][i]}[EOS]")
> 
>         return {
>               'prompt': prompts,
>               'chosen': chosens,
>               'rejected':rejects,
>         }
> 
> dataset = dataset.map(split_prompt_and_responses, batched=True,).shuffle(2333)
> 
> model = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)
> model_ref = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)
> 
> model_size = sum(t.numel() for t in model.parameters())
> print(f"Phi-2 size: {model_size / 1000**2:.1f}M parameters")
> 
> 
> class EmptyCudaCacheCallback(TrainerCallback):
>     log_cnt = 0
>     def on_log(self, args, state, control, logs=None, **kwargs):
>         self.log_cnt += 1
>         if self.log_cnt % 5 == 0:
>             torch.cuda.empty_cache()
>             
> empty_cuda_cahce = EmptyCudaCacheCallback()
> 
> 
> args = TrainingArguments(
>     output_dir=model_save_dir,
>     per_device_train_batch_size=2,
>     gradient_accumulation_steps=16,
>     num_train_epochs=4,
>     weight_decay=0.1,
>     warmup_steps=1000,
>     learning_rate=2e-5,
>     save_steps=2000,
>     save_total_limit=3,
>     report_to='tensorboard',
>     bf16=True,
>     logging_steps=10,
>     log_level='info',
>     logging_first_step=True,
>     optim="adafactor",
>     remove_unused_columns=False,
>     group_by_length=True,
> )
> 
> trainer = DPOTrainer(
>     model,
>     model_ref,
>     args=args,
>     beta=0.1,
>     train_dataset=dataset,
>     tokenizer=tokenizer,
>     callbacks=[empty_cuda_cahce],
>     max_length=max_seq_len * 2 + 16, # 16 for eos bos
>     max_prompt_length=max_seq_len,
> )
> 
> 
> trainer.train()
> 
> loss_log = pd.DataFrame(trainer.state.log_history)
> loss_log.to_csv(f"./logs/dpo_train_log_{time.strftime('%Y%m%d-%H%M')}.csv")
> 
> 
> trainer.save_model(model_save_dir)
> ```
> 
> ### Solution
> This is not a problem with my code, as I encounter the same error even when following the official DPO tutorial.
> 
> So I delved into the source code and discovered the root of the problem.
> 
> In the LengthGroupedSampler class within trainer_pt_utils.py of the transformers library:
> 
> ```
> model_input_name = model_input_name if model_input_name is not None else "input_ids"
> lengths = [len(feature[model_input_name]) for feature in dataset]
> ```
> 
> These two lines of code are responsible for obtaining the lengths to be used for sampling. Specifically, they retrieve the length of the **'input_ids'** feature in the dataset. If model_input_name has a specified value, it will use that as the key to access the relevant feature; otherwise, it defaults to using "input_ids". The list comprehension then calculates the lengths based on these features across the entire dataset.
> 
> In the **Dpo_trainer.py** at line **692,** I found that the **'input_ids'** key in the batch was missing after printing out the batch.
> 
> However, the 'input_ids' key was present in the chosen_sequence_tokens above. Therefore, I reassigned the 'input_ids' value to the batch: **batch['input_ids'] = chosen_sequence_tokens['input_ids'].** This resolved the issue.
> 
> So, the crux of this issue lies in the construction of the batch where the 'input_ids' key was inadvertently dropped. It's unclear whether this is due to an incorrect usage on my part or if it's indeed a bug within the system itself.

I have the same issue, and I believe that group_by_length=True is causing the error.

**Comment by jiahe7ay** [comment]
> > ### 1.Error
> > ValueError( "Can only automatically infer lengths for datasets whose items are dictionaries with an input_ids key."
> > ### 2. Package version
> > My version of TRL is 0.7.10 and transformers is 4.36.2
> > ### 3. My code
> > ```
> > 
> > from dataclasses import dataclass, field
> > from typing import List, Optional, Dict
> > 
> > from datasets import load_dataset
> > from transformers import PreTrainedTokenizerFast, PhiForCausalLM, TrainingArguments, TrainerCallback
> > import pandas as pd
> > import time
> > import torch 
> > from trl import DPOTrainer
> > 
> > 
> > 
> > dpo_file = './data/dpo_train_data.json'
> > tokenizer_dir = './model_save/tokenizer/'
> > sft_from_checkpoint_file = './model_save/sft/'
> > model_save_dir = './model_save/dpo/'
> > max_seq_len = 320
> > 
> > 
> > tokenizer = PreTrainedTokenizerFast.from_pretrained(tokenizer_dir)
> > print(f"vicab size: {len(tokenizer)}")
> > 
> > dataset = load_dataset(path='json', data_files=dpo_file, split='train', cache_dir='.cache')
> > 
> > def split_prompt_and_responses(samples: dict[str, str]) -> Dict[str, str]:
> >         prompts, chosens, rejects = [], [], []
> >         batch_size = len(samples['prompt'])
> >         for i in range(batch_size):
> >             # add an eos token for signal that end of sentence, using in generate.
> >             prompts.append(f"[BOS]{samples['prompt'][i]}[EOS]")
> >             chosens.append(f"[BOS]{samples['chosen'][i]}[EOS]")
> >             rejects.append(f"[BOS]{samples['rejected'][i]}[EOS]")
> > 
> >         return {
> >               'prompt': prompts,
> >               'chosen': chosens,
> >               'rejected':rejects,
> >         }
> > 
> > dataset = dataset.map(split_prompt_and_responses, batched=True,).shuffle(2333)
> > 
> > model = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)
> > model_ref = PhiForCausalLM.from_pretrained(sft_from_checkpoint_file)
> > 
> > model_size = sum(t.numel() for t in model.parameters())
> > print(f"Phi-2 size: {model_size / 1000**2:.1f}M parameters")
> > 
> > 
> > class EmptyCudaCacheCallback(TrainerCallback):
> >     log_cnt = 0
> >     def on_log(self, args, state, control, logs=None, **kwargs):
> >         self.log_cnt += 1
> >         if self.log_cnt % 5 == 0:
> >             torch.cuda.empty_cache()
> >             
> > empty_cuda_cahce = EmptyCudaCacheCallback()
> > 
> > 
> > args = TrainingArguments(
> >     output_dir=model_save_dir,
> >     per_device_train_batch_size=2,
> >     gradient_accumulation_steps=16,
> >     num_train_epochs=4,
> >     weight_decay=0.1,
> >     warmup_steps=1000,
> >     learning_rate=2e-5,
> >     save_steps=2000,
> >     save_total_limit=3,
> >     report_to='tensorboard',
> >     bf16=True,
> >     logging_steps=10,
> >     log_level='info',
> >     logging_first_step=True,
> >     optim="adafactor",
> >     remove_unused_columns=False,
> >     group_by_length=True,
> > )
> > 
> > trainer = DPOTrainer(
> >     model,
> >     model_ref,
> >     args=args,
> >     beta=0.1,
> >     train_dataset=dataset,
> >     tokenizer=tokenizer,
> >     callbacks=[empty_cuda_cahce],
> >     max_length=max_seq_len * 2 + 16, # 16 for eos bos
> >     max_prompt_length=max_seq_len,
> > )
> > 
> > 
> > trainer.train()
> > 
> > loss_log = pd.DataFrame(trainer.state.log_history)
> > loss_log.to_csv(f"./logs/dpo_train_log_{time.strftime('%Y%m%d-%H%M')}.csv")
> > 
> > 
> > trainer.save_model(model_save_dir)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Solution
> > This is not a problem with my code, as I encounter the same error even when following the official DPO tutorial.
> > So I delved into the source code and discovered the root of the problem.
> > In the LengthGroupedSampler class within trainer_pt_utils.py of the transformers library:
> > ```
> > model_input_name = model_input_name if model_input_name is not None else "input_ids"
> > lengths = [len(feature[model_input_name]) for feature in dataset]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These two lines of code are responsible for obtaining the lengths to be used for sampling. Specifically, they retrieve the length of the **'input_ids'** feature in the dataset. If model_input_name has a specified value, it will use that as the key to access the relevant feature; otherwise, it defaults to using "input_ids". The list comprehension then calculates the lengths based on these features across the entire dataset.
> > In the **Dpo_trainer.py** at line **692,** I found that the **'input_ids'** key in the batch was missing after printing out the batch.
> > However, the 'input_ids' key was present in the chosen_sequence_tokens above. Therefore, I reassigned the 'input_ids' value to the batch: **batch['input_ids'] = chosen_sequence_tokens['input_ids'].** This resolved the issue.
> > So, the crux of this issue lies in the construction of the batch where the 'input_ids' key was inadvertently dropped. It's unclear whether this is due to an incorrect usage on my part or if it's indeed a bug within the system itself.
> 
> I have the same issue, and I believe that group_by_length=True is causing the error.

So you set group_by_length=False and the problem was solved?

**Comment by Edenzzzz** [comment]
In my case, I'm doing mmlu eval like this, and the training forces eval to group by length too, which is kind of dumb.
https://github.com/SprocketLab/sparse_matrix_fine_tuning/blob/c6893029f3514220e2db944cff6ef0cd212a48ff/qlora/qlora_monarch.py#L671
