### ISSUE TITLE
import SFTTrainer from trl has error

### ISSUE THREAD

**Issue by zl1e08** [huggingface/trl#1293]
When I try to import SFTTrainer from trl,

from trl import SFTTrainer

The following error comes out:

ImportError: cannot import name 'convert_state_dict_to_diffusers' from 'diffusers.utils'

I am using windows machine and install the trl via:
pip install -U git+https://github.com/huggingface/trl

**Comment by younesbelkada** [comment]
Hi @zl1e08 
That method should be still importable: https://github.com/huggingface/diffusers/blob/main/src/diffusers/utils/__init__.py#L100 what is the diffusers version you are using? can you try out with the most recent version of diffusers: `pip install -U diffusers`?

**Comment by younesbelkada** [comment]
cc @sayakpaul FYI

**Comment by zl1e08** [comment]
Hi, thanks for your reply. after updaing to the lastest version diffuser, the issue is fixed. Thanks!

**Comment by SaqlainHussainShah** [comment]
I was having same error on colab so i commented line `from transformers import top_k_top_p_filtering` inside trl/core.py file and it si working now. 
![image](https://github.com/huggingface/trl/assets/13719933/4c0017e1-b664-4a44-aee9-372f9744a7af)

**Comment by aseef2289** [comment]
@SaqlainHussainShah How did you access trl/core.py ? I am using kaggle. is there an way I can access this file directly.
