### ISSUE TITLE
Feature Request: Contrastive Preference Optimization (CPO)

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/trl#1318]
It's pretty much DPO without the reference model

Here's the paper 

https://huggingface.co/papers/2401.08417

**Comment by norabelrose** [comment]
If it's literally DPO without the reference model then this is already possible with `DPOTrainer`? If there's a slight difference in the loss we might be able to just add a new loss type

**Comment by anderleich** [comment]
Any news on this?
