### ISSUE TITLE
Kbit_device_map import error. DPO

### ISSUE THREAD

**Issue by sankydesai** [huggingface/trl#1319]
from trl import get_kbit_device_map

ImportError                               Traceback (most recent call last)
[<ipython-input-8-7531915a94f4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from trl import get_kbit_device_map

ImportError: cannot import name 'get_kbit_device_map' from 'trl' (/usr/local/lib/python3.10/dist-packages/trl/__init__.py)

Also Tried from trl.trainer.utils
Still Got:

ImportError      
Traceback (most recent call last)

----> 1 from trl.trainer.utils import get_kbit_device_map

ImportError: cannot import name 'get_kbit_device_map' from 'trl.trainer.utils' (/usr/local/lib/python3.10/dist-packages/trl/trainer/utils.py)

**Comment by younesbelkada** [comment]
hi @sankydesai 
Can you update TRL? `pip install -U trl` and let me know if you still face the issue

**Comment by sankydesai** [comment]
Nope. The issue is very simple. I went to colab, did pip install -U trl and then imported  from trl import get_kbit_device_map. It fails. Please check.

**Comment by younesbelkada** [comment]
Hi @sankydesai 
Sorry for the confusion, as https://github.com/huggingface/trl/pull/1176 is not included in the pypi release, you need to install TRL from source
```bash
pip install -U git+https://github.com/huggingface/trl
```

**Comment by younesbelkada** [comment]
closing as we made a recent release
