### ISSUE TITLE
Questionable best-practice recommendation in DPO docs

### ISSUE THREAD

**Issue by R-seny** [huggingface/trl#1324]
[This DPO documentation page](https://huggingface.co/docs/trl/dpo_trainer) suggests that the best way to merge adaptors is to merge them into a quantized model and then dequantize, quoting [this tweet](https://twitter.com/Tim_Dettmers/status/1694654191325573456) with anecdotal evidence (no measurements).

This goes against common intuition (QLoRA trains high-precision adapters to compensate for quantization precision losses, so merging them into a highly quantized is highly unintuitive). It also goes against some [more in-depth investigations](https://medium.com/@bnjmn_marie/dont-merge-your-lora-adapter-into-a-4-bit-llm-65b6da287997) and does not mention principled research approaches, e.g. [QALoRA](https://arxiv.org/abs/2309.14717).

Moreover, the script linked as an example goes against the recommendation in the tweet, first DEquantizing the model and then merging. Maybe there was simply a typo in the referenced tweet.

I also don't fully understand where the 1-2% performance loss figure comes from in the next sentence. Maybe it's a coincidence, but this is similar to the reported advantage of QALoRA vs regular merging, but QALoRA is not the same thing as what the tweet suggests.

I submitted a pull request with a slightly revised version of this and the next paragraphs (https://github.com/huggingface/trl/pull/1325).

**Comment by younesbelkada** [comment]
Thanks for submitting the PR to address that! Closing the issue as #1325 being merged
