### ISSUE TITLE
RewardTrainer multiple forward passes

### ISSUE THREAD

**Issue by IvanSedykh** [huggingface/trl#1345]
During RewardModel training we do 2 forward passes for each batch -- one for the chosen samples and the other for rejected ones.
The link to the related code is below:

https://github.com/huggingface/trl/blob/a46cd84a6405312837f0d0e56fd1cf4d45585770/trl/trainer/reward_trainer.py#L228-L242

Wouldn't it be better (probably more efficient in some cases) if we concatenate these samples and perform a single forward pass with 2х actual batch size like in `DPOTrainer`? 
May be add this as an option somehow.

What do you think? Is it reasonable?

**Comment by younesbelkada** [comment]
It's totally reasonable and it makes a lot of sense, would you like to give it a try 🙏 ? I'll be happy to assist / guide you, it seems you just need to change that piece of code right?

**Comment by younesbelkada** [comment]
awesome @IvanSedykh , looking forward to it !

**Comment by IvanSedykh** [comment]
bump
The issue still persists, I will work on this later
