### ISSUE TITLE
The average ratio of batch exceeds threshold 10.00. Skipping batch.

### ISSUE THREAD

**Issue by jinz2014** [huggingface/trl#1347]
Can you please provide some instructions/suggestions about what new users of TRL need to do when seeing the message ?  

Thanks

**Comment by younesbelkada** [comment]
Hi @jinz2014 
Can you share a snippet on how you get that error message?

**Comment by jinz2014** [comment]
gpt-j-6b-toxicity.py --model_name mistralai/Mistral-7B-Instruct-v0.2 --log_with wandb 

Thanks.

**Comment by jinz2014** [comment]
Make it unstale.

**Comment by ritwikmishra** [comment]
Looking for an explanation for this.

**Comment by jinz2014** [comment]
@ritwikmishra  Thanks.
