### ISSUE TITLE
Can no longer train custom models with the newer version of trl

### ISSUE THREAD

**Issue by mobicham** [huggingface/trl#1351]
So in the previous versions, I was able to train some custom models (not pure transformers model) by wrapping the model as follows:

``` Python
class WrappedModel(torch.nn.Module):
	def __init__(self, model):
		super().__init__()
		self.model = model

	def forward(self, *args, **kwargs):
		return self.model.forward(*args, **kwargs)

	def train(self):
		return self.model.train()

	def eval(self):
		return self.model.eval()

	def parameters(self):
		return self.model.parameters()

```

Then I was just using SFTTrainer and calling` model=WrappedModel(model)` and it was working fine. 
Now it complains about: 

> ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

and if I remove `remove_unused_columns=False` it complains about the index of the data:

> IndexError: Invalid key: 1088 is out of bounds for size 0

The same code with a transformers model works. 

I am not sure why would it complain about the data/tokenization. Is there something I need to add in my wrapped model after the latest updates?
Thank you in advance!

**Comment by younesbelkada** [comment]
Hi @mobicham ! 👋 
Great to see you here ! 
Do you have a simple reproducer snippet using SFTTrainer & a small dataset, let's say `imdb` - do you also have an idea on from when it started failing for you?

**Comment by mobicham** [comment]
Hi @younesbelkada ! Thank you for your reply!

So it was working fine about a month ago. You can find an example here: https://github.com/mobiusml/hqq/blob/master/examples/lora/train_hqq_lora_example.py . This should produce: 

> ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

The only reason I wrap the model is because it complains it can't use the function `parameters()` , but it is already there. The wrapping fixed that issue at that time.
