### ISSUE TITLE
max_grad_norm for DPOTrainer?

### ISSUE THREAD

**Issue by kmn1024** [huggingface/trl#1356]
There doesn't seem to be a max_grad_norm for DPOTrainer. Is this because the DPOTrainer algorithms tend to be quite stable already?

When using DPO, I've noticed that small models (3B or less) seem less stable than larger ones - high grad_norm's get reported, and then the generated output becomes gibberish. Is this something max_grad_norm could help with?

**Comment by kashif** [comment]
we can add it to the DPOTrainer configs as an option, would you like to send a PR?
