### ISSUE TITLE
load_in_8bit deprecated in llama rl script

### ISSUE THREAD

**Issue by HassanJbara** [huggingface/trl#1361]
Running the script in `examples/research_projects/stack_llama/scripts/rl_training.py` with the following command:

```
accelerate launch --multi_gpu --num_machines 1  --num_processes 4 llama_example.py --model_name meta-llama/Llama-2-7b-chat-hf 
--tokenizer_name meta-llama/Llama-2-7b-chat-hf --log_with wandb --reward_model text-classification:Hello-SimpleAI/chatgpt-detector-roberta
```

produces the following error messages:

```
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
raise ImportError(
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`
```

Latest version of all the libraries.
```
trl=0.7.11
accelerate=0.27.2
torch=2.0.1
transformers=4.38.1
```

I assume that the script needs updating.

**Comment by SAMMYBOOOOM** [comment]
Any solution for this?

**Comment by HassanJbara** [comment]
> Any solution for this?

Presumably the proposed solution is in the error message. I created the issue to notify the maintainers of the examples in need of updates.

**Comment by younesbelkada** [comment]
Hi everyone! 
Thanks for the issue !
The research projects scripts are not really maintained by now, the fix should be fairly easy, just replace `load_in_8bit=True` by `quantization_config=BitsAndBytesConfig(load_in_8bit=True)`. Would you like to open a PR for the fix? Otherwise happy to do it !

**Comment by HassanJbara** [comment]
> Hi everyone! Thanks for the issue ! The research projects scripts are not really maintained by now, the fix should be fairly easy, just replace `load_in_8bit=True` by `quantization_config=BitsAndBytesConfig(load_in_8bit=True)`. Would you like to open a PR for the fix? Otherwise happy to do it !

Do what you see fit. This issue is not that important, but can you check this one please?
https://github.com/huggingface/trl/issues/1381
