### ISSUE TITLE
ref_model for training PEFT model with DPO

### ISSUE THREAD

**Issue by rachellxy** [huggingface/trl#1365]
In the current version of the DPO trainer, it appears that the ref_model needs to be set as None when utilizing a PEFT model (a peft_config is passed during trainer initialization), and the PEFT model with adapters disabled will be used as the ref_model by default. In our experiments, the ref_model is a different model from the base model, so we cannot directly use the current implementation. I am wondering whether it would be possible to allow the option of passing in a ref_model for training PEFT model with DPO, or could you please suggest any workarounds for our experiments using the current DPO?

Your guidance and help would be greatly appreciated. Thank you very much!

**Comment by younesbelkada** [comment]
hi @rachellxy 
This makes sense, I just made https://github.com/huggingface/trl/pull/1367 which should fix this issue, you would have to pass `force_use_ref_model` in the DPOTrainer's init method
