### ISSUE TITLE
 memory usage of DPO trainer seems stepwise growing with time

### ISSUE THREAD

**Issue by Emerald01** [huggingface/trl#1377]
Hi, 

I am DPO training a checkpoint of Mixtral-8x7B-Instruct, from the previous supervised finetune. 

I mainly followed this script https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
with 8 H100 GPUs, flash attn and deepspeed zero 2, everything looks good but I notice that the memory consumption has stepwise growing. 

Any ideas why it is not a constant? Look like there is some memory garbage collection issues?

<img width="1814" alt="Screenshot 2024-02-27 at 8 00 52 PM" src="https://github.com/huggingface/trl/assets/31748898/7ef7c1bc-333e-4df5-b73e-f9f2b29ff927">

**Comment by younesbelkada** [comment]
cc @kashif have you ever experienced with this?

**Comment by sambroy** [comment]
I am seeing something similar for some PPO runs also, using Mistral-7b-v01 on 4 A100s. 

I am using the https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama/scripts/rl_training.py code with the ultrafeedback dataset. 
<img width="1234" alt="firefox_GJYEaLTbv6" src="https://github.com/huggingface/trl/assets/65827957/792e1908-1fff-4028-997c-f2d9e27f6ce8">

<img width="836" alt="firefox_6RyyMTClt7" src="https://github.com/huggingface/trl/assets/65827957/04a71e53-7268-48bb-a25a-831fd811fa89">

**Comment by saeedkhaki92** [comment]
@Emerald01 could you share your zero2 config? do you use cpu offloading?
I have the same problem as it goes out of memory after some steps with Mixtral. 
My env: 8 A-100 GPUS

**Comment by younesbelkada** [comment]
Hi ! 
Can you try to clear the cuda cache between each training step? 
You could modify the DPOTrainer source code to overwrite `def training_step()` method: https://github.com/huggingface/transformers/blob/e9476832942a19cf99354776ef112babc83c139a/src/transformers/trainer.py#L2848 and call `torch.cuda.empty_cache()` after each step together with `gc.collect()`

**Comment by Emerald01** [comment]
@younesbelkada that works!

**Comment by younesbelkada** [comment]
oh nice! 
cc @muellerz do you know if Trainer properly handles `torch.cuda.empty_cache()` affter each training step? Perhaps worth making a PR on transformers side? Let me know if you want me to have a look as well

**Comment by Emerald01** [comment]
@younesbelkada 
I believe transformer does not properly clear the cache after each training step, after your suggestion, I did the empty cache and gc collection, compared to the previous stepwise growing memory, now it becomes almost a constant
```
    def training_step(self, model: nn.Module, inputs: Dict[str, Union[torch.Tensor, Any]]) -> torch.Tensor:
        loss_step = super().training_step(model, inputs)
        torch.cuda.empty_cache()
        gc.collect()
        return loss_step
```
The following is the current GPU memory running the same script
<img width="1685" alt="Screenshot 2024-03-06 at 9 30 09 AM" src="https://github.com/huggingface/trl/assets/31748898/ed8d4583-0591-41ad-8cdb-e578df157c2f">
