### ISSUE TITLE
KTOTrainer and KTOConfig not importing

### ISSUE THREAD

**Issue by jackhogan** [huggingface/trl#1389]
`from trl import KTOTrainer` yields `ImportError: cannot import name 'KTOTrainer' from 'trl'`.

I tried upgrading from source and the problem persists. Perhaps a circular import?

**Comment by kashif** [comment]
it could be an older installation? can you try to `pip uninstall trl` and then try to install from main? We will try to cut a new version with KTO shortly

**Comment by jackhogan** [comment]
Thanks, yes it seems to only be a problem in v0.7.11. When I install from main (v0.7.12.dev0), it works.
