### ISSUE TITLE
DPOTrainer: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! 

### ISSUE THREAD

**Issue by sanduntharaka** [huggingface/trl#1399]
I have try to dpo trainer for  llama2. but in training step following error gives. Im using g5.12xlarge instance.
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3!

code is:

```
compute_dtype = getattr(torch, "float16")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

model = AutoPeftModelForCausalLM.from_pretrained(
    peft_model_path,  # location of saved SFT model
    device_map="auto",
    quantization_config=bnb_config,
)

model_ref = AutoPeftModelForCausalLM.from_pretrained(
    peft_model_path,  # same model as the main one
    device_map="auto",
    quantization_config=bnb_config,

)

tokenizer = AutoTokenizer.from_pretrained(
    peft_model_path, use_auth_token=hf_auth, trust_remote_code=True, device_map="auto")

training_args = TrainingArguments(
    output_dir=output_dir,
    remove_unused_columns=True,
    per_device_train_batch_size=4,
)

peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM",
)

dpo_trainer = DPOTrainer(
    model,
    model_ref,
    args=training_args,
    beta=0.1,
    train_dataset=dataset['train'],
    # eval_dataset=eval_dataset,
    tokenizer=tokenizer,
    peft_config=peft_config,
    max_length=1024,
    max_prompt_length=512,
)

dpo_trainer.train()
```

this instance has 4 GPUs 

GPU 0: NVIDIA A10G
GPU 1: NVIDIA A10G
GPU 2: NVIDIA A10G
GPU 3: NVIDIA A10G

Moreover i used    ref_model=None and device_map={"": PartialState().process_index} in both model and tokenizer. Then it gives : 
```
 output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 0 has a total capacity of 22.02 GiB of which 142.19 MiB is free. Including non-PyTorch memory, this process has 21.88 GiB memory in use. Of the allocated memory 19.27 GiB is allocated by PyTorch, and 1.35 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by fancyerii** [comment]
Do you the latest source code? We need to add to use DDP multi-gpu traning:

```
device_map = {"": Accelerator().local_process_index}
```

For llama 2 7b, I can train with ddp using a100 40GB gpu card. it will take about 30GB memory. So if you have gpu with 22 GB memory, you should train with fsdp or deepspeed to shard parameters/gradients.

**Comment by sanduntharaka** [comment]
@fancyerii I used your method but when training it uses a single GPU. Cannot increase  per_device_train_batch_size. Maximum  per_device_train_batch_size is 4, otherwise it  gives: 
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 274.00 MiB. GPU 0 has a total capacity of 22.02 GiB of which 26.19 MiB is free. Including non-PyTorch memory, this process has 21.99 GiB memory in use. Of the allocated memory 16.97 GiB is allocated by PyTorch, and 3.76 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
![image](https://github.com/huggingface/trl/assets/67332822/911c7e6e-3bf1-49ff-8889-b7f3eaac098a)

**Comment by fancyerii** [comment]
you don't have enough gpu memory, so you should set per_device_train_batch_size to 1. Also you should turn on load_in_4bit, low_cpu_mem_usage and gradient_checkpointing. These argument trys to lower the memory usage. But If you still find oom. I think you should use a gpu with more memory or use multiple gpus with fsdp/deepspeed to train.

**Comment by ra1995** [comment]
@fancyerii hi used your suggestion and though I don't face out of memory errors, Its only using 1 gpu for training, but memory on both gpus is in use. Could you suggest what needs to be done for parallelizing both gpus in DPOTrainer. Thanks
![image](https://github.com/huggingface/trl/assets/7086028/0e541a86-e67c-443e-a9e9-18e3ea82c0a0)
