### ISSUE TITLE
Bos token in `prompt_input_ids` but not in `completion_input_ids`?

### ISSUE THREAD

**Issue by fahadh4ilyas** [huggingface/trl#1401]
I've checked the way dataset in created in `KTOTrainer` and it seems that only `completion_` prefixed data that is fed into model.  But, data with `completion_` prefixed did not contain bos token at the beginning of sequence. Here is the result from `tokenizer_row` method in the trainer:

```python
{'prompt': 'How are you',
 'completion': 'leave me alone',
 'label': False,
 'completion_input_ids': [1602, 460, 368, 24427, 528, 4411, 2],
 'completion_attention_mask': [1, 1, 1, 1, 1, 1, 1],
 'completion_labels': [-100, -100, -100, 24427, 528, 4411, 2],
 'prompt_input_ids': [1, 1602, 460, 368],
 'prompt_attention_mask': [1, 1, 1, 1]}
```

Is this intentional?

**Comment by younesbelkada** [comment]
cc @kashif wdyt?

**Comment by kashif** [comment]
i believe this is intentional ... the completion are the resulting outputs from the given prompts and are in fact concerted together when being fed to the decoder-only model to calculate the log-probs

I think in real-life one also does not have a BOS token when generating...

**Comment by fahadh4ilyas** [comment]
> i believe this is intentional ... the completion are the resulting outputs from the given prompts and are in fact concated together when being fed to the decoder-only model to calculate the log-probs
> 
> I think in real-life one also does not have a BOS token when generating... 

The problem is, DPOTrainer is not like that. DPOTrainer is adding bos token to completion wether it's accepted or rejected. Even in KTOTrainer script there is a written comment telling that bos token is added to prompt (even though I don't know what for because only completion is fed to the model).

**Comment by kashif** [comment]
the BOS is added to prompt to make sure that the log-probs are in distribution as the model is auto-regressive... we can ask the KTO Trainer if he has time to chime in

cc @kawine

**Comment by kawine** [comment]
thanks for catching this @fahadh4ilyas ! you appear to be correct -- the completion IDs should have a BOS token at the beginning of the sequence. I think the confusion stems from "completion" being used in the code to refer to both the output on its own in some places and the input + output in other places

since this overloading of the term "completion" is used throughout, i'll push a minimal change to fix just the bug you identified for now. for your example with the huggyllama tokenizer, i'm now getting
```
{'prompt': 'How are you', 
'completion': ' leave me alone', 
'label': True, 
'prompt_input_ids': [1, 1128, 526, 366], 
'prompt_attention_mask': [1, 1, 1, 1], 
'completion_input_ids': [1, 1128, 526, 366, 5967, 592, 7432, 2], 
'completion_attention_mask': [1, 1, 1, 1, 1, 1, 1, 1], 
'completion_labels': [-100, -100, -100, -100, 5967, 592, 7432, 2]}
```
and if you tried to decode ```completion_input_ids```, you'd get '<s> How are you leave me alone</s>'
