### ISSUE TITLE
Can not import name top_k_top_p_filtering

### ISSUE THREAD

**Issue by chillestt** [huggingface/trl#1409]
Hello everyone, I just came across this kind of error, I cannot import trl because of this kind of error: 
```ImportError: cannot import name 'top_k_top_p_filtering' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)```
although I upgrade transformers library, it remained not working

https://github.com/huggingface/trl/blob/22b4f548f4954319ece6f17cab226a26e2db65be/trl/core.py#L25

**Comment by polarbeargo** [comment]
Same here I encountered the same error this week. Last week can imported SFTTrainer without this error. Other Developer also bumped into this error see this closed [issue](https://github.com/huggingface/trl/issues/6)
![git](https://github.com/huggingface/trl/assets/8589224/97c935af-b310-4cb5-a614-71d3270e07f4)

**Comment by dangl00** [comment]
Make sure that you have transformers version 4.38.2. Then, importing 'top_k_top_p_filtering' from"transformers.generation.utils" should work.

**Comment by baba-bug** [comment]
I use

`pip install --upgrade trl `

AND it worked for me

**Comment by vivekkaradbhajne23** [comment]
i also used 

`pip install --upgrade trl  `

and it worked for me

**Comment by rachitsaluja** [comment]
Upgrading it worked for me as well.

**Comment by Gaomengcanbestrong** [comment]
Upgrading it didn't work for me.555

**Comment by rdhande92** [comment]
i also used

pip install --upgrade trl  

and it worked for me

**Comment by Usamamanzoor2** [comment]
ImportError: cannot import name 'top_k_top_p_filtering' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/__init__.py)
