### ISSUE TITLE
KTO - support loading the adapter twice

### ISSUE THREAD

**Issue by claralp** [huggingface/trl#1430]
For DPOTrainer there exists the option to load the Adapter from SFT training twice, as in [Reference model considerations with PEFT - load-the-adapter-twice](https://huggingface.co/docs/trl/main/en/dpo_trainer#using-option-3---load-the-adapter-twice):

``` python
# Initialize the trainer, without a ref_model param.
dpo_trainer = DPOTrainer(
    model,
    ...
    model_adapter_name="train",
    ref_adapter_name="reference",
)
```

In DPOTrainer this allows me to use a larger batch size and speed up training.
Would be cool to have this option in KTOTrainer as well. Anyone working on this already?

**Comment by PhilipMay** [comment]
Hi @lewtun , we had a discussion about KTO. Do you already work on this or should we come up with a PR?

**Comment by claralp** [comment]
@younesbelkada @kashif, is this a desired feature for you as well?  
If yes, is someone already implementing it or should we come up with a PR?

**Comment by kashif** [comment]
I believe would be good to have yes

**Comment by PhilipMay** [comment]
That feature would be super useful @claralp . Thanks.
