### ISSUE TITLE
AttributeError: 'ModelConfig' object has no attribute 'lora_task_type'

### ISSUE THREAD

**Issue by joshhu** [huggingface/trl#1432]
using the example script, shows the error
`AttributeError: 'ModelConfig' object has no attribute 'lora_task_type'`

another error shows when I put the lora_task_type to command line args
`ValueError: Some specified arguments are not used by the HfArgumentParser: ['--lora_task_type', 'SEQ_CLS']`

**Comment by younesbelkada** [comment]
can you share the command you use for training?

**Comment by younesbelkada** [comment]
as well as the full traceback of the issue

**Comment by joshhu** [comment]
> as well as the full traceback of the issue

Thank you for replying. 

The command line is
```
(llm) (JoshDev)joshhu:trl/ (main✓) $ python examples/scripts/reward_modeling.py \                             [0:21:56]
    --model_name_or_path="gpt2"  \
    --output_dir="reward_modeling_anthropic_hh" \
    --per_device_train_batch_size=64 \
    --num_train_epochs=1 \
    --gradient_accumulation_steps=16 \
    --gradient_checkpointing=True \
    --learning_rate=1.41e-5 \
    --remove_unused_columns=False \
    --optim="adamw_torch" \
    --logging_steps=10 \
    --evaluation_strategy="steps" \
    --max_length=512  \
    --lora_task_type = "SEQ_CLS"
```
and the traceback is
```
Traceback (most recent call last):
  File "/home/joshhu/playground/trl/examples/scripts/reward_modeling.py", line 45, in <module>
    reward_config, model_config = parser.parse_args_into_dataclasses()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joshhu/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/hf_argparser.py", line 347, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--lora_task_type', '=', 'SEQ_CLS']
```

**Comment by mengdi-li** [comment]
Hi @joshhu, I got the same issue. It can be solved by installing TRL from the source code. 

You need to first uninstall TRL of version _0.7.11:_
`pip uninstall trl`

and then install TRL from the souce code that was cloned from github:
`pip install -e path/to/local/trl`

The version of the newly installed TRL should be _0.7.12.dev0_ as of today

**Comment by joshhu** [comment]
> Hi @joshhu, I got the same issue. It can be solved by installing TRL from the source code.
> 
> You need to first uninstall TRL of version _0.7.11:_ `pip uninstall trl`
> 
> and then install TRL from the souce code that was cloned from github: `pip install -e path/to/local/trl`
> 
> The version of the newly installed TRL should be _0.7.12.dev0_ as of today

It now works, thank you.

**Comment by younesbelkada** [comment]
Thanks. ! closing the issue then
