### ISSUE TITLE
update in DPO raise several problems...

### ISSUE THREAD

**Issue by holarissun** [huggingface/trl#1440]
1. get_hh was removed. There is no dataset now.

2. from trl.commands.cli_utils import DpoScriptArguments, init_zero_verbose, TrlParser: No module named 'trl.commands'

**Comment by lvwerra** [comment]
Those changes are currently only on main, did you install TRL from source?

**Comment by steveepreston** [comment]
trl v0.13.0
```python
from trl.commands.cli_utils import TrlParser
```
error:
```
ModuleNotFoundError: No module named 'trl.commands'
```

**Comment by steveepreston** [comment]
Solution:
```python
from trl.scripts.utils import TrlParser
```
