### ISSUE TITLE
This PPOTrainer example code fails to run

### ISSUE THREAD

**Issue by nikihowe** [huggingface/trl#1442]
When running the code proposed [here](https://github.com/huggingface/trl/blob/304e208f778a5442c30cdda500348226cdc97d90/docs/source/ppo_trainer.mdx#L120), the first batch loaded in by the dataloader is `None` and the program crashes.

**Comment by nikihowe** [comment]
@younesbelkada Please note that this is a different file than that referenced by #1441 !

**Comment by MischaQI** [comment]
Same error. Did you address it? @nikihowe

**Comment by nikihowe** [comment]
> Same error. Did you address it? @nikihowe

I did not—my fix was for a different README file.
