### ISSUE TITLE
PPOTrainer.save_model is referenced in docs but is not implemented

### ISSUE THREAD

**Issue by nikihowe** [huggingface/trl#1443]
Referenced [here](https://github.com/huggingface/trl/blob/304e208f778a5442c30cdda500348226cdc97d90/docs/source/ppo_trainer.mdx#L136)

**Comment by younesbelkada** [comment]
Hi @nikihowe 
nice catch ! would you like to open a pr to replace `save_model` with `save_pretrained`?

**Comment by nikihowe** [comment]
It looks like #1537 fixed this.

**Comment by younesbelkada** [comment]
Nice, closing the issue then !
