### ISSUE TITLE
Is batch_size < num GPUs possible?

### ISSUE THREAD

**Issue by noamgat** [huggingface/trl#1445]
Hi,

I'm trying to train a LoRA on Mistral7B. When I increase the max_seq_length from 4096 to 8192, I'm getting CUDA out of memory errors, regardless of my configuration. I  think that it comes down to the fact that no matter what I try, the total train batch size is at least the number of GPUs, and I'm guessing that the attention buffers are not all able to fit on a single GPU:

For the sake of this experiment, I'm running on a machine with 4x80GB GPUs, but am still not able to avoid OOM errors.

I'm using accelerate, and have tried both zero3 and multi-gpu setups as shown in this guide:
https://huggingface.co/docs/trl/main/en/customization

The logs always end up like this:
```
[INFO|trainer.py:1812] 2024-03-19 08:23:08,065 >> ***** Running training *****
[INFO|trainer.py:1813] 2024-03-19 08:23:08,065 >>   Num examples = 3,057
[INFO|trainer.py:1814] 2024-03-19 08:23:08,065 >>   Num Epochs = 1
[INFO|trainer.py:1815] 2024-03-19 08:23:08,065 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1818] 2024-03-19 08:23:08,065 >>   Total train batch size (w. parallel, distributed & accumulation) = 4
[INFO|trainer.py:1819] 2024-03-19 08:23:08,066 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1820] 2024-03-19 08:23:08,066 >>   Total optimization steps = 765
[INFO|trainer.py:1821] 2024-03-19 08:23:08,070 >>   Number of trainable parameters = 13,631,488
```

Is there a configuration method to make this work?

**Comment by kashif** [comment]
@noamgat perhaps try to turn on gradient checkpointing?

**Comment by noamgat** [comment]
It was on
