### ISSUE TITLE
After supervised fine tuning, the model repeat the answer 

### ISSUE THREAD

**Issue by imrankh46** [huggingface/trl#1449]
Hi, I fine tune openchat 3.5 model using sft trainer with unsloth+peft library.
I use different chat template, adding eos token and with out... However after fine tuning and in inference time the model generate the answer,

After that the model, 
Generate question from it own and generate answer and repeat it to n time.
Like this

Question
....
Answer
....
Question
....
Answer
....

**Comment by bizhen46766** [comment]
Have you solved the problem?
