### ISSUE TITLE
A problem about trl-kto.py

### ISSUE THREAD

**Issue by Tyx-main** [huggingface/trl#1457]
When I test the example of kto.py:
https://github.com/huggingface/trl/blob/66b043a910594bb678466ca11d2e780c10566e47/examples/scripts/kto.py#L36

In the first step of training, here is an error:

`
RuntimeError:  element 0 if tensors does not require grad and does not have a grad_fn
`

Here is the detailed stack of error:
```
Traceback (most recent call last):
  File "examples/scripts/kto.py", line 152, in <module>
    kto_trainer.train()
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/transformers/trainer.py", line 2777, in training_step
    self.accelerator.backward(loss)
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/accelerate/accelerator.py", line 1966, in backward
    loss.backward(**kwargs)
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/trl/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Is it a probelm or we can fix it?

**Comment by kashif** [comment]
@Tyx-main i believe the issue is on your side... can you paste the exact command you used as well as your version of peft?

**Comment by sycny** [comment]
I have experienced a similar issue. I have tried the approaches in [#731](https://github.com/huggingface/trl/issues/731) and [#801](https://github.com/huggingface/trl/issues/801). None of them is working.

**Comment by Tyx-main** [comment]
> @Tyx-main i believe the issue is on your side... can you paste the exact command you used as well as your version of peft?

sorry for having not pasting:
```
python examples/scripts/kto.py \
    --model_name_or_path=gpt2 \
    --per_device_train_batch_size 4 \
    --max_steps 1000 \
    --learning_rate 1e-3 \
    --gradient_accumulation_steps 1 \
    --logging_steps 10 \
    --eval_steps 500 \
    --output_dir="kto_anthropic_hh" \
    --optim rmsprop \
    --warmup_steps 150 \
    --report_to wandb \
    --bf16 \
    --logging_first_step \
    --no_remove_unused_columns \
    --use_peft \
    --lora_r=16 \
    --lora_alpha=16
```

It seems that I haved not change anything, I tested it on several A100, the same error occured.

**Comment by Tyx-main** [comment]
> > @Tyx-main i believe the issue is on your side... can you paste the exact command you used as well as your version of peft?
> 
> @kashif kashifsorry for having not pasting:
> 
> ```
> python examples/scripts/kto.py \
>     --model_name_or_path=gpt2 \
>     --per_device_train_batch_size 4 \
>     --max_steps 1000 \
>     --learning_rate 1e-3 \
>     --gradient_accumulation_steps 1 \
>     --logging_steps 10 \
>     --eval_steps 500 \
>     --output_dir="kto_anthropic_hh" \
>     --optim rmsprop \
>     --warmup_steps 150 \
>     --report_to wandb \
>     --bf16 \
>     --logging_first_step \
>     --no_remove_unused_columns \
>     --use_peft \
>     --lora_r=16 \
>     --lora_alpha=16
> ```
> 
> It seems that I haved not change anything, I tested it on several A100, the same error occured.

**Comment by Tyx-main** [comment]
> I have experienced a similar issue. I have tried the approaches in [#731](https://github.com/huggingface/trl/issues/731) and [#801](https://github.com/huggingface/trl/issues/801). None of them is working.
> 
> Update:
> 
> I tried to include `torch.set_grad_enabled(True)` in `step()` function. It seems to work now.
> 
> I add it in every ppo_epochs, after `for _ in range(self.config.ppo_epochs):`, shown in [here](https://github.com/huggingface/trl/blob/423991c204c4b36d4aea6955eeb53140fbbea9bb/trl/trainer/ppo_trainer.py#L762)

@sycny  Thanks, Phd Shi, let me try to fix it via your method.

**Comment by Tyx-main** [comment]
> I have experienced a similar issue. I have tried the approaches in [#731](https://github.com/huggingface/trl/issues/731) and [#801](https://github.com/huggingface/trl/issues/801). None of them is working.
> 
> Update:
> 
> I tried to include `torch.set_grad_enabled(True)` in `step()` function. It seems to work now.
> 
> I add it in every ppo_epochs, after `for _ in range(self.config.ppo_epochs):`, shown in [here](https://github.com/huggingface/trl/blob/423991c204c4b36d4aea6955eeb53140fbbea9bb/trl/trainer/ppo_trainer.py#L762)

Thanks! Via your method, I found that if I add `loss.requires_grad_(True)` before
https://github.com/huggingface/transformers/blob/a81cf9ee90c2e3c802b6454e84a4545876382b7d/src/transformers/trainer.py#L3077

and I can train.

**Comment by philharmonikerzzy** [comment]
@Tyx-main @sycny 
i'm running into the same issue right now. do you guys know whether this should be something that's fixed in the latest transformers version, or did you just add this fix yourself locally?
