### ISSUE TITLE
SFTTrainer CUDA:out of memory

### ISSUE THREAD

**Issue by chenguang-200** [huggingface/trl#1475]
When I use SFTTrainer to train my model(starcoder2),CUDA:out of memory appear.I try to set PYTORCH_CUDA_ALLOC_CONF but nothing change.And It also have something wrong with accelerate.

> /home/llm/.conda/envs/wjy/lib/python3.9/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
  0%|                                                                                                                           | 0/1164 [00:00<?, ?it/s]/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "/home/llm/training.py", line 32, in <module>
    trainer.train()
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/trl/trainer/sft_trainer.py", line 360, in train
    output = super().train(*args, **kwargs)
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/transformers/trainer.py", line 1637, in train
    return inner_training_loop(
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/transformers/trainer.py", line 1974, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/transformers/trainer.py", line 2897, in training_step
    self.accelerator.backward(loss)
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/accelerate/accelerator.py", line 2001, in backward
    loss.backward(**kwargs)
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/llm/.conda/envs/wjy/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 23.64 GiB total capacity; 22.88 GiB already allocated; 133.69 MiB free; 23.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|          | 0/1164 [00:02<?, ?it/s]      

Moreover,when CUDA out of memory,I find out that only one of my CUDA is out of memory.
![$UB%7OT{44EMA98O9E`Z9NC](https://github.com/huggingface/trl/assets/139483199/f7790968-5157-4778-a84a-59c175545579)

My code are the following,how can I solve my problem?

````
from datasets import load_dataset
from transformers import AutoModelForCausalLM,TrainingArguments, Trainer
from trl import SFTTrainer
from accelerate import Accelerator

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:4000"

checkpoint = "/home/llm/wjy/starcoder2"

model = AutoModelForCausalLM.from_pretrained(checkpoint)
dataset = load_dataset("json", data_files="/home/llm/datasets/secure_programming_dpo.json")['train']

training_args = TrainingArguments(
    output_dir="./output",
    overwrite_output_dir=True,
    num_train_epochs=2,
    per_device_train_batch_size=4,
    save_steps=10_000,
    save_total_limit=4,
)

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    args=training_args,
    dataset_batch_size=4,
    dataset_text_field="vulnerability",
    max_seq_length=512,
)

trainer.train()
````

**Comment by halfrot** [comment]
@younesbelkada Seems like @ the wrong person?

**Comment by chenguang-200** [comment]
I have solved this problem bymodel = AutoModelForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.bfloat16)"

**Comment by chenguang-200** [comment]
I have solved this problem by
`model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.bfloat16)"`

**Comment by younesbelkada** [comment]
ok thanks !
