### ISSUE TITLE
Prompt format clarification for ORPO

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/trl#1484]
The [docs](https://huggingface.co/docs/trl/main/en/orpo_trainer) provide an example of prompt formatting:
```
orpo_dataset_dict = {
    "prompt": [
        "hello",
        "how are you",
        "What is your name?",
        "What is your name?",
        "Which is the best programming language?",
        "Which is the best programming language?",
        "Which is the best programming language?",
    ],
    "chosen": [
        "hi nice to meet you",
        "I am fine",
        "My name is Mary",
        "My name is Mary",
        "Python",
        "Python",
        "Java",
    ],
    "rejected": [
        "leave me alone",
        "I am not fine",
        "Whats it to you?",
        "I dont have a name",
        "Javascript",
        "C++",
        "C++",
    ],
}
```

My understanding is that, if one is using a chat template, the entries in the dictionary above should be formatted (not raw as shown).

It would be a nice addition if the docs could add a note on how chat_templates are to be used with ORPO.

**Comment by jannikjw** [comment]
I absolutely agree. Some formatting examples would be great.

**Comment by blakechi** [comment]
agree, and it's kind of misleading as most of the cases are instruction tuning.

Found [this](https://github.com/huggingface/alignment-handbook/blob/main/src/alignment/data.py#L42-L108) useful but doesn't apply to every chat templates.
