### ISSUE TITLE
ValueError: The model is offloaded on CPU or disk - CPU & disk offloading is not supported for ValueHead models.

### ISSUE THREAD

**Issue by WinstonLiyt** [huggingface/trl#1492]
Here is my code: 
```
model = AutoModelForCausalLMWithValueHead.from_pretrained(
        config.model_name,
        load_in_4bit=True,
        device_map="auto",
        peft_config=lora_config,
        quantization_config=BitsAndBytesConfig(llm_int8_enable_fp32_cpu_offload=True)
    )
```
Terminal output (Error): 
**File "predict_module/tuning_lm_with_rl.py", line 154, in tuning_lm_with_rl
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
  File "trl/models/modeling_base.py", line 308, in from_pretrained
    model.post_init(state_dict=state_dict)
  File "trl/models/modeling_value_head.py", line 238, in post_init
    raise ValueError(
ValueError: The model is offloaded on CPU or disk - CPU & disk offloading is not supported for ValueHead models.** 

Can anyone help me? TKS!!

**Comment by HassanJbara** [comment]
Having the same problem, is there a solution to this?

**Comment by EnsiyehRaoufi** [comment]
#Loading the model
model_name= "google/flan-ul2" 
original_model = AutoModelForSeq2SeqLM.from_pretrained(model_name, device_map="auto")

from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    r=32, # Rank
    lora_alpha=32,
    target_modules=["q", "v"], #print(model) to find its target module's names e.g. q_proj, query_proj etc.
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM # FLAN-T5 #"CAUSAL_LM" for Mixtral
)

peft_model = get_peft_model(original_model,
                            lora_config)

ppo_model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(peft_model,
                                                               torch_dtype=torch.bfloat16,
                                                               is_trainable=True)

After successfully loading the original Flan-UL2 model, I encounter the following error for running the last part of the above code:

ValueError                                Traceback (most recent call last)
[<ipython-input-14-8c0c59acb5a3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 ppo_model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(peft_model,
      2                                                                torch_dtype=torch.bfloat16,
      3                                                                is_trainable=True)
[/usr/local/lib/python3.10/dist-packages/trl/models/modeling_base.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    335 
    336         if is_resuming_training:
--> 337             model.post_init(state_dict=state_dict)
    338 
    339         return model

[/usr/local/lib/python3.10/dist-packages/trl/models/modeling_value_head.py](https://localhost:8080/#) in post_init(***failed resolving arguments***)
    330                 or "disk" in self.pretrained_model.hf_device_map.values()
    331             ):
--> 332                 raise ValueError(
    333                     "The model is offloaded on CPU or disk - CPU & disk offloading is not supported for ValueHead models."
    334                 )

ValueError: The model is offloaded on CPU or disk - CPU & disk offloading is not supported for ValueHead models.

I'm running the codes on the A100 GPUs of Colab Pro.

Any help would be greatly appreciated.

**Comment by younesbelkada** [comment]
Hi @EnsiyehRaoufi 
You are loading the reference model in full precision, can you try to load it in half-precision ? This might free-up some GPU memory and make sure to not offload the value head on the CPU
