### ISSUE TITLE
UserWarning: Could not find a config file

### ISSUE THREAD

**Issue by snassimr** [huggingface/trl#1498]
I am running pretty simple code :

```
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    peft_config=peft_config,
    max_seq_length = 4096,
    dataset_text_field="text",
    tokenizer=tokenizer,
    args=training_arguments,
    packing=False,
)

trainer.train()
```

and get UserWarning: Could not find a config file in /content/gdrive/MyDrive/Colab Notebooks/mcllma/Mistral-7B-Instruct-v0.2 - will assume that the vocabulary was not modified.

I guess it relates to Mistral's (base model) config.json is missing in checkpoint folder that Peft only .
Any clue how to fix it ?

**Comment by setayeshk** [comment]
> I am running pretty simple code :
> 
> ```
> from trl import SFTTrainer
> 
> trainer = SFTTrainer(
>     model=model,
>     train_dataset=train_dataset,
>     peft_config=peft_config,
>     max_seq_length = 4096,
>     dataset_text_field="text",
>     tokenizer=tokenizer,
>     args=training_arguments,
>     packing=False,
> )
> 
> trainer.train()
> ```
> 
> and get UserWarning: Could not find a config file in /content/gdrive/MyDrive/Colab Notebooks/mcllma/Mistral-7B-Instruct-v0.2 - will assume that the vocabulary was not modified.
> 
> I guess it relates to Mistral's (base model) config.json is missing in checkpoint folder that Peft only . Any clue how to fix it ?

i am getting the same warning did you fix it?
i am finetuning clip with lora and when i try to load that i get weight mismatch too
