### ISSUE TITLE
PPOTrainer behavior with `device_map = "auto"`

### ISSUE THREAD

**Issue by zyzhang1130** [huggingface/trl#1504]
I always get the error that all my tensors are not on the same device at `ppo_trainer.step(query_tensors, response_tensors, rewards)` despite `query_tensors`, `response_tensors` and `rewards` are all on the same device (i.e., 'cuda:0') when I load my model with `device_map = "auto"`. However I wish to set `device_map = "auto"` in order to make use of all the gpus I have. What should I do?

**Comment by ejmejm** [comment]
If you want to make use of multiple GPUs, you should use the accelerate library. There is a guide on that here: https://huggingface.co/docs/trl/main/en/customization#train-on-multiple-gpus--nodes. When you use accelerate, so long as you use the model and dataloader prepared by the trainer, it handles sending data and model to the correct devices.
