### ISSUE TITLE
DPOTrainer tokenization fails after 30 minutes

### ISSUE THREAD

**Issue by IvanSedykh** [huggingface/trl#1519]
I was wondering why my dpo training scripts were failing when using big datasets and found out that it is happening always after 30 minutes. After a brief investigation I have discovered that the root cause was this nice context manager, allowing to tokenize only on the main process. 
https://github.com/huggingface/trl/blob/57aebe9c36021e679662181468b04ff42432daf3/trl/trainer/dpo_trainer.py#L377

Internally it is using `torch.distributed.barrier()`, which has default timeout of 30 minutes.
https://github.com/huggingface/accelerate/blob/e9b9c7d022098a53e0ec207b2803ef4ded2d40ea/src/accelerate/state.py#L376

I am not sure what is the best solution for this problem 🧐. Also I am not sure if it is trl or accelerate issue. But obviously we need to fix it somehow.

**Comment by SuperSecureHuman** [comment]
Try

In TrainingArguments - set 

`ddp_timeout=3600 * num_hrs_u_want`

In my case, I had this issue with dataset packing, and setting higher ddp timeout was the workaround

**Comment by SuperSecureHuman** [comment]
when u init `TrainingArguments`, add ddp_timeout as arg.

```py
TrainingArguments(
....
....
ddp_timeout=3600 * 50)
```
