### ISSUE TITLE
Bug in example DPO script in dataloading

### ISSUE THREAD

**Issue by sohrabi1** [huggingface/trl#1541]
Since the example [DPO script](https://github.com/huggingface/trl/blob/main/examples/scripts/dpo.py) uses [hh-rlhf dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style) in OpenAI messages format, the loading in the script [here](https://github.com/huggingface/trl/blob/e823458a6a793778b959a1c134cd2ee3eaa9a9bd/examples/scripts/dpo.py#L148) seems incorrect:

```
    def process(row):
        row["chosen"] = tokenizer.apply_chat_template(row["chosen"], tokenize=False)
        row["rejected"] = tokenizer.apply_chat_template(row["rejected"], tokenize=False)
        return row
```

since it adds all messages to both chosen and rejected. But it also ignores the prompt template for the prompt.
If my understanding is correct the right process function would be

```
    def process(row):
        # we should extract the final turn of messages to define chosen/rejected responses and keep the rest as prompt
        prompt_messages = row["chosen"][:-1]
        chosen_messages = row["chosen"][-1:]
        rejected_messages = row["rejected"][-1:]

        row["prompt"] = tokenizer.apply_chat_template(prompt_messages, tokenize=False)
        row["chosen"] = tokenizer.apply_chat_template(chosen_messages, tokenize=False)
        row["rejected"] = tokenizer.apply_chat_template(rejected_messages, tokenize=False)
        return row
```
As far as i see only the answer is expected in the chosen / rejected parts in the DPO trainer.

**Comment by AIR-hl** [comment]
> Since the example [DPO script](https://github.com/huggingface/trl/blob/main/examples/scripts/dpo.py) uses [hh-rlhf dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style) in OpenAI messages format, the loading in the script [here](https://github.com/huggingface/trl/blob/e823458a6a793778b959a1c134cd2ee3eaa9a9bd/examples/scripts/dpo.py#L148) seems incorrect:
> 
> ```
>     def process(row):
>         row["chosen"] = tokenizer.apply_chat_template(row["chosen"], tokenize=False)
>         row["rejected"] = tokenizer.apply_chat_template(row["rejected"], tokenize=False)
>         return row
> ```
> 
> since it adds all messages to both chosen and rejected. But it also ignores the prompt template for the prompt. If my understanding is correct the right process function would be
> 
> ```
>     def process(row):
>         # we should extract the final turn of messages to define chosen/rejected responses and keep the rest as prompt
>         prompt_messages = row["chosen"][:-1]
>         chosen_messages = row["chosen"][-1:]
>         rejected_messages = row["rejected"][-1:]
> 
>         row["prompt"] = tokenizer.apply_chat_template(prompt_messages, tokenize=False)
>         row["chosen"] = tokenizer.apply_chat_template(chosen_messages, tokenize=False)
>         row["rejected"] = tokenizer.apply_chat_template(rejected_messages, tokenize=False)
>         return row
> ```
> 
> As far as i see only the answer is expected in the chosen / rejected parts in the DPO trainer.

you means the `prompt` shouldn't be the first question but the messages before the last reponse?
If that's what you mean, I couldn't agree more, I alse find that the `chosen` and `rejected` in `hh-rlhf` only different between the last answer

**Comment by sohrabi1** [comment]
@AIR-hl Yes, that's one of the issues. I believe there are two more bugs:
+ not adding the chat template to `row["prompt"]`
+ chosen and rejected rows expecting only the response parts while the script passes the whole conversation including the prompts

**Comment by AIR-hl** [comment]
> @AIR-hl Yes, that's one of the issues. I believe there are two more bugs:
> 
> * not adding the chat template to `row["prompt"]`
> * chosen and rejected rows expecting only the response parts while the script passes the whole conversation including the prompts

I've tried to do that, but the `tokenize_row` function in `DPOTrainer` will cause memory to grow until it overflows

the data structure: 
![image](https://github.com/huggingface/trl/assets/66808901/d422fe23-3af4-48ef-a5ee-ab39990784cd)

add chat template to all rows:
![image](https://github.com/huggingface/trl/assets/66808901/51e0e64e-a3e6-46b9-8601-50a8b7d3761a)

ERRO: 
![image](https://github.com/huggingface/trl/assets/66808901/d367818d-7911-4865-b9e1-6ec5df245f5b)

**Comment by AIR-hl** [comment]
> @AIR-hl Yes, that's one of the issues. I believe there are two more bugs:
> 
> * not adding the chat template to `row["prompt"]`
> * chosen and rejected rows expecting only the response parts while the script passes the whole conversation including the prompts

I've tried to do that, but the function `tokenize_row` in `DPOTrainer` will cause memory usage continue to grow until it overflows

my data style:
![image](https://github.com/huggingface/trl/assets/66808901/0a280bfb-d049-4756-8abb-dc91e037973a)

add template to all rows:
I've tried to do that, but calling `tokenize_row` internally with `DPOTrainer` causes memory to grow until it overflows

memory usage continues to increase:
![image](https://github.com/huggingface/trl/assets/66808901/e194a744-d565-47ea-8978-d8b9a1dbdb30)

**Comment by younesbelkada** [comment]
Hi everyone,

Thanks for the detailed report, for me to understand, I think we should indeed apply the chat template to the entire `"chosen"` and `"rejected"` row to include the entire chat history no? The text differ only on the last answer and the model needs to calculate the logprobs on the entire chat sequence if I understood it right. 

I agree we should apply the chat template to the prompt, I will run the fix proposed by @AIR-hl and see if I observe any memory increase
