### ISSUE TITLE
User turn masking is not robust with the DataCollatorForCompletionOnlyLM

### ISSUE THREAD

**Issue by edbeeching** [huggingface/trl#1550]
I have been running some experiments using `packing=False` and the [DataCollatorForCompletionOnlyLM](https://github.com/huggingface/trl/blob/75c1c47fcc922136ca1de249d79d34742ab1783b/trl/trainer/utils.py#L69). 

## Problem:
Perhaps I have been using this incorrectly but I find the masking implementation to be not very robust to adjacent words/symbols.
Some examples using the template from the docs and the llama2 tokenizer:
```
chat_template = f"### Question: {question}\n ### Answer: {answer}"
response_template = " ### Answer:"
```

```
tokenizer.encode(" ### Answer:", add_special_tokens=False)    # [28705,     774, 26307, 28747] 
tokenizer.encode("\n ### Answer:", add_special_tokens=False)  # [28705, 13, 774, 26307, 28747]
tokenizer.encode(".\n ### Answer:", add_special_tokens=False) # [842,   13, 774, 26307, 28747]
```
The collator uses the response_token_ids (first line above) to identify where in the sequence of token ids to start / end masking, but as you can see from the examples above, the encoded token ids change based on the words/symbols around them. Because of this mismatch many samples have their labels all set to -100 and do not contribute to the loss. I have tried a few variations to include the `\n` etc in the template but there are too many edge cases to resolve.

## Proposed solution:
I suggest that we have a new/updated collator and add the option to include masking tokens within the chat template itself. We use them to identify the start/end indices of where to mask, but the mask tokens themselves are not added to the model embedding layer. We would omit mask token ids from the sequence of token ids and adjust the masking indices accordingly, or set the mask token ids to -100.
An example:
```
tokenizer.add_special_tokens({"additional_special_tokens":["<MASK_START>", "<MASK_END>"]})
template = f"<MASK_START>### Question: {question}\n<MASK_END> ### Answer: {answer}"
# use these tokens to identify where to mask 
```

Potential issue: if the mask tokens sits between two symbols that are usually mapped to one index by the tokenizer then there may be a mismatch between tokenization with and without the mask tokens.

**Comment by lewtun** [comment]
cc @younesbelkada who implemented the masking collator I believe and may have some good input on the above!

**Comment by RonanKMcGovern** [comment]
Thanks, yeah that's definitely a more robust suggestion to explicitly define the mask.
