### ISSUE TITLE
Cannot train custom `PeftModelForCausalLM` model with `PPOTrainer`

### ISSUE THREAD

**Issue by mertsayar8** [huggingface/trl#1558]
Hi, I have been running into a problem while trying to run a PPO Training with my custom language model. My custom langauge model is an instance of `PeftModelForCausalLM` class which is supported in `from_pretrained()` function. The `AutoModelForCausalLMWithValueHead` instance is created via:
```
peft_model = PeftModelForCausalLM.from_pretrained(lang_model, lora_model, torch_dtype=torch.float16, use_ram_optimized_load=False).half()
lang_model = AutoModelForCausalLMWithValueHead.from_pretrained(peft_model, peft_config = lora_config)

```
I have faced no issues loading the model into the `AutoModelForCausalLMWithValueHead`, however I have realized the PPO training did not change the behavior of the language model. I have traced the state_dict of the model, and apparently the model only consists of `v_head` layers(so only updated layer is v_head and no effect on text generation):
```
('v_head.summary.weight', tensor([[ 0.0146,  0.0001,  0.0152,  ..., -0.0105, -0.0138, -0.0066]],
       device='cuda:0'))
('v_head.summary.bias', tensor([0.0040], device='cuda:0'))
```
I have checked the trl repo and this is not the case for other existing examples(`AutoModelForCausalLMWithValueHead` model has all the layers inside along with the v_head)

**Comment by Wuyxin** [comment]
Hi I am wondering if this is resolved, currently facing the same issue! Thank you!
