### ISSUE TITLE
Fail to train with ORPOTrainer under multi-GPUs setting

### ISSUE THREAD

**Issue by blaze7451** [huggingface/trl#1571]
I was trying to use `ORPOTrainer` to train model with 4 GPUs by applying `device_map="auto"`. The code I used is similar to the code [here](https://towardsdatascience.com/fine-tune-llama-3-with-orpo-56cfab2f9ada), however, i got the following error:

`/home/inxid/anaconda3/envs/idd-3.10/lib/python3.10/site-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(Could not estimate the number of tokens of the input, floating-point operations will not be computed
Traceback (most recent call last):
  File "/home/inxid/Python/model/Training/ORPO/ORPO_training.py", line 170, in <module>
    trainer.train()
  File "/home/inxid/anaconda3/envs/idd-3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/inxid/anaconda3/envs/idd-3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2214, in _inner_training_loop
    raise ValueError(
ValueError: Calculated loss must be on the original device: cuda:0 but device in use is cuda:3
  0%|          | 0/1925 [00:04<?, ?it/s]
`
It looks like the issue is arised when the loss was calculating, any suggestions to fix this error? thanks. 

The core libraries I use are:
accelerate==0.29.3
transformers==4.40.0
trl==0.8.6
bitsandbytes==0.42.0

**Comment by blaze7451** [comment]
@alvarobartt hi, thx for your detailed explanation at another post, looks like I misuse `device_map="auto"` for training, I will follow your instruction to try later. big thx again.

**Comment by huangxinping** [comment]
@alvarobartt Hi buddy, thx. I will try again later.

**Comment by Aisuko** [comment]
hi @alvarobartt, thanks for your response. I hit this issue too, from the same article. I have some experience with `device_map="auto"` to fine-tune models like [phi-2](https://www.kaggle.com/code/aisuko/fine-tuning-phi-2-with-qlora), [Gemma](https://www.kaggle.com/code/aisuko/llm-prompt-recovery-with-gemma). It is really useful when the single GPU does not have enough memory to load the model and training data. Do you have any suggestion here that we can use ORPO on multiple GPUs in notebook environment(like kaggle)? Thank you.

**Comment by alvarobartt** [comment]
But the issue for you @Aisuko is that you're not able to fine-tune Llama 3B with `device_map="auto"` right? Or is it that you're just unable to use `trl.ORPOTrainer` + `device_map="auto"`?

**Comment by Aisuko** [comment]
> But the issue for you @Aisuko is that you're not able to fine-tune Llama 3B with `device_map="auto"` right? Or is it that you're just unable to use `trl.ORPOTrainer` + `device_map="auto"`?

Hi @alvarobartt thanks for your quick replying. Let's make it clearly, can we use `trl.ORPOTrainer` to fine-tune model on multiple GPUs with `device_map="auto"` parameter?

**Comment by alvarobartt** [comment]
> Hi @alvarobartt thanks for your quick replying. Let's make it clearly, can we use `trl.ORPOTrainer` to fine-tune model on multiple GPUs with `device_map="auto"` parameter?

Hi @Aisuko as mentioned before I don't have much experience on relying on `device_map="auto"` to fine-tune models, indeed I thought it was not even supported, but it seems it is with some tweaks. After reading some issues I realised that @younesbelkada answered a similar question for the `KTOTrainer` that can be easily solved apparently, please read https://github.com/huggingface/trl/issues/1560#issuecomment-2070223958
