### ISSUE TITLE
Anthropic HH new dataset format repeats the prompt

### ISSUE THREAD

**Issue by JubilantJerry** [huggingface/trl#1582]
With the new data format of Anthropic HH in v0.8.2 (for example, see https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style vs. the older https://huggingface.co/datasets/trl-internal-testing/Anthropic-hh-rlhf-processed), I think the samples for DPO training end up repeating the first message of the chat. For example, if the original row of the dataset is:

```
prompt: "How do I program a robot?"
chosen: [ { "content": "How do I program a robot?", "role": "user" }, { "content": "Programming a robot requires some knowledge of programming. What kind of robot are you trying to program?", "role": "assistant" } ]
```
Then the processed sample (for chosen) will look like:
```
<s> How do I program a robot? user: How do I program a robot?

assistant: Programming a robot requires some knowledge of programming. What kind of robot are you trying to program?
```

**Comment by fiberleif** [comment]
Fully agree.

The current data processing code (e.g., tokenize_row function in DPOTrainer: 
https://github.com/huggingface/trl/blob/1d0a7ea17b8055a6850970ab59a34709d8ca494d/trl/trainer/dpo_trainer.py#L716C9-L716C21) is incompatible with the new data format of https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-trl-style. 

![image](https://github.com/huggingface/trl/assets/11922971/f68044c6-6a66-4b48-b567-578319cb96c0)

**Comment by JubilantJerry** [comment]
I believe the dataset still has this issue.

**Comment by AIR-hl** [comment]
Has this problem been fixed?
