### ISSUE TITLE
Group Relative Policy Optimization Trainer

### ISSUE THREAD

**Issue by samuelzxu** [huggingface/trl#1583]
Hi all,

I'd like to implement the RL technique from this paper called Group Relative Policy Optimization and I think it would go quite nicely in this library:
https://arxiv.org/pdf/2402.03300.pdf

Can anyone give me a possible path to implement this as a starting point or some potential problems they see? I'm not too familiar with TRL but I'm familiar with ML engineering.

**Comment by Ye-Yang-SDUWH** [comment]
Hello, have you tried to implement GRPO? 
Looking for a start point as well.

**Comment by lewtun** [comment]
Currently being implemented in #1954

**Comment by lewtun** [comment]
Closing in favour #2103
