### ISSUE TITLE
CLI utils class cases seem to be incorrect

### ISSUE THREAD

**Issue by busycalibrating** [huggingface/trl#1600]
The cases for the `DPOScriptArguments` and `SFTScriptArguments` (as seen [here](https://github.com/huggingface/trl/blob/6c18e40e9755d4db6ed430eafe3b6df5ae82343b/trl/commands/cli_utils.py#L143-L154)) have the correctly capitalized `DPO` and `SFT` names, but in the downloaded codebase, it seems to be in camel-case, i.e.

```python
@dataclass
class SftScriptArguments:
    ...

@dataclass
class DpoScriptArguments:
    ...
```
I'm currently running version `0.8.6`, installed from pip, but you can also see this in the downloaded zip release of [`v0.8.6`](https://github.com/huggingface/trl/releases/tag/v0.8.6). 

Does anybody else see this or is this something just affecting me?

**Comment by younesbelkada** [comment]
Hi @busycalibrating 
Thanks for the issue, when searching into the codebase, only the capitalized `DPO` and `SFT` names are present:

https://github.com/search?q=repo%3Ahuggingface%2Ftrl+SftScriptArguments&type=code

https://github.com/search?q=repo%3Ahuggingface%2Ftrl+DpoScriptArguments&type=code

**Comment by busycalibrating** [comment]
Can you check that this is true when you download the zip release I linked?

**Comment by younesbelkada** [comment]
Apologies for the delay @busycalibrating - we just made a new release, can you double check it is still the case for trl==0.9.4 ?

**Comment by busycalibrating** [comment]
Yes this seems to be resolved: 

![image](https://github.com/huggingface/trl/assets/19653980/82294a01-c4ab-4e7f-afc1-d7dce29085b6)

What a bizarre issue :S Thanks for following up on it!
