### ISSUE TITLE
Long data length cause Cuda ouf of memory when DPO training

### ISSUE THREAD

**Issue by virt9** [huggingface/trl#1619]
hello!  i make a dataset on my own but i found  the data length may lead to cuda out of memory error. I use DPOTrainer and my max prompt length is 512, max_length is 1024 ,batch size is 16 ,my cuda memory is 40GB,  what should i do if i don't change my dataset to solve the problem? thanks a lot !

**Comment by younesbelkada** [comment]
Hi @virt9 
Thanks for the issue and apologies for the delay, for that you could use a smaller batch size and use gradient accumulation. If you have a GPU that is compatible with Flash Attention 2, you could also load your model with Flash Attention 2.
