### ISSUE TITLE
DDPO cannot use SDXL

### ISSUE THREAD

**Issue by mao-code** [huggingface/trl#1630]
When I am using DDPO to train diffusion model, I choose SDXL to be the target. However, I keep encounter this error:
```
File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py:973, in UNet2DConditionModel.get_aug_embed(self, emb, encoder_hidden_states, added_cond_kwargs)
    970     aug_emb = self.add_embedding(text_embs, image_embs)
    971 elif self.config.addition_embed_type == "text_time":
    972     # SDXL - style
--> 973     if "text_embeds" not in added_cond_kwargs:
    974         raise ValueError(
    975             f"{self.__class__} has the config param `addition_embed_type` set to 'text_time' which requires the keyword argument `text_embeds` to be passed in `added_cond_kwargs`"
    976         )
    977     text_embeds = added_cond_kwargs.get("text_embeds")

TypeError: argument of type 'NoneType' is not iterable
```

Will DDPO support SDXL in the future?

**Comment by younesbelkada** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Hi 👋 

DDPO fails behind performance in comparison to Diffusion DPO so it's hard for us see value in adding SDXL support to DDPO. I welcome you to try out Diffusion DPO [here](https://github.com/huggingface/diffusers/tree/main/examples/research_projects/diffusion_dpo) (verified by the first author of Diffusion DPO :)). 

WDYT @younesbelkada?

**Comment by younesbelkada** [comment]
Sounds great ! @mao-code what do you think?

**Comment by mao-code** [comment]
It looks like a good idea!

**Comment by Wonder1905** [comment]
Any plans to adjust it to SD3?
