### ISSUE TITLE
How to use trl\trainer\kto_trainer.py

### ISSUE THREAD

**Issue by mazhengyufreedom** [huggingface/trl#1635]
If I want to use KTO trainer, I could set the parameter [loss_type == "kto_pair"] in dpo_trainer.py. Then what is kto_trainer.py used for? And how to use it?

**Comment by kawine** [comment]
kto_pair is a variant of KTO that you can use with preference data. I recommend *not* using this and using KTOTrainer, which doesn't learn from preferences but rather based on whether a particular example is good or bad

like if you have 5 x for which you only have positive examples y_pos and 50 x for which you have only negative examples y_neg, you can't use any preference-based method but you can still use KTO

and even if you do have n preference pairs of the type (x, y_w, y_l), the original kto paper found that if you break it up into 2n  examples (x, y_w), (x, y_l) and use KTO, it usually works better than just learning from the preference data

**Comment by mazhengyufreedom** [comment]
Do you mean that the results from KTOTrainer would be better than those from kto_pair? And how to use kto_trainer instead of dpo_trainer?  Is there any instrustion?

**Comment by kawine** [comment]
yes, the results from KTOTrainer should be much better than kto_pair

you can check out the docs here: https://huggingface.co/docs/trl/main/en/kto_trainer
