### ISSUE TITLE
Do we need to consider the chat template when doing DPO/KTO training?

### ISSUE THREAD

**Issue by ZeroYuHuang** [huggingface/trl#1640]
Hi! I closely check the data processing in the KTO trainer and DPO trainer. I find that the chatting template is not considered when combining the prompt and its completion. 

For DPOTrainer: `full_tokenized = self.tokenizer(prompt + answer, add_special_tokens=False)`
And for KTOTrainer: `prompt_and_completion = [prompt + completion for prompt, completion in zip(batch["prompt"], batch["completion"])]`

Do we need to consider the chat template when combining them, something like: `[INST] + prompt + [\INST] + completion`.

**Comment by younesbelkada** [comment]
cc @kashif @kawine

**Comment by kashif** [comment]
let me check! Thanks for the report!

**Comment by yaoxiao1999** [comment]
> let me check! Thanks for the report!

Hi, didn't mean to chase you up, but do you have any updates on this question? Thanks!
