### ISSUE TITLE
ImportError: cannot import name 'DPOConfig' from 'trl' 

### ISSUE THREAD

**Issue by AswiniNLP** [huggingface/trl#1642]
![Screenshot from 2024-05-14 14-48-09](https://github.com/huggingface/trl/assets/132350955/19f92354-eec8-45c4-a78f-48e207992051)
from trl import DPOConfig
I am not able to import DPOConfig, however, I can import DPOTrainer 

can we use DPO on flanT5 , automodelforseq2seqLM ?

**Comment by younesbelkada** [comment]
Hi @AswiniNLP 
What is your TRL version? Can you try to install the latest TRL version `pip install -U trl`

**Comment by AswiniNLP** [comment]
Dear @younesbelkada, 
It is not working.

**Comment by AswiniNLP** [comment]
Hi how to apply dpo on flanT5 ?

**Comment by trangtv57** [comment]
hey, the same issuse, I don't sure what version trl need to use so I can run dpo trainer script in example, so bad. 
tks

**Comment by AswiniNLP** [comment]
Dear, DPOconfig is not working

**Comment by AswiniNLP** [comment]
How to run dpo for flant5

**Comment by trangtv57** [comment]
install from source may help:
pip install git+https://github.com/huggingface/trl.git

**Comment by AswiniNLP** [comment]
Tried not working

**Comment by AswiniNLP** [comment]
Can we use DPO on the top of flant5?

**Comment by AswiniNLP** [comment]
> Dear @younesbelkada, It is not working. Same error. TRL version is 0.8.6

Could you please help me know how to apply DPO on the seq to seq model through the DPO trainer?

**Comment by JhonDan1999** [comment]
the same issue here 

![Screenshot 2024-05-25 at 12 25 13 AM](https://github.com/huggingface/trl/assets/145554661/9cf6ec23-86f9-49ab-98df-afe3b7f5c6bf)

**Comment by younesbelkada** [comment]
Hi there! 
I am sure you are facing a weird env conflict issue, make sure to use the latest TRL from pypi and refresh the kernels if you are using a google colab environment `pip install -U trl`

**Comment by JhonDan1999** [comment]
> `pip install -U trl`

thank you @younesbelkada I already did ```!pip install --upgrade trl``` but the issue is still there

**Comment by HarryMayne** [comment]
> install from source may help: pip install git+https://github.com/huggingface/trl.git

Installing 0.8.7 dev version from source works for me. Seems to work for 0.8.7 dev but not for 0.8.6. (latest release)

**Comment by younesbelkada** [comment]
Sorry for the confusion, indeed `DPOConfig` and `SFTConfig` are available features on main only, so as @HarryMayne pointed out, you need to install TRL from source. I will make a release soon on pypi to include that + many other bugfixes

**Comment by kevinjesse** [comment]
Installing from source on main does not resolve the missing DPOConfig. Even if DPOConfig.py is in trl/trl/trainer/, it is missing from the __init__.py.

**Comment by meixtan** [comment]
Installing from the source did not solve this for me. Same issue.

**Comment by Rhitabrat** [comment]
not working
