### ISSUE TITLE
How to save and resume a checkpoint from PPOTrainer

### ISSUE THREAD

**Issue by paraGONG** [huggingface/trl#1643]
https://github.com/huggingface/trl/blob/5aeb752053876cce64f2164a178635db08d96158/trl/trainer/ppo_trainer.py#L203
It seems that every time the PPOTrainer is initialized, the accelerator is initialized as well. There's no API provided by PPOTrainer to resume checkpoints. How can we save and resume checkpoints?

**Comment by sweetice** [comment]
Did you solve it? I also met such a problem.
