### ISSUE TITLE
Set seed

### ISSUE THREAD

**Issue by user799595** [huggingface/trl#1648]
Please don't set the global random seed to zero when initializing a `PPOTrainer` object. Constructors should not generally have side effects.

Setting the seed doesn't actually create reproducible experiments because the code between `PPOTrainer.__init__` and `PPOTrainer.generate/step` can change between runs.

I don't know how feasible it is to have a `PPOTrainer` object specific random state (I'm guessing not very), but could you at least make setting the global state optional?

E.g. by adding ```trl.core.set_seed(seed=0)``` to the documentation/example scripts. And removing this from init.

I'm happy to add a PR to this effect if it's of interest.

**Comment by younesbelkada** [comment]
Hi @user799595 
This makes totally sense, can you open a PR for that and we'll take it from there? 🙏
