### ISSUE TITLE
Adapter name for SFT trainer

### ISSUE THREAD

**Issue by para-zhou** [huggingface/trl#1649]
Hi, I appreciate that the PPOTrainer is enabled to assign ''adapter_name'' to trainable adapters, would you please also enable SFTTrainer with this function?

**Comment by younesbelkada** [comment]
Hi @para-zhou 
Thanks for the issue ! `adapter_name` is used on our `AutoModelForxxx` classes that are internal to TRL. In order to switch between adapters in SFTTrainer you should first create your `PeftModelForxxx` and call `model.set_adapter(adapter_name)`
