### ISSUE TITLE
examples don't work

### ISSUE THREAD

**Issue by yechenzhi** [huggingface/trl#1656]
I run examples you provided [here](https://huggingface.co/docs/trl/sft_trainer#best-practices), it says AttributeError: 'NoneType' object has no attribute 'model_init_kwargs'.  

Then I also run the example you provided in the README, like this:
```
# imports
from datasets import load_dataset
from trl import SFTTrainer

# get dataset
dataset = load_dataset("imdb", split="train")

# get trainer
trainer = SFTTrainer(
    "facebook/opt-350m",
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)

# train
trainer.train()  
```                                                                                                                                                                                      
still the same error. Any plan to update these examples?

**Comment by yechenzhi** [comment]
I also run [this](https://github.com/huggingface/trl/blob/main/examples/scripts/sft.py), still not work. 'ValueError: You passed `packing=False` to the SFTTrainer/SFTConfig, but you didn't pass a `dataset_text_field` or `formatting_func` argument.
', I'm in wrong version of transformer trl?

**Comment by rahulseetharaman** [comment]
@yechenzhi Did you find a workaround ? I am also facing the same issue.

**Comment by younesbelkada** [comment]
Hi everyone,
Thanks for the report, there was indeed a bug, that is fixed in https://github.com/huggingface/trl/pull/1678 
I will make sure to make a patch release asap to include that + other fixes
@yechenzhi could you file a separate issue for the second issue you are facing?
