### ISSUE TITLE
OOM with DPO Trainer on A100 GPU

### ISSUE THREAD

**Issue by JhonDan1999** [huggingface/trl#1667]
I am encountering an out-of-memory (OOM) issue while using the DPOTrainer even though I am running it on an A100 GPU. The model I am using is mistralai/Mistral-7B-Instruct-v0.2. This issue is similar to the previously closed issue [#1227.](https://github.com/huggingface/trl/issues/1227)

Despite using Qlora and attempting two different approaches, both methods result in OOM errors. Here are the two approaches I have tried:

1- [https://huggingface.co/docs/trl/main/en/dpo_trainer#using-option-3---load-the-adapter-twice](https://huggingface.co/docs/trl/main/en/dpo_trainer#using-option-3---load-the-adapter-twice)
2- [https://colab.research.google.com/drive/1mWiOFBy3zY6OdINEvHN9EPoQ_VIvfFKw?usp=sharing&utm_campaign=Events%20Follow%20Up&utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz--zYcYKj9_o5fLbt_D3P4tzLanpAyfFm14Z2NXEvCZxbsjLtax9y5mYCzRg-opvXZhsYGEH#scrollTo=33gqLvEQhxd1](https://colab.research.google.com/drive/1mWiOFBy3zY6OdINEvHN9EPoQ_VIvfFKw?usp=sharing&utm_campaign=Events%20Follow%20Up&utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz--zYcYKj9_o5fLbt_D3P4tzLanpAyfFm14Z2NXEvCZxbsjLtax9y5mYCzRg-opvXZhsYGEH#scrollTo=33gqLvEQhxd1)

all gave me 

```
OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 

```

Could you please provide assistance in resolving this issue?

**Comment by miraliahmadli** [comment]
I am also having the same issue. Mentioned approach in the issue you have attached didn't work for me. 

I think they are keeping some logs / metrics or smth on the device, which results in this issue after few thousand steps..

Let me know if you can find a solution.

**Comment by ductri** [comment]
Any update on this? I encountered this issue as well. I was able to train DPO with the same setting without using DPOTrainer.

**Comment by tanaybaswa** [comment]
Open
