### ISSUE TITLE
ppov2 & rloo trainer doesn't correctly compute reward if reward tokenizer is different from policy tokenizer

### ISSUE THREAD

**Issue by TheBlackCat22** [huggingface/trl#1674]
Both the ppov2 and the rloo trainers use the following to compute rewards .
https://github.com/huggingface/trl/blob/3c0a10b1aedbe533005dbfe18f2cc8057093f80b/trl/trainer/ppov2_trainer.py#L322-L324
Here, `postprocessed_query_response` stores token_ids (generated by policy tokenizer) of the query+response

With `get_reward` function defined as follows,
https://github.com/huggingface/trl/blob/3c0a10b1aedbe533005dbfe18f2cc8057093f80b/trl/trainer/utils.py#L922-L969

This should not make sense if the tokenizer for the reward model is different from the tokenizer for the policy model. Because, then the tokens will map to different words. And so our reward will be wrong.

**Comment by vwxyzjn** [comment]
Hey @TheBlackCat22 that is intended. For PPO in particular, you need to also initialize the value model from the reward model, so for this reason, we assume the reward model and policy model would be of the same type.

**Comment by TheBlackCat22** [comment]
Hey @vwxyzjn thanks for the clarification. 
In my head it made more sense to initialize the value model as a separate head of the policy model (Like they have done in the ppov1 example) or even just outright deep copying it and replacing the final layer.

https://github.com/huggingface/trl/blob/275d33b3ef4f7afd40f79cc53591659bacfa3499/examples/scripts/ppo.py#L54
https://github.com/huggingface/trl/blob/275d33b3ef4f7afd40f79cc53591659bacfa3499/examples/scripts/ppo.py#L119-L124

Maybe I am understanding something wrong.

So it possible to recreate this example using ppov2?
https://github.com/huggingface/trl/blob/main/examples/scripts/ppo.py

**Comment by vwxyzjn** [comment]
> In my head it made more sense to initialize the value model as a separate head of the policy model (Like they have done in the ppov1 example) or even just outright deep copying it and replacing the final layer.

See https://github.com/huggingface/trl/issues/1063#issuecomment-1875926087 for some related discussion

> So it possible to recreate this example using ppov2? https://github.com/huggingface/trl/blob/main/examples/scripts/ppo.py

It is possible if we train a reward model using the same arch as the policy model.
