### ISSUE TITLE
SFTrainer with FSDP on a model that doens't fit in GPU memory

### ISSUE THREAD

**Issue by tambulkar** [huggingface/trl#1681]
The [example of multi-gpu training on the SFTrainer docs](https://huggingface.co/docs/trl/en/sft_trainer#multi-gpu-training) shows that I should load the GPU into memory, but this doesn't work if the model doesn't fit into memory in the first place. Is there any guidance somewhere on how to use FSDP with SFTtrainer for models that don't fit in one GPU? Can we shard the model  before loading it onto the GPU?

**Comment by younesbelkada** [comment]
Hi @tambulkar 
Thanks for the issue! I am not super familiar myself with FSDP. I can give you this pointer: https://github.com/huggingface/peft/blob/main/examples/sft/run_peft_qlora_fsdp.sh which is the official PEFT script that you can use to run QLoRA + SFTTrainer using FSDP

**Comment by zirui** [comment]
I have the same question. Are there any updates?
