### ISSUE TITLE
Feature Request: Simple Preference Optimization Integration

### ISSUE THREAD

**Issue by 1485840691-eng** [huggingface/trl#1684]
Its implementation: https://github.com/princeton-nlp/SimPO

I wonder if this is a good fit into this repo. Its code seems to already leverage trl. 

If so, we might integrate that back into this repo. Maybe I could work on it.

**Comment by vwxyzjn** [comment]
Close by https://github.com/huggingface/trl/pull/1703. Feel free to give it a try by installing from main and follow docs at https://huggingface.co/docs/trl/main/en/cpo_trainer#loss-functions .
