### ISSUE TITLE
There is no chat_template of the model used when constructing data in DPOTrainer

### ISSUE THREAD

**Issue by mst272** [huggingface/trl#1687]
When performing DPO training, the data does not add the chat template of the model, will this lead to poor results? Because each model is trained with a specific chat template.
Or was it added somewhere, but I didn't find it?

**Comment by kashif** [comment]
so that is applied externally to the trainer... see for example the `dpo.py` example script in `examples/scripts/dpo.py`

**Comment by mst272** [comment]
> so that is applied externally to the trainer... see for example the `dpo.py` example script in `examples/scripts/dpo.py`

oh thanks!
