### ISSUE TITLE
Backwards compatability support for passing in transformers.TrainingArguments to SFTTrainer args

### ISSUE THREAD

**Issue by anhuong** [huggingface/trl#1711]
Due to [the change](https://github.com/huggingface/trl/commit/f30daa4225c2769130c443e21df39b91632f63a7) that added in SFTConfig, for the parameter in SFTTrainer.args, this broke previous behavior that allowed passing transformers.TrainingArguments into SFTTrainer.args. This was tried to be fixed by [this commit](https://github.com/huggingface/trl/commit/39a7d1c121d26224fd7455d3d2038e0d20831c54) a few hours ago, however the full set of TrainingArguments has many more parameters than SFTConfig. Thus converting TrainingArguments to a dictionary is insufficient. 

Currently this is resulting in error: `TypeError: SFTConfig.__init__() got an unexpected keyword argument 'cache_dir'` because TrainingArguments has a field for cache_dir but SFTConfig does not.

Previously I ran with:
```py
trainer = SFTTrainer(
         model=model,
         tokenizer=tokenizer,
         train_dataset=formatted_train_dataset,
         eval_dataset=formatted_validation_dataset,
         packing=packing,
         data_collator=data_collator,
         dataset_text_field=data_args.dataset_text_field,
         args=transformers.TrainingArguments,
         max_seq_length=max_seq_length,
         callbacks=trainer_callbacks,
         peft_config=peft_config,
     )
```

Since SFTTrainer is built from/inherits transformers.Trainer, these training argument configurations are important and used. Perhaps `SFTConfig` should also inherit from transformers.TrainingArguments?

**Comment by vwxyzjn** [comment]
Sorry you are running into this issue.

>          args=transformers.TrainingArguments,

This doesn't seem to make sense. Shouldn't you pass an instance of `transformers.TrainingArguments`? 

> Perhaps SFTConfig should also inherit from transformers.TrainingArguments?

It is already the case.

https://github.com/huggingface/trl/blob/3eb9ccb104e2c46360adb937f3f25871c167eb90/trl/trainer/sft_config.py#L21

**Comment by anhuong** [comment]
Apologies I see this is mixture of TrainingArguments where my project built a class off of transformers.TrainingArguments that we pass into trl.SFTTrainer and so the additional parameters that we are adding to TrainingArguments is causing the discrepancy issue.
