### ISSUE TITLE
Feature request: Adaptive Preference Scaling for Reinforcement Learning with Human Feedback

### ISSUE THREAD

**Issue by Trangle** [huggingface/trl#1715]
This job introduces an iteratively updated adaptive parameter for each pair of samples, considering the degree of reward adaptively to affect learning. It's a great idea. Do you have any plans to join?

**Comment by qgallouedec** [comment]
I'm closing because this feature hasn't received any PR, and doesn't seem to be widely requested by the community. This issue may be reopened at a later date if that changes.
