### ISSUE TITLE
Distributed fine-tuning using KTO, QLorA and FSDP throws ValueError You cannot perform fine-tuning on purely quantized models... 

### ISSUE THREAD

**Issue by nubloso** [huggingface/trl#1719]
When using float32 as computing datatype, after training steps are complete I get the error message:

ValueError: You cannot perform fine-tuning on purely quantized models. Please attach trainable adapters on top of the quantized model to correctly perform fine-tuning. 

Even thought I'm using PEFT. I'm fine-tuning a 13B model based on the Bloom architecture using KTO, QLorA and FSDP on a distributed setting. The script works on a single GPU, but when I wrap it using accelerate and run it, it throws the aforementioned error after finishing the training steps.

I've tried running the script with  fsdp_use_orig_params:true with and without the script modifications suggested in the PEFT documentation regarding FSDP; but it resulted in the same error.

I'm using float32 because when I try to use bfloat16 or float16, I get ValueError: Must flatten tensors with uniform dtype but got torch.float32 and torch.float16. 

Here are my settings and script:

    arguments_dict = {
        "model_name_or_path": "xxxx/xxxxxxxx",
        "per_device_train_batch_size": 16,
        "num_train_epochs": 1,
        "learning_rate": 0.0008,
        "lr_scheduler_type": "cosine",
        "logging_steps": 10,
        "output_dir": "lora-13b-2",
        "hub_strategy": "every_save",
        "warmup_ratio": 0.1,
        "logging_first_step": True,
        "use_peft": True,
        "lora_target_modules": "all-linear",
        "lora_r": 32,
        "lora_alpha": 64,
        "max_length": 256,
        "max_prompt_length": 128,
        "max_completion_length": 128,
        "remove_unused_columns":False,
        "report_to":"wandb",
        "weight_decay":3e-07,
    }

    arguments_list = []
    for key, value in arguments_dict.items():
        arguments_list.append(f"--{key}")
        arguments_list.append(str(value))

    # Parse the arguments
    script_args, kto_args, model_args = parser.parse_args_into_dataclasses(args=arguments_list)

    #script_args, kto_args, model_args = parser.parse_args_into_dataclasses()

    # Load a pretrained model
    compute_dtype = getattr(torch, "float32")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_storage="float32",
    )

    # To have Accelerate compute the most optimized device_map automatically, set device_map="auto"
    model = AutoModelForCausalLM.from_pretrained(model_args.model_name_or_path, quantization_config=bnb_config,trust_remote_code=True,torch_dtype=torch.float32,)
    model_ref = AutoModelForCausalLM.from_pretrained(model_args.model_name_or_path, quantization_config=bnb_config, trust_remote_code=True,torch_dtype=torch.float32,)

    model.enable_input_require_grads()
    model_ref.enable_input_require_grads()

    tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # If we are aligning a base model, we use ChatML as the default template
    if tokenizer.chat_template is None:
        model, tokenizer = setup_chat_format(model, tokenizer, format="chatml")

    # Load the dataset
    dataset = load_dataset(script_args.dataset_name)

    # Apply chat template
    def format_dataset(example):
        example["prompt"] = tokenizer.apply_chat_template(example["prompt"], tokenize=False)
        example["completion"] = tokenizer.apply_chat_template(example["completion"], tokenize=False)
        return example

    formatted_dataset = dataset.map(format_dataset)

    # Print an example of the formatted dataset
    print(formatted_dataset["train"][0])
    print(formatted_dataset["train"][20])
    print(formatted_dataset["train"][100])
    print(formatted_dataset["train"][200])

    # Initialize the KTO trainer
    trainer= kto_trainer = KTOTrainer(
        model,
        model_ref,
        args=kto_args,
        train_dataset=formatted_dataset["train"],
        tokenizer=tokenizer,
        peft_config=get_peft_config(model_args),
        callbacks=[SystemMetricsCallback]
    )

    trainer.accelerator.print(f"{trainer.model}")
    if model_args.use_peft:
    # handle PEFT+FSDP case
        trainer.model.print_trainable_parameters()
        if getattr(trainer.accelerator.state, "fsdp_plugin", None):
            from peft.utils.other import fsdp_auto_wrap_policy

            fsdp_plugin = trainer.accelerator.state.fsdp_plugin
            fsdp_plugin.auto_wrap_policy = fsdp_auto_wrap_policy(trainer.model)

    # Train and push the model to the Hub
    kto_trainer.train()
    if trainer.is_fsdp_enabled:
        trainer.accelerator.state.fsdp_plugin.set_state_dict_type("FULL_STATE_DICT")
    kto_trainer.save_model(kto_args.output_dir)
    kto_trainer.push_to_hub("Trained lora")

fsdp_config.yaml:
```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: 'no'
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: "no"
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

```
And this is the error:

```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [05:17<00:00, 20.31s/it]Traceback (most recent call last):
  File "//kto-runpod-fsdp.py", line 194, in <module>
    kto_trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2373, in _inner_training_loop
    self.control = self.callback_handler.on_train_end(args, self.state, self.control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 457, in on_train_end
    return self.call_event("on_train_end", args, state, control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 498, in call_event
    result = getattr(callback, event)(
  File "/usr/local/lib/python3.10/dist-packages/transformers/integrations/integration_utils.py", line 781, in on_train_end
    fake_trainer = Trainer(args=args, model=model, tokenizer=tokenizer)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 475, in __init__
    raise ValueError(
ValueError: You cannot perform fine-tuning on purely quantized models. Please attach trainable adapters on top of the quantized model to correctly perform fine-tuning. Please see: https://huggingface.co/docs/transformers/peft for more details
```

**Comment by MikaSie** [comment]
I have the same issue! Are you any further yet with solving this? My setup is a bit different but I think the settings that differ shouldn't have an effect on this.

**Comment by famimahmud** [comment]
I have the same issue! Have you found any solutions to the problem?

**Comment by MikaSie** [comment]
Hi! I had the same issue but also some other ones. I did find what the issue was for this value error specifically. It was a while ago for me but maybe this helps: https://github.com/huggingface/accelerate/issues/2872#issuecomment-2180950511

**Comment by famimahmud** [comment]
Thanks a lot, @MikaSie! That was a big help! Deleting the line `os.environ["WANDB_LOG_MODEL"]="end"`, which is responsible for the callback at the end, solved it for me.
