### ISSUE TITLE
[DOCS] Some headers (h2, h3) not rendered properly

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/trl#1745]
## Description

Hi here! :hugs: I've noticed that some headers (h2, h3) are not rendered properly in the documentation at https://huggingface.co/docs/trl/main/en/lora_tuning_peft (every header after the #launch-scripts anchor).

![image](https://github.com/huggingface/trl/assets/36760800/0cde2ed2-fd03-4061-90be-4642ebc93851)

Not sure if this happens in other pages too, just saw that there; but apparently the Markdown file (see https://github.com/huggingface/trl/blob/main/docs/source/lora_tuning_peft.mdx) in GitHub is indeed properly rendered and everything looks good IMO, so there may be something wrong when building those, formatting, or something similar.

**Comment by qgallouedec** [comment]
For the record, the rendering is ok for me 

<img width="1320" alt="Screenshot 2024-07-26 at 17 11 36" src="https://github.com/user-attachments/assets/87f75dd5-9e8c-4fe3-aadb-1d887cd405ac">

the problem may have been corrected in the meantime, thanks for pointing it out anyway @alvarobartt
