### ISSUE TITLE
DataCollatorForCompletionOnlyLM does not work with FSDP 

### ISSUE THREAD

**Issue by aabhasgupta** [huggingface/trl#1756]
[fsdp_qlora.txt](https://github.com/user-attachments/files/15917513/fsdp_qlora.txt)
The loss is returned as NaN when using DataCollatorForCompletionOnlyLM with the FSDP pipeline (attached for reference)
_"could not find instruction key `[882]` in the following instance: <|start_header_id|>user<|end_header_id|> "_
Upon checking the collator function in a separate jupyter notebook, I dont see this error.
Is this something to do with the distributed learning approach?
I followed the FSDP approach as mentioned here:
https://www.philschmid.de/fsdp-qlora-llama3
Can anyone suggest what is it that I am missing here?

**Comment by qgallouedec** [comment]
Hey! Sorry for the late reply, thank you for reporting this issue.
I can't reproduce what you describe. Can you describe precisely how to reproduce the error: minimal code, dataset, script etc, all included in this issue (no link). Also specify the configuration you are using and the versions of the various packages.
