### ISSUE TITLE
Supports of SFTTrainer / PPOTrainer / DPOTrainer for LLaVA-alike model

### ISSUE THREAD

**Issue by fangkuoyu** [huggingface/trl#1784]
TRL SFTTrainer supports LLaVA (Large Language and Vision Assistant) as described in the following link [Vision Language Models Explained](https://huggingface.co/blog/vlms)

Is there any plan to release PPOTrainer and DPOTrainer for LLaVA? If not, could someone explain the concerns about implementing those trainers or suggest any alternatives? Thanks!

**Comment by kashif** [comment]
@fangkuoyu  #1647 supports VLLM training for DPO

**Comment by fangkuoyu** [comment]
@kashif Thanks for your comment. Do you know the status of PPOTrainer for LLaVA or other similar models?

**Comment by qgallouedec** [comment]
For ref, part of answer here: https://github.com/huggingface/trl/pull/1647#issuecomment-2191711885

**Comment by qgallouedec** [comment]
I've added DPO support for Llava in #1797. This requires a few hacky tricks, especially as processor functions are not completely standard across VLMs. We'll use Idefics2 as a reference.
I don't know if it makes sense to propose PR for merge, I'd be happy to hear opinions here or in the PR thread.

**Comment by DavidePaglieri** [comment]
I'm looking for the same thing, ideally something that supports all new VLM, like Phi-3-vision etc...

What's missing I think are proper data collators compatible with all vision language models at the moment.

**Comment by fangkuoyu** [comment]
> I've added DPO support for Llava in #1797. This requires a few hacky tricks, especially as processor functions are not completely standard across VLMs. We'll use Idefics2 as a reference. I don't know if it makes sense to propose PR for merge, I'd be happy to hear opinions here or in the PR thread.

@qgallouedec Thanks for the update. I will try to run the example and provide some feedback.

**Comment by just1nseo** [comment]
@qgallouedec Thanks for the great work! Any plans on supporting PPO for LLaVa and other vlms as well ?

**Comment by qgallouedec** [comment]
> Any plans on supporting PPO for LLaVa and other vlms as well ?

LLava 1.5 is support
LLava 1.6 will be supported
PPO for VLM is not planned but we welcome contributions

**Comment by psych0v0yager** [comment]
Is phi 3 vision currently supported?

**Comment by lucasjinreal** [comment]
How about GRPO supporting?
