### ISSUE TITLE
[Feature] Add DiscoPOP algorithm

### ISSUE THREAD

**Issue by khalil-Hennara** [huggingface/trl#1796]
I've read this paper recently https://arxiv.org/abs/2406.08414, I am wandering if I can work on adding this algorithm to the framework, I want to implement for myself, but I can add it to the framework as a dependent trainer object.

**Comment by qgallouedec** [comment]
As I understand it, DiscoPOP is a meta-optimisation method, i.e. it rewrites online the objective function, among other things. I have no idea how to make it work in TRL. If you have a reference implementation or are willing to work on it, please do. I can't guarantee that it would make sense to merge it in the future, but it's certainly something that could benefit the community (maybe as a research project, or as a link in the description).

**Comment by qgallouedec** [comment]
I'm closing because this feature hasn't received any PR, and doesn't seem to be widely requested by the community. This issue may be reopened at a later date if that changes.
