### ISSUE TITLE
Update `TRL_USE_RICH` flag for CLI

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/trl#1800]
## Description

Apparently the usage of `rich` when using `trl`'s CLI is currently enforced to `True` (set to `"1"`), meaning that `rich` will always be used.

While this may be a nice enhancement to the CLI display to some, in some cases as logging to an external tracking tool as e.g. GCP's Log Explorer, makes the experience a bit hard since `rich` is not properly handled so no logs are propagated, as the `tqdm` bar is being updated.

So on, how the `TRL_USE_RICH` flag is defined and handled could be improved, so that it can be both enabled and disabled (at the moment it can only be enabled as per https://github.com/huggingface/trl/blob/78f8228874d5cf9c0e68952533cb377202e1eb22/examples/scripts/dpo.py#L58, meaning that when set, no matter what value is is, the condition `if TRL_USE_RICH` will always be true).

## Proposal

- Handle the boolean value for the environment value similarly to https://github.com/python/cpython/blob/48f9d3e3faec5faaa4f7c9849fecd27eae4da213/Lib/distutils/util.py#L308-L321 (already deprecated since Python 3.10, meaning we would need to copy that function into `utils.py`)
- If `TRL_USE_RICH` is not set when running `trl`'s CLI, then set it to `True` by default; otherwise, simply evaluate what's provided using the function mentioned above

**Comment by vwxyzjn** [comment]
Hi @alvarobartt thanks for bring up this issue. What do you think about just running the underlying script (instead of using the CLI)? Something like 

```python
python examples/scripts/sft.py \
    --model_name_or_path="facebook/opt-350m" \
    --dataset_text_field="text" \
    --report_to="wandb" \
    --learning_rate=1.41e-5 \
    --per_device_train_batch_size=64 \
    --gradient_accumulation_steps=16 \
    --output_dir="sft_openassistant-guanaco" \
    --logging_steps=1 \
    --num_train_epochs=3 \
    --max_steps=-1 \
    --push_to_hub \
    --gradient_checkpointing
```
