### ISSUE TITLE
[Possible Bug] `RewardTrainer`'s `seed` makes a difference but `data_seed` has no impact?

### ISSUE THREAD

**Issue by RylanSchaeffer** [huggingface/trl#1810]
Here is a tutorial for training a reward model: https://github.com/huggingface/trl/blob/main/examples/scripts/reward_modeling.py

If you try sweeping both `data_seed` and `seed` (both passed to `RewardConfig`), you'll find that `seed` makes a reasonable difference but `data_seed` makes **no** difference:

![image](https://github.com/huggingface/trl/assets/8942987/d9b8f189-5bb9-4e66-9ada-003f6b9f01fa)

I suspect that there might be no data shuffling. That would explain why `data_seed` makes no difference and might explain why I'm seeing odd behavior if training for more than 1 epoch:

https://twitter.com/RylanSchaeffer/status/1809201563606364389

**Comment by RylanSchaeffer** [comment]
Bump!

**Comment by qgallouedec** [comment]
Hey @RylanSchaeffer, sorry for the delay.
Actually, I encounter a different issue right now: the `RewardTrainer` is not deterministic. After further investigation, it seems not to come from trl but from transformers (and probably affect all our trainers). I'll then transfer the discussion to the issue you've opened.

**Comment by qgallouedec** [comment]
Not strictly related to the initial question, but side note from https://github.com/huggingface/transformers/issues/31818#issuecomment-2295382646, I recommend adding `set_seed` in our script.

**Comment by qgallouedec** [comment]
> Not strictly related to the initial question, but side note from [huggingface/transformers#31818 (comment)](https://github.com/huggingface/transformers/issues/31818#issuecomment-2295382646), I recommend adding `set_seed` in our script.

`set_seed` is called in the trainer initialisation so we actually don't need it in script (expected if we run random things before the trainer initialisation, which seems not to be the case).

**Comment by qgallouedec** [comment]
Closed via https://github.com/huggingface/transformers/pull/33731
