### ISSUE TITLE
Support for more trainers in CLI

### ISSUE THREAD

**Issue by martinakaduc** [huggingface/trl#1811]
Currently, the trl CLI only supports `sft` and `dpo` trainers (see [here](https://github.com/huggingface/trl/blob/747612f9d3063de56b6524e5feb0c9feab21d4c4/trl/commands/cli.py#L24)).
Other trainers such as PPO, KTO, etc. are not supported at this time.

Do you have plans to support other trainers? Or is there a specific reason for not supporting these trainers?
I can help you add these trainers to the CLI if you think it is possible but do not have the bandwidth to do it.

**Comment by qgallouedec** [comment]
Thanks for the proposal @martinakaduc, sorry for the late reply. Yes we would be interested to add more of them. Feel free to open a PR if you're still interested in contributing :)

**Comment by qgallouedec** [comment]
Closing in favour of #2101
