### ISSUE TITLE
BUG: UserWarning: Could not find response key in the following instance:

### ISSUE THREAD

**Issue by TangJiakai** [huggingface/trl#1820]
I used DataCollatorForCompletionOnlyLM, and regardless of whether I use a string or the ID encoded by the tokenizer, it gives a warning: UserWarning: Could not find response key [22559, 25, 220] in the following instance. However, I am certain that my input contains this response template."

p.s. [22559, 25, 220] is the token ids encoded by “\n### Answer: ”

Here is my code
```

def formatting_prompts_func(example):
    output_texts = []
    for i in range(len(example['prompt'])):
        text = f"### Question: {example['prompt'][i]}\n### Answer: {example['completion'][i]}"
        output_texts.append(text)
    return output_texts

# The first method
response_template_string = "\n### Answer: "
response_template_ids = tokenizer.encode(response_template_string, add_special_tokens=False)[2:]
collator = DataCollatorForCompletionOnlyLM(response_template_ids, tokenizer=tokenizer)

# The second method
response_template_string = "\n### Answer: "
collator = DataCollatorForCompletionOnlyLM(response_template_string, tokenizer=tokenizer)

```

**Comment by AIR-hl** [comment]
Please provide more information about the model tokenizer

**Comment by aspears-premierinc** [comment]
@TangJiakai did you end up finding a solution? Running into the same issue...
