### ISSUE TITLE
Support for Iterative DPO

### ISSUE THREAD

**Issue by RishabhMaheshwary** [huggingface/trl#1824]
Do we have support for iterative DPO in TRL? I came across IterativeTrainer #737 not sure if it is the same.
In Iterative DPO the reference model is updated with the previous trained checkpoint for subsequent DPO trains.

Some of the papers that use it:
1. [Self-rewarding Language Models](https://arxiv.org/abs/2401.10020).
2. [Cring-Loss](https://arxiv.org/abs/2312.16682).
3. [Curri-DPO](https://arxiv.org/abs/2403.07230).
4. [sDPO](https://arxiv.org/abs/2403.19270).

**Comment by AIR-hl** [comment]
You can see [RLHFlow](https://github.com/RLHFlow/Online-RLHF)
