### ISSUE TITLE
No way to drop samples which are longer than `max_length` in ORPOTrainer?

### ISSUE THREAD

**Issue by xzuyn** [huggingface/trl#1832]
Unless I'm missing something there's no way to give it your dataset and then have it throw away anything that doesn't fit within `max_length`. It seems like you're forced to either;
1. Tokenize the samples yourself first to find which are too long, then throw them away before letting the ORPOTrainer deal with the samples that do fit.
2. Have ORPOTrainer truncate your samples which don't fit.

Preference training is already finicky, so trying to properly train a model when your original samples have data removed from them sounds like a recipe for disaster. It's also just not what I want to happen when I train. I'd much rather have less samples and know they are all exactly as I saved them in my dataset than have more samples and what they contain is completely different.

Is there any way or any plan to allow the samples to be dropped instead of truncated? Also I haven't looked at the other trainers so this might be an issue for them as well?

**Comment by kashif** [comment]
so the `max_length` is used to truncate the prompt+completions rather than remove them... I suppose if you need to remove them can't do that in the data-preparation stage?

**Comment by xzuyn** [comment]
That's what I mean. You have to setup your own way of filtering out the samples beforehand, when it would make more sense to have a flag to drop instead of truncate. The code is already checking sample length to decide if it needs to truncate, so the code could just be done there to drop the samples instead.
