### ISSUE TITLE
Some questions about PPO trainer

### ISSUE THREAD

**Issue by cjh0526** [huggingface/trl#1857]
I used the PPO trainer will have warnings, such as The average ratio of batch (12.26) exceeds threshold 10.00. Skipping batch. and UserWarning: KL divergence is starting to become negative: -2.44 - this might be a precursor for failed training. sometimes this happens because the generation kwargs are not correctly set. Please make sure that the generation kwargs are set correctly, or review your training hyperparameters. Could someone tell me reasons.

**Comment by qhe97** [comment]
Same issue, Did you solve it?

**Comment by qgallouedec** [comment]
Thanks for asking. 

- Batch Ratio Warning: for some mini-batches, the new policy diverges too much from the old one, so the trainer skips these mini-batches to avoid loss spikes.

- Negative KL Divergence: KL divergence should be positive, so a negative value might indicate that the training is diverging/  becoming numerically unstable.

It's not possible to give a more precise answer to your rather general question. If my answer isn't enough, feel free to open one or more other issues and describe your question more precisely, if possible with a minimal code to reproduce what you're describing.
