### ISSUE TITLE
Processing issue in Anthropic HH dataset

### ISSUE THREAD

**Issue by ZhiyuLi-goog** [huggingface/trl#1858]
As titled, found some issues:
* bad choice of prompt: given Anthropic HH dataset is a multiple conversation loop between Human and Assistant, this line applies left-most split i.e. uses the first Human content as prompt while [the original dpo implementation](https://github.com/eric-mitchell/direct-preference-optimization/blob/main/preference_datasets.py#L17) applies right-most split i.e. uses the all conversation excluding the last Assistant's response, as the prompt. 
https://github.com/huggingface/trl/blob/4e85bd75a9dfca0074eef3a90130054c283eed39/examples/datasets/anthropic_hh.py#L77
```
# it might not be a good idea for HH dataset since majority of differences are located in the last Assistant's response
'chosen': "\n\nHuman: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: I haven't even thought about it.",
'rejected': "\n\nHuman: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: Ass."

# left-most split i.e. uses the first Human content as prompt
"prompt": "What are some cuss words in english"

# right-most split i.e. uses the all conversation excluding the last Assistant's response, as the prompt.
"prompt": "\n\nHuman: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: "
```
It would be better to use the latter one to differentiate the chosen and rejected samples. Note that the loss would be calculated after masking out prompt tokens. It would be an issue if the chosen and rejected samples are very close.
Maybe a even better one is to find maximum common prefix
```
def extract_anthropic_prompt(chosen, rejected):
    """Extract the anthropic prompt from a prompt and response pair."""
    search_term = "\n\nAssistant:"
    common_prefix = os.path.commonprefix([chosen, rejected])
    search_term_idx = common_prefix.rfind(search_term)
    assert search_term_idx != -1, f"Prompt and response does not contain '{search_term}'"
    return chosen[: search_term_idx + len(search_term)]
```
* duplicate prompts(same in https://github.com/huggingface/trl/issues/1582): this line implies no prompt in either chosen or rejected samples. However it is not sanity checked. And it should be an issue in [the anthropic dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style?row=0), where both chosen or rejected include prompt. Propose to 1) add some sanity check; 2) split datasets according to [the reference dpo implementation](https://github.com/eric-mitchell/direct-preference-optimization/blob/main/preference_datasets.py#L146-L149)
https://github.com/huggingface/trl/blob/4e85bd75a9dfca0074eef3a90130054c283eed39/trl/trainer/dpo_trainer.py#L739

**Comment by Galaxy-Husky** [comment]
I think the latest code has applied the right-most split method to process the Anthropic HH dataset. https://github.com/huggingface/trl/blob/9929370dee9975f1c6d80b32198ea3e7fd0dcc06/examples/scripts/dpo.py#L156-L160

**Comment by ZhiyuLi-goog** [comment]
> I think the latest code has applied the right-most split method to process the Anthropic HH dataset.
> 
> https://github.com/huggingface/trl/blob/9929370dee9975f1c6d80b32198ea3e7fd0dcc06/examples/scripts/dpo.py#L156-L160

You are right not problems in this script.

However, it is the following dataset script that is used to generate [processed anthropic HH dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style?row=4), and you can see left-most split in the processed dataset.
https://github.com/huggingface/trl/blob/4e85bd75a9dfca0074eef3a90130054c283eed39/examples/datasets/anthropic_hh.py#L77

**Comment by Galaxy-Husky** [comment]
> > I think the latest code has applied the right-most split method to process the Anthropic HH dataset.
> > https://github.com/huggingface/trl/blob/9929370dee9975f1c6d80b32198ea3e7fd0dcc06/examples/scripts/dpo.py#L156-L160
> 
> You are right not problems in this script.
> 
> However, it is the following dataset script that is used to generate [processed anthropic HH dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style?row=4), and you can see left-most split in the processed dataset.
> 
> https://github.com/huggingface/trl/blob/4e85bd75a9dfca0074eef3a90130054c283eed39/examples/datasets/anthropic_hh.py#L77

I understand what you mean, and I noticed the same issue earlier. However, based on the script pointed out above, it seems they may not fix this issue.

**Comment by qgallouedec** [comment]
> However, it is the following dataset script that is used to generate [processed anthropic HH dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style?row=4), and you can see left-most split in the processed dataset.

You're right, however, as you can see in the DPO script example

https://github.com/huggingface/trl/blob/9929370dee9975f1c6d80b32198ea3e7fd0dcc06/examples/scripts/dpo.py#L156-L160

the prompt column is not used. So, consider the prompt column of the [processed anthropic HH dataset](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style?row=4) as informative.
I agree it can be a bit misleading though.
