### ISSUE TITLE
Use `WinRateCallback` without `ref_model`

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#1860]
> Another comment unrelated to this exact PR, but perhaps we can include this change. In the original version of the WinRateCallback, it was possible to use the starting model as the reference directly, without having the following:
```
    if not hasattr(trainer, "ref_model"):
        raise AttributeError("Trainer must have a `ref_model` attribute.")
```
and the `model` rather than `ref_model` was used here:
```
    def on_train_begin(self, args: TrainingArguments, state: TrainerState, control: TrainerControl, **kwargs):
        tokenizer = kwargs["tokenizer"]
        tokenizer.padding_side = "left"
        accelerator = self.trainer.accelerator
        with accelerator.split_between_processes(self.eval_dataset["prompt"], apply_padding=True) as prompts:
            self.ref_completions = self.generate_completions_for_model(self.trainer.ref_model, tokenizer, prompts)
```

This enabled us to use this callback to monitor progress during an SFT, without the need for a ref model.

I believe the result should be the same even in a DPO setting. @qgallouedec are you aware of why this was changed in @lewtun's PR?

_Originally posted by @edbeeching in https://github.com/huggingface/trl/issues/1856#issuecomment-2243218041_

**Comment by qgallouedec** [comment]
Ok! When a ref_model is not provided, we will use the model, so that we can use it with sft!

> and the `model` rather than `ref_model` was used here:

Where? On training begin we use the ref model to generate the reference completions. So we do use the ref_model here. But I don't see where the model is used instead.

**Comment by edbeeching** [comment]
> Ok! When a ref_model is not provided, we will use the model, so that we can use it with sft!
> 
> > and the `model` rather than `ref_model` was used here:
> 
> Where? On training begin we use the ref model to generate the reference completions. So we do use the ref_model here. But I don't see where the model is used instead.

At the start of training `ref_model == model` so I do not think there is a requirement to reference the ref model at all. This will make the implementation simpler for when using the callback in an SFT setting. In addition, there appears to be a naming mismatch as the `OnlineDPOTrainer` calls `ref_model`, `ref_policy` this will need to be harmonized.

**Comment by qgallouedec** [comment]
> At the start of training ref_model == model so I do not think there is a requirement to reference the ref model at all.

Is it always the case? Do we want to assume that it's always the case? If so, it would simplify things.

> In addition, there appears to be a naming mismatch as the `OnlineDPOTrainer` calls `ref_model`, `ref_policy` this will need to be harmonized.

Yep, it's planned

**Comment by lewtun** [comment]
Reopen
