### ISSUE TITLE
Incorrect reference responses when using PEFT with PPOTrainer

### ISSUE THREAD

**Issue by Sean-OB** [huggingface/trl#1871]
Below is a snippet from `ppo_trainer.py`

[Line permalink](https://github.com/huggingface/trl/blob/7dcf437a1997cb1b252e8ea0b8ad7dca13261d7e/trl/trainer/ppo_trainer.py#L485)

```
if generate_ref_response:
            ref_model = self.model if self.is_peft_model else self.ref_model
        if isinstance(query_tensor, List):
            response = self._generate_batched(
                self.model,
                query_tensor,
                length_sampler=length_sampler,
                batch_size=batch_size,
                return_prompt=return_prompt,
                **generation_kwargs,
            )
            if generate_ref_response:
                ref_response = self._generate_batched(
                    ref_model,
                    query_tensor,
                    length_sampler=length_sampler,
                    batch_size=batch_size,
                    return_prompt=return_prompt,
                    **generation_kwargs,
                )
```

When training with PEFT, we have `ref_model` the same as the base model but instead called with a context to disable the adapters:

```
with torch.no_grad():
            all_logprobs, logits_or_none, values, masks = self.batched_forward_pass(
                self.model,
                queries,
                responses,
                model_inputs,
                response_masks=response_masks,
                return_logits=full_kl_penalty,
            )
            with self.optional_peft_ctx():
                ref_logprobs, ref_logits_or_none, _, _ = self.batched_forward_pass(
                    self.model if self.is_peft_model else self.ref_model,
                    queries,
                    responses,
                    model_inputs,
                    return_logits=full_kl_penalty,
                )
```

However, code to generate reference responses doesn't use this context. This leads to the reference responses logged in the tables to come from the optimized RL model rather than the reference model.

To reproduce, run any training loop with the PPOTrainer with your logging software of choice -- my setup uses WandB -- and look at the table of responses. The reference responses will be drawn from the same distribution as the model responses. Below is a screenshot from a dummy run where I rewarded the model for outputting the word "but." The reference responses should not be any different after the loop.

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/3e478cfe-0e1f-4a6a-a483-d654f551785c">

**Comment by skylooop** [comment]
I observed same problem with DPOTrainer. `generate_during_eval=True` in DPOConfig produces reference outputs from current model being trained.

**Comment by qgallouedec** [comment]
Closing as `PPOTrainer` as been deprecated (replaced by `PPOv2Trainer`)
