### ISSUE TITLE
ImportError: cannot import name 'DDPOConfig' from 'trl' (unknown location)

### ISSUE THREAD

**Issue by long-yy** [huggingface/trl#1875]
`(diffusion_ddpo) XXX@sf:~/code/diffusion_ddpo$ python ddpo.py     --num_epochs=200     --train_gradient_accumulation_steps=1     --sample_num_steps=50     --sample_batch_size=6     --train_batch_size=3     --sample_num_batches_per_epoch=4     --per_prompt_stat_tracking=True     --per_prompt_stat_tracking_buffer_size=32     --tracker_project_name="stable_diffusion_training"     --log_with="wandb"
Traceback (most recent call last):
  File "/lab/XXX/code/diffusion_ddpo/ddpo.py", line 36, in <module>
    from trl import DDPOConfig, DDPOTrainer, DefaultDDPOStableDiffusionPipeline
ImportError: cannot import name 'DDPOConfig' from 'trl' (unknown location)`

To modify the source code of TRL, install by'pip install -- editable' , but there are issues

**Comment by qgallouedec** [comment]
Closed as not enough information to reproduce.
