### ISSUE TITLE
Dataset format for `ORPOTrainer`

### ISSUE THREAD

**Issue by anakin87** [huggingface/trl#1886]
Hello, and thanks for the great work. :blue_heart: 

I am having trouble understanding the expected format for the dataset in the `ORPOTrainer`.

- the [docs](https://huggingface.co/docs/trl/main/en/orpo_trainer#expected-dataset-format) are somewhat ambiguous and refer to separated entries `prompt`, `chosen`, and `rejected` (`chosen` and `rejected` do not seem to have to include the `prompt`)

- the [example script](https://github.com/huggingface/trl/blob/main/examples/scripts/orpo.py) uses [trl-internal-testing/hh-rlhf-helpful-base-trl-style](https://huggingface.co/datasets/trl-internal-testing/hh-rlhf-helpful-base-trl-style), where `prompt` is a text column, while `chosen` and `rejected` are list of messages that also include the `prompt`.

  https://github.com/huggingface/trl/blob/9929370dee9975f1c6d80b32198ea3e7fd0dcc06/examples/scripts/orpo.py#L98-L100
  here, the chat template is applied to the entire `chosen` and `rejected` (including the prompt), but the `prompt` column itself seems to be ignored.
  
-  [the TRL example in the xfactlab/orpo](https://github.com/xfactlab/orpo/blob/main/trl/test_orpo_trainer_demo.py) uses [argilla/ultrafeedback-binarized-preferences-cleaned](https://huggingface.co/datasets/argilla/ultrafeedback-binarized-preferences-cleaned), which follows the same format as hh-rlhf-helpful-base-trl-style. In this case ([code](https://github.com/xfactlab/orpo/blob/208d2d648068e700cbb1ae0e8320b1dc99b014ec/trl/test_orpo_trainer_demo.py#L108-L113)), the `prompt` is taken into account (chat template is applied); the second (=assistant) message is extracted from `chosen` and `rejected` (and the chat template is not applied; might be an oversight).

Can you help me figure out what is the right format for the `ORPOTrainer`?

I previously managed to train a model with `ORPOTrained` (using [alvarobartt/dpo-mix-7k-simplified](https://huggingface.co/datasets/alvarobartt/dpo-mix-7k-simplified) - where `chosen` and `rejected` do not include the prompt), but at this point I'm not sure what's right. :smiley: 

@alvarobartt @jiwooya1000 
:pray:

**Comment by anakin87** [comment]
Another reference in the Alignment Handbook: https://github.com/huggingface/alignment-handbook/blob/444e0f8414e066693b50e6756f90f736e5782b74/src/alignment/data.py#L80

**Comment by jiwooya1000** [comment]
Hello @anakin87, thank you for the ping!
In the TRL implementation, both `chosen` and `rejected` responses should not include the `prompt`.
And by `prompt`, it refers to the actual prompt wrapped with the chat template (e.g., `<|user|>\n{prompt}\n<|assistant|>\n` for Zephyr template).
Therefore, `chosen` and `rejected` responses would only have the response (it may have a chat template-related token at the end like `<end_of_turn>` if the model needs one)

**Comment by anakin87** [comment]
@jiwooya1000 thanks for the clarification!
So it seems there is something wrong with the [example script](https://github.com/huggingface/trl/blob/main/examples/scripts/orpo.py)...

**Comment by qgallouedec** [comment]
To clarify, the `ORPOTrainer` expects the input to be in the following format:


```python
{"prompt": "USER: Where is Paris?\n",
 "chosen": "ASSISTANT: Paris is in France.\n",
 "rejected": "ASSISTANT: Paris is in Germany.\n"}
```

and **not**

```python
{"prompt": "USER: Where is Paris?\n",
 "chosen": "USER: Where is Paris?\nASSISTANT: Paris is in France.\n",
 "rejected": "USER: Where is Paris?\nASSISTANT: Paris is in Germany.\n"
}
```

Thank you for reporting the issue with the ORPO example, fix is on the way.
