### ISSUE TITLE
Cannot import name 'DPOConfig' from 'trl'

### ISSUE THREAD

**Issue by Na00s** [huggingface/trl#1910]
Hi everyone,

I stumbled upon the following error: 

Traceback (most recent call last):
  File "/mnt/datascience3/Ali/Pruning_Llama_3.1/train_DPO.py", line 50, in <module>
    from trl import SFTTrainer, DPOTrainer, DPOConfig
ImportError: cannot import name 'DPOConfig' from 'trl' (/mnt/datascience3/Ali/.venv/lib/python3.9/site-packages/trl/__init__.py)

All my packages are up to date with the unsloth requirements.

I also think this issue only arises when using unsloth.

I think there is a similar issue that was opened but I don't think it was solved yet.

Thanks in advance for your help.

**Comment by burtenshaw** [comment]
Hey @Na00s 👋 . I tried to reproduce this on two environments (google-colab and ubuntu with fresh python 3.9 env) and I wasn't able to. I installed `trl` from pip and source in both cases. I know you mentioned that your packages are up to date, but it seems like a dependency issue to me. 

From using [Unsloth](https://github.com/unslothai/unsloth/tree/main#installation-instructions), I know that installation requires environment parameters for cuda, colab, etc. Unsloth's pip installation is documented [here](https://docs.unsloth.ai/get-started/installation/pip-install). 

If those docs don't resolve your issue, you should consider an issue on [Unsloth](https://github.com/unslothai/unsloth/tree/main#installation-instructions) or their Discord.

**Comment by Na00s** [comment]
Thank you for the prompt answer, I'll try the fix you mentioned !

**Comment by qgallouedec** [comment]
It seems that the error cannot be reproduced. I'm closing. If the issue remains, please open a new issue and provide all the information and steps to reproduce the error.
