### ISSUE TITLE
Redundant special tokens when applying chat template (?)

### ISSUE THREAD

**Issue by LawrenceGrigoryan** [huggingface/trl#1912]
https://github.com/huggingface/trl/blob/e3fe28ee1a8bfab9739f849759c93d56776376e2/trl/trainer/sft_trainer.py#L323

Seems like if the `formatting_func` is defined during the initialization of `SFTTrainer`,  redundant special tokens will be added because everywhere else the parameter `add_special_tokens` is `True`

Or is it an intended logic? A bit confusing to be honest

**Comment by qgallouedec** [comment]
The value of `add_special_tokens` comes from `SFTConfig.dataset_kwargs`. So you can disable it using this arg
