### ISSUE TITLE
how to use kto_pair loss in the latest version ?

### ISSUE THREAD

**Issue by vincezengqiang** [huggingface/trl#1927]
I can see that kto_pair losstype is no longer available in the latest version of dpo trainer. You suggest to use ktotrainer instead. 
But kto_pair loss worked much better than kto_trainer on my dataset, so how do I continue to use kto_pair if I'm using the latest version of the trl library?
thanks a lot!

**Comment by hjh0119** [comment]
maybe you can try trl < 0.9.5

**Comment by vincezengqiang** [comment]
> maybe you can try trl < 0.9.5

fine

**Comment by qgallouedec** [comment]
Do you mind sharing your dataset?

**Comment by qgallouedec** [comment]
Closing as not enough information to reproduce that kto_pair is worst than using KTOTrainer
