### ISSUE TITLE
Additional Optional Loss to Center Reward Models

### ISSUE THREAD

**Issue by RylanSchaeffer** [huggingface/trl#1931]
Reward models are invariant since for any prompt-dependent function $f: \mathcal{P} \rightarrow \mathbb{R}$:

$$\sigma \Big( R(p, r_1) - R(p, r_2) \Big) = \sigma \Big( R(p, r_1) + f(p) - R(p, r_2) - f(p) \Big) := \sigma \Big( \tilde{R}(p, r_1) - \tilde{R}(p, r_2) \Big)$$

Consequently, in a number of subsequent situations, one often needs to compute a reward model's average score and subtract that. This is a pain.

As a different solution, to address this, a [paper by Google](https://arxiv.org/abs/2312.09244) added an auxiliary loss function to encourage the reward model to be mean zero:

$$\Big( R(p, r_1) + R(p, r_2) \Big)^2 $$

Could this additional loss please be added as an optional additional loss function to `RewardTrainer`?

**Comment by qgallouedec** [comment]
Thank you very much for suggesting this new feature! I agree that it's an interesting new feature. Let's work on it as part of your PR.

**Comment by RylanSchaeffer** [comment]
@qgallouedec awesome! I'm happy to make whatever changes to the PR you want. I'm not a TRL contributor so I don't know what your guidelines / standards are :)

**Comment by RylanSchaeffer** [comment]
I just realized my PR has a bug. We don't want the mean of the squared **differences**. We want the mean of the squared **sums**.

**Comment by RylanSchaeffer** [comment]
@qgallouedec Your implementation is correct.
