### ISSUE TITLE
How to Save the PPOTrainer?

### ISSUE THREAD

**Issue by ThisGuyIsNotAJumpingBear** [huggingface/trl#1934]
The previous issue for this question https://github.com/huggingface/trl/issues/1643#issue-2294886330 is closed but remained unanswered. If I do `ppo_trainer.save_pretrained('path/to/a/folder')` and then `ppo_trainer.from_pretrained('path/to/that/folder')`, I get this error:

ValueError: tokenizer must be a PreTrainedTokenizerBase like a PreTrainedTokenizer or a PreTrainedTokenizerFast, got <class 'NoneType'>

It seems that the `PPOTrainer` object does not implement the two functions from `huggingface_hub.PyTorchModelHubMixin`. How should I save my trainer then?

**Comment by qgallouedec** [comment]
Thanks for reporting @ThisGuyIsNotAJumpingBear. Indeed, `PPOTrainer` does not implement a `save_model`, and probably will not. But `PPOTrainerv2` does. We strongly recommend that you update your code to use `PPOTrainerv2`.

**Comment by ThisGuyIsNotAJumpingBear** [comment]
I see. I will update to `PPOTrainerv2`.

It would be great if you could leave comments in `PPOTrainer` if it is no longer under maintainance, or change the example codes. It might be a bit misleading to new people who want to try PPO at this stage.

**Comment by qgallouedec** [comment]
True! I'll keep this issue opened until it's done

**Comment by qgallouedec** [comment]
Done in #2016
