### ISSUE TITLE
Is there a way to finetune a finetuned model?

### ISSUE THREAD

**Issue by sherlcok314159** [huggingface/trl#1937]
I use peft and SFTrainer to train a lora model. And I want to fintune this lora model on new datasets. How can I manage this? When using the code below, the grad norm is always zero.

```python
peft_model = ...
model = AutoModelForCausalLM.from_pretrained(
    peft_model,
    device_map='auto',
)
training_args = TrainingArguments(...)
trainer = SFTrainer(...)
trainer.train()
````

**Comment by AIR-hl** [comment]
> I use peft and SFTrainer to train a lora model. And I want to fintune this lora model on new datasets. How can I manage this? When using the code below, the grad norm is always zero.我使用 peft 和 SFTrainer 来训练 lora 模型。我想在新数据集上调整这个 lora 模型。我该如何处理这个问题？使用下面的代码时，梯度范数始终为零。
> 
> ```python
> peft_model = ...
> model = AutoModelForCausalLM.from_pretrained(
>     peft_model,
>     device_map='auto',
> )
> training_args = TrainingArguments(...)
> trainer = SFTrainer(...)
> trainer.train()
> ```

you can merge the peft model through `merge_and_unload` function of `peft` firstly, and then use the merged model to fine-tune.
