### ISSUE TITLE
A bug in `__init__` method of class `DPOTrainer`?

### ISSUE THREAD

**Issue by jiaweihhuang** [huggingface/trl#1942]
Hi, I'm trying to use `DPOTrainer` without specifying the argument `model_init_kwargs`. However, it raises an error: `AttributeError: 'TrainingArguments' object has no attribute 'model_init_kwargs'`.

I check the initialization code of `DPOTrainer`, and find the following codes from line 170 to 196 in the `__init__` method of the `DPOTrainer`.
```
def __init__(
        self,
        model: Optional[Union[PreTrainedModel, nn.Module, str]] = None,
        ref_model: Optional[Union[PreTrainedModel, nn.Module, str]] = None,
        beta: float = 0.1,
        label_smoothing: float = 0,
        loss_type: Literal["sigmoid", "hinge", "ipo", "bco_pair", "robust", "aot", "aot_pair"] = "sigmoid",
        args: Optional[DPOConfig] = None,
        data_collator: Optional[DataCollator] = None,
        label_pad_token_id: int = -100,
        padding_value: Optional[int] = None,
        truncation_mode: str = "keep_end",
        train_dataset: Optional[Dataset] = None,
        eval_dataset: Optional[Union[Dataset, Dict[str, Dataset]]] = None,
        tokenizer: Optional[PreTrainedTokenizerBase] = None,
        model_init: Optional[Callable[[], PreTrainedModel]] = None,
        callbacks: Optional[List[TrainerCallback]] = None,
        optimizers: Tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LambdaLR] = (None, None),
        preprocess_logits_for_metrics: Optional[Callable[[torch.Tensor, torch.Tensor], torch.Tensor]] = None,
        max_length: Optional[int] = None,
        max_prompt_length: Optional[int] = None,
        max_target_length: Optional[int] = None,
        peft_config: Optional[Dict] = None,
        is_encoder_decoder: Optional[bool] = None,
        disable_dropout: bool = True,
        generate_during_eval: bool = False,
        compute_metrics: Optional[Callable[[EvalLoopOutput], Dict]] = None,
        precompute_ref_log_probs: bool = False,
        dataset_num_proc: Optional[int] = None,
        model_init_kwargs: Optional[Dict] = None,
        ref_model_init_kwargs: Optional[Dict] = None,
        model_adapter_name: Optional[str] = None,
        ref_adapter_name: Optional[str] = None,
        reference_free: bool = False,
        force_use_ref_model: bool = False,
    ):
        if model_init_kwargs is not None:
            warnings.warn(
                "You passed `model_init_kwargs` to the DPOTrainer, the value you passed will override the one in the `DPOConfig`."
            )
            args.model_init_kwargs = model_init_kwargs

        if args.model_init_kwargs is None:
            model_init_kwargs = {}
        elif not isinstance(model, str):
            raise ValueError(
                "You passed model_init_kwargs to the DPOTrainer/DPOConfig, but your model is already instantiated."
            )
        else:
            model_init_kwargs = args.model_init_kwargs

            torch_dtype = model_init_kwargs["torch_dtype"]
            if torch_dtype is not None:
                # Convert to `torch.dtype` if an str is passed
                if isinstance(torch_dtype, str) and torch_dtype != "auto":
                    torch_dtype = getattr(torch, torch_dtype)

                if torch_dtype != "auto" and not isinstance(torch_dtype, torch.dtype):
                    raise ValueError(
                        f"Invalid `torch_dtype` passed to the DPOConfig. Expected a string with either `torch.dtype` or 'auto', but got {torch_dtype}."
                    )

            model_init_kwargs["torch_dtype"] = torch_dtype
```

It seems to me that if I do not specify `model_init_kwargs` when I call `__init__`, `args.model_init_kwargs` will not be assigned and line 176 (`if args.model_init_kwargs is None:`) will always cause an error?

Do you have easy ways to fix it? or maybe please correct me if I made a mistake.

Thank you!

**Comment by jiaweihhuang** [comment]
Oh, it seems `model_init_kwargs` is not the only variable has this issue. For example, `ref_model_init_kwargs`, `model_adapter_name`, etc.

**Comment by AIR-hl** [comment]
> Hi, I'm trying to use `DPOTrainer` without specifying the argument `model_init_kwargs`. However, it raises an error: `AttributeError: 'TrainingArguments' object has no attribute 'model_init_kwargs'`.
> 
> I check the initialization code of `DPOTrainer`, and find the following codes from line 170 to 196 in the `__init__` method of the `DPOTrainer`.
> 
> ```
> def __init__(
>         self,
>         model: Optional[Union[PreTrainedModel, nn.Module, str]] = None,
>         ref_model: Optional[Union[PreTrainedModel, nn.Module, str]] = None,
>         beta: float = 0.1,
>         label_smoothing: float = 0,
>         loss_type: Literal["sigmoid", "hinge", "ipo", "bco_pair", "robust", "aot", "aot_pair"] = "sigmoid",
>         args: Optional[DPOConfig] = None,
>         data_collator: Optional[DataCollator] = None,
>         label_pad_token_id: int = -100,
>         padding_value: Optional[int] = None,
>         truncation_mode: str = "keep_end",
>         train_dataset: Optional[Dataset] = None,
>         eval_dataset: Optional[Union[Dataset, Dict[str, Dataset]]] = None,
>         tokenizer: Optional[PreTrainedTokenizerBase] = None,
>         model_init: Optional[Callable[[], PreTrainedModel]] = None,
>         callbacks: Optional[List[TrainerCallback]] = None,
>         optimizers: Tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LambdaLR] = (None, None),
>         preprocess_logits_for_metrics: Optional[Callable[[torch.Tensor, torch.Tensor], torch.Tensor]] = None,
>         max_length: Optional[int] = None,
>         max_prompt_length: Optional[int] = None,
>         max_target_length: Optional[int] = None,
>         peft_config: Optional[Dict] = None,
>         is_encoder_decoder: Optional[bool] = None,
>         disable_dropout: bool = True,
>         generate_during_eval: bool = False,
>         compute_metrics: Optional[Callable[[EvalLoopOutput], Dict]] = None,
>         precompute_ref_log_probs: bool = False,
>         dataset_num_proc: Optional[int] = None,
>         model_init_kwargs: Optional[Dict] = None,
>         ref_model_init_kwargs: Optional[Dict] = None,
>         model_adapter_name: Optional[str] = None,
>         ref_adapter_name: Optional[str] = None,
>         reference_free: bool = False,
>         force_use_ref_model: bool = False,
>     ):
>         if model_init_kwargs is not None:
>             warnings.warn(
>                 "You passed `model_init_kwargs` to the DPOTrainer, the value you passed will override the one in the `DPOConfig`."
>             )
>             args.model_init_kwargs = model_init_kwargs
> 
>         if args.model_init_kwargs is None:
>             model_init_kwargs = {}
>         elif not isinstance(model, str):
>             raise ValueError(
>                 "You passed model_init_kwargs to the DPOTrainer/DPOConfig, but your model is already instantiated."
>             )
>         else:
>             model_init_kwargs = args.model_init_kwargs
> 
>             torch_dtype = model_init_kwargs["torch_dtype"]
>             if torch_dtype is not None:
>                 # Convert to `torch.dtype` if an str is passed
>                 if isinstance(torch_dtype, str) and torch_dtype != "auto":
>                     torch_dtype = getattr(torch, torch_dtype)
> 
>                 if torch_dtype != "auto" and not isinstance(torch_dtype, torch.dtype):
>                     raise ValueError(
>                         f"Invalid `torch_dtype` passed to the DPOConfig. Expected a string with either `torch.dtype` or 'auto', but got {torch_dtype}."
>                     )
> 
>             model_init_kwargs["torch_dtype"] = torch_dtype
> ```
> 
> It seems to me that if I do not specify `model_init_kwargs` when I call `__init__`, `args.model_init_kwargs` will not be assigned and line 176 (`if args.model_init_kwargs is None:`) will always cause an error?
> 
> Do you have easy ways to fix it? or maybe please correct me if I made a mistake.
> 
> Thank you!

没看明白你的问题，代码似乎没有问题

**Comment by AIR-hl** [comment]
> Oh, it seems `model_init_kwargs` is not the only variable has this issue. For example, `ref_model_init_kwargs`, `model_adapter_name`, etc.

没理解你的问题，代码似乎没有问题

**Comment by jiaweihhuang** [comment]
我好像找到原因了，我run code的时候还是用之前的TrainingArgument，好像最新版本应该用trl自己的DPOConfig，换了之后就没问题了。

**Comment by qgallouedec** [comment]
In English. Please.
