### ISSUE TITLE
llama3 tokenizer compatibility of DPOTrainer

### ISSUE THREAD

**Issue by hash2430** [huggingface/trl#1960]
I see annotations in build_tokenized_answer of DPOTrainer regarding llama tokenizer compatibility.
        """
        Llama tokenizer does satisfy `enc(a + b) = enc(a) + enc(b)`.
        It does ensure `enc(a + b) = enc(a) + enc(a + b)[len(enc(a)):]`.
        Reference:
            https://github.com/EleutherAI/lm-evaluation-harness/pull/531#issuecomment-1595586257
        """
I'm confused because it says on top that enc(a+b)=enc(a)+enc(b) is guarantted and also it says

"        # On some tokenizers, like Llama-2 tokenizer, there are occasions where tokens
        # can be merged together when tokenizing prompt+answer. This could result
        # on the last token from the prompt being different when tokenized on its own
        # vs when done as prompt+answer.
"
I might be misunderstood but they seem conflicted.
However I believe the contributors must have covered any possible issues with llama2 tokenizers.
My question is, is this also the case with llama3?
Because I don't see any comments regarding llama3 tokenizer.

**Comment by qgallouedec** [comment]
I understand your question. This will change with #2209, as we will tokenize prompt and completion separately.
Feel free to take a look at the corresponding section in the PR description.
