### ISSUE TITLE
issue with precompute_ref_log_probs  and dpo training loss stucks at 0.6931

### ISSUE THREAD

**Issue by mina-parham** [huggingface/trl#1962]
When using the `precompute_ref_log_probs=True` option, the training process is halted( the training loss sucks at 0.6931 which shows the model is not training). This issue arises due to the following code segment:

```
if (
            "reference_chosen_logps" in batch
            and "reference_rejected_logps" in batch
            and self.args.rpo_alpha is not None
        ):
            reference_chosen_logps = batch["reference_chosen_logps"]
            reference_rejected_logps = batch["reference_rejected_logps"]
```

The condition `self.args.rpo_alpha` is not None prevents the `reference_chosen_logps` and `reference_rejected_logps` from being used in the training process when `rpo_alpha` is set to None. This is problematic because when `precompute_ref_log_probs=True`, we still need to access these log probabilities from the batch regardless of the `rpo_alpha` value.

To resolve this issue, the condition should be adjusted to ensure that `reference_chosen_logps` and `reference_rejected_logps` are accessed when `precompute_ref_log_probs` is set to True, independent of the `rpo_alpha` value.

I propose a fix in this following pull request:
[https://github.com/huggingface/trl/pull/1961/files](https://github.com/huggingface/trl/pull/1961/files)

**Comment by qgallouedec** [comment]
Fixed in #1961
