### ISSUE TITLE
VLM dpo bug

### ISSUE THREAD

**Issue by liuchaohu** [huggingface/trl#1972]
trl/trainer/dpo_trainer.py line 542
The tokenizer for _super().init ()_ should be set to _self.tokenizer_ instead of _tokenizer_, otherwise the previous _is_vision_model_ will be invalid.

**Comment by qgallouedec** [comment]
what do you mean by

> otherwise the previous is_vision_model will be invalid.

?

When the model is a VLM, the `transformers.Trainer` expect a processor for the arg `tokenizer`, not a tokenizer.
in other words:
```python
Trainer(
    ...,
    # tokenizer=processor.tokenizer, # NO
    tokenizer=processor, # YES
)
```

**Comment by liuchaohu** [comment]
In line 341-343, if self.is_vision_model == True, then self.processor = tokenizer(i.e., processor) and self.tokenizer = tokenizer.tokenizer.
However, In line 536-548, super().__init__(...) will set self.tokenizer = tokenizer(i.e., processor).  
In this case, self.tokenizer & self.processor = tokenizer(i.e., processor)

**Comment by qgallouedec** [comment]
We are refactoring DPO data processing. The new implementation should be more readable.
