### ISSUE TITLE
Question: Does `trl` support training on AMD GPUs?

### ISSUE THREAD

**Issue by asmith26** [huggingface/trl#2008]
Hi there,

Just wondering, does `trl` support training on AMD GPUs?

Many thanks for any help, and for this amazing lib!

**Comment by qgallouedec** [comment]
`trl` is fully backed by `transformers`. Also, as `transformers` [supports AMD GPUs via ROCm](https://rocm.docs.amd.com/en/latest/how-to/rocm-for-ai/hugging-face-models.html), I would say that yes, you should be able to use `trl` with an AMD GPU. However, as I didn't have one available, I am not able to test it myself.

**Comment by asmith26** [comment]
Many thanks for your help and info @qgallouedec
