### ISSUE TITLE
I'm closing this issue because no one has provided any code to reproduce the error. If you think you are facing the same problem, please open another issue (link this one) with a precise description and a code to reproduce the error.

### ISSUE THREAD

**Issue by rrmaura** [huggingface/trl#2021]
I'm closing this issue because no one has provided any code to reproduce the error. If you think you are facing the same problem, please open another issue (link this one) with a precise description and a code to reproduce the error.

_Originally posted by @qgallouedec in https://github.com/huggingface/trl/issues/1010#issuecomment-2304106804_
            
—————————
—————————
I just copy pasted all cells from your tutorial in huggingface.co/docs/trl/en/ppo_trainer on a google colab with a GPU T4 and that reproduces the error. See an example here:

https://colab.research.google.com/drive/1iJXbGMFJiTf5gfW4u09uNNvXjjeSW675?usp=sharing

Do not hesitate to contact me if you cannot reproduce it.

Thank you!

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by qgallouedec** [comment]
Thank you for reporting this problem.
PPOTrainer has been deprecated in favor of PPOv2Trainer. Therefore, maintainers will probably not take the time to address it.
We keep this issue open to allow the community to propose a solution.

**Comment by qgallouedec** [comment]
Closing as PPO is now removed in favour of PPOv2Trainer
