### ISSUE TITLE
AttributeError: 'PPOv2Trainer' object has no attribute 'deepspeed' 

### ISSUE THREAD

**Issue by RylanSchaeffer** [huggingface/trl#2025]
### System Info

- `transformers` version: 4.44.0
- Platform: Linux-5.4.0-162-generic-x86_64-with-glibc2.31
- Python version: 3.11.9
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config:    - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - fsdp_config: {'fsdp_activation_checkpointing': True, 'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': True, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 'FULL_SHARD', 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'EAGER'}
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: Yes
- Using GPU in script? Yes
- GPU type: NVIDIA A100-SXM4-80GB

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

In [TRL's PPOv2Trainer TLDR example](https://github.com/huggingface/trl/blob/main/examples/scripts/ppo/ppo_tldr.py), run the [default command](https://github.com/huggingface/trl/blob/main/examples/scripts/ppo/ppo_tldr.py#L32-L44):

```
accelerate launch --config_file examples/accelerate_configs/deepspeed_zero2.yaml \
    examples/scripts/ppo/ppo_tldr.py \
    --output_dir models/minimal/ppo_tldr \
    --learning_rate 3e-6 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --total_episodes 1000000 \
    --model_name_or_path EleutherAI/pythia-1b-deduped \
    --sft_model_path cleanrl/EleutherAI_pythia-1b-deduped__sft__tldr \
    --reward_model_path cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr \
    --local_rollout_forward_batch_size 16 \
    --non_eos_penalty \
    --stop_token eos
```

It will crash with:

```
  File "/lfs/skampere1/0/rschaef/trl/examples/scripts/ppo/ppo_tldr.py", line 133, in <module>
    trainer.train()
  File "/lfs/skampere1/0/rschaef/trl/trl/trainer/ppov2_trainer.py", line 529, in train
    self._save_checkpoint(model, trial=None, metrics=metrics)
  File "/lfs/skampere1/0/rschaef/miniconda3/envs/reward_modeling_20240708/lib/python3.11/site-packages/transformers/trainer.py", line 2896, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/lfs/skampere1/0/rschaef/trl/trl/trainer/ppov2_trainer.py", line 225, in save_model
    backup_deepspeed = self.deepspeed
                       ^^^^^^^^^^^^^^
AttributeError: 'PPOv2Trainer' object has no attribute 'deepspeed' 
````

### Expected behavior

I expect the run to not crash.

**Comment by suanflower** [comment]
same error

**Comment by real-ljs** [comment]
same

**Comment by kechunFIVE** [comment]
same
