### ISSUE TITLE
The ppo_trainer.generate() call results in an error.

### ISSUE THREAD

**Issue by jusrook** [huggingface/trl#2034]
When I call the ppo_trainer.generate() function with the parameters output_scores=True and return_dict_in_generate=True, it results in an error: TypeError: 'in <string>' requires string as left operand, not int.
![图片1](https://github.com/user-attachments/assets/bbcbcc78-8171-4324-b570-e452489823b9)

**Comment by qgallouedec** [comment]
Thanks for reporting, unfortunately, PPOTrainer is deprecated and will be soon removed. We recommend using PPOv2Trainer.
As it's not a priority, the issues related to PPOTrainer have low chance to be addressed by the maintainers in the meantime. But we still welcome contributions.

**Comment by jusrook** [comment]
> Thanks for reporting, unfortunately, PPOTrainer is deprecated and will be soon removed. We recommend using PPOv2Trainer. As it's not a priority, the issues related to PPOTrainer have low chance to be addressed by the maintainers in the meantime. But we still welcome contributions.

Thank you for your response!
