### ISSUE TITLE
Disable the dropout by default in Online DPO

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#2042]
When there are methods that use log-probs, the added dropout causes fluctuations in its calculation compared to the reference model which, since it is typically used in eval mode, has no dropout.
To avoid this additional noise, it is usually deactivated.

We already have such option in other trainer:

https://github.com/huggingface/trl/blob/72f19c3fcecb0d53f356b1821d36073b65148aa0/trl/trainer/dpo_config.py#L157

Originally spotted by @kashif

**Comment by kashif** [comment]
i have fixed it in the xpo PR #1943
