### ISSUE TITLE
Reward model

### ISSUE THREAD

**Issue by Jsjgjhg** [huggingface/trl#2052]
I have a question about the selection of reward models. The loss curve and accuracy on the test set can be certain indicators, but under different training parameters, I can achieve equally low loss and accuracy. How can I make the most favorable checkpoint for PPO training reward models?

**Comment by qgallouedec** [comment]
Is your question about the metrics to use?

**Comment by Jsjgjhg** [comment]
> Is your question about the metrics to use?

Yes，how to measure whether a reward model is beneficial for PPO training?

**Comment by Jsjgjhg** [comment]
Why is indicator ppo/policy/loss always negative?like this:
![Uploading 1726630796123.png…]()

**Comment by Jsjgjhg** [comment]
I hope to receive your guidance, thank you

**Comment by qgallouedec** [comment]
Reward model evaluation is a rather broad question. I suggest you take a look at https://huggingface.co/papers/2403.13787

**Comment by Jsjgjhg** [comment]
Thank you.
