### ISSUE TITLE
Model does not generate eos when SFTTrainer with setup_chat_format is used

### ISSUE THREAD

**Issue by acforvs** [huggingface/trl#2059]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.6
- Safetensors version: 0.4.5
- Accelerate version: 0.33.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): 2.17.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: Yes
- GPU type: Tesla T4

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to use SFTTrainer along with `setup_chat_format`. When trained even for large number of steps (max_steps set to 100 in the example below for reproducibility), the model fails to generate eos_token. Instead, it outputs the chat_template directly and then continues to ramble.

Running:
```python
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer, setup_chat_format

model_name = "HuggingFaceTB/SmolLM-135M"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
dataset = load_dataset("grammarly/coedit", split="train").filter(lambda x: x["task"] == "gec")
dataset = dataset.train_test_split(test_size=0.005, seed=42)
dataset_train_sft, dataset_test_sft = dataset["train"], dataset["test"]

def format_to_messages(example):
    messages = [
        {"role": "user", "content": example["src"]},
        {"role": "assistant", "content": example["tgt"]}
    ]
    return {"messages": messages}

def format_ds(ds):
    return ds.map(format_to_messages, remove_columns=["src", "tgt", "_id", "task"])

model = AutoModelForCausalLM.from_pretrained(model_name, attn_implementation="sdpa", device_map={"": 0})
model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": True})

model, tokenizer = setup_chat_format(model, tokenizer) 

training_arguments = SFTConfig(  
    output_dir="./sft",
    log_level="debug",
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    max_steps=100,
    warmup_steps=10,
    max_seq_length=512,
    learning_rate=2e-5,
    eval_strategy="steps",
    eval_steps=50,
    do_eval=True,
    optim="adamw_torch",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    per_device_eval_batch_size=4,
    save_steps=100,
    logging_steps=50,
)  

trainer = SFTTrainer(
    model=model,
    train_dataset=format_ds(dataset_train_sft),
    eval_dataset=format_ds(dataset_test_sft),
    tokenizer=tokenizer,
    args=training_arguments,
)

trainer.train()

inputs = tokenizer.apply_chat_template(
    [{"role": "user", "content": "Improve the grammar: I doesn't like you"}], 
    tokenize=True, 
    return_tensors="pt", 
    add_generation_prompt=True,
).to(trainer.model.device)

tokens = trainer.model.generate(inputs=inputs, max_new_tokens=256)[0]
print(tokenizer.decode(tokens))
```

Outputs: 
```
<|im_start|>user
Improve the grammar: I doesn't like you<|im_end|>
<|im_start|>assistant
I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like you. I don't like
```

Is there something I'm doing wrong?

### Expected behavior

The generation returns `I don't like you.<eos_token>`.

I also tried setting tokenizer.padding_size = "left", but it doesn't help

**Comment by asparius** [comment]
Base model's bos, eos, and pad token ids are the same, however, if you set the chat template bos is changed to <|im_start|>, and eos<|im_end|> and pad token is the same as eos. This is what causes the endless generation because the model does not learn eos_token because it is the same as the pad which is ignored during training. if you change the id of the pad token to something like <endoftext>, it should be fine. This is similar to this [issue](https://github.com/unslothai/unsloth/issues/416)
