### ISSUE TITLE
xpo can not work

### ISSUE THREAD

**Issue by ArcherShirou** [huggingface/trl#2106]
### System Info

When I used the parameters below for training, the following error occurred. How can I modify it?
My parameters:
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
deepspeed --num_gpus 8 --master_port=29501  examples/scripts/nash_md.py \
    --config_file examples/accelerate_configs/deepspeed_zero2.yaml \
    --model_name_or_path  /workspace/qwen2.5-14B-sft \
    --reward_model_path /workspace/Qwen2.5-14B-Instruct \
    --dataset_name /workspace/ultrafeedback-prompt.json \
    --learning_rate 5.0e-7 \
    --beta 0.1 \
    --output_dir /workspace/qwen2.5-14B-xpo \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --num_train_epochs 3 \
    --max_new_tokens 2048 \
    --warmup_ratio 0.1 \
    --missing_eos_penalty 1.0 \
    --overwrite_output_dir \
    --logging_steps 10 \
    --save_steps 50 \
    --bf16 \
    --ddp_timeout 180000000

The error message is:
Traceback (most recent call last):
  File "/workspace/trl/examples/scripts/nash_md.py", line 67, in <module>
    parser = TrlParser((DPOScriptArguments, NashMDConfig, ModelConfig))
  File "/workspace/trl/trl/commands/cli_utils.py", line 217, in __init__
    super().__init__(parsers)
  File "/workspace/transformers/src/transformers/hf_argparser.py", line 137, in __init__
    self._add_dataclass_arguments(dtype)
  File "/workspace/transformers/src/transformers/hf_argparser.py", line 264, in _add_dataclass_arguments
    self._parse_dataclass_field(parser, field)
  File "/workspace/transformers/src/transformers/hf_argparser.py", line 160, in _parse_dataclass_field
    raise ValueError(
ValueError: Only `Union[X, NoneType]` (i.e., `Optional[X]`) is allowed for `Union` because the argument parser only supports one type per argument. Problem encountered in field 'beta'.

Below are some other questions. Please provide guidance：
1. Does XPO support LoRA and 4-bit quantization? How can models like 14B or 72B use XPO?
2. Does XPO support DeepSpeed?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

no

### Expected behavior

no

**Comment by qgallouedec** [comment]
Hi, please provide the system info

**Comment by ArcherShirou** [comment]
system info is:
GPU is 8  NVIDIA A800 80G

**Comment by qgallouedec** [comment]
> If it is your first time submitting, be sure to check our [bug report guidelines](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#did-you-find-a-bug)

**Comment by ArcherShirou** [comment]
sorry for that, here is systen info:
- Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.35
- Python version: 3.10.14
- PyTorch version: 2.4.0
- CUDA device: NVIDIA A800-SXM4-80GB
- Transformers version: 4.45.0.dev0
- Accelerate version: 0.34.2
- Accelerate config: not found
- Datasets version: 2.20.0
- HF Hub version: 0.24.5
- TRL version: 0.12.0.dev0+9861559
- bitsandbytes version: 0.43.3
- DeepSpeed version: 0.14.4
- Diffusers version: not installed
- Liger-Kernel version: 0.2.1
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: 0.12.0

**Comment by kashif** [comment]
so to confirm you are running the `nash_md` script or the `xpo` one?

**Comment by ArcherShirou** [comment]
yes，I run this file :examples/scripts/nash_md.py，follow the instruction by trl in huggingface web
