### ISSUE TITLE
RLOO generating checkpoints every 2 steps

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#2124]
I am not sure if this is related, but I have observed a strange behaviour in RLOO checkpointing. For example, I have set it to checkpoint every 500 steps and it follows that for some time, but after a while it starts generating checkpoints every 2 steps. Is this an intended functionality?

_Originally posted by @sahandrez in https://github.com/huggingface/trl/pull/2114#issuecomment-2374454624_

**Comment by lewtun** [comment]
Ah I recall we had a similar issue with online DPO here: https://github.com/huggingface/trl/issues/1889#issuecomment-2297190131

tl;dr the global step wasn't incremented correctly

**Comment by sahandrez** [comment]
Thank you! Are there any plans for fixing this for RLOO as well?

**Comment by lewtun** [comment]
@sahandrez we would welcome a PR! The implementation details are somewhat different across the trainers, so my suggestion would be to first craft an example the reproduces the issue quickly and then pinpoint where the `global_step` isn't being updated correctly

**Comment by sahandrez** [comment]
Re-opening this because it seems the issue still persists on `trl==0.12.1`. 
The network usage after 100k starts to spike and checkpoints are saved every 2 steps, regardless of the value of `save_every`.
![image](https://github.com/user-attachments/assets/98585668-1f76-4553-8079-d84724aae527)
