### ISSUE TITLE
Use `unittest`'s methods for the tests

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#2137]
In test, drop lines lines like

```python
assert x in y
```

in favour of

```python
self.assertIn(x, y)
```

**Comment by ccs96307** [comment]
Hi,
I’d like to help with this issue if it's still open! I’m happy to contribute and will do my best to handle it smoothly.
Thanks!

**Comment by qgallouedec** [comment]
Thanks @ccs96307! Feel free to open a PR then :)
