### ISSUE TITLE
Doc: Hub filters in trainers doc

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/trl#2149]
> Not for this PR, but WDYT about putting these Hub filters as a badge at the top of each trainer doc, similar to how `transformers` does it for architectures: https://huggingface.co/docs/transformers/model_doc/bert

![Screenshot 2024-10-01 at 17 31 20](https://github.com/user-attachments/assets/da452bde-3257-4389-88ea-2e1cfabddf4a)

You can generate these badges with: https://shields.io

_Originally posted by @lewtun in https://github.com/huggingface/trl/pull/2131#discussion_r1783088699_

**Comment by qgallouedec** [comment]
To find datasets or models? For datasets it a bit tricky but for models we could have something like:

[![](https://img.shields.io/badge/All_models-dpo-blue)](https://huggingface.co/models?other=dpo)

**Comment by lewtun** [comment]
> To find datasets or models? For datasets it a bit tricky but for models we could have something like:
> 
> [![](https://camo.githubusercontent.com/c2ec84a57473b4feb40b2463fb4ed2aa635efb040b73f388ad60d751e9e1eff0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f416c6c5f6d6f64656c732d64706f2d626c7565)](https://huggingface.co/models?other=dpo)

Yes I think datasets are harder to find because they aren't always tagged. Nevertheless, we could try adding badges for filters like: https://huggingface.co/datasets?other={sft,dpo,kto}

**Comment by qgallouedec** [comment]
But what was you initial suggestion?
