### ISSUE TITLE
fine-tuning llama 3.2

### ISSUE THREAD

**Issue by AugustLigh** [huggingface/trl#2167]
### System Info

im use python 3.10 and last version of all libraries on 04.10.2024,
and i try to run: trl sft  --model_name_or_path meta-llama/Llama-3.2-3B --dataset_name Vikhrmodels/GrandMaster-PRO-MAX --output_dir Llama-3.2-3B-Instruct-sft --gradient_checkpointing

But, i get the error:

Loading checkpoint shards:   0%|                                                                                                      | 0/2 [00:00<?, ?it/s]
⠇ Initializing the SFTTrainer...Traceback (most recent call last):
  File "/home/test/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/test/.local/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/test/.local/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/test/.local/lib/python3.11/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.11', '/home/test/.local/lib/python3.10/site-packages/trl/commands/scripts/sft.py', '--model_name_or_path', 'meta-llama/Llama-3.2-3B', '--dataset_name', 'Vikhrmodels/GrandMaster-PRO-MAX', '--output_dir', 'Llama-3.2-3B-Instruct-sft', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '4', '--gradient_checkpointing', '--learning_rate', '1e-5', '--max_seq_length', '512']' died with <Signals.SIGKILL: 9>.
[08:33:52] TRL - SFT failed on ! See the logs above for further details.                                                                           cli.py:66
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.10/site-packages/trl/commands/cli.py", line 57, in main
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', '/home/test/.local/lib/python3.10/site-packages/trl/commands/scripts/sft.py', '--model_name_or_path', 'meta-llama/Llama-3.2-3B', '--dataset_name', 'Vikhrmodels/GrandMaster-PRO-MAX', '--output_dir', 'Llama-3.2-3B-Instruct-sft', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '4', '--gradient_checkpointing', '--learning_rate', '1e-5', '--max_seq_length', '512']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/.local/bin/trl", line 8, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python3.10/site-packages/trl/commands/cli.py", line 67, in main
    raise ValueError("TRL CLI failed! Check the traceback above..") from exc
ValueError: TRL CLI failed! Check the traceback above..

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

trl sft  --model_name_or_path meta-llama/Llama-3.2-3B --dataset_name Vikhrmodels/GrandMaster-PRO-MAX --output_dir Llama-3.2-3B-Instruct-sft --gradient_checkpointing

### Expected behavior

i juust want to fine-tuning llm

**Comment by qgallouedec** [comment]
Hi thanks for reporting, can you provide the full system info? See issue template

**Comment by AugustLigh** [comment]
> Hi thanks for reporting, can you provide the full system info? See issue template

Of course.
initially I tried to run everything on windows 11, then on WSL 2. But I get the same error.

I have a CPU: i5-9300H, GPU: GTX 1050
python 3.11

**Comment by August-murr** [comment]
Looks like you're running out of VRAM. You could try quantizing the model to 4 bits and use PEFT, but given your hardware setup, that would still not work.
I'd recommend using a cloud-based solution like Google Colab, Kaggle, or AWS, where you'll have access to better GPUs.
