### ISSUE TITLE
Grammatical errors in readme 

### ISSUE THREAD

**Issue by PRIYANKjakharia** [huggingface/trl#2185]
I found a grammatical error in the README.md of the project. The error may affect the readability and clarity of the documentation.

Expected Behavior: The documentation should be free of grammatical errors and easy to understand.

Actual Behavior: The current documentation contains a grammatical error that can cause confusion for readers.

Steps to Reproduce:

1-Open README.md
2-Navigate to line 38
3-Observe the grammatical errors in the text

If you have any additional information or context about the error, feel free to add it to the description.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by PRIYANKjakharia** [comment]
> Please assign this issue to me

I appreciate your enthusiasm but I have already  updated all the necessary changes
