### ISSUE TITLE
KTO Trainer

### ISSUE THREAD

**Issue by bjb19** [huggingface/trl#2218]
### System Info

TRL: 0.11.3
Transformers: 4.45.2
Python: 3.10.15
OS:  Debian 11

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Running this
python examples/scripts/kto.py \
    --model_name_or_path=trl-lib/qwen1.5-1.8b-sft \
    --per_device_train_batch_size 8 \
    --num_train_epochs 1 \
    --learning_rate 5e-7 \
    --lr_scheduler_type=cosine \
    --gradient_accumulation_steps 1 \
    --logging_steps 10 \
    --eval_steps 500 \
    --output_dir=kto-aligned-model-lora \
    --warmup_ratio 0.1 \
    --report_to wandb \
    --bf16 \
    --logging_first_step \
    --use_peft \
    --load_in_4bit \
    --lora_target_modules=all-linear \
    --lora_r=16 \
    --lora_alpha=16

Which is given in an example first fails at this step
    # Compute that only on the main process for faster data processing.
    # see: https://github.com/huggingface/trl/pull/1255
    # with PartialState().local_main_process_first():
    #     dataset = dataset.map(format_dataset, num_proc=training_args.dataset_num_proc)

After commenting this out I get this error 
TypeError: KTOTrainer.__init__() got an unexpected keyword argument 'processing_class'

Even though it is shown in the docs

### Expected behavior

The example train function would complete

**Comment by bjb19** [comment]
Updating as I have solved the source of the issue

1) Is how the datset is being processed in the example
2) Is it looks like there were changes to the constructor class that are in the docs but not the most recent version

Might put in a PR this weekend to fix

**Comment by qgallouedec** [comment]
You're probably using an example for the dev version (0.12.0dev) while having the latest released version (0.11.3) installed.
Either use the latest version example, or install the dev version.

**Comment by qgallouedec** [comment]
Duplicate #2207
