### ISSUE TITLE
`log_reports.py` Inefficiencies in Processing Log Files

### ISSUE THREAD

**Issue by Mefisto04** [huggingface/trl#2237]
### System Info

Platform : Windows 11

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce the issue, follow these steps:

- Run the script with a set of log files.
- Notice the increased processing time when dealing with a large number of logs.
- Observe the redundancy in file operations and data handling.

### Expected behavior

The script should handle large sets of log files more efficiently, avoiding redundant operations and optimizing the processing loop.
The current implementation could benefit from batch processing techniques, improved file handling, and more efficient data parsing mechanisms.

**Comment by Mefisto04** [comment]
hey @qgallouedec, please review this and assign me this issue

**Comment by qgallouedec** [comment]
Hi, thanks for reporting @Mefisto04. Feel free to open a PR if you can improve it.

**Comment by Mefisto04** [comment]
hey @qgallouedec , i have made a pr #2249, please review that.

**Comment by Mefisto04** [comment]
hey @qgallouedec , i have made a pr #2249  , please review that.

**Comment by qgallouedec** [comment]
Closed via #2249
