### ISSUE TITLE
example/scripts/sft.py doesn't work

### ISSUE THREAD

**Issue by Reductionreaction** [huggingface/trl#2253]
### System Info

- Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
- Python version: 3.11.0
- PyTorch version: 2.5.0
- Transformers version: 4.46.0.dev0
- Accelerate version: 1.0.1
- Accelerate config: not found
- Datasets version: 3.0.1
- HF Hub version: 0.26.0
- TRL version: 0.12.0.dev0
- bitsandbytes version: 0.44.1
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: 0.13.2

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

When I run bash run 'bash commands/run_sft.sh' with my own dataset,there is no key 'test' found in loaded dataset. I solved this problem by split dataset on my own. Cause in 'example/scripts/sft.py', I didn't found any operations to split my dataset. Here is what I wrote in example/scripts/sft.py
```python
split_dataset = dataset['train'].train_test_split(test_size=0.2)

### Expected behavior

I was wandering if there is any script to process my dataset or I have to split dataset on my own in'example/scripts/sft.py'

**Comment by qgallouedec** [comment]
This is because you need to provide a split dataset (containing both a training split and an evaluation split) when you use TRL scripts .
I realize the following limitations:

- when you're not evaluating, you still need to have a split dataset
- you may want the script to split the dataset when necessary.

This could be solved by adding something like :

```python
if training_args.eval_strategy != "none" and script_args.dataset_test_split not in dataset :
    dataset = dataset[script_args.dataset_train_split].split(test_size=0.05)

...

trainer = AnyTrainer(
    ...
    train_dataset=dataset[script_args.dataset_train_split],
    eval_dataset=dataset[script_args.dataset_test_split] if training_args.eval_strategy != "none" else None,
    ...
)
```

WDYT @kashif @lewtun ? Is this situation common enough to justify this addition?

**Comment by lewtun** [comment]
I don't think we should automatically generate a test split for the user (it's a bit too much magic), but I would be in favour of having the logic to set `eval_dataset` to `None` if no eval strategy is provided

**Comment by qgallouedec** [comment]
> I don't think we should automatically generate a test split for the user (it's a bit too much magic), but I would be in favour of having the logic to set `eval_dataset` to `None` if no eval strategy is provided

Sounds reasonable.
