### ISSUE TITLE
Segmentation fault (core dumped) when running the sft scripts

### ISSUE THREAD

**Issue by SinclairCoder** [huggingface/trl#2257]
### System Info

- Platform: Linux-5.15.0-107-generic-x86_64-with-glibc2.35
- Python version: 3.10.0
- PyTorch version: 2.5.0+cu121
- CUDA device(s): NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3
- Transformers version: 4.46.0.dev0
- Accelerate version: 1.0.1
- Accelerate config: not found
- Datasets version: 3.0.1
- HF Hub version: 0.26.0
- TRL version: 0.12.0.dev0
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: not installed

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

python examples/scripts/sft.py \
    --model_name_or_path ${BASE_MODEL_PATH} \
    --dataset_name test \
    --max_seq_length 2048 \
    --dataset_num_proc 8 \
    --torch_dtype auto \
    --output_dir ${CKPT_DIR}/${BASE_NAME}_${DATA_NAME}/${LR}_${BS} \
    --overwrite_output_dir True \
    --learning_rate 2.0e-5 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.1 \
    --logging_steps 10 \
    --save_strategy steps \
    --save_steps 100 \
    --report_to wandb \
    --run_name test

### Expected behavior

When I run the above script, a segmentation fault was encountered unexceptedly.

site-packages/trl/trainer/sft_trainer.py:203: UserWarning: You passed a model_id to the SFTTrainer. This will automatically create an `AutoModelForCausalLM` or a `PeftModel` (if you passed a `peft_config`) for you.
  warnings.warn(
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: xxx. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in xxx/wandb/run-20241021_124738-rnk6v5jx
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run test
wandb: ⭐️ View project at https://wandb.ai/xxxx
wandb: 🚀 View run at https://wandb.ai/xxx
  0%|                                                                                                                                                                     | 0/17 [00:00<?, ?it/s]

xxx/miniconda3/envs/trl/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
xxx/miniconda3/envs/trl/lib/python3.10/site-packages/torch/autograd/graph.py:825: UserWarning: cuDNN SDPA backward got grad_output.strides() != output.strides(), attempting to materialize a grad_output with matching strides... (Triggered internally at ../aten/src/ATen/native/cudnn/MHA.cpp:674.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

run_sft.sh: line 37: 2935332 Segmentation fault      (core dumped) python examples/sft.py --model_name_or_path ${BASE_MODEL_PATH} --dataset_name test --max_seq_length 2048 --dataset_num_proc 8 --torch_dtype auto --output_dir ${CKPT_DIR}/${BASE_NAME}_${DATA_NAME}/${LR}_${BS} --overwrite_output_dir True --learning_rate 2.0e-5 --num_train_epochs 1 --per_device_train_batch_size 8 --gradient_accumulation_steps 8 --gradient_checkpointing --lr_scheduler_type cosine --warmup_ratio 0.1 --logging_steps 10 --save_strategy steps --save_steps 100 --report_to wandb --run_name test

**Comment by SinclairCoder** [comment]
I solved it with torchrun launch.

**Comment by Qinghao-Hu** [comment]
same problem
