### ISSUE TITLE
how much data needed when training 11B model, Llama-3.2-11B-Vision-Instruct?

### ISSUE THREAD

**Issue by cutecharmingkid** [huggingface/trl#2269]
Hello, I would like to ask how much data is needed to fine-tune an 11B model, Llama-3.2-11B-Vision-Instruct, using the sft_vlm.py script?

**Comment by edbeeching** [comment]
Hi @cutecharmingkid , unfortunately the answer is not trivial. Does the domain of your task match the tasks used to fine-tune the base vision-instruct model? I would imagine 10k-100k example would be enough, but I have not tested extensively.
