### ISSUE TITLE
"tokenizer" attribute is now deprecated on Transformers Trainer class

### ISSUE THREAD

**Issue by danib08** [huggingface/trl#2290]
Just a heads up that the `tokenizer` attribute is now deprecated on `transformers.Trainer` and will be removed soon:

`python3.10/site-packages/trl/trainer/sft_trainer.py:401: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for 'SFTTrainer.__init__'. Use 'processing_class' instead.`

This is happening on TRL's newest version 0.11.4 and Transformers 4.46.0.

**Comment by qgallouedec** [comment]
Thanks for reporting @danib08, it has been taken into account in #2162
