### ISSUE TITLE
AttributeError: 'TrainingArguments' object has no attribute 'model_init_kwargs'

### ISSUE THREAD

**Issue by MonolithFoundation** [huggingface/trl#2291]
AttributeError: 'TrainingArguments' object has no attribute 'model_init_kwargs'

**Comment by qgallouedec** [comment]
Please share the MRE and your system info

**Comment by mohit-raghavendra** [comment]
I observed this too when I used args through the TrainingArguments into DPOTrainer instead of a DPOConfig object

**Comment by qgallouedec** [comment]
`DPOTrainer` expects `DPOConfig` for `args`. `TrainingArguments` is not supported.
