### ISSUE TITLE
Tries to iterate over Modules of value_model, even when it is NoneType (the default value)

### ISSUE THREAD

**Issue by ColinG03** [huggingface/trl#2312]
### System Info

- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version: 2.5.0+cu121
- CUDA device(s): not available
- Transformers version: 4.46.1
- Accelerate version: 0.34.2
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.24.7
- TRL version: 0.12.0
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: 0.30.3
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.52.2
- PEFT version: 0.13.2

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Repro:
1. Copy and paste code from https://huggingface.co/docs/trl/v0.11.4/quickstart 
2. Step # 2 from the code immediately won't work because PPO config is missing output_dir value
3. Fix that by manually adding an output directory
4. Rerun, see that it still doesn't work because PPOTrainer is missing 'reward_model' and 'train_dataset' parameters
5. Fix that by adding reward_model and train_dataset parameters
6. Rerun, inspect error to see that it is iterating over the modules in 'value_model', which we have not defined and defaults to NoneType

### Expected behavior

It appears that the documention is just completely incorrect, and even when I attempt to fix it, I'm running into an internal library. Fixing the documentation examples to run properly would be a first step, the second would be to either check if value_models is NoneType before iterating through its modules or making it a mandetory parameter.

**Comment by qgallouedec** [comment]
That true, the documentation is outdated. Further information here https://github.com/huggingface/trl/issues/2314#issuecomment-2456683497. Closing in favour of #2314 (mostly duplicate)
