### ISSUE TITLE
save `training_args` in another file format

### ISSUE THREAD

**Issue by not-lain** [huggingface/trl#2313]
### Feature request

switch saving training arguments from `bin` format to another file extension. 

### Motivation

for security reasons `bin` format is deemed unsafe as marked by huggingface's new security system.
![image](https://github.com/user-attachments/assets/03d9c511-716e-4d15-8a2d-38d9a108e289)

### Your contribution

I'll try submitting a pr, but if anyone wishes to submit their own feel free to do so

**Comment by qgallouedec** [comment]
Thanks for sharing this. We rely on `transformers.Trainer` to save checkpoints and push on the hub. I think this issue would be more relevant to [huggingface/transformers](https://github.com/huggingface/transformers).

**Comment by not-lain** [comment]
thanks for the reply, I will close this one and open a new issue in the transformers library
