### ISSUE TITLE
Documentation for PairRM Judge is not displaying correctly

### ISSUE THREAD

**Issue by LuisVasquezBSC** [huggingface/trl#2317]
In your documentation for PairRM Judge, the example is not displaying correctly as a code block, instead, it is displaying as a quote block

[Check here](https://github.com/huggingface/trl/blob/6138439df4212951409e77cdf028a42b9492938c/trl/trainer/judges.py#L169)

![image](https://github.com/user-attachments/assets/4db086b3-f20b-40c8-b695-b615454edaa5)

**Comment by qgallouedec** [comment]
Closed by #2318, thanks for reporting @LuisVasquezBSC
