### ISSUE TITLE
[Question] `add_generation_prompt=True` on prompt

### ISSUE THREAD

**Issue by Galaxy-Husky** [huggingface/trl#2346]
Hi,

I noticed that from v0.11.0, `maybe_apply_chat_template` added generation prompt on the prompt of the example, which was different from the previous version.
https://github.com/huggingface/trl/blob/0238d96c6f43abd808804ddb0065883964073060/trl/data_utils.py#L86-L88

Was it a little bug? Will the generation prompt influence the final result?

A prompt reply is appreciated.

**Comment by qgallouedec** [comment]
Can you point the "previous version" you are refering to?

**Comment by qgallouedec** [comment]
I think it has been like this from the initial implementation (see #2020)

**Comment by Galaxy-Husky** [comment]
> I think it has been like this from the initial implementation (see #2020)

Sorry, I didn't say that right. I mean before v0.11.0, there was no  `maybe_apply_chat_template` back then.  For example, the dpo dataset was preprocessed like:
https://github.com/huggingface/trl/blob/55cc4b1076144b74a6ce5d07557b7f664b1de8d9/examples/scripts/dpo.py#L156-L160

Since the code has been refactored , I'm not sure if there was generation prompt or not. If so, could you please point out where it was implemented?

**Comment by qgallouedec** [comment]
Yes the example code was wrong, you need to add a generation prompt at the end of the prompt.

**Comment by Galaxy-Husky** [comment]
> Yes the example code was wrong, you need to add a generation prompt at the end of the prompt.

I see. Thanks a lot!
