### ISSUE TITLE
Contributing new distillation related trainers

### ISSUE THREAD

**Issue by YihanCao123** [huggingface/trl#2361]
### Method description

Hi team, I have implemented some distillation based trainers, and would like contribute them to `trl`. Do you accept contributions on this or probably this is something already in progress? I see `GKD` has already been added into the trainer list, but some of the more basic distillation methods, as well as other knowledge distillation techniques, haven’t been included yet. I’d be happy to help expand if there’s interest. Thanks!

### Open source status

- [X] The method implementation is available
- [ ] The model weights are available
- [ ] The training datasets are available

**Comment by deekshaVarshney** [comment]
@YihanCao123 are you still thinking of contributing the knowledge distillation techniques? or if there aare any open source codes for the same , could you guide me to it?
