### ISSUE TITLE
数据集支持多轮对话反馈吗

### ISSUE THREAD

**Issue by dosometingbyme** [huggingface/trl#2366]
### Feature request

PPO, does the dataset support multi-turn dialogue feedback, such as I have a multi-turn dialogue dataset, and at different steps, the model's responses are all rated

### Motivation

Does the dataset support multi-turn dialogue feedback?

### Your Contribution

PPO, does the dataset support multi-turn dialogue feedback, such as I have a multi-turn dialogue dataset, and at different steps, the model's responses are all rated

**Comment by qgallouedec** [comment]
Please use english only

**Comment by qgallouedec** [comment]
Probably linked to #2127. Closing as the title is not in English and the question isn't clear enough for us to help you. Feel free to open a clearer issue the complies with our guidelines
