### ISSUE TITLE
The DPO reward accuracy value is only 0 or 1

### ISSUE THREAD

**Issue by carrot0117** [huggingface/trl#2371]
Has anyone face with problems that the DPO reward accuracy value is only 0 or 1？Rewards/accuracies is always 0 or 1 during the training process, but this should not be the case for a batch calculation
<img width="367" alt="image" src="https://github.com/user-attachments/assets/a1f7d27e-37d1-42c5-aba8-3188f134e5b4">

**Comment by qgallouedec** [comment]
Thanks for reporting. Please provide more info, like the training arguments etc
