### ISSUE TITLE
A doubt in KTO _process_tokens

### ISSUE THREAD

**Issue by a7217339** [huggingface/trl#2374]
![图片1](https://github.com/user-attachments/assets/5d10ba81-8b20-4824-9c30-dc0a85316e57)
![屏幕截图 2024-11-20 172130](https://github.com/user-attachments/assets/fedd14ec-4858-4b2d-9e91-21f0b6153e1d)
I have a code comprehension problem: train_dataset should be in the form of dict after processing the map with _tokenize（
prompt_input_ids=prompt_input_ids,
prompt_attention_mask=prompt_attention_mask,
answer_input_ids=answer_input_ids,
answer_attention_mask=answer_attention_mask,
）
How can I still access 'keys' like 'prompt' in the map of process_token? （ prompt = example["prompt"]
completion = example["completion"]）

**Comment by qgallouedec** [comment]
Please don't use image when referring to code next time. Use [permalink to code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet).

---

> train_dataset should be in the form of dict after processing the map

No, `map` returns a `Dataset` instance (see [`datasets.map` documentation](https://huggingface.co/docs/datasets/en/process#map)). Unless you remove these columns (prompt, completion) from the dataset, they remain.

**Comment by a7217339** [comment]
Thank you for your guidance. As a beginner, I am not yet proficient in grammar. Sorry.
