### ISSUE TITLE
Does simply passing the adapter folders in the model_path allow continued training of the LoRA adapters?

### ISSUE THREAD

**Issue by iBibek** [huggingface/trl#2418]
Does simply passing the adapter folders in the model_path allow continued training of the LoRA adapters?

I have already trained the adapters once, and the LoRA adapters are stored in the folder```qwen_7B_v1```. I would like to continue training these adapters. How can I achieve this?

Is the method below correct for continuing training, by passing the adapter path in the model_name parameter?

```
accelerate launch --config_file examples/accelerate_configs/multi_gpu.yaml --num_processes=4 examples/scripts/sft.py \
    --model_name qwen_7B_v1 \
    --dataset_name mydataset/dataset_v1 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --learning_rate 2e-4 \
    --save_steps 20_000 \
    --use_peft \
    --lora_r 64 \
    --lora_alpha 8 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --load_in_4bit \
    --do_eval True \
    --report_to wandb \
    --run_name qwen_7B_v2 \
    --output_dir qwen_7B_v2 \
    --eval_steps 25 \
    --num_train_epochs 1
``

**Comment by qgallouedec** [comment]
Yes, that's the right way to do it. Your code looks fine, feel free to share if you get an error running it.
