### ISSUE TITLE
make test in dev environment has failures

### ISSUE THREAD

**Issue by AMindToThink** [huggingface/trl#2524]
### System Info

- Platform: Linux-5.4.0-1125-kvm-x86_64-with-glibc2.31
- Python version: 3.10.16
- PyTorch version: 2.5.1
- CUDA device(s): Quadro RTX 8000, Quadro RTX 8000
- Transformers version: 4.47.1
- Accelerate version: 1.0.1
- Accelerate config: 
  - compute_environment: LOCAL_MACHINE
  - distributed_type: NO
  - mixed_precision: bf16
  - use_cpu: False
  - debug: False
  - num_processes: 1
  - machine_rank: 0
  - num_machines: 1
  - gpu_ids: 0
  - rdzv_backend: static
  - same_network: True
  - main_training_function: main
  - enable_cpu_affinity: False
  - downcast_bf16: no
  - tpu_use_cluster: False
  - tpu_use_sudo: False
  - tpu_env: []
- Datasets version: 3.2.0
- HF Hub version: 0.27.0
- TRL version: 0.14.0.dev0+aed5da5
- bitsandbytes version: 0.45.0
- DeepSpeed version: 0.16.2
- Diffusers version: 0.32.1
- Liger-Kernel version: 0.5.2
- LLM-Blender version: 0.0.2
- OpenAI version: 1.58.1
- PEFT version: 0.14.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

After following the Submitting a pull request (PR) instructions [here](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#did-you-find-a-bug), I tried running `make test`. Most passed, but some failed. Is this a problem with my environment or a problem with the tests or code?

`=============================== 9 failed, 392 passed, 25 skipped, 252 warnings, 57 rerun in 139.39s (0:02:19) ================================
`

### Expected behavior

0 failed

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

**Comment by August-murr** [comment]
I recommend using GitHub Actions since they run the tests more reliably. Just enable it on your fork, push your changes, and it’ll automatically trigger the tests.

**Comment by AMindToThink** [comment]
Does this mean that my environment is not set up incorrectly?

**Comment by AMindToThink** [comment]
Thank you, took a while to figure out, but the tests that were triggered when I made an empty .py file in trl/trl worked. Somewhat bothersome that it tries and fails to post the results to slack, but the tests themselves pass. 
`Error: Need to provide at least one botToken or webhookUrl`

I would appreciate if the [contributing](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md) document explained that the tests may not run properly locally and are auto-run by Github when changes are pushed to main. 

My workflow will be:
Make changes to a branch of my fork.
When I want to test, I'll merge my branch into main.
Github will run the tests
They'll fail.
If on inspection the failure is because of the slack upload attempt, then everything is fine.
If on inspection there was an error before the slack upload attempt, then there's a problem with my code.
If my code is fine and my feature is ready, I can make a pull request.

**Comment by qgallouedec** [comment]
Which tests fail locally?

**Comment by AMindToThink** [comment]
Oddly, it says 6 failed when I only see 5. 

I'm on this commit:
`commit aed5da580e9fcba6517460daf65106bc42fb6167 (upstream/main, origin/sac, sac)
Author: Quentin Gallouédec <45557362+qgallouedec@users.noreply.github.com>
Date:   Sun Dec 22 12:44:07 2024 +0100`

 `   📦 Packing documentation (#2503)`

These are the failures:
```
[gw2] FAILED tests/test_dpo_trainer.py::DPOTrainerTester::test_dpo_lora_bf16_autocast_llama 
[gw11] FAILED tests/test_gkd_trainer.py::GKDTrainerTester::test_gkd_trainer 
[gw12] FAILED tests/test_callbacks.py::WinRateCallbackTester::test_basic 
[gw11] FAILED tests/test_peft_models.py::PeftModelTester::test_create_bnb_peft_model_from_config 
[gw15] FAILED tests/test_xpo_trainer.py::TestXPOTrainer::test_training_with_peft             | 0/50 [00:00<?, ?it/s]
================== 6 failed, 345 passed, 25 skipped, 242 warnings, 45 rerun in 113.62s (0:01:53) ===================
```
