### ISSUE TITLE
Can TRL support fine tuning of QA models?

### ISSUE THREAD

**Issue by princetyagitech** [huggingface/trl#264]
Thanks for the awesome library , i was having a doubt if it can support AutoModelForQuestionAnswering like models?

**Comment by lvwerra** [comment]
There are two types of QA: extractive and generative. The `AutoModelForQuestionAnswering ` is an extractive model IIRC, so it simply classifies the passage inside the context that contains the answer. With that model you can't use TRL. However, the second type of QA, generative, takes the context as input and generates a text answer based on that context. That's the same as doing causal language modeling with a prompt and you can use the `AutoModelForCausalLMWithValueHead` model to do this. 

Hope this helps!

**Comment by princetyagitech** [comment]
Thank you so much for your response!
