### ISSUE TITLE
More complex reward mechanism

### ISSUE THREAD

**Issue by davide221** [huggingface/trl#419]
I'm experimenting with chain of thoughts and finetuning, is there a way to use this library to assign different reward for each steps towards the problem resolution of the LLM? Like the new technique proposed in the step by step paper from OpenAI.

Would be amazing to experiment with it

**Comment by lvwerra** [comment]
Currently only a reward can be given to the last token and it discounted towards the beginning. The KL-div however is added per token and you could adapt the [`compute_rewards`](https://github.com/lvwerra/trl/blob/d1ad5405cb90cbfd8cfa252069104cf493787476/trl/trainer/ppo_trainer.py#L951) method to accept lists of scores for each sample.

**Comment by vwxyzjn** [comment]
This could be related to #424 and #429, which allow users to inject rewards mid-trajectory.
