### ISSUE TITLE
Training stops before finishing the epoch

### ISSUE THREAD

**Issue by Top34051** [huggingface/trl#475]
I'm trying to train the SFT model where the `num_train_epochs` is set to 1. However, the training just stops at around epoch 0.45 without showing any error. I already set the `infinite` to `True` and `packing` to `True`, so I'm not sure what I did wrong here. Could you please help me? Thanks in advance!

Log:
```
2368 {'loss': 1.5472, 'learning_rate': 1.0119421747328725e-05, 'epoch': 0.49}
2369 {'loss': 1.5248, 'learning_rate': 1.0115231510580348e-05, 'epoch': 0.49}
2370 {'loss': 1.5033, 'learning_rate': 1.0111041273831971e-05, 'epoch': 0.49}
2371 {'train_runtime': 2772.1724, 'train_samples_per_second': 55.105, 'train_steps_per_second': 1.722, 'train_loss': 1.5517177024130093, 'epoch': 0.49}
2372 Save last checkpoint of the model
```

Code:
```python
import argparse
import os
from tqdm import tqdm

import torch
from accelerate import Accelerator
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, set_seed
from trl import SFTTrainer
from trl.trainer import ConstantLengthDataset


os.environ["WANDB_PROJECT"] = "llama-hh-rlhf"
os.environ["WANDB_RUN_NAME"] = "llama-7b-sft"


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_path", type=str, default="huggyllama/llama-7b")
    parser.add_argument("--output_dir", type=str, default="./llama-7b-sft-adapter")
    parser.add_argument("--num_train_epochs", type=int, default=1)
    parser.add_argument("--per_device_train_batch_size", type=int, default=4)
    parser.add_argument("--per_device_eval_batch_size", type=int, default=4)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--gradient_checkpointing", action="store_true", default=False)
    parser.add_argument("--fp16", action="store_true", default=True)
    parser.add_argument("--bf16", action="store_true", default=False)
    parser.add_argument("--learning_rate", type=float, default=2e-5)
    parser.add_argument("--lr_scheduler_type", type=str, default="linear")
    parser.add_argument("--weight_decay", type=float, default=0.05)
    parser.add_argument("--warmup_ratio", type=float, default=0.0)
    parser.add_argument("--eval_steps", type=int, default=1000)
    parser.add_argument("--logging_steps", type=int, default=1)
    parser.add_argument("--save_steps", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--seq_length", type=int, default=512)
    args = parser.parse_args()
    return args


def prepare_sample_text(example):
    text = example["text"]
    return text


def chars_token_ratio(dataset, tokenizer, nb_examples=400):
    total_characters, total_tokens = 0, 0
    for _, example in tqdm(zip(range(nb_examples), iter(dataset)), total=nb_examples):
        text = prepare_sample_text(example)
        total_characters += len(text)
        if tokenizer.is_fast:
            total_tokens += len(tokenizer(text).tokens())
        else:
            total_tokens += len(tokenizer.tokenize(text))
    return total_characters / total_tokens


def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}")


def get_dataset(args, tokenizer):
    dataset = load_dataset("Anthropic/hh-rlhf", split="train")
    dataset = dataset.train_test_split(test_size=0.05, seed=args.seed)
    train_dataset = dataset["train"]
    eval_dataset = dataset["test"]
    
    chars_per_token = chars_token_ratio(train_dataset, tokenizer)
    train_dataset = ConstantLengthDataset(
        tokenizer,
        train_dataset,
        formatting_func=prepare_sample_text,
        infinite=True,
        seq_length=args.seq_length,
        chars_per_token=chars_per_token,
    )
    eval_dataset = ConstantLengthDataset(
        tokenizer,
        eval_dataset,
        formatting_func=prepare_sample_text,
        infinite=False,
        seq_length=args.seq_length,
        chars_per_token=chars_per_token,
    )
    train_dataset.start_iteration = 0
    return train_dataset, eval_dataset


def run_training(args):
    model = AutoModelForCausalLM.from_pretrained(
        args.model_path,
        load_in_8bit=False,
        device_map={"": Accelerator().process_index},
        torch_dtype=torch.float16,
    )
    tokenizer = AutoTokenizer.from_pretrained(args.model_path)

    train_dataset, eval_dataset = get_dataset(args, tokenizer)

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )

    trainer = SFTTrainer(
        model,
        args=TrainingArguments(
            output_dir=args.output_dir,
            dataloader_drop_last=True,
            num_train_epochs=args.num_train_epochs,
            per_device_train_batch_size=args.per_device_train_batch_size,
            per_device_eval_batch_size=args.per_device_eval_batch_size,
            gradient_accumulation_steps=args.gradient_accumulation_steps,
            gradient_checkpointing=args.gradient_checkpointing,
            fp16=args.fp16,
            bf16=args.bf16,
            learning_rate=args.learning_rate,
            weight_decay=args.weight_decay,
            lr_scheduler_type=args.lr_scheduler_type,
            warmup_ratio=args.warmup_ratio,
            evaluation_strategy="steps",
            eval_steps=args.eval_steps,
            logging_steps=args.logging_steps,
            save_steps=args.save_steps,
            report_to="wandb",
            ddp_find_unused_parameters=False,
        ),
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        packing=True,
        peft_config=lora_config,
    )

    print_trainable_parameters(trainer.model)

    print("Start training")
    trainer.train()

    print("Save last checkpoint of the model")
    trainer.model.save_pretrained(args.output_dir)


if __name__ == "__main__":
    args = get_args()

    set_seed(args.seed)
    os.makedirs(args.output_dir, exist_ok=True)

    run_training(args)
```

**Comment by younesbelkada** [comment]
Hi @Top34051 
Thanks for reporting, what version of TRL are you using?

**Comment by Top34051** [comment]
Hi @younesbelkada! I cloned the trl repo and built it locally. This should be up to date, I think.

**Comment by younesbelkada** [comment]
Hi @Top34051 
Thanks, before digging into that, can you double check your clone contains d1ad5405cb90cbfd8cfa252069104cf493787476 & 1e88b84ab9c7dcc879e560746ebda72f284ae1ab ? 🙏

**Comment by Top34051** [comment]
Yeah, it does contain both revisions:
```
(top) ➜  trl git:(main) git log | head -n 100

commit 7705daa672f9264d7b5b789b6a1fd6b1cff03a58
Author: Younes Belkada <49240599+younesbelkada@users.noreply.github.com>
Date:   Tue Jun 20 17:51:23 2023 +0200

    [`SFTTrainer`] Introducing `DataCollatorForCompletionOnlyLM` (#445)
    
    * v1 of alpaca datacollator
    
    * make sure to match the response tokens
    
    * add test
    
    * add it in main init
    
    * add check
    
    * adapt test
    
    ---------
    
    Co-authored-by: Costa Huang <costa.huang@outlook.com>

commit fe49697e66affc5baf9e19c71e1bb6a00380ddd4
Author: Younes Belkada <49240599+younesbelkada@users.noreply.github.com>
Date:   Mon Jun 19 17:26:17 2023 +0200

    add stale bot (#447)

commit d1ad5405cb90cbfd8cfa252069104cf493787476
Author: Younes Belkada <49240599+younesbelkada@users.noreply.github.com>
Date:   Fri Jun 16 18:51:20 2023 +0200

    [`SFTTrainer`] Fix non packed dataset (#444)
    
    * fix non packed dataset
    
    * fixing tests and documentation
    
    * Update docs/source/sft_trainer.mdx

commit 1e88b84ab9c7dcc879e560746ebda72f284ae1ab
Author: Younes Belkada <49240599+younesbelkada@users.noreply.github.com>
Date:   Fri Jun 16 13:55:47 2023 +0200

    fix packing issue (#442)
```

**Comment by zss70719696** [comment]
Hi @younesbelkada, I ran into the exact same issue like @Top34051. Mine always stops around 16%-17% of a epoch. Here are my training script, I didn't set any early stopping or lr decay strategies.

`training_arguments = TrainingArguments(
        output_dir="./falcon-finetune-with-summary-contd-10/",
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        optim="paged_adamw_32bit",
        save_steps=100,
        logging_steps=10,
        learning_rate=2e-4,
        fp16=True,
        max_grad_norm=0.3,
        num_train_epochs=1,
        group_by_length=False,
        lr_scheduler_type="constant",
        logging_dir="./logs"
    )
    
    peft_model_id = './checkpoint-400/'
    model = PeftModel.from_pretrained(model, peft_model_id, is_trainable=True)
    loaded_peft_config = model.active_peft_config

    model.gradient_checkpointing_enable()
    model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
    
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        peft_config=loaded_peft_config,
        # dataset_text_field="instruction" + "input",
        packing=True,
        infinite=True,
        max_seq_length=2048,
        args=training_arguments,
        formatting_func=formatting_func,
    )
    
    trainer.train()
    `
I ran several rounds of continue training and hope these stats may help you identify what went wrong:

In total I have 57416 samples in my fine-tuning dataset. Fine-tuning loop first stops a bit more than step 2300, (2300*4/57416~=16%) says the training was completed.

I resumed the training by moving the data from 9200 onwards and loaded the adapter_model.bin checkpoint, this time train for 1900 steps, still tops around 16% of the total steps remained.

I iteratively move forward the data and load saved checkpoint everytime the training stopped before the full epoch is reached and these are the max number of steps trained:
2300 ->1900 ->1600 ->1300 ->1100 ->900 ->800 ->700 ->600 ->500

For me this looks like while iterating through the dataset, the next() may not correctly called. Looking forward to hear back from you.

**Comment by sachinkun21** [comment]
i am also observing a similar issue while trying to train LlamaV2 with standard arguments and No Early stopping. Training stops automaticallu around 150-160 steps even though there are a total of around 670 steps.

**Comment by qrdlgit** [comment]
I'm seeing this as well, no max steps, and it's jumping from 0.25 to the next epoch.  Using a packed dataset

```
{'loss': 1.8227, 'learning_rate': 2.904297351759579e-05, 'epoch': 1.24}
{'loss': 1.6868, 'learning_rate': 2.9029185381077875e-05, 'epoch': 1.24}
{'loss': 1.7226, 'learning_rate': 2.901530194967737e-05, 'epoch': 1.25}
{'loss': 1.8355, 'learning_rate': 2.900132331769911e-05, 'epoch': 2.0}
```

Using 0.7.1

p```
eft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules=["Wqkv", "out_proj"],
    task_type="CAUSAL_LM",
)
​
​
args = TrainingArguments(
    output_dir="kaggle",
    num_train_epochs=4,
    per_device_train_batch_size=2,
    save_total_limit=3,  # Keeps the last 3 checkpoints
    gradient_accumulation_steps=3,
    optim="paged_adamw_32bit",
    logging_steps=10,
    learning_rate=3e-5,
    max_grad_norm=0.4,
    weight_decay = 0.05,
    warmup_ratio=0.01,
    #lr_scheduler_type= get_cosine_with_hard_restarts_schedule_with_warmup(optimizer, num_warmup_steps=3, num_training_steps=10, num_cycles=5)
    lr_scheduler_type= "cosine_with_restarts",
    disable_tqdm=True,# disable tqdm since with packing values are in correct
    
) 
```

**Comment by lvwerra** [comment]
When using packing and long context windows it can happen that `n` text samples are packed into `m` training samples where `n>m`. Since we perform packing on the fly we don't know in advance how many samples there are in total per epoch which explains the jumps/early stops.

**Comment by qrdlgit** [comment]
Ah, cool.  Is there a workaround so we can adjust for this?

**Comment by lvwerra** [comment]
Not really at the moment, maybe we could preprocess the whole dataset before or at least count tokens but this is not done at the moment.
