### ISSUE TITLE
response become shorter and shorter 

### ISSUE THREAD

**Issue by IceKimi** [huggingface/trl#522]
hi lvwerra thx for your greate job. I'm using bloomz to run ppo step. as training goes on i notice that the model response is become shorter and shorter , finally to eos. i also try to fix the lenght of resp , but after servral training step the model start to generate gibberish response also reward score to the lowest.
so how can i solve this problem. is there any suggest?

**Comment by lvwerra** [comment]
Maybe an issue when computing the rewards? What kind of model are you training? Without any code it's impossible to see where the issue could be.
