### ISSUE TITLE
Device placement for active, reference and reward model in PPOTrainer

### ISSUE THREAD

**Issue by tannonk** [huggingface/trl#532]
Hey,

In the RL step for the [stack_llama example](https://github.com/lvwerra/trl/blob/main/examples/research_projects/stack_llama/scripts/rl_training.py), all 3 models (active, reference and reward models) are loaded to the same device(s), however, this can quickly run into OOM issues.

Is there a way to utilise separate devices for each of the models needed by the `PPOTrainer`? E.g. using `cuda:0` for the active model for rollout and updates, `cuda:1` for reference model and `cuda:2` for scoring with the reward model.

I tried this out simply by calling the script directly without accelerate and specifying a separate device for each, e.g.:

```python
# load active model
model = AutoModelForCausalLMWithValueHead.from_pretrained(
        config.model_name,
        torch_dtype=torch.bfloat16
        device_map={"": 0},
        use_cache=False,
    )

...

# load ref model (passed to PPOTrainer)
ref_model = AutoModelForCausalLMWithValueHead.from_pretrained(
        config.model_name,
        torch_dtype=torch.bfloat16
        device_map={"": 1},
        use_cache=False,
    )

```

But this hits the following `RuntimeError` when trying to compute the `ref_logprobs` on [this line](https://github.com/lvwerra/trl/blob/7f297b38c665e6d2357dfd5ba552ef685afe1302/trl/trainer/ppo_trainer.py#L649).

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

Based on this, I played around with relocating the tensors to ref_model's device inside the `PPOTrainer`, but so far no luck. 

I'm wondering if there's a recommended way of setting this up or whether this kind of approach should simply be avoided for some reason.

Thanks in advance for any clarification!

**Comment by lvwerra** [comment]
Hi @tannonk, no this is not supported at the moment. It would require to route the inputs/outputs of the models the the  appropriate devices which we are not doing at the moment.

**Comment by uahmad235** [comment]
I ran into the same issue when i ran the example script at `examples/sctipts/sentiment_tuning.py` using `deepspeed`. The configuration i am using is `deepspeed_zero2.yaml` :
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
script 
My understanding is that `trl` supports `deepspeed` out-of-the-box hence this should be working. Or am i doing something wrong here?

**Comment by younesbelkada** [comment]
@uahmad235 , the DeepSpeed integration has been completed in https://github.com/huggingface/trl/pull/758
Can you try to install trl from source and try again?

**Comment by uahmad235** [comment]
I'll do that right away. Thanks for the prompt response.

**Comment by uahmad235** [comment]
I was able to run the example with the default settings but it deepspeed was skipping batches due to memory limits (although i have 2xA6000s) and it should be enough for gpt2. I reduced batch sized to 8, and it somehow got stable
However, i tried using peft by changing `use_peft=True` in script but it failed (same issue i.e., tensors on different devices).
I really need peft support here since i am planning to finetune larger model such as `llama2-7b`. 
Please correct me if i am wrong but i am assuming that deepspeed does have compatibility with peft.
