### ISSUE TITLE
How to load a trained model to continue trianing?

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [huggingface/trl#534]
Dear TRL team,

I face a challenge that I can't finish the training in one go. Thus, I need to load the model that is trained half-way and continue the training process. Could you please guide me how to load the half-way trained model and continue the trianing process?

Best

**Comment by younesbelkada** [comment]
Hi @zyzisastudyreallyhardguy 
Thanks for the issue, you can save the model after your first training batch using `ppo_trainer.save_pretrained(xxxx)` then load back the model using `AutoModelForCausalLMWithValueHead.from_pretrained(xxx)`, this should load correctly the trained model and value head.

**Comment by lvwerra** [comment]
If you also want to save optimizer states and dataloader progress you could use functionality from `accelerate`: https://huggingface.co/docs/accelerate/usage_guides/checkpoint

You can access the `accelerator` from the the `PPOTrainer` with `ppo_trainer.accelerator`. Not that we did not fully check for compatibility but there are not major obstacles why this shouldn't work.
