### ISSUE TITLE
Why we compute advantage and return inside the self.loss function in the PPOTrainer? Seems like we do not need to do it everytime.

### ISSUE THREAD

**Issue by shamanez** [huggingface/trl#548]
As mentioned [in the self.loss function](https://github.com/lvwerra/trl/blob/main/trl/trainer/ppo_trainer.py#L1056), we use state values from the [original episode ](https://github.com/lvwerra/trl/blob/main/trl/trainer/ppo_trainer.py#L692) to compute the advantage and the return.  

So we can compute them once prior to the [ppo optimization loop](https://github.com/lvwerra/trl/blob/main/trl/trainer/ppo_trainer.py#L688).

**Comment by vwxyzjn** [comment]
@shamanez this is a very good point. Reward and values don't change and so won't advantages change. I am doing a refactor at #546 and hopefully can do this later.
