### ISSUE TITLE
Fine tune classification model with SFTTrainer 

### ISSUE THREAD

**Issue by Imran-tech-lab** [huggingface/trl#564]
Hi, I am getting confused. My question is, can I fine-tune a classification model, like movie classification, etc., with SFTTrainer? My second question is about named entity recognition.

I know how to fine-tune classical methods for both text classification and NER, where you will need to prepare the text and labels.

Please give me an example using SFTTrainer

**Comment by lvwerra** [comment]
Hi @imrankh46, the SFTTrainer is specifically for the causal language modeling objective and as such not suited for your task. You can use the `transformers.Trainer` for these tasks. Checkout the examples: https://huggingface.co/docs/transformers/notebooks

**Comment by lvwerra** [comment]
Ok, that's not supported in the `SFTTrainer`. The goal is specifically to fine-tune the language model itself on new text.
