### ISSUE TITLE
Llama 2 fine-tuning with PEFT taking days on free Google Colab?

### ISSUE THREAD

**Issue by MichaelKarpe** [huggingface/trl#572]
Hey @lvwerra @younesbelkada and team,

I tried to run the SFTTrainer fine-tuning script as described [here](https://github.com/huggingface/blog/blob/main/llama2.md#fine-tuning-with-peft) on free Google Colab, GPU T4 runtime, by executing a simple notebook with the three following cells:

```
!pip install trl peft>=0.3.0 bitsandbytes
!git clone https://github.com/lvwerra/trl
```

```
!huggingface-cli login
```

```
!python trl/examples/scripts/sft_trainer.py \
    --model_name meta-llama/Llama-2-7b-hf \
    --dataset_name timdettmers/openassistant-guanaco \
    --load_in_4bit \
    --use_peft \
    --batch_size 4 \
    --gradient_accumulation_steps 2
```

However, the estimated training time is about 3 days, as one epoch takes more than 1 minute.
I spotted the following warning, I don't know if it can help in explaining such a long training:
```
You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
```

Is it expected or am I missing something? I was expecting something quicker... :smile:

**Comment by ryanshrott** [comment]
yeah it's slow. takes 67 hours. Do you know how to save the model after you train?

**Comment by lvwerra** [comment]
Yes, depending on the dataset size it can take a while to train on Colab notebooks. Subsampling could help.

**Comment by conderls** [comment]
the test dataset(timdettmers/openassistant-guanaco) contains 9846 rows and the estimated training time is about 16 hours on 8*V100(32GB) with the same given options.

it seems that it does not training in parallel and takes full usage of all GPU resources.


![image](https://github.com/lvwerra/trl/assets/6688515/8a5e605b-b8ba-45b1-ab98-43c13dfcaf6f)

**Comment by younesbelkada** [comment]
To increase training speed, you can train adapters on GPTQ quantized models: https://huggingface.co/blog/gptq-integration#native-support-of-gptq-models-in--transformers note however that you can't merge the trained adapter weights into base model after training

**Comment by younesbelkada** [comment]
You can also use flash attention 1 & 2 + quantization to speedup training, see more about it here: https://huggingface.co/docs/trl/main/en/sft_trainer#using-flash-attention-and-flash-attention-2
