### ISSUE TITLE
merge_and_push

### ISSUE THREAD

**Issue by ryanshrott** [huggingface/trl#575]
How to merge and push to hub?

From the blog post:
"The script can merge the LoRA weights into the model weights and save them as safetensor weights by providing the merge_and_push argument. This allows us to deploy our fine-tuned model after training using text-generation-inference and inference endpoints."

**Comment by younesbelkada** [comment]
Hi @ryanshrott 
To merge the adapter weights to the base model and push, simply run:
```python
from peft import AutoPeftModelForCausalLM

adapter_model_path = "xxx"
pushed_model_id = "xxx"
peft_model = AutoPeftModelForCausalLM.from_pretrained(adapter_model_path)
merged_model = peft_model.merge_and_unload()
merged_model.push_to_hub(pushed_model_id)
```

**Comment by osma** [comment]
I was wondering the same - the [HF blog post section on fine-tuning Llama 2 with PEFT](https://huggingface.co/blog/llama2#fine-tuning-with-peft) seems to promise a feature that's not actually implemented in the [sft_trainer.py](https://github.com/lvwerra/trl/blob/main/examples/scripts/sft_trainer.py) script it links to.

FWIW, this [similar script](https://gist.github.com/younesbelkada/9f7f75c94bdc1981c8ca5cc937d4a4da) actually implements the `merge_and_push` option at the end of the script. Maybe that part could be added to `sft_trainer.py` as well?

**Comment by ryanshrott** [comment]
@younesbelkada 

I ran this code at end of my notebook:
from peft import AutoPeftModelForCausalLM
del model
adapter_model_path = "rshrott/llama2-qlora-finetunined-french"
pushed_model_id = "rshrott/llama2-qlora-finetunined-french-full-model"
peft_model = AutoPeftModelForCausalLM.from_pretrained(adapter_model_path)
merged_model = peft_model.merge_and_unload()
merged_model.push_to_hub(pushed_model_id)

here is the model in HF:
https://huggingface.co/rshrott/llama2-qlora-finetunined-french-full-model/tree/main

Does it look correct? Can i deploy as inference endpoint now?

**Comment by ryanshrott** [comment]
@younesbelkada 

Error when I get when deploying to A10 in HF. Any idea?
2023/07/26 21:46:15 ~ {"timestamp":"2023-07-27T01:46:15.433331Z","level":"ERROR","fields":{"message":"Error when initializing model\nTraceback (most recent call last):\n File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py\", line 39, in __init__\n tokenizer = LlamaTokenizer.from_pretrained(\n File \"/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py\", line 1796, in from_pretrained\n raise EnvironmentError(\nOSError: Can't load tokenizer for '/repository'

**Comment by younesbelkada** [comment]
hi @ryanshrott 
Looking at your repository the model looks definitelty correct

For your second error can you also push the tokenizer on your repo?

```python
from transformers import AutoTokenizer

adapter_model_path = "rshrott/llama2-qlora-finetunined-french"
tokenizer_id = "meta-llama/Llama-2-7b-hf"

tokenizer = AutoTokenizer.from_pretrained(tokenizer_id)
tokenizer.push_to_hub(adapter_model_path)
```

**Comment by ryanshrott** [comment]
@younesbelkada  thanks, still Struggling with this. I am following this notebook:
https://colab.research.google.com/drive/1PEQyJO1-f6j0S_XJ8DV50NkpzasXkrzd?usp=sharing
https://towardsdatascience.com/fine-tune-your-own-llama-2-model-in-a-colab-notebook-df9823a04a32

Here is relevant code:
# Reload model in FP16 and merge it with LoRA weights
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map=device_map,
)
model = PeftModel.from_pretrained(base_model, output_dir)
model = model.merge_and_unload()

# Reload tokenizer to save it
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"


model.push_to_hub(new_model, use_temp_dir=False, use_auth_token=True)
tokenizer.push_to_hub(new_model, use_temp_dir=False, use_auth_token=True)

Error message:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
 in 
----> 1 model.push_to_hub(new_model, use_temp_dir=False, use_auth_token=True)
      2 tokenizer.push_to_hub(new_model, use_temp_dir=False, use_auth_token=True)

[~/.local/lib/python3.8/site-packages/transformers/utils/hub.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Ryan/Downloads/~/.local/lib/python3.8/site-packages/transformers/utils/hub.py) in push_to_hub(self, repo_id, use_temp_dir, commit_message, private, use_auth_token, max_shard_size, create_pr, safe_serialization, **deprecated_kwargs)
    809 
    810         with working_or_temp_dir(working_dir=working_dir, use_temp_dir=use_temp_dir) as work_dir:
--> 811             files_timestamps = self._get_files_timestamps(work_dir)
    812 
    813             # Save all files.

[~/.local/lib/python3.8/site-packages/transformers/utils/hub.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Ryan/Downloads/~/.local/lib/python3.8/site-packages/transformers/utils/hub.py) in _get_files_timestamps(self, working_dir)
    670         Returns the list of files with their last modification timestamp.
    671         """
--> 672         return {f: os.path.getmtime(os.path.join(working_dir, f)) for f in os.listdir(working_dir)}
    673 
    674     def _upload_modified_files(

FileNotFoundError: [Errno 2] No such file or directory: 'llama-2-7b-miniguanaco'
