### ISSUE TITLE
Decreasing the dataset

### ISSUE THREAD

**Issue by zehrayigit** [huggingface/trl#577]
Hello,
After I decreased dataset I am constantly getting error(TypeError: 'NoneType' object is not subscriptable) at the training part of sentiment control gpt-2. How can I fix it?

**Comment by lvwerra** [comment]
Can you provide a reproducible example?

**Comment by zehrayigit** [comment]
Here is the full code:
[gpt2-sentiment-control (6) (1).ipynb.zip](https://github.com/lvwerra/trl/files/12182952/gpt2-sentiment-control.6.1.ipynb.zip)

**Comment by zehrayigit** [comment]
> Can you provide a reproducible example?

Here is the full code:
[gpt2-sentiment-control (6) (1).ipynb.zip](https://github.com/lvwerra/trl/files/12182952/gpt2-sentiment-control.6.1.ipynb.zip)

**Comment by lvwerra** [comment]
Maybe worth checking how `task_list` and `batch["query"]` look like. This seems where the error is coming from.

**Comment by pzhang84** [comment]
Hi @zehrayigit , did you resolve this issue? I met the same issue of "TypeError: 'NoneType' object is not subscriptable".
