### ISSUE TITLE
Seq2Seq model training with DPO

### ISSUE THREAD

**Issue by gaetanlop** [huggingface/trl#579]
Hello, 

I was looking at the DPO implementation to train T5 on a summarization task. It looks like both the DPOCollator and the DPOTrainer won't work for encoder-decoder architectures. Is it on purpose? Does DPO not work well for seq2seq models (I didn't find any experiments with T5 in their paper)?

If it is relevant I can try to work on an implementation that supports seq2seq models (it won't require that much changes from what I have seen).

**Comment by younesbelkada** [comment]
Great point! 
Quickly looking at the DPOTrainer source code I don't think there is anything blocking for enc-dec models. I did not tested or tried anything though. Perhaps you can try to adapt the script: https://github.com/lvwerra/trl/blob/main/examples/dpo.py to a T5-like model and see if you face into any issue ! If it does not work out of the box then we'll need to think of how to adapt the trainer for seq2seq models
Maybe @kashif, @TevenLeScao & @tomaarsen can also share their thoughts as I am not 100% familiar with DPO
Thanks !

**Comment by tomaarsen** [comment]
Hello!

I've also not experimented with any models other than ones that are loaded with `AutoModelForCausalLM` - I've only tested with GPT2 and some other tiny models.

Did you get this error?
```python
  File "[path]\transformers\models\t5\modeling_t5.py", line 987, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
```

- Tom Aarsen

**Comment by gaetanlop** [comment]
Hello @tomaarsen @younesbelkada, T5 like models require labels in order to do teacher forcing + the prompt and the chosen/rejected responses should not be concatenated together. This is the case in the current DPO implementation. I have worked on something yesterday. I will make a pull request if that's okay for you.

**Comment by younesbelkada** [comment]
Hi @gaetanlop @tomaarsen 
Thanks for all your replies,
That sounds great, looking forward to your PR !

**Comment by kashif** [comment]
@gaetanlop thanks for this... yes currently we only tested with decoder only models and thus things were contacted together to avoid multiple forward calls... but you are right in the enc-dec setting those helpers would need to be extended appropriately... I do not think there is inherently anything in DPO stopping the use of enc-dec models so your PR will be a useful extension!

**Comment by gaetanlop** [comment]
Thanks for the confirmation @kashif!

**Comment by chansurgeplus** [comment]
I've tested this with flan-t5-small model with the following configuration.
```python
training_args = TrainingArguments(
    run_name="abc",
    output_dir="outputs",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    learning_rate=9e-1,
    max_grad_norm=10.0,
    optim="adamw_hf",
    evaluation_strategy="steps",
    eval_steps=350,
    logging_strategy="steps",
    logging_steps=50,
    logging_first_step=True,
    save_strategy="steps",
    save_steps=300,
    fsdp="auto_wrap",
    fsdp_config={
        "xla": True,
    },
    remove_unused_columns=False,
)
```

```python
trainer = DPOTrainer(
    model=model,
    ref_model=model_ref,
    args=training_args,
    beta=0.1,
    train_dataset=dataset_train,
    eval_dataset=dataset_test,
    tokenizer=tokenizer,
    max_length=512,
    max_prompt_length=512,
    max_target_length=512,
)
```

Here's the training loss I get, and it doesn't necessarily decrease.
![W B Chart 09_08_2023, 16_51_36](https://github.com/lvwerra/trl/assets/134255133/b7cb818a-220f-4198-a995-8a75a6491ea7)

I think there's more to this since as my own experimentation with the original DPO repo by eric-mitchell resembled a very similar DPO loss: [here](https://github.com/eric-mitchell/direct-preference-optimization/issues/26)

**Comment by chansurgeplus** [comment]
Not stale!

**Comment by younesbelkada** [comment]
#586 is in a great shape and should be merged soon!
