### ISSUE TITLE
LLaMa 2 70B fine-tuning

### ISSUE THREAD

**Issue by qanastek** [huggingface/trl#581]
Dear maintainers,

I am currently looking to perform a PEFT fine-tuning of the LLaMa 70B parameters on the MedAlpaca datasets using the jean-zay infrastructure (here V100 32GB GPUs) and QLoRA. But I cannot find anything in TRL repository about how to handle multi GPU and multi node fine-tuning of a model which doesn't fit into a single GPU (FSDP).

Do you have any ideas of how I could make it possible ?

Thank you so much for your work on this library!

**Comment by younesbelkada** [comment]
Hi @qanastek 
Thanks for your interest ! And looking forward to your experiments
Sadly QLoRA does not support FSDP - however you can go for Naive Pipeline Parallelism + (hopefully) multi-node setup. 
I assume you have multiple GPUs in each node, in your fine-tuning main script, load your model with:

```python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    model_name, 
    load_in_4bit=True, 
    device_map="auto"
)

# check: https://github.com/huggingface/transformers/pull/24906
model.config.pretraining_tp = 1 
```

`device_map="auto"` should split your model across all available GPUs. Make sure to install transformers from source (regarding https://github.com/huggingface/transformers/pull/24906) and have all these libraries:

```bash
# accelerate == 0.21.0
# peft == 0.4.0
# bitsandbytes == 0.40.2
# trl == 0.4.7
```

Running your script simply with the command `python xxxx.py` should work - this would give you a v1 of fine-tuning script that work on a single node.

For going into multi-node (didn't tried `SFTTrainer` on multi-node yet) you can try to first run

```bash
accelerate config
```
And select multi-node (and not multi-gpu) and run `accelerate run xxx.py`. 

Let us know how it goes!

**Comment by liebkne** [comment]
@younesbelkada When I use you settings for `device_map` and `model.config.pretraining_tp`, it still uses only single GPU.

**Comment by younesbelkada** [comment]
hi @liebkne 
Thanks for trying it, can you share a screen shot of `nvidia-smi` ? Do you mean that only one GPU gets busy at each timestep while others are kept idle?
