### ISSUE TITLE
Llama 2 loaded in 8bit produces warning

### ISSUE THREAD

**Issue by conscell** [huggingface/trl#582]
Hi,

When I run Llama 2 fine-tuning in 8bit mode
```
python trl/examples/scripts/sft_trainer.py \
    --model_name meta-llama/Llama-2-7b-hf \
    --dataset_name timdettmers/openassistant-guanaco \
    --load_in_8bit \
    --use_peft \
    --batch_size 4 \
    --gradient_accumulation_steps 2
```
the training script produces this warning:
```
<...>/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:322: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
```
Is it safe to ignore it? 
When the model is loaded in 4-bit mode there are no warnings about cast from torch.float32 to float16, but the process is extremely slow on RTX3090.

**Comment by younesbelkada** [comment]
Hi @conscell 
Thanks for the issue, yes it is safe to ignore the warning. To make it disappear , can you try to add `torch_dtype=torch.float16` here: https://github.com/lvwerra/trl/blob/main/examples/scripts/sft_trainer.py#L74 (actually the value is hard-coded, I suggest to add a new CLI arg for that). 
For the speed, perhaps you can try `bnb_4bit_compute_dtype=torch.float16`. I will also make that argument exposed through the CLI.

**Comment by conscell** [comment]
Hi @younesbelkada,
Thank you very much for your reply. Setting `torch_dtype=torch.float16` doesn't affect the warning, it still persists. 
Not sure if this is related, but original fairseq Llama 2 model uses `torch.bfloat16`
```
>>> import torch
>>> weights = torch.load("./consolidated.00.pth")
>>> for k,v in weights.items():
...   print(v.dtype)
... 
torch.bfloat16
torch.bfloat16
<...>
```
Hugging Face Llama 2 model configuration file says  ` "torch_dtype": "float16"`. Don't know exactly how HF weights were created, but `convert_llama_weights_to_hf.py` script sets `torch_dtype=torch.float16`. 
Unfortunately, setting `bnb_4bit_compute_dtype=torch.float16` (I also tried `bfloat16`) doesn't improve things, it is twice slower than 8bit regime.
