### ISSUE TITLE
How to load a custom structure model？

### ISSUE THREAD

**Issue by estuday** [huggingface/trl#592]
hello， when I run the following code, I am prompted that only support  `AutoModelForCausalLMWithValueHead` and `AutoModelForSeq2SeqLMWithValueHead`. But these two structures seem to only be able to load the specified pre-trained model.
`ppo_trainer = PPOTrainer(config, gen_model, gen_ref_model, tokenizer)`

My model is trained by the T5, and the structure has changed. I would like to know how to load my model? Is it supported?

**Comment by younesbelkada** [comment]
Hi @estuday 
Thanks for the issue, how your new architecture is defined? Perhaps you can make it inherit from an `AutoModelForSeq2SeqLMWithValueHead` and overwrite the necessary methods.

**Comment by estuday** [comment]
> Hi @estuday Thanks for the issue, how your new architecture is defined? Perhaps you can make it inherit from an `AutoModelForSeq2SeqLMWithValueHead` and overwrite the necessary methods.

hi @younesbelkada , thanks for your reply. If the model is loaded with the following code, how to apply it to the trl frame?
```
from transformers import T5ForConditionalGeneration
model=T5ForConditionalGeneration.from_pretrained('t5-small')
```

**Comment by younesbelkada** [comment]
Hi @estuday 
If you want to fine-tune a T5 model using PPO you should run:

```python
from trl import AutoModelForSeq2SeqLMWithValueHead

model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained("t5-small")

...
ppo_trainer = PPOTrainer(config, model, ref_model=None, ...)
```

You can reproduce the sentiment tuning experiment with t5 model: https://github.com/lvwerra/trl/blob/main/examples/scripts/sentiment_tuning.py by passing `--use_seq2seq` argument.

**Comment by estuday** [comment]
> Hi @estuday If you want to fine-tune a T5 model using PPO you should run:
> 
> ```python
> from trl import AutoModelForSeq2SeqLMWithValueHead
> 
> model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained("t5-small")
> 
> ...
> ppo_trainer = PPOTrainer(config, model, ref_model=None, ...)
> ```
> 
> You can reproduce the sentiment tuning experiment with t5 model: https://github.com/lvwerra/trl/blob/main/examples/scripts/sentiment_tuning.py by passing `--use_seq2seq` argument.

hi @younesbelkada.
Actually, I don't want to use the T5 model directly for the trl framework. I've fine-tuned the T5 before this, so its structure has changed.
I have tried the following code, but failed:
```
trl_model=AutoModelForSeq2SeqLMWithValueHead.from_pretrained('t5-base')
finetuned_model=Mymodel.load_from_checkpoint('path/to/mymodel.ckpt')
trl_model=trl_model.load_state_dict(finetuned_model.state_dict())
```
Mymodel can be regarded as a model read by `T5ForConditionalGeneration.from_pretrained('t5-base')`, which is different from the structure read by `AutoModelForSeq2SeqLMWithValueHead.from_pretrained('t5-base')`

**Comment by lvwerra** [comment]
What do you mean by "different from the structure"? Is it a different architecture? Otherwise you could simply do:
```python
trl_model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained('path/to/mymodel.ckpt')
```
