### ISSUE TITLE
Deepspeed Parameter redundancy in single GPU Training

### ISSUE THREAD

**Issue by LiuZhihhxx** [huggingface/trl#596]
Referring to https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/deepspeed#deployment-with-one-gpu I write a basic deepspeed config as:
```
{
  "zero_optimization": {
     "stage": 2,
     "offload_optimizer": {
         "device": "cpu",
         "pin_memory": true
     },
     "allgather_partitions": true,
     "allgather_bucket_size": 2e8,
     "reduce_scatter": true,
     "reduce_bucket_size": 2e8,
     "overlap_comm": true,
     "contiguous_gradients": true
  }
}
```
and add it in `TrainingArguments(..., deepspeed='trl/examples/scripts/ds_config.json')`.

Run in terminal (other parameters were set default values respectively in the TrainingArguments())
```
deepspeed trl/examples/scripts/sft_trainer.py 
--model_name Chinese-Llama-2-7b 
--dataset_name timdettmers/openassistant-guanaco 
--batch_size 8
--gradient_accumulation_steps 2 
--num_train_epochs 1
```
and then an error arised: `ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local_rank=0']`

Anyone knows what 'local_rank' mean and how to deal with? I didn't find it in any scripts.

**Comment by lvwerra** [comment]
I think you should be able to configure DeepSpeed via `accelerate` and then launch the script with `accelerate launch trl/examples/scripts/sft_trainer.py ...`.

**Comment by lvwerra** [comment]
I am guessing that's something that's passed under the hood maybe of DeepSpeed? If it works now can we close the issue?
