### ISSUE TITLE
DPO training model and model ref on different GPUs causing error issues.

### ISSUE THREAD

**Issue by testerpce** [huggingface/trl#606]
I am working on 8 V100 16 GB GPUs and I am trying to train a 3.7B parameter mt5-xl model on the DPO training. 
I managed to load both model and model ref as separate instances of mT5-xl in 8 bit. However, there seems to be an error in loading the 2 systems as it gives the following error.

`Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.45s/it]
Some weights of MT5ForConditionalGeneration were not initialized from the model checkpoint at /efs-storage/save_outputs/models/umt5-xl and are newly initialized: ['encoder.embed_tokens.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.07s/it]
Some weights of MT5ForConditionalGeneration were not initialized from the model checkpoint at /efs-storage/save_outputs/models/umt5-xl and are newly initialized: ['encoder.embed_tokens.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "dpot5.py", line 142, in <module>
    main()
  File "dpot5.py", line 121, in main
    dpo_trainer = DPOTrainer(
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/trl-0.4.8.dev0-py3.8.egg/trl/trainer/dpo_trainer.py", line 200, in __init__
    self.ref_model = self.accelerator.prepare_model(self.ref_model, evaluation_mode=True)
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/accelerate/accelerator.py", line 1281, in prepare_model
    raise ValueError(
ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}`

**Comment by kashif** [comment]
thanks @testerpce for the report, I will try to replicate it as well and report back

**Comment by lvwerra** [comment]
Note that Seq2Seq models are still being integrated: https://github.com/lvwerra/trl/pull/586
