### ISSUE TITLE
Add warning for removing response token when padding

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/trl#613]
If `max_seq_length` is not long enough then the `DataCollatorForCompletionOnlyLM` will pad off your response token which will lead to errors like the following

```bash
RuntimeError: Could not find response key [518, 29914, 25580, 29962, 13] in 
token IDs tensor([    1,   518, 25580,  ..., 31164, 30870, 30380])
```

In hindsight it is obvious that i sequences are truncated then left padded that some examples will have the response token delimiter removed but boy would it have been nice if during initialization `SFTTrainer` had just told me it was chopping off the tokens and would lead to downstream errors.

Let me know if I can be of any help!

**Comment by lvwerra** [comment]
Indeed, I can see how that's a bit annoying to debug! Could you open a PR for that? I think we can do the warning selectively only when 1) some sequences have been cutoff and 2) if there is a response template.
