### ISSUE TITLE
PPO Training issue 

### ISSUE THREAD

**Issue by allzero-kwon** [huggingface/trl#615]
Hi. Im trying to reproduce summarize from human feedback with PPO. 

And i stuck on some issue in ppo training.
My reward_mean is not only unstable (not increasing) but objective/kl value is decreasing.
Is there any way i can do for it? 

my reword model : [gpt2 ](https://huggingface.co/Tristan/gpt2_reward_summarization)
my sft model : gpt2 based sft trained with openai tldr dataset.

**Comment by lvwerra** [comment]
Can you post a reproducible example? Usually negative KL is due to the generation settings.

**Comment by laosuan** [comment]
The training in ppo stage can't converge. Is it better to sample 100 best K samples and calculate the average reward?

**Comment by lvwerra** [comment]
It's worth also varying the LR. Usually for batch sizes I use something like: `batch_size=256` and `mini_batch_size*gradient_accumulation_steps=64`.
