### ISSUE TITLE
Would DPOTrainer with a single model in memory be possible?

### ISSUE THREAD

**Issue by vincentmin** [huggingface/trl#624]
Currently the DPOTrainer needs two models in memory: 1. the model to be trained, 2. the reference model. The reference model is frozen here. I was thinking that it could be possible to load the model only once in memory and have a single LoRA adapter. When the model needs to be used in reference mode, we simply turn off the adapter. The base model would be frozen and only the LoRA adapter would be trainable.

Is there a theoretical obstruction to doing this? If not, is there a significant overhead for having to turn the adapter on and off during training? If the answer is no to both of these questions, I think it would be interesting to create an implementation of such a DPOTrainer as it would cut the required vram in half and therefore further democratise llm finetuning.

**Comment by lvwerra** [comment]
Indeed we could and it's what we are doing in the `PPOTrainer`. What do you think @younesbelkada and @kashif?

**Comment by kashif** [comment]
@vincentmin Yes in theory that would be indeed possible and something we should do! Do you want to have a crack at it?

**Comment by vincentmin** [comment]
Good to hear this is possible. I am restricted in my free time at the moment (life with a newborn 😄), so I'll let someone else take a crack at it.

**Comment by vincentmin** [comment]
Actually, let me give this a shot. It seems to me it shouldn't take so much time.

Do you prefer a new DPOTrainer class, or to modify the input arguments to the current DPOTrainer?

**Comment by lvwerra** [comment]
Probably similar to the `PPOTrainer` should work: if model is a peft model and there's no reference model we deactivate the adapter for the reference model.

**Comment by vincentmin** [comment]
PR is live! #640
