### ISSUE TITLE
how to use Reward model?

### ISSUE THREAD

**Issue by zhuxiaosheng** [huggingface/trl#627]
How to use Reward Model in RLHF PPO stage? 
Could you provide an example?
thank you very much

**Comment by lvwerra** [comment]
You can have a look at a full example here: https://github.com/lvwerra/trl/blob/main/examples/scripts/sentiment_tuning.py

Essentially you can replace the sentiment classifier with any reward model.

**Comment by zhuxiaosheng** [comment]
My English is not very good and Thank you for your response，I am a beginner and have a question. When training large language models for RLHF to align with human thinking, besides using sentiment analysis as a reward model, are there any other tasks used as reward models?

**Comment by lvwerra** [comment]
In general the reward function can be any model or even a coded rule that returns a scalar value. For RLHF the reward model usually encodes if a human would choose this response. But it can also incorporate rules as mentioned like a hard coded penalty for long responses.
