### ISSUE TITLE
sft_llama2 error

### ISSUE THREAD

**Issue by zl-liu** [huggingface/trl#629]
Hello! 

I made no changes to the sample code or the dataset. I just simply wanted to get it to run the stacked llama2 example. However, I get this error:

UserWarning: The passed formatting_func has more than one argument. Usually that function should have a single argument `example` which corresponds to the dictionary returned by each element of the dataset. Make sure you know what you are doing.

 in __init__
    raise ValueError("the `--group_by_length` option is only available for `Dataset`, not `IterableDataset")
ValueError: the `--group_by_length` option is only available for `Dataset`, not `IterableDataset

(Sorry, I must omit certain parts of the error message since I am working on an institution's server). 

Thank you!

**Comment by zl-liu** [comment]
Can someone please just follow the example in https://github.com/huggingface/trl/tree/main/examples/research_projects/stack_llama_2/scripts ? (and don't change the code or the dataset)

I am sure this error is reproducible. 

Thank you!

**Comment by lvwerra** [comment]
Are you using the constant length dataset? That's indeed incompatible with `--group_by_length` as this requires globally sorting the dataset whereas with the constant length dataset the dataset is generated on the fly and thus not globally sortable.

**Comment by zl-liu** [comment]
@lvwerra Thank you for your quick reply! Honestly, I am not sure what do you mean by "constant length dataset". I did not change a single line of code in https://github.com/huggingface/trl/tree/main/examples/research_projects/stack_llama_2/scripts (which is a very new tutorial published 2 days ago).

**Comment by zl-liu** [comment]
I am using the default "lvwerra/stack-exchange-paired" as the dataset.

**Comment by zl-liu** [comment]
I checked sft_llama2.py and I see that it is indeed using constant length dataset (https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/sft_llama2.py)https://github.com/huggingface/trl/blob/3b2c820db68aecca36c2ff5d152de59deec8fe5c/examples/research_projects/stack_llama_2/scripts/sft_llama2.py#L118 ). However, the default flag for --group_by_length is also set to "True" (https://github.com/huggingface/trl/blob/3b2c820db68aecca36c2ff5d152de59deec8fe5c/examples/research_projects/stack_llama_2/scripts/sft_llama2.py#L38C5-L38C34)

**Comment by lvwerra** [comment]
Does it work if you set `--group_by_length` to `False`?

**Comment by zl-liu** [comment]
It is training now after I set --group_by_length to False. Hopefully this is how it is supposed to work! Thank you so much @lvwerra  . Sorry, I was working on another project recently, so I was not checking my email linked to my GitHub

**Comment by lvwerra** [comment]
@younesbelkada I think we should catch that combination of args and throw an error before we start training. What do you think?

**Comment by younesbelkada** [comment]
Sounds good, will propose something!
