### ISSUE TITLE
TypeError: GradientAccumulationPlugin.__init__() got an unexpected keyword argument 'sync_with_dataloader'

### ISSUE THREAD

**Issue by lebronjamesking** [huggingface/trl#630]
Hi there,

I'm using torch =2.0.1, trl=0.5.0, peft=0.4.0; and I was trying to load gpt2 for sft_trainer.py on a single GPU. However, I got the following error, I'm not sure if some dependencies are incompatible?

TypeError: GradientAccumulationPlugin.__init__() got an unexpected keyword argument 'sync_with_dataloader'

**Comment by lvwerra** [comment]
Can you also provide the version of `accelerate`, it is likely where the error originates? Are you using the official script?

**Comment by lebronjamesking** [comment]
Many thanks, I think I solved the problem. Previously I was using a dev version of accelerate.

**Comment by lvwerra** [comment]
Awesome, I am closing the issue then!
