### ISSUE TITLE
`peft_config` type annotations are inconsistent

### ISSUE THREAD

**Issue by mjspeck** [huggingface/trl#634]
In the docstring for `SFTTrainer` the type for the `peft_config` parameters is listed as `Optional[PeftConfig]` but in the init function it is type annotated as `Optional[Dict]`. The docstring is correct and the type annotations is incorrect.

**Comment by lvwerra** [comment]
Thanks for reporting - would you be happy to open a PR for that?

**Comment by mjspeck** [comment]
Sorry, I hadn't seen this reply. I'm happy to open a PR.
