### ISSUE TITLE
 Avoid re-downloading the model files 

### ISSUE THREAD

**Issue by zhuxiaosheng** [huggingface/trl#635]
The llama2 model is very large. When I loaded it using transformers on my local computer, I set the cache_dir, so I have the complete model cache. Could you please guide me on how to configure the parameters when using SFTTrainer to make use of this cached model and avoid re-downloading the model files from Hugging Face?

**Comment by lvwerra** [comment]
We are using the same `transformers` logic to download/cache the model so I believe if you cached it once it should work unless you changed the cache location? Can you confirm that this is not the case?

**Comment by zhuxiaosheng** [comment]
My apologies, I misunderstood earlier. I thought the 'cache_dir' had to be set in SFTTrainer, but it turns out model instantiation is still done through AutoModelForCausalLM, just like before.

**Comment by lvwerra** [comment]
So it is working? In that case can we close the issue?

**Comment by zhuxiaosheng** [comment]
thank you very much
