### ISSUE TITLE
ValueError: You cannot specify an optimizer in the config file and in the code at the same time.

### ISSUE THREAD

**Issue by gopstrit** [huggingface/trl#636]
Anyone had this error?

Here's my launch command: (used ds_config_zero2.json in accelerate config)
(I have used a custom fine-tuned model "falcon=7b" instead of gpt-j-6b in the script).

accelerate launch /ipython-docker/notebook_dir/data/trl/examples/research_projects/toxicity/scripts/gpt-j-6b-toxicity.py

![image](https://github.com/huggingface/trl/assets/51286679/08f46168-2b17-4981-9a47-6c7c9c3b4fa8)

Would appreciate guidance. 

Thanks

**Comment by lvwerra** [comment]
Can you share the accelerate config you are using? And are you additionally specifying an optimizer in the code? I am not super familiar with DeepSpeed but the error suggests that you can't define an optimizer in the DeepSpeed config and in the TRL code.

**Comment by gopstrit** [comment]
Hi @lvwerra Thanks for your reply.

I've used the same file/code as in gpt-j-6b-toxicity.py with only the name of the locally saved model changed (which is, a fine-tuned falcon-7b model).

Accelerate settings:

Tried with the following (With deepspeed) (and got the error as previously mentioned)
*********************************************
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /ipython-docker/notebook_dir/data/configs/ds_config_zero2.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

Also tried the following (without deepspeed)
*********************************************
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: false
  fsdp_transformer_layer_cls_to_wrap: DecoderLayer
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

Got the following error:

![image](https://github.com/huggingface/trl/assets/51286679/b9388e7d-253b-441a-8d74-8d50df026c82)

**Comment by lvwerra** [comment]
We haven't experimented with FSDP much and not sure it's compatible, yet. `accelerate` offers many options and backends and we should better investigate which ones are natively compatible with `trl` (cc @vwxyzjn & @younesbelkada).

Can you also post the content of `/ipython-docker/notebook_dir/data/configs/ds_config_zero2.json`?

Alternatively, if GPU memory is a concern you can use the `peft` integration and use adapters. That way you can go with the native data parallel and without any model parallelism.
