### ISSUE TITLE
AutoModelForCausalLMWithValueHead broken when loading LLAMA2 7B chat with uint8

### ISSUE THREAD

**Issue by jvhoffbauer** [huggingface/trl#647]
It seems like loading LLAMA-2 Chat 7B with `AutoModelForCausalLMWithValueHead` like this leads to a model that only generates random strings

```
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = AutoModelForCausalLMWithValueHead.from_pretrained(
    model_name,
    #torch_dtype=torch.bfloat16,
    load_in_8bit=True,
    device_map={"": 0},
    peft_config=lora_config,
)

```

This generates for example the following 

```
Question: What is 1+1?\nAnswer: cedimen1 Hamilton romanば Touch FORhell Prefakerietumenagr einges relativeadealufeldouxbahGMlass banragma unwIdentity loopbal Bentrachlingsфеelteenda민ialimgolaaroburylev Guylaceoraindaimenовано Ritterpoythonnaleedaretriicarij Gonz Ezola dece pur címurrent arcueomaignonershellusta Zarassarumumer Graybjectyn familjenpoleatz Dun�uth pairsRCendorubyrafubyaki My beskrerouestoregh� släktetBehaviorrite baron Gl Baron Jules Handpiciloalusrile handsurbron Havignoniz
```

Here is also a full repro: [Repro](https://github.com/jvhoffbauer/Repro-TRL-uint8-AutoModelForCausalLMWithValueHead/blob/main/repro_uint8_llama2_trl.ipynb)

**Comment by lvwerra** [comment]
Hi, I tried to reproduce here but the model seems to generate reasonable responses: https://colab.research.google.com/drive/1Qge2AtEk2lPvJBJuLZqlpl2cNPNHnsw-?usp=sharing

```python
print(tokenizer.decode(result[0]))
```
Result:
```
<s> Question: What is 1+1?
Answer: 2

Question: What is 2+2?
Answer: 4

Question: What is 4-2?
Answer: 2

Question: What is 2+3?
Answer: 5

Question: What is 5-2?
Answer: 3

Question: What is 3+2?
Answer: 5

Question: What is 5-3?
Answer: 2

Question: What is 2+4?
Answer: 6
```

**Comment by lvwerra** [comment]
Maybe worth comparing the versions on Colab with your local versions of `peft`, `bitsandbytes` and even `transformers`/`trl`?

**Comment by PoojaG20** [comment]
Hi, While you are using AutoTokenizer for this model, make sure you give padding as `right` to the tokenizer as below - 
`tokenizer.pad_token = tokenizer.eos_token`
`tokenizer.padding_side = "right"`

I was also facing this issue but adding padding solved it for me.
