### ISSUE TITLE
[REFACTOR] unify API-usage `PPOTrainer`

### ISSUE THREAD

**Issue by davidberenstein1957** [huggingface/trl#650]
![image](https://github.com/huggingface/trl/assets/25269220/1ac84dc4-1eb8-4e2d-936f-975a5e86eb08)

Given the examples above, might it be more comprehensive to move some of the `PPO`-logic into the `PPOConfig`? 

Having something like what is shown underneath my unify the API usage a bit more.

```python 
from transformers import pipeline
from trl import PPOConfig, PPOTrainer

config = PPOConfig(
    *args,
    **kwargs,
    reward_model: pipeline,
    generation_args: dict
)
trainer = PPOTrainer(
    config=config,
    model,
    tokenizer
)
trainer.train()
```

Alternatively, we might pass a `Callable` `reward_function` to the config?

```python 
from transformers import pipeline
from trl import PPOConfig, PPOTrainer

def reward_func(examples):
    return rewards

config = PPOConfig(
    *args,
    **kwargs,
    reward_func: Callable,
)
trainer = PPOTrainer(
    config=config,
    model,
    tokenizer
)
trainer.train()
```

**Comment by davidberenstein1957** [comment]
Referenced first, here https://github.com/huggingface/trl/issues/623

**Comment by vwxyzjn** [comment]
Might hold off this a bit as #662 is coming :)
