### ISSUE TITLE
LORA models are not properly handled in examples/research_projects/stack_llama_2/scripts/dpo_llama2.py

### ISSUE THREAD

**Issue by liyaxin999** [huggingface/trl#652]
The training example here is not generating useful output,  because the `DPOTrainer` didn't handle lora model properly.

When initializing the `DPOTrainer` in dpo_llama2.py, model and model_ref are passed in, which are both peft models
```
    # 5. initialize the DPO trainer
    dpo_trainer = DPOTrainer(
        model,
        model_ref,
        args=training_args,
        beta=script_args.beta,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        peft_config=peft_config,
        max_prompt_length=script_args.max_prompt_length,
        max_length=script_args.max_length,
    )
```

But in `DPOTrainer` it will run `get_peft_model(model, peft_config)` again, which will lead to weird output.

```
  elif is_peft_available() and peft_config is not None:
        if getattr(model, "is_loaded_in_8bit", False) or getattr(model, "is_loaded_in_4bit", False):
            model = prepare_model_for_int8_training(model)
        model = get_peft_model(model, peft_config)
```

Also, the passed in `peft_config` could be different from the original model, which also leads to weird behaviors.

It works totally fine if the model is not a peft model.

Could you add another check in the DPOTrainer to make sure `get_peft_model` will not run twice?

Here is my workaround: 
1. load the peft model

```
from transformers import BitsAndBytesConfig, AutoModelForCausalLM
from peft import prepare_model_for_kbit_training
from peft import LoraConfig, get_peft_model

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    #bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
base_model = "meta-llama/Llama-2-13b-hf"

model = AutoModelForCausalLM.from_pretrained(base_model, quantization_config=bnb_config)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

peft_model_id = "Yaxin1992/llama2-13b-1800"

config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=[
          "q_proj",
          "v_proj",
          ],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, config)
model.load_adapter(peft_model_id, adapter_name="default")

```

2. when initialize the DPOTrainer, leave the peft_config None.
```
dpo_trainer = DPOTrainer(
        model,
        model_ref,
        args=training_args,
        beta=beta,
        train_dataset=train_dataset,
        tokenizer=tokenizer,
        #peft_config=peft_config,
        max_prompt_length=max_prompt_length,
        max_length=max_length,
    )
```

**Comment by younesbelkada** [comment]
Hi @liyaxin999 
Thanks for reporting, I believe https://github.com/huggingface/trl/pull/640 should address your issue

**Comment by wibrown** [comment]
Calling `model = model.merge_and_unload()` first to merge the LoRA weights before initializing the trainer fixed this for me.

**Comment by psych0v0yager** [comment]
If I understand correctly, will the trainer train the adapter with (peft_model_id = "Yaxin1992/llama2-13b-1800") as the starting point or will it just copy the config hyperparameters?

Also does this work for SFTTrainer as well?
