### ISSUE TITLE
Pre-Generating Responses for PPO?

### ISSUE THREAD

**Issue by DinhLuan14** [huggingface/trl#655]
From what I understand, the PPO process unfolds as follows:

1. The SFT Model generates a response for the given prompt.
2. The Reward model scores the prompt+response pair.
3. Loss is computed and the SFT model is updated.

Question: In step 1, to reduce the time for the SFT to generate a response, can I pre-generate responses offline?

**Comment by younesbelkada** [comment]
hi @DinhLuan14 
I think that you can indeed to that, however the model weights gets updated after step 3. This means you need to re-generate the responses right after that step with the new weights.

**Comment by DinhLuan14** [comment]
From what I understand, when the weights are updated in the LoRa network's weight layer, the original model remains unaffected, right?

**Comment by younesbelkada** [comment]
Correct but you want to generate the responses with the model that contains the LoRA additional layers, not the original model

**Comment by DinhLuan14** [comment]
> Correct but you want to generate the responses with the model that contains the LoRA additional layers, not the original model

I still don't quite understand your answer, can you explain it in more detail?

**Comment by younesbelkada** [comment]
Check out how the PPO should work in the context of fine-tuning LLMs using TRL: https://github.com/huggingface/trl#how-ppo-works as you can see, in the rollout stage (text generation stage), one should always use the active model. When fine-tuning the model using LoRA the active model corresponds to the model together with the LoRA additional layers.

**Comment by DinhLuan14** [comment]
> Check out how the PPO should work in the context of fine-tuning LLMs using TRL: https://github.com/huggingface/trl#how-ppo-works as you can see, in the rollout stage (text generation stage), one should always use the active model. When fine-tuning the model using LoRA the active model corresponds to the model together with the LoRA additional layers.

Very helpful, thanks @younesbelkada
