### ISSUE TITLE
Error in trl 0.5.0

### ISSUE THREAD

**Issue by coralexbadea** [huggingface/trl#667]
If you copy paste the code from hugging face SFTTrainer page ([Supervised Fine-tuning Trainer](https://huggingface.co/docs/trl/main/en/sft_trainer)) it results in error:
```
name ‘PeftModel’ is not defined
```

Code:
```
trainer = SFTTrainer(
“facebook/opt-350m”,
train_dataset=dataset,
dataset_text_field=“text”,
max_seq_length=512,
)
trainer.train()
```

If I downgrade to 0.4.0 the issue is no longer there.

**Comment by younesbelkada** [comment]
Thanks @coralexbadea , I have managed to reproduce, meanwhile you can install PEFT `pip install peft` to overcome the issue
