### ISSUE TITLE
Tutorial script missing eval_batch_size

### ISSUE THREAD

**Issue by rahuljha** [huggingface/trl#671]
Following this tutorial https://huggingface.co/blog/dpo-trl, I ran into out of memory issues with the DPO script. The problem was that the script missed copying per_device_eval_batch_size to Training Arguments [here](https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L166C12-L166C12). This makes it use the default size of 8 for eval_batch_size instead of 1 as set in this script. The below addition fixes the issue.

```
training_args = TrainingArguments(
        per_device_train_batch_size=script_args.per_device_train_batch_size,
-->        per_device_eval_batch_size=script_args.per_device_eval_batch_size,
```

**Comment by lvwerra** [comment]
Would you mind opening a PR?

**Comment by rahuljha** [comment]
Happy to do it, but I am getting a permission error. This is my first time using github (though I am a long time git user). I tried creating a personal access token (classic) on github and used that as the password (with my username), but that didn't work. Do I need a specific access token for the trl repo?

```
git push -u origin rahuljha/fix_arg_setting
Username for 'https://github.com': rahuljha
Password for 'https://rahuljha@github.com': 
remote: Permission to huggingface/trl.git denied to rahuljha.
fatal: unable to access 'https://github.com/huggingface/trl.git/': The requested URL returned error: 403
```

**Comment by rahuljha** [comment]
Reading through some more docs, looks like I need to first fork the repo. Will do this and try creating a pull request.
