### ISSUE TITLE
how to run reward_trainer.py

### ISSUE THREAD

**Issue by samitTAN** [huggingface/trl#677]
ValueError: Some specified arguments are not used by the HfArgumentParser: ['-f', '/Users/samittan/Library/Jupyter/runtime/kernel-32045810-5e16-48f4-8d44-c7a7f975f8a4.json']

**Comment by younesbelkada** [comment]
hi @samitTAN 
Can you share the command you ran?

**Comment by samitTAN** [comment]
examples/scripts/reward_trainer.py

**Comment by samitTAN** [comment]
![image](https://github.com/huggingface/trl/assets/42274231/d48ee624-5ba4-4114-a136-01e7f10754ad)

**Comment by samitTAN** [comment]
Is there something should be add in?

**Comment by samitTAN** [comment]
![Screen Shot 2023-08-23 at 5 55 39 PM](https://github.com/huggingface/trl/assets/42274231/6661111b-038b-4cb8-9ae9-deb11bb8c3ad)
the traceback on colab says the same
