### ISSUE TITLE
PPOTrainer gives an error when using CUDA

### ISSUE THREAD

**Issue by backpropper** [huggingface/trl#680]
The step function in the PPOTrainer gives an error when using a GPU. Specifically, the `scores` tensor [here](https://github.com/huggingface/trl/blob/c115453fba481cc8a9212a4abd56904b08316913/trl/trainer/ppo_trainer.py#L593) is not loaded to the GPU which makes it a `cpu` tensor and gives an error when gathering all the stats [here](https://github.com/huggingface/trl/blob/c115453fba481cc8a9212a4abd56904b08316913/trl/trainer/ppo_trainer.py#L865).

**Comment by mnoukhov** [comment]
I haven't encountered this. Could be a recent regression?

Can you give basic steps to repro the error?
