### ISSUE TITLE
PPO training of LLaMA-13B on 24GB GPUs

### ISSUE THREAD

**Issue by ghtaro** [huggingface/trl#688]
Hi, 

I would like to do PPO training for LLaMA-13B in trl.
Computational resource-wise, I can use 1 GPU of 24GB or 4 GPUs of 24GB. 

I tried to run https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama/scripts/rl_training.py, but got CUDA OOM error in PPOTrainer.step() funciton.

I modified rl_training.py by applying 4-bit model loading like.
```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)
model = AutoModelForCausalLMWithValueHead.from_pretrained(
    config.model_name,
    quantization_config=bnb_config,
    trust_remote_code=script_args.trust_remote_code,
    peft_config=lora_config,
)
```

And my shell script is below.
```
%sh
cd <PATH>/trl/
accelerate launch --num_machines=1 --num_processes=1 \
examples/stack_llama/scripts/rl_training.py \
--log_with=mlflow \
--logging_dir=<LOG PATH> \
--model_name=meta-llama/Llama-2-13b-hf \
--reward_model_name=OpenAssistant/reward-model-deberta-v3-base \
--adafactor=False \
--tokenizer_name=meta-llama/Llama-2-13b-hf \
--save_freq=100 \
--steps 10 \
--output_max_length=128 \
--batch_size=1 \
--gradient_accumulation_steps=1 \
--batched_gen=True \
--ppo_epochs=4 \
--seed=0 \
--learning_rate=1.4e-5 \
--early_stopping=True \
--trust_remote_code True \
--run_name ppo_test \
--output_dir=<OUT PATH>
```

I also tried `--multi_gpu --num_processes=4`, but got CUDA OOM error again (My understanding is that it does DDP, so copying full model to 4GPUs).

Could you tell me if there are ways to run rl_training.py for 13B model with my computational resources?
(For example, deepspeed Zero 2 or 3(splitting full model into 4GPUs) is available in trl?)

**Comment by mnoukhov** [comment]
I don't think you'll be able to run this with your memory budget on a single GPU :/ I could be wrong. Maybe if you try using [multi-adapter](https://github.com/huggingface/trl/blob/main/examples/scripts/multi_adapter_rl.py) and train a new reward model instead of using the deberta one and go down to LLaMA 7B.

Or you can shard the model across your GPUs but that might be quite a bit slower

**Comment by ghtaro** [comment]
@mnoukhov Hi, thank you very much for your suggestions. I will have a look at multi-adapter.

On model sharding, do we have any sample code in PPO training?
As you said, it would be a lot slower, but I want to have an option to run larger LLM in my environment without error.

**Comment by ghtaro** [comment]
Actually, I was surprised that LLaMA2 13B (4-bit + LoRA) + deberta Reward model failed in PPO training due to CUDA OOM....

I am not very familiar with PPO algorithm, but I assumed that the algorithm consumes GPU memory like below.
If my understanding is wrong, please correct me.

- Active LLM:
  - Base model: 4-bit * 13B ~ 6.5GB
  - LoRA adapter: ~ roughly 1GB at most?
-  Reference LLM
  - we share Base model
- Value function model
  - we share Active LLM (If I understand correctly, AutoModelForCausalLM**WithValueHead** do a trick)
- Optimizer and Gradient
  - for LoRA ~ a few GB?
- Batched input and output
  - not so large I assume? (let's say **X** GB)
- deberta-v3-base reward model
  - ~0.15B params ~ 1GB at most

In total, I thought we need about 10+X GB and 24GB would be enough...

**Comment by younesbelkada** [comment]
Hi @ghtaro 

Note that one bottleneck usually is the hidden states size as they are still in half-precision which can blow up GPU memory, one thing you can tweak is the batch_size / gradient accumulation step to mitigate that. Where did it failed exactly during PPO optimization or during generation?

**Comment by ghtaro** [comment]
@younesbelkada Thank you very much for your valuable comments.

CUDA OOM happened in PPO optimization (step() function).

- batch_size=1
- gradient_accumulation_steps=1
- mini_batch_size=1

Sorry for my messy summary, but here are the GPU memory footprints.

- LLaMA2 13B 4-bit Loading: 8547/22731 (meaning 8.5GB used out of 22.7GB VRAM)
-  Init PPO Trainer
  -self.ref_model = self.accelerator.prepare(self.ref_model): **13921/22731** (5GB increase here for some reasons which I did not expected)
  -consume tiny bit gpu for all other procedure in init.
- Reward model loading: 14625/22731
- In 1-st epoch:
  -Response Generation:14989/22731
  - PPO Step:
    -After batched_forward_pass() function (no grad = no training): 11443/22731
    -In PPO Epoch loop
      - In batched_forward_pass() function (auto grad = training): 19389/22731
        - 8GB increase happens exactly in **model forward function** (model(**input_kwargs))
        - Given LoRA adapter is applied, number of trainable params is around 13M, so I do not understand why we need extra 8GB here... **Is this related your comment (the hidden states size as they are still in half-precision which can blow up GPU memory)?**
- In 2-nd epoch:
  -In PPO Epoch loop, CUDA OOM happens in model forward function (model(**input_kwargs)).

**Comment by younesbelkada** [comment]
Thanks for providing all these details,
Hmm the 8GB might be because of the intermediate hidden states. I would maybe also make sure the training of the adapters is done in mixed precision (you can select that when calling `accelerate config`). Another thing I would add is this flag: https://github.com/huggingface/trl/blob/main/trl/trainer/ppo_config.py#L146 since the first epoch worked successfully maybe you just need to empty the cuda cache to free memory and make sure the second epoch works fine

**Comment by ghtaro** [comment]
@younesbelkada Thanks, let me check those are correctly set in my code. Related to intermediate hidden states you said, can I set `gradient checkpointing` in rl_training.py? If I understand correctly, it will save GPU (we do not need to keep all the intermediate results in forward pass).

**Comment by Ali1858** [comment]
Hi

I am also getting OOM while doing PPO fine-tuning. I am fine-tuning the Llama-2-7B on A100 (40GB VRAM) and the reward model (also Llama-2-7B) is kept on a separate A100 (10GB VRAM) for inference. I have tried keeping batch_size, mini_batch_size, and gradient_accumulation all at 1, then also it's throwing OOM with a sudden spike in memory. 

Implementing the suggestion of gradient checkpointing throws an `AttributeError: 'AutoModelForCausalLMWithValueHead' object has no attribute 'is_peft_model'`. Can you tell me how you pass the Lora config and enable checkpointing?

Following code give me error:

```python
    lora_config = LoraConfig(
        r=64,
        lora_alpha=16,
        lora_dropout=0.1,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model_args = {
        "torch_dtype": dtype,
        "quantization_config": BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=dtype,
            bnb_4bit_use_double_quant=True,
            ),
        "cache_dir": CACHE_DIR,
        "device_map": device_map,
    }

    base_model =  transformers.AutoModelForCausalLM.from_pretrained(
        conf.model_name, trust_remote_code=True, **model_args
    )
    base_model.gradient_checkpointing_enable()

    base_model = AutoModelForCausalLMWithValueHead(base_model, trust_remote_code=True,peft_config= lora_config)
```

PPO training loop. 
Since the data loader set batch_size to `batch_size`, I am generating one response at a time to avoid OOM. 
```python
for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
        query_tensor = batch["input_ids"]
        
        # Initialize empty lists to store responses and rewards
        response_tensors = []
        responses = []
        rewards = []

        # Iterate through each query in the query_tensor
        for idx in range(len(query_tensor)):

            single_response_tensor = ppo_trainer.generate(
                [query_tensor[idx]],
                return_prompt=False,
                # length_sampler=512
                **generation_kwargs,
            )
            
            response = tokenizer.decode(single_response_tensor[0], skip_special_tokens=True)
            responses.append(response)

            # Prepare input for reward model
            text = batch["query"][idx] + response
            inputs = tokenizer(text, max_length=2048, padding=True, truncation=True, return_tensors="pt").to(base_reward_model.device)
            
            
            reward = compute_reward_score(inputs,base_reward_model,conf)
            reward = reward[0][0]

            # Append the generated response tensor and computed reward
            response_tensors.append(single_response_tensor[0])
            rewards.append(reward)
        
        # Convert lists to tensors
        # response_tensors = torch.cat(response_tensors, dim=0) 
        batch["response"] = responses
                
        #Run PPO step
        stats = ppo_trainer.step(query_tensor, response_tensors, rewards)

        rewards = [r.float() if r.dtype == torch.bfloat16 else r for r in rewards]
        if epoch%conf.log_step==0:
            ppo_trainer.log_stats(stats, batch, rewards)
        
        if epoch > 0 and epoch%conf.save_steps==0:
            ppo_trainer.save_pretrained(save_dir + f"/checkpoint_{epoch}")
```

Can you please tell me what I am doing wrong?

**Comment by mdabbah** [comment]
were you able to train with this memory budget?

also does any one have a guide on model sharing across gpus?

> make sure the training of the adapters is done in mixed precision (you can select that when calling accelerate config

can you elaborate on that?
