### ISSUE TITLE
A few questions on the function respond_to_batch()

### ISSUE THREAD

**Issue by w32zhong** [huggingface/trl#698]
I see the repo README uses the `respond_to_batch` function to obtain model responses, but this function does not have stop criteria, is this because we need to support batched inputs? And no stop criteria will be the easiest to implement?

Another question is, the `respond_to_batch` function does not use KV cache, is this because we want to generate complete gradients for KV during learning?

Both issues limit the speed of the function, and when model is far larger than the GPT2 used in the README example, it is hard to get RL working due to low efficiency.

**Comment by lvwerra** [comment]
The `respond_to_batch` function is deprecated and you should now use `PPOTrainer.generate` which uses the `generate` function of `transformers` under the hood.

**Comment by w32zhong** [comment]
I see. thanks for this information!
