### ISSUE TITLE
KL during Training

### ISSUE THREAD

**Issue by wanghao-007** [huggingface/trl#702]
I don't know why KL is always 0 during training, does anyone have this problem?

**Comment by sakinafatima** [comment]
Many issues with my KL value were resolved by setting the generation arguments. Check this thread.

Add warning when KL-divergence is negative · Issue #235 · huggingface/trl (github.com)

**Comment by lvwerra** [comment]
In addition to what @sakinafatima said, if the KL is strictly zero it means that the active and reference model are identical and so your active model is not learning anything.

**Comment by chenyang399** [comment]
i get the same problem, but my loss and rewards seems fine for me while kl=0
