### ISSUE TITLE
Docs list unsupported arguments for SFTTrainer

### ISSUE THREAD

**Issue by johnowhitaker** [huggingface/trl#714]
The docs (https://huggingface.co/docs/trl/sft_trainer) mention arguments to SFTTrainer like `torch_dtype`, for example [here](https://github.com/huggingface/trl/blob/main/docs/source/sft_trainer.mdx#L241) but this is not an [argument that SFTTrainer accepts](https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L99) and so you get an error:
`TypeError: SFTTrainer.__init__() got an unexpected keyword argument 'torch_dtype'`

I'm guessing the right way to pass this and other OG Trainer arguments like batch size, whether to use bf16 and so on is via the `args` (TrainingArguments)? Anyway, just flagging this since some of the examples in the docs won't work as currently written.

**Comment by younesbelkada** [comment]
Thanks a lot for poitning out @johnowhitaker 
#717 should update the SFTTrainer docs accordingly
