### ISSUE TITLE
PromptLearningConfig is not supported for PPO training

### ISSUE THREAD

**Issue by jonathanlimsc** [huggingface/trl#721]
I am trying to finetune a T5 model with prompt tuning (PEFT library), and do so using PPO (trl library) to see how an RL approach will affect performance.

However when I execute the code snippet below, I get an error "ValueError: PromptLearningConfig is not supported for PPO training". Will Prompt tuning be supported in the near future by the trl library? Any quick fix would be appreciated.

```
from trl import AutoModelForSeq2SeqLMWithValueHead, PPOConfig, PPOTrainer
from peft import PEFT_TYPE_TO_CONFIG_MAPPING
from peft.tuners.prompt_tuning import PromptTuningConfig

peft_config_dict = { 
    "task_type": "SEQ_2_SEQ_LM",
    "num_virtual_tokens": 10,
    "peft_type": "PROMPT_TUNING",
}

peft_config = PromptTuningConfig(**peft_config_dict)

model_name = "google/t5-small-lm-adapt"

model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(model_name, peft_config=peft_config)
```

**Comment by younesbelkada** [comment]
Hi @jonathanlimsc 
Thanks for the issue, please refer to my comment here: https://github.com/huggingface/trl/pull/500#issuecomment-1623623554 about why we cannot currently support Prompt Learning with PPO. Let me know if you feel that this is wrong
