### ISSUE TITLE
Struggling to fine-tune StackLlama with RLHF

### ISSUE THREAD

**Issue by BillChan226** [huggingface/trl#723]
I'm trying to reproduce the result of "fine-tuning StackLlama with RLHF" indicated in this [blog](https://huggingface.co/blog/stackllama). I didn't change any of the code, and follow the command prompt indicated in the [README file](https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama/scripts/README.md). It seems that I have successfully done SFT and reward model training and get expected performance as indicated in the blog. However, when I try to do RLHF upon these two models, **the reward seems to be going down**...

Here is the training log for about 800 steps of batch size 8 and PPO mini batchsize 1.
<img width="895" alt="image" src="https://github.com/huggingface/trl/assets/48212682/249e7f7b-ab54-4652-971f-e5dabd552f03">

The original blog trains on a huggingface cluster of 3 * 8 A100 80G GPU, but I don't have equivalent GPU sources, so I trained on 2 * A100 80G, which I think should be enough for most of the fine-tuning tasks.

The prompt code I used:
`accelerate launch --multi_gpu --num_machines 1  --num_processes 2 examples/stack_llama/scripts/rl_training.py --log_with=tensorboard --model_name=TRL/llama_SFT_model --reward_model_name=TRL/llama_reward_model --adafactor=False --tokenizer_name=meta-llama/llama-2-7b-hf --save_freq=100 --output_max_length=128 --batch_size=8 --gradient_accumulation_steps=8 --batched_gen=True --ppo_epochs=4 --seed=0 --learning_rate=1.4e-5 --early_stopping=True --output_dir=llama-se-rl-finetune-128-8-8-1.4e-5_adam`

Is it because the batchsize is two small for 2 GPUs (2*8), as compared to 3*8 GPUs (24*8)? Anyone might know what's happening? It takes me one whole day to train 800 steps, but the result is indeed somehow discouraging. I'd really appreciate any help.

**Comment by lvwerra** [comment]
For the batch size I would try to match it globally by setting gradient accumulation accordingly: `global_batch_size = num_gpus * batch_size * gradient_accumulation`. 

Have you tried with the SFT and RW models we trained? To exclude one source of issues.

**Comment by BillChan226** [comment]
> 

Thank you for answering my question.
According to your suggestion, now I'm trying to use the SFT and RW models that you already trained (found in [here](https://huggingface.co/trl-lib/llama-7b-se-rm-peft). However, this is only the Peft adapter model, that I believe we should first run 
`python examples/research_projects/stack_llama/scripts/merge_peft_adapter.py --adapter_model_name=trl-lib/llama-7b-se-peft --base_model_name=meta-llama/Llama-2-7b-hf --output_name=llama-se`
to get the merged SFT model and
`python examples/research_projects/stack_llama/scripts/merge_peft_adapter.py --adapter_model_name=trl-lib/llama-7b-se-rm-peft --base_model_name=/home/xyq/trl/llama-se --output_name=llama-se-rm` 
to get the RW model, whose base model here is the SFT model that I just got, rather than the pre-trained meta-llama/Llama-2-7b-hf. Is that correct?

And could you please elaborate on which argument does `global_batch_size` refer to? I couldn't find it in the config list.
In my case where I have two A100 80G, what would you suggest my `batch_size`, `mini_batch_size` and `gradient_accumulation_steps`be?

Thank you!

**Comment by lvwerra** [comment]
> whose base model here is the SFT model that I just got, rather than the pre-trained meta-llama/Llama-2-7b-hf. Is that correct?

yes!

> And could you please elaborate on which argument does global_batch_size refer to? I couldn't find it in the config list.
In my case where I have two A100 80G, what would you suggest my batch_size, mini_batch_size and gradient_accumulation_stepsbe?

There is no variable for `global_batch_size` - it's just the result of `num_gpus * batch_size * gradient_accumulation`. So you just need to adapt the `batch_size` and `gradient_accumulation` to match with your `num_gpus` the same product.

As an example: `--batch_size=2 --gradient_accumulation_steps=8` on 38 GPUs means the global batch size was 512 (2*8*38). If you want to get the same results with 2 GPUs you would need `--batch_size=2 --gradient_accumulation_steps=128`. The `batch_size` you can increase until you run out of memory and then the rest you can compensate with `gradient_accumulation_steps `. Hope that helps!
