### ISSUE TITLE
DPO training fails: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by LuJunru** [huggingface/trl#731]
Lora training with DPO on llama-2-7b-chat-hf meets following errors:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Here's my main function:
```
def main():
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()

    # load config and tokenziers
    config = LlamaConfig.from_pretrained(model_args.model_name_or_path)
    config.use_cache = False
    tokenizer = LlamaTokenizer.from_pretrained(model_args.model_name_or_path, truncation_side='left')

    # initialize modules
    model = LlamaForCausalLM.from_pretrained(model_args.model_name_or_path, config=config)

    # add pad token in tokenizer if needed
    if tokenizer.pad_token is None:
        tokenizer.add_special_tokens({"pad_token":"<pad>"})
        tokenizer.pad_token_id = 0

    # Setup seed
    set_seed(training_args.seed)
    embedding_size = model.get_input_embeddings().weight.shape[0]
    if len(tokenizer) > embedding_size:
        model.resize_token_embeddings(len(tokenizer))

    # Setup Trainer
    training_args = training_args.to_dict()
    training_args |= {'remove_unused_columns': False}
    training_args = TrainingArguments(**training_args)
    peft_config = LoraConfig(
        r=model_args.lora_r,
        lora_alpha=model_args.lora_alpha,
        lora_dropout=model_args.lora_dropout,
        target_modules=[
            "q_proj",
            "v_proj",
            "k_proj",
            "out_proj",
            "fc_in",
            "fc_out",
            "wte",
        ],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model_peft = get_peft_model(model, peft_config)
    trainer = DPOTrainer(
        model=model_peft,
        ref_model=None,
        beta=0.1, # DPO temprature
        train_dataset=prepared_dataset["train"],
        eval_dataset=prepared_dataset["eval"],
        tokenizer=tokenizer,
        args=training_args,
        peft_config=peft_config,
        max_length=data_args.model_max_length,
        max_prompt_length=int(data_args.model_max_length) * 3 // 4,
    )

    # Training
    train_result = trainer.train()
````

**Comment by younesbelkada** [comment]
Hi @LuJunru 
can you call `model.enable_input_require_grads()` right after the call `model = LlamaForCausalLM.from_pretrained(model_args.model_name_or_path, config=config)`. That method should make sure the inputs will have `requires_grad` set to `True` thus avoid your issue I believe

**Comment by LuJunru** [comment]
Hi @younesbelkada,

Thank you for the response. I've tried this, here's the new output:
```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 191 with name base_model.model.base_model.model.model.layers.31.self_attn.v_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
```

I think the issue may related to here: https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L358, where the basic frozen model are not correctly recalled.
```
        with torch.no_grad():
            if self.ref_model is None:
                with self.accelerator.unwrap_model(self.model).disable_adapter():
                    (
                        reference_chosen_logps,
                        reference_rejected_logps,
                        _,
                        _,
                    ) = self.concatenated_forward(self.model, batch)
            else:
                (
                    reference_chosen_logps,
                    reference_rejected_logps,
                    _,
                    _,
                ) = self.concatenated_forward(self.ref_model, batch)
```

By the way, my env:
```
accelerate 0.22.0
bitsandbytes 0.41.1
peft 0.5.0
trl 0.7.1
transformers 4.31.0
```

thanks,
Junru

**Comment by LuJunru** [comment]
> Hi @younesbelkada,
> 
> Thank you for the response. I've tried this, here's the new output:
> 
> ```
> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
> Parameter at index 191 with name base_model.model.base_model.model.model.layers.31.self_attn.v_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
> ```
> 
> I think the issue may related to here: https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L358, where the basic frozen model are not correctly recalled.
> 
> ```
>         with torch.no_grad():
>             if self.ref_model is None:
>                 with self.accelerator.unwrap_model(self.model).disable_adapter():
>                     (
>                         reference_chosen_logps,
>                         reference_rejected_logps,
>                         _,
>                         _,
>                     ) = self.concatenated_forward(self.model, batch)
>             else:
>                 (
>                     reference_chosen_logps,
>                     reference_rejected_logps,
>                     _,
>                     _,
>                 ) = self.concatenated_forward(self.ref_model, batch)
> ```
> 
> By the way, my env:
> 
> ```
> accelerate 0.22.0
> bitsandbytes 0.41.1
> peft 0.5.0
> trl 0.7.1
> transformers 4.31.0
> ```
> 
> thanks, Junru

Once I change ```self.concatenated_forward(self.model, batch)``` to ```self.concatenated_forward(self.accelerator.unwrap_model(self.model).disable_adapter(), batch)```, then the new error is ```TypeError: __call__() got an unexpected keyword argument 'attention_mask'```. My torch version is 2.0.1.

**Comment by TingchenFu** [comment]
Hi, I am using DPO to train llama-3-8b without a LoRA (full-parameter finetuning) and I also encountered with the problem. I call model.enable_input_require_grads() right after the initialization of model but the grad_norm becomes zero and the model is not updated. Do you have any idea on how to fix this? Thanks!
