### ISSUE TITLE
Prevent finetuned models from always generating endlessly

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/trl#734]
Hello!

I'm afraid I don't have a quick snippet for you to reproduce this, but I've noticed that various models that I've finetuned using SFT+RM+PPO & SFT+DPO endlessly generate texts until `max_new_tokens` is reached. This is quite frustrating as it always causes text to be cut off, and generally causes the generated text to be much longer than expected.

I'm wondering if you're familiar with this issue, and if you happen to know where the issue might lie? I.e. whether the model fails to train to follow the pattern well enough, or whether the generation configuration or tokenizer pad/eos tokens are set up incorrectly during inference.

To give an example, I have an instruction dataset where answers very consistently range between ~10 and ~15 tokens. Finetuning on this dataset with SFT and/or SFT+RM+PPO has resulted in models that generates 50 tokens if you set `max_new_tokens=50`.

I'm open to any advice.

- Tom Aarsen

**Comment by lvwerra** [comment]
Hi @tomaarsen, could this be related to #696? Are you training Llama models?

**Comment by tomaarsen** [comment]
That was indeed the primary model I was training with. It definitely could be related.

**Comment by tomaarsen** [comment]
I've resolved it using two changes:
* Add `add_eos_token=True` to the Tokenizer initialization. Not all tokenizers provide this, but if the tokenizer is fast, then you can usually do
   ```python
   tokenizer._tokenizer.post_processor = TemplateProcessing(
       single="$A <|endoftext|>",
       special_tokens=[("<|endoftext|>", 50256)],
   )
   ```
   to still place the EOS at the end if it's missing. This ensures that there's always an EOS.
* The next problem is that the EOS is often replaced with `-100` by the data collator. A simple workaround is to use a subclass of the Seq2Seq collator that creates labels by copying the `input_ids`:
   ```python
   class DataCollatorForSeq2SeqNoLabels(DataCollatorForSeq2Seq):
       def __call__(self, features, return_tensors=None):
           for feature in features:
               if "labels" not in feature:
                   feature["labels"] = feature["input_ids"].copy()
           return super().__call__(features, return_tensors=return_tensors)

   data_collator = DataCollatorForSeq2SeqNoLabels(tokenizer=tokenizer, model=model)
   ```
Afterwards, the model actually learns to stop 🎉 

### Before:
```
### Instruction: Who was Julius Caesar?

### Response in Emojis: 👨‍⚔️🗡️🇮�
```
```
### Instruction: What is the Coronavirus?

### Response in Emojis: 🦠🔬🌎😷���
```
```
### Instruction: What is the Cretaceous-Paleogene extinction event?

### Response in Emojis: 🌎⚰️🦕👉���
```
```
### Instruction: What will happen in 2070?

### Response in Emojis: 🌎🌍🏛️💥📜�
```
### After:
```
### Instruction: Who was Julius Caesar?

### Response in Emojis: 👨‍⚖️🗡️🇮🇹🏛️
```
```
### Instruction: What is the Coronavirus?

### Response in Emojis: 🦠🏛️💉
```
```
### Instruction: What is the Cretaceous-Paleogene extinction event?

### Response in Emojis: 🌎⚰️🦕🔭
```
```
### Instruction: What will happen in 2070?

### Response in Emojis: 🌎🌍🌏
```

I appreciate the reference to the issue @lvwerra.

- Tom Aarsen

**Comment by lvwerra** [comment]
Awesome, thanks a lot for the detailed investigation! 🔥
