### ISSUE TITLE
Bug in dpo_trainer.py, prediction_step function

### ISSUE THREAD

**Issue by Emperorizzis** [huggingface/trl#738]
I see the following code in dpo_trainer.py's prediction_step method:
```python
... ...
logits_dict = {
    "logits_test/chosen": metrics["logits_test/chosen"],
    "logits_test/rejected": metrics["logits_test/rejected"],
}
... ...
```
But the keys and values are defined in get_batch_metrics function:
```python
... ...
prefix = "eval_" if train_eval == "eval" else ""
metrics[f"{prefix}rewards/chosen"] = chosen_rewards.cpu().numpy().mean()
metrics[f"{prefix}rewards/rejected"] = rejected_rewards.cpu().numpy().mean()
metrics[f"{prefix}rewards/accuracies"] = reward_accuracies.cpu().numpy().mean()
metrics[f"{prefix}rewards/margins"] = (chosen_rewards - rejected_rewards).cpu().numpy().mean()
metrics[f"{prefix}logps/rejected"] = policy_rejected_logps.detach().cpu().numpy().mean()
metrics[f"{prefix}logps/chosen"] = policy_chosen_logps.detach().cpu().numpy().mean()
metrics[f"{prefix}logits/rejected"] = policy_rejected_logits.detach().cpu().numpy().mean()
metrics[f"{prefix}logits/chosen"] = policy_chosen_logits.detach().cpu().numpy().mean()
... ...
```

That is, the variable metrics doesn't have "logits_test/chosen"、"logits_test/rejected".

I have run this code. For transformers framework, if the compute_metrics method is not defined, prediction_loss_only will be set to True and errors will be ignored. But if prediction_loss_only is forced to False, an error is indeed occurred.
So should we use the keys defined in get_batch_metrics when constructing logits_dict?

**Comment by lvwerra** [comment]
Referring to @kashif for DPO related questions.

**Comment by kashif** [comment]
indeed @Emperorizzis looks like a typo bug let me double check and make a PR
