### ISSUE TITLE
[Feature] Enhancement for `save_pretrained()` Function in `PreTrainedModelWrapper`

### ISSUE THREAD

**Issue by ywangmy** [huggingface/trl#740]
Currently, the `save_pretrained()` function in `PreTrainedModelWrapper` (starting from this [line](https://github.com/huggingface/trl/blob/34e6948d459540a21f80c5be227fb4da039dd97a/trl/models/modeling_base.py#L401)):
1. only extracts `save_path` from `args`. However, it would be beneficial if it allows passing the path via the keyword argument `save_directory`, akin to `PreTrainedModel.save_pretrained`.
2. does not create the specified directory if it does not exist, while `PreTrainedModel.save_pretrained` performs this operation.

Hence, I propose implementing these functionalities to ensure alignment with the usage of `PreTrainedModel.save_pretrained`.

**Comment by younesbelkada** [comment]
Hi @ywangmy 
Thanks for these suggestions, they all make sense, would you be happy to take the lead on this? Otherwise I am happy to open a PR as well !

**Comment by ywangmy** [comment]
Thank you for your prompt response! As I am not a professional developer, it would be most effective for you to lead the implementation.

**Comment by younesbelkada** [comment]
No worries, assigned to issue to myself, will have a look when I will have some spare time :) !
