### ISSUE TITLE
[Feature] Integrate TRL with Flash Attention 1/2?

### ISSUE THREAD

**Issue by larekrow** [huggingface/trl#756]
Would like to reap the benefits of Flash Attention that has been [integrated in Hugging Face](https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/model#transformers.PreTrainedModel.to_bettertransformer) in TRL as well.

Seeing that `model.to_bettertransformer()` and `with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=False, enable_mem_efficient=False):` [both](https://huggingface.co/docs/transformers/en/perf_infer_gpu_one#decoder-models) [work](https://pytorch.org/blog/out-of-the-box-acceleration/) with regular Hugging Face trainers, it should not be a stretch for them to also work with TRL trainers. My current need is to use the `PPOTrainer`.

PR https://github.com/huggingface/transformers/pull/25598 is working on integrating Flash Attention 2, but I don't know if the same API will be recycled and used.

I lack in-depth understanding of both techniques, so I will not be able to contribute. Hopefully someone can take up this feature.

**Comment by LuJunru** [comment]
I think you can directly import bettertransformer to convert model before deliver it to trainer

**Comment by larekrow** [comment]
Silly me! Somehow I did not think of this solution 😅 Thanks @LuJunru!

I am still met with an error, but it does not seem like a TRL issue, so I'll close this for now.
