### ISSUE TITLE
Is it possible to pass an adapter to an SFTTrainer and continue training?

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/trl#786]
A peft_config can be passed in, but is it possible to pass in an adapter and train it further?

Perhaps the best way is to pre-load the adapter onto the base model and then pass that peft model into the trainer (and not specify peft_config)?

[Docs](https://huggingface.co/docs/trl/main/en/sft_trainer)

**Comment by younesbelkada** [comment]
Yes currently the way to perform this is to pass an already-loaded `PeftModel` to the SFTTrainer directly. 
I agree this is not very clear in the docs, I can work on that!
