### ISSUE TITLE
TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not list

### ISSUE THREAD

**Issue by raihan0824** [huggingface/trl#787]
I got an error while reproducing the `rl_training.py`

```
Traceback (most recent call last):
  File "/home/ai-lead/repository/trl-llama/rlhf.py", line 343, in <module>
    response_tensors = ppo_trainer.generate(
  File "/home/ai-lead/miniconda3/envs/trl-llama/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 446, in generate
    return self._generate_batched(
  File "/home/ai-lead/miniconda3/envs/trl-llama/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 492, in _generate_batched
    batch_mask = [torch.ones_like(element) for element in batch]
  File "/home/ai-lead/miniconda3/envs/trl-llama/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 492, in <listcomp>
    batch_mask = [torch.ones_like(element) for element in batch]
TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not list
```

the error is from this line:
```
    question_tensors = batch["input_ids"]
    response_tensors = ppo_trainer.generate(
        question_tensors,
        return_prompt=False,
        length_sampler=output_length_sampler,
        **generation_kwargs,
    )
```
it seems like the question_tensors should be tensor instead of list, but from the code, it's a list because its appended on the `build_dataset` function. Am I missing something here?

**Comment by lvwerra** [comment]
Can you provide the library versions you used and which script you ran with which parameters?

**Comment by gauss5930** [comment]
I am also experiencing the same situation with this error. How can I solve the problem?

**Comment by chenmoneygithub** [comment]
In case people bump into this in the future, here is what is happening:

For some reason if you use tokenizer with streaming dataset, i.e., `dataset.map(tokenizer(..., return_tensors="pt"))`, `return_tensors="pt"` part will be ignored. As a result, the tokenized batch will be a list of list, which cannot be used as the input of `ppo_trainer.generate`. To fix the issue, the simplest way is to cast each element to a Tensor explicitly:

```
inputs = [torch.Tensor(question_tensor).type(torch.int32) for question_tensor in question_tensors]
```
