### ISSUE TITLE
Why not average the log probs in DPO trainer?

### ISSUE THREAD

**Issue by dblakely** [huggingface/trl#789]
In the DPOTrainer the `_get_batch_logprobs` method takes a param called `average_log_prob`, which if enabled, lets us get back the averaged logprobs for the chosen and rejected sequences. If disabled, we get back the sum of the logprobs. But in the `DPOTrainer`, [it's hard-coded to False](https://github.com/huggingface/trl/blob/0a6c42c12c637bb7f28782fa72ec45dd64bce0bd/trl/trainer/dpo_trainer.py#L372). 

I was just wondering why this is the case. Couldn't this bias the model towards writing long sequences? Thanks for the help.

**Comment by younesbelkada** [comment]
Hi @dblakely , thanks, this is a good question
I personally don't have the answer, perhaps we should make that modulable but not sure. I would like to ask this question to @kashif and @natolambert, what do you think of having that parameter configurable?

**Comment by i4never** [comment]
My experience is training will collapse with average_log_prob.

**Comment by dblakely** [comment]
I tested it as well and am seeing the same thing - the model became pretty degenerative

**Comment by i4never** [comment]
Another thought. If you average logprob, each token contributes equally to the results. It's kind of sequence level instead of token level reward. If an answer wins, only some token are better.

**Comment by Shenzhi-Wang** [comment]
I have another possible explanation from math.

We understand that $\pi_\theta(y_w) = \pi_\theta(y_w^1) \pi_\theta(y_w^2 | y_w^1) \cdots \pi_\theta(y_w^n | y_w^1\cdots y_w^{n-1})$, where $y_w^i$ denotes the i-th token of $y_w$.

Consequently, $\pi_\theta(y_w | x) = \pi_\theta(x | y_w)\pi_\theta(y_w)/\pi_\theta(x) = \pi_\theta(y_w^1) \pi_\theta(y_w^2 | y_w^1) \cdots \pi_\theta(y_w^n | y_w^1\cdots y_w^{n-1}) / {\pi_\theta(x)}$.

Similarly, $\pi_\theta(y_l | x) = {\pi_\theta(x | y_l)\pi_\theta(y_l)} / {\pi_\theta(x)} = {\pi_\theta(y_l^1) \pi_\theta(y_l^2 | y_l^1) \cdots \pi_\theta(y_l^n | y_l^1\cdots y_l^{n-1})} / {\pi_\theta(x)}$.

Thus, $\log \pi_\theta(y_w | x) - \log \pi_\theta(y_l | x)$
$= \log \pi_\theta (x|y_w) + \sum_{i=1}^{n_{w}} \log \pi_\theta(y_w^i | y_w^1 \cdots y_w^{i-1}) - \log \pi_\theta (x|y_l) - \sum_{i=1}^{n_l} \log \pi_\theta(y_l^i | y_l^1 \cdots y_l^{i-1})$

Assuming $\log \pi_\theta (x|y_w) \approx \log \pi_\theta (x|y_l)$, the calculation in the code would be correct.

Even if the assumption $\log \pi_\theta (x|y_w) \approx \log \pi_\theta (x|y_l)$ is not made, the above derivation indicates that a sum of log probabilities is a more justifiable choice than an average of log probabilities.
