### ISSUE TITLE
Cannot import name 'RewardConfig' from 'trl'

### ISSUE THREAD

**Issue by medhanshrath-t** [huggingface/trl#791]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-7-89b17d9b2762>](https://localhost:8080/#) in <cell line: 19>()
     17 )
     18 from peft import PeftModel, LoraConfig, prepare_model_for_kbit_training, get_peft_model, TaskType
---> 19 from trl import (
     20     PPOTrainer,
     21     PPOConfig,

ImportError: cannot import name 'RewardConfig' from 'trl' (/usr/local/lib/python3.10/dist-packages/trl/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I am unable to import RewardConfig from neither trl nor trl.trainer.

**Comment by younesbelkada** [comment]
Hi @medhanshrath-t 
Can you try to install TRL from source?

```bash
pip install git+https://github.com/huggingface/trl
```

**Comment by medhanshrath-t** [comment]
It works when I install TRL from source, no error is thrown

**Comment by lvwerra** [comment]
Closing issue since solution seems to work.
