### ISSUE TITLE
PPOTrainer generate method does not take batched tensors as input 

### ISSUE THREAD

**Issue by EdoardoPona** [huggingface/trl#793]
The documentation claims that the first parameter of `PPOTrainer.generate` is `query_tensor (torch.LongTensor) — A tensor of shape (batch_size, seq_len) containing query tokens.`

However, it seems to me the function actually expects a `List[Tensor]`. 
Given the following code 
```python
batch_size = 32
config = PPOConfig(
    model_name='gpt2',
    steps=10,
    learning_rate=1.41e-5,
    batch_size=batch_size,
    remove_unused_columns=False,
    log_with=None,
)
ppo_trainer = PPOTrainer(
    config,
    model,
    model_ref,
    tokenizer,
)

txt_out_len = 8
generation_kwargs = {
    "min_length": txt_out_len,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
    "max_new_tokens": txt_out_len,
    "eos_token_id": tokenizer.eos_token_id,
}
```

the following fails:
```python
# inputs = dataset['input_ids'][:2]
inputs = torch.randint(0, 10, size=(batch_size, 16)).to(device)

print(inputs.shape)
resp = ppo_trainer.generate(
    inputs, **generation_kwargs
)
```
with error:
```
RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 0
```
inputs here is a Tensor of shape `[batch_size, seq_len]` as requested.

Converting the input to a List of Tensors, as in the following snippet is successful: 
```python
resp = ppo_trainer.generate(
    list(inputs), **generation_kwargs
)
```
However, this causes overhead, as the tensor has to be unpacked in a list, and most importantly, undoes any speed gains from batching. 

Upon further investigation, I noticed how the `PPOTrainer` `generate` method calls the underlying model's `generate` function:
```python
resp = ppo_trainer.accelerator.unwrap_model(ppo_trainer.model).generate(
    input_ids=inputs.unsqueeze(0), **generation_kwargs
)
```

notice the `.unsqueeze(0)` on the input. This assumes that input is in fact not batched, but just a tensor of shape `[,seq_len]`, which needs to be expanded since the model's `generate` correctly expects batched inputs. 
If we remove the `unsqueeze` operation, and call the following snippet 
```python
resp = ppo_trainer.accelerator.unwrap_model(ppo_trainer.model).generate(
    input_ids=inputs, **generation_kwargs
)
```
we get the expected output, with the correct input. 

Is this a bug in the implementation? Or is this intended for some reason, and the documentation isn't clear about it?

**Comment by younesbelkada** [comment]
Hi @EdoardoPona 
Thanks for raising this up, I think that there is a small typo indeed, it can accept either a list of tensors (in case of batched generation) or a tensor of a single dimension in case of non-batched generation
We had to come up with a custom implementation of batched generation as we need to properly deal with encoder-decoder model case, while padding correctly the input.

**Comment by EdoardoPona** [comment]
Thanks, got it! Does this affect performance compared to hypothetically feeding a single batched tensor to `model.generate`, assuming padding was already taken care of by the dataloader?
