### ISSUE TITLE
Cannot pass in a pretokenized dataset to SFTTrainer with error "text input must of type `str`"

### ISSUE THREAD

**Issue by pdeubel** [huggingface/trl#794]
Hi,

I tokenized my dataset and uploaded it to HF. When passing it into `SFTTrainer` I get the following error:

```
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example)
or `List[List[str]]` (batch of pretokenized examples).
```

Since my dataset is tokenized, all the data points are Integers and not Strings. Is it possible to use a pretokenized dataset at all? I could cast the datapoints to Strings (i.e. token `1234` will become `"1234"`). Would that mean that the strings will be tokenized again, thus creating garbage data? In the error message the term "pretokenized" is listed so I guess it is possible, but why are Integers not accepted?

Minimal example (cannot share my dataset so this uses a different dataset than mine, but still same issue):

```python
from transformers import AutoModelForCausalLM, AutoTokenizer, DataCollatorForLanguageModeling, TrainingArguments
from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("kennbyee25/distilroberta-base_tokenized_english_patents")  # dataset that has integers in column "input_ids"
train_dataset = dataset["train"]

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-gpt2")  # small test model
tokenizer.pad_token = tokenizer.eos_token

data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

model = AutoModelForCausalLM.from_pretrained(
    "sshleifer/tiny-gpt2"
)


output_dir = "./results"
per_device_train_batch_size = 1
gradient_accumulation_steps = 4
optim = "paged_adamw_32bit"
save_steps = 10
logging_steps = 10
learning_rate = 2e-4
max_grad_norm = 0.3
max_steps = 2 
warmup_ratio = 0.03
lr_scheduler_type = "constant"

training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=True,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=False,
    lr_scheduler_type=lr_scheduler_type,
)

max_seq_length = 512

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    data_collator=data_collator,
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    dataset_text_field="input_ids"
)
```

Btw: The ["standard" trainer from HuggingFace](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Trainer) accepts the pretokenized dataset, is that because `Trainer` requires tokenizing your data before passing it through and `SFTTrainer` requires non-tokenized data?

**Comment by lvwerra** [comment]
The `SFTTrainer` is a wrapper around the `Trainer` with the goal of making training on text easier, that's why tokenization is handled internally and you can't pass tokenized datasets. You have two options:

1.  Decode the tokenized dataset again and pass it to the `SFTTrainer`.
2. Use the `Trainer` instead.

Hope this helps!

**Comment by pdeubel** [comment]
Yes thanks that helps a lot and is good to know!

Although I would say it would make things easier if both non-tokenized and tokenized datasets can be passed in. Maybe checking the datatype (which is already done) could be used to distinguish between the two types of datasets but I am not sure if this would be a robust solution.

**Comment by lbaligand** [comment]
yes

**Comment by palash04** [comment]
Ideally I think there should be a way of letting know that we are passing tokenised dataset to the SFTTrainer. 
In my case, while I am performing multiple experiments with the same and huge amount of data (~10M samples of 2k seq_len), it  becomes cumbersome and time consuming on rented GPUs to wait for couple of hours first to tokenise and then train the model.

**Comment by amrothemich** [comment]
yes this and I need to be able to pass custom labels (some set to ignore index)

**Comment by satyaprakashdhfm** [comment]
same issue....good to listen you all
