### ISSUE TITLE
DPODataCollatorWithPadding why is the `eos_token_id` not accepted ?

### ISSUE THREAD

**Issue by AntoineBlanot** [huggingface/trl#806]
I am training a [llama2-chat](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) based model on conversations from [Anthropic's HH-RLHF](https://huggingface.co/datasets/Anthropic/hh-rlhf) dataset with the DPOTrainer and I am having issues with the default Data Collator.

In the DPODataCollatorWithPadding we can find this:
```
assert self.tokenizer.eos_token_id not in prompt_tokens["input_ids"], f"Prompt contains EOS token: {prompt}"

assert (self.tokenizer.eos_token_id not in chosen_tokens["input_ids"]), f"Chosen response contains EOS token: {chosen}"

assert (self.tokenizer.eos_token_id not in rejected_tokens["input_ids"]), f"Rejected response contains EOS token: {rejected}"
```

The llama2-chat models have a specific format which contains the eos_token. Thus when formatting the data we get an error in the DPODataCollatorWithPadding. I tried to look in the code and I do not understand why those assertions are made. I did not found a use of the eos_token in the DPOTrainer. 
My question is can I just remove those assertions without breaking the Trainer (especially how the loss is calculated)? 

Thank you for your replies.

For info, the Llama2-chat format taken from the model page: `To get the expected features and performance for the chat versions, a specific formatting needs to be followed, including the INST and <<SYS>> tags, BOS and EOS tokens, and the whitespaces and breaklines in between (we recommend calling strip() on inputs to avoid double-spaces).`

**Comment by kashif** [comment]
perhaps check the discussion in #741 and try with the dev version of TRL
