### ISSUE TITLE
Need guidance for PPO training

### ISSUE THREAD

**Issue by BaleChen** [huggingface/trl#810]
Hey, I have been working on the PPO stage for a while but haven't managed to train a Llama model with the trl library. I used mainly the code from stack_llama/scripts/rl_training.py and the dataset from Anthropic/hh-rlhf

In my case, the reward mean is just fluctuating around (-1, 0) and not going up. Objective KL is around 10 and does not change throughout training.

Has anyone successfully trained a model with the stack_llama scripts? If so, would you be so kind as to share the training logs and hyperparameters? Also, how many steps did you wait until you see some increase in the mean rewards? I'm also concerned if I'm simply not training long enough (i.e. It hasn't found a good action through exploration).

**Comment by lvwerra** [comment]
There are some training details for StackLlama in the [blog](https://huggingface.co/blog/stackllama), does that help?
