### ISSUE TITLE
Git repo error caused by PPOConfig

### ISSUE THREAD

**Issue by freQuensy23-coder** [huggingface/trl#812]
# Issue Description:

Upon initializing the PPOConfig in the code provided below, a fatal warning is displayed indicating that the Git repository is not invited. The warning message is as follows:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

# Code:

```python
from trl import PPOConfig

config = PPOConfig(
    model_name="meta-llama/Llama-2-7b-hf",
    learning_rate=1.41e-5,
    log_with="wandb",
)
```

# Expected Behavior:

The expected behavior is that the PPO config is initialized without any errors or warnings.

**Comment by lvwerra** [comment]
Can you provide the full stack trace? Do you know what throws the error? I don't know where a git repo is needed in ppo config.
