### ISSUE TITLE
DPO: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by vecorro** [huggingface/trl#814]
Hi,

When running script [dpo_llama2.py](https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py) from the TRL examples I get this error. Issue #801 describes the same problem and recommends a workaround  but it might be more appropriate to verify it that is an appropriate fix and if so, make it part of a new release. Thanks.

**Comment by lvwerra** [comment]
Thanks for reporting the issue, I reopened the original one and am closing this one so we only track it once.

**Comment by vecorro** [comment]
Thank you @lvwerra
