### ISSUE TITLE
`accelerate launch sftrain.py`, get error if `use_peft=True`

### ISSUE THREAD

**Issue by ma-ji** [huggingface/trl#815]
https://github.com/huggingface/trl/blob/7877e92991c242458ab31676a75846cedb985062/examples/scripts/sft_trainer.py#L52C6-L52C6

Tested okay with `use_peft=False`, but got error message below when ``use_peft=True`

> File "/home/xxx/.local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
> Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass 
> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
> Parameter at index 447 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

**Comment by younesbelkada** [comment]
Hi @ma-ji 
This should be now fixed if you use transformers + TRL + PEFT main branch, please refer to my comment here: https://github.com/huggingface/trl/issues/891#issuecomment-1787703591 - the fix is to use `use_reentrant=False` when callign gradient checkpointing

**Comment by ma-ji** [comment]
Thanks @younesbelkada for getting back! Will test it. For now I'm closing this issue.
