### ISSUE TITLE
Nightly `trl` QLoRA Training OOM

### ISSUE THREAD

**Issue by jeromeku** [huggingface/trl#818]
When running the Colab [notebook](https://colab.research.google.com/drive/1BiQiw31DT7-cDp1-0ySXvvhzqomTdI-o?usp=sharing) mentioned in this [blogpost](https://huggingface.co/blog/falcon#fine-tuning-with-peft) on finetuning Falcon on a single GPU, I get the dreaded `CUDA OOM Error` when using the latest (pre-release) version of `trl` (cloned the repo as of `9/25` and did an editable install).

Tried various combinations of stable / pre-release versions of `transformers`, `peft`, and `accelerate` with the latest **stable** release of `trl` and the notebook runs fine, no `OOM`.  However, when I switch to the **pre-release** `trl` per above, GPU memory spikes to `24+ Gb`.  Tried both in Colab environment (`T4`) as well as in a virtualenv using an `A5000` on a separate cloud service, same issue.

Curious what changes to pre-release `trl` could be leading to this error?

**Comment by younesbelkada** [comment]
Thanks very much @jeromeku for reporting

With https://github.com/huggingface/trl/pull/728 being merged one needs to explicitly pass `gradient_checkpointing=True` in the training arguments 

I have updated the notebook accordingly, please do let me know if this works

**Comment by Emerald01** [comment]
I pull the latest main branch and install locally, and tried to run this demo script for llama2
`accelerate launch --config_file multi_gpu.yaml sft_llama2.py`

I added gradient_checkpointing
```
training_args = TrainingArguments(
    output_dir=script_args.output_dir,
    per_device_train_batch_size=script_args.per_device_train_batch_size,
    gradient_accumulation_steps=script_args.gradient_accumulation_steps,
    gradient_checkpointing=True,
```

Somehow, this error is still here
```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 127 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

```

**Comment by younesbelkada** [comment]
@jeromeku @Emerald01 
A fix has been introduced recently on transformers, PEFT and trl main, please refer to my comment here: https://github.com/huggingface/trl/issues/891#issuecomment-1787703591 to solve the above bug. The trick is to use `use_reentrant=False` when calling gradient checkpointing

**Comment by wei-ann-Github** [comment]
Hi @younesbelkada , exactly where do I add `use_reentrant=False`? I am finetuning falcon-7b in 4bit, QLoRA, using SFTTrainer and TrainingArguments. I set the following
```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    load_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model = AutoModelForCausalLM.from_pretrained(
    'tiiuae/falcon-7b-instruct',
    device_map='auto',
    quantization_config=bnb_config,
)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model,)  # prepare_model_for_kbit_training, https://github.com/huggingface/peft/issues/742#issuecomment-1647829086

config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=[
            "query_key_value",
            "dense",
            "dense_h_to_4h",
            "dense_4h_to_h",
        ],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
    gradient_checkpointing_kwargs={"use_reentrant": False}
)

model.enable_input_require_grads()  # https://github.com/huggingface/peft/issues/137#issuecomment-1445912413
model = get_peft_model(model, config)
```
I explicitely set `gradient_checkpointing=False` in Training arguments, but still, I got `RuntimeError: Expected to mark a variable ready only once`

I've just installed the trl, transformers and peft library from source today.
