### ISSUE TITLE
Bugs in dpo evaluation during training

### ISSUE THREAD

**Issue by Emperorizzis** [huggingface/trl#819]
Hi, thanks the [previous bug fixed (#738)](https://github.com/huggingface/trl/issues/738) , but I still find some bugs in the dpo evaluation during training.

***First***, [the returned metrics in get_batch_metrics](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L383)
I see that you converted all the variables to numpy, but there are some tensor operation in the "prediction_step" function, at the same time, in the case of multiple gpu training, transformers needs to gather the data from each gpu together, these operation should be of tensor type.
So I think we should remove the ".numpy()" operation like this:
```python
... ...
metrics[f"{prefix}rewards/margins"] = (chosen_rewards - rejected_rewards).cpu().mean()
... ...
```

***Second***, [in the prediction_step](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L493)
I see the code in the prediction_step:
```python
... ...
logits = tuple(v for k, v in logits_dict.items() if k not in ignore_keys)
logits = torch.stack(logits).mean(axis=1)
labels = torch.zeros(logits.shape[0])
... ...
```
In the "get_batch_metrics" method, various are converted to the (n,) shape, so the ".stack().mean() "operation cannot be performed, and because of the data gather operation discussed above, I think we should do some changes like this:
```python
... ...
logits = tuple(v.unsqueeze(dim=0) for k, v in logits_dict.items() if k not in ignore_keys)
logits = torch.stack(logits).mean(axis=1).to(model.device)
labels = torch.zeros(logits.shape[0]).to(model.device)
... ...
```

***Third***, if the "compute_metrics" method is not passed in the transformers, the prediction_loss_only parameter will be forced to True, that is, we cannot use custom metrics to evaluate, but I see that the "[\_\_init\_\_](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L86)" method of the DPOTrainer class is not passed the compute_metrics parameter. So I think we should change it to:
```python
def __init__(
    self,
    ... ...
    disable_dropout: bool = True,
    compute_metrics = None
):
    ... ...
    super().__init__(
        ... ...,
        compute_metrics=compute_metrics
    )
    ... ...
```

**Comment by lvwerra** [comment]
Maybe again a question for @kashif :)

**Comment by kashif** [comment]
thanks @Emperorizzis for the report... I have to go over it to respond

**Comment by kashif** [comment]
can you kindly check @Emperorizzis  and let me know if it works for you?

**Comment by younesbelkada** [comment]
Closing as #822 got merged, feel free to re-open if you think that the issue has not been addressed

**Comment by Emperorizzis** [comment]
> can you kindly check @Emperorizzis and let me know if it works for you?

It seems there is no problem now, thank you ~
