### ISSUE TITLE
fail to import SFTTrainer due to ModuleNotFoundError: No module named 'transformers.integrations.deepspeed'; 'transformers.integrations' is not a package

### ISSUE THREAD

**Issue by ka4on** [huggingface/trl#852]
I try to import sfttrainer today but fail to do so because of the following error:
**ModuleNotFoundError: No module named 'transformers.integrations.deepspeed'; 'transformers.integrations' is not a package**
Can anyone help, many thanks!
![Screenshot 2023-10-10 175046](https://github.com/huggingface/trl/assets/91173533/16e26c54-269e-4344-b70d-7785b0bb0ed3)

**Comment by ka4on** [comment]
i use `!pip install -q -U git+https://github.com/lvwerra/trl.git` to install trl and import sfttrainer. Now i changed to `pip install trl` and now sfttrainer is imported successfully

**Comment by littletomatodonkey** [comment]
Hi, @ka4on i meet the same problem, i install trl, transformers and deepspeed as follows. But `transformers.integrations.deepspeed` can not be imported as before.

```bash
pip install trl
pip install transformers[deepspeed]
```

My releated libs' version are

```
transformers==4.33.1
deepspeed==0.10.1
trl==0.7.2.dev0
```

Could you please tell me about your version? Thanks!
