### ISSUE TITLE
DPO appears overwriting previous Lora layer from SFT in dpo_llama2.py?

### ISSUE THREAD

**Issue by Emerald01** [huggingface/trl#872]
Hello,

I am trying to confirm that the following script is running as we expect. And I am simply following the two step procedure for DPO training here: https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/README.md

I think for DPO part, loading model includes two steps:
(1) We load the model checkpoint after supervised FT with Lora layers
https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L127

It is like this:
```
sft_model = AutoPeftModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        load_in_4bit=True,
    )
```
(2) Then we call DPOTrainer, inside of it, we have this model adding a new peft configure to form a new model target
https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L138C13-L138C55

It is like this
```
dpo_model = get_peft_model(sft_model, peft_config)
```

The problem is that, if I understand right, this second `peft_config` seems overwriting the previous lora layer learned by the `sft_model`, if that is the case, it essentially suggests that the SFT step is overwritten by DPO Trainer constructor without any effect then. 

To confirm this, I simply do this

First, I load my SFT final_checkpoint
```
sft_model = AutoPeftModelForCausalLM.from_pretrained(
        "XXXXXXXX/sft/final_checkpoint/",
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        load_in_4bit=True,
    )
```
You can see that I am using a Lora layer with rank 4, everything is good
```
PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(32000, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): Linear4bit(
                in_features=4096, out_features=4096, bias=False
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=4, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=4, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
              (v_proj): Linear4bit(
                in_features=4096, out_features=4096, bias=False
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=4, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=4, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): LlamaMLP(
              (gate_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
              (up_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
              (down_proj): Linear4bit(in_features=11008, out_features=4096, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm()
            (post_attention_layernorm): LlamaRMSNorm()
          )
        )
        (norm): LlamaRMSNorm()
      )
      (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
    )
  )
)
```
I can print out a few simple statistics of any lora layer to see the numbers
```
In: sft_model.base_model.model.model.layers[5].self_attn.q_proj.lora_A.default.weight.mean()
Out: tensor(-0.0002, device='cuda:0')

In: sft_model.base_model.model.model.layers[5].self_attn.q_proj.lora_A.default.weight.std()
Out: tensor(0.0100, device='cuda:0')
```
Now if I follow what `DPOTrainer` is doing, let me provide a new lora configure of the same structure as we used for SFTTrainer (I try to include different target_modules, it does not change any picture as I confirmed). So for simplicity, I just provide the same lora configure as being used in SFTTrainer stage.
```
peft_config = LoraConfig(
        r=4,
        lora_alpha=16,
        lora_dropout=0.05,
        target_modules=[
            "q_proj",
            "v_proj",
        ],
        bias="none",
        task_type="CAUSAL_LM",
    )
```
And we call peft construction as DPOTrainer does
```
dpo_model = get_peft_model(sft_model, peft_config)
```
Now if you check the same layer, it gives
```
In: dpo_model.base_model.base_model.model.model.layers[5].self_attn.q_proj.lora_A.default.weight.mean()
Out: tensor(3.8875e-05, device='cuda:0', grad_fn=<MeanBackward0>)
In: dpo_model.base_model.base_model.model.model.layers[5].self_attn.q_proj.lora_A.default.weight.std()
Out: tensor(0.0090, device='cuda:0', grad_fn=<StdBackward0>)
```
It appears that the original lora layer of `sft_model` has been replaced with a newly initialized weights. My thought would be, it will either keep the same Lora layer untouched and learn on top of it. Do I misunderstand anything or miss any important step during constructing the model?

Otherwise SFT step is essentially doing nothing. I hope I am doing something wrong somewhere, otherwise, this is a big bug.

**Comment by lvwerra** [comment]
cc @younesbelkada and @kashif

**Comment by Emerald01** [comment]
Wondering if there is any conclusion here? Should I merge the lora weight to the base to form the new model and then add a new lora layer at DPO stage? Anyway, I think running the example directly could be problematic, just want to confirm. Thank you. @younesbelkada @kashif @lvwerra

**Comment by younesbelkada** [comment]
I think the issue has been fixed here: https://github.com/huggingface/trl/pull/934

**Comment by thusinh1969** [comment]
> Wondering if there is any conclusion here? Should I merge the lora weight to the base to form the new model and then add a new lora layer at DPO stage? Anyway, I think running the example directly could be problematic, just want to confirm. Thank you. @younesbelkada @kashif @lvwerra

Can someone plese confirm this question please. Shall I merged then **create a new LoRA for DPO** or should DPO be trained continuously **from latest Peft path to trained SFT** ?

Thanks,
Steve
