### ISSUE TITLE
SFT trainer progress bar is not indicative

### ISSUE THREAD

**Issue by abhishekkrthakur** [huggingface/trl#879]
Since we merge the rows in SFT Trainer but use the same total count, the progress bar is not indicative. This is what happens: 
https://discuss.huggingface.co/t/llama-2-meta-llama-llama-2-7b-hf-fine-tunning/58709/

**Comment by tcapelle** [comment]
I am curious why the epoch length is not reported correctly. Looking at `trainer.get_train_dataloader()` the length is correct, but the progress bar (and the scheduler value for instance) are wrongly computed.

**Comment by lvwerra** [comment]
Thanks for reporting, will look into this!

**Comment by abhishekkrthakur** [comment]
note: this only happens when packing=True

**Comment by KnutJaegersberg** [comment]
While it is a minor issue, it still exits. 
In low-code / no-code autotrain-advanced the progress bar is confusing. 

https://github.com/huggingface/autotrain-advanced/issues/450

**Comment by abhishekkrthakur** [comment]
it will still be confusing with just trl if packing is enabled :)

**Comment by lvwerra** [comment]
Note that we fixed this in #979 since this should now yield an accurate dataset length.

**Comment by abhishekkrthakur** [comment]
has it been released?

**Comment by lvwerra** [comment]
Yes, since [`v0.7.5`](https://github.com/huggingface/trl/releases/tag/v0.7.5) I believe.
