### ISSUE TITLE
DPO Data Collator  EOS token

### ISSUE THREAD

**Issue by pablovicente** [huggingface/trl#884]
`DPODataCollatorWithPadding` switches the attention mask to 0 for any preexisting eos token in the sequence and automatically adds one such token at the end of it. 
I believe the end user should be aware of this behavior either by either a warning message or in the documentation as it might lead to malformed samples. One example is when using the Llama chat template since it will add </s> on the user interaction. 

Here are the two parts of the `DPODataCollatorWithPadding` that I'm referring to: 

- https://github.com/huggingface/trl/blob/v0.7.2/trl/trainer/utils.py#L326
- https://github.com/huggingface/trl/blob/v0.7.2/trl/trainer/utils.py#L347

**Comment by kashif** [comment]
ah yes i'll add the appropriate documentation
