### ISSUE TITLE
PPOTrainer no train_dataset?

### ISSUE THREAD

**Issue by Boltzmachine** [huggingface/trl#886]
Following the official example:

```python
ppo_trainer = PPOTrainer(
    model=model,
    config=config,
    train_dataset=train_dataset,
    tokenizer=tokenizer,
)
```

But I found now PPOTrainer does not have the `train_dataset` argument, why is that? And why is there no `eval_dataset`?

**Comment by lvwerra** [comment]
The `PPOTrainer` uses the `step` method to train the model which is called iteratively and a batch is provided there directly.
