### ISSUE TITLE
Loss is 0 when policy (model) and reference models (model_ref) are the same

### ISSUE THREAD

**Issue by luffycodes** [huggingface/trl#892]
Hi,

I had a question about the implementation. When the [policy ](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L51)and [reference](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L53) models are the same, will the [loss ](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L355)not be 0?
https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L361
Or equation 7 in the [paper](https://arxiv.org/abs/2305.18290)?

Maybe I am missing something? Can you please help me understand it better?

In [tutorials](https://huggingface.co/blog/dpo-trl), since base model has a LoRA weights addon, I think this issue does not pop up.
But full fine-tuning of the base model will likely cause the issue.

**Comment by Santosh-Gupta** [comment]
Looks like we do the chosen rejection subtraction first

https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L355
