### ISSUE TITLE
Adding P3O trainer

### ISSUE THREAD

**Issue by gaetanlop** [huggingface/trl#905]
P3O (Pairwise Policy Optimization) is a recent paper from Berkeley: 

It introduces a new way to align LLMs to human preferences. The loss function is particularly cool as it directly operates on comparative rewards. They show that it outperforms Direct Preference Optimization and Proximal Policy Optimization in terms of KL-Reward trade-off and GPT-4 Evaluation.

![image](https://github.com/huggingface/trl/assets/66413927/400fe6ab-4ac4-4fed-a012-8742c0f643b3)

What do you think of adding it to trl? @younesbelkada @lvwerra 

If you are interested, I can work on this.

**Comment by lvwerra** [comment]
Looks interesting - would be a cool addition indeed!

**Comment by gaetanlop** [comment]
Cool, I will work on this soon

**Comment by lvwerra** [comment]
Let's keep it open :)
