### ISSUE TITLE
text dataset for SFTTrainer

### ISSUE THREAD

**Issue by piotr-sikora-v** [huggingface/trl#915]
I want to use SFFTrain from normal text files.
When I try:
```
dataset = load_dataset("text", data_files={"train": "to-train.txt", "test": "to-test.txt"})
```
And I think is loaded good... `dateset` dump:
```
DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 180
    })
    test: Dataset({
        features: ['text'],
        num_rows: 40
    })
})
```

Then when I run:
```
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    dataset_text_field="text",
)
```

I got error:
```
Traceback (most recent call last):
  File "/Users/xxxxx/zzzzz/train.py", line 88, in <module>
    trainer = SFTTrainer(
              ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 173, in __init__
    train_dataset = self._prepare_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 239, in _prepare_dataset
    return self._prepare_non_packed_dataloader(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 292, in _prepare_non_packed_dataloader
    tokenized_dataset = dataset.map(tokenize, batched=True, remove_columns=dataset.column_names)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasets/dataset_dict.py", line 851, in map
    {
  File "/opt/homebrew/lib/python3.11/site-packages/datasets/dataset_dict.py", line 852, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2991, in map
    raise ValueError(
ValueError: Column to remove ['train', 'test'] not in the dataset. Current columns in the dataset: ['text']
```

**Comment by piotr-sikora-v** [comment]
my small bad... sorry.

**Comment by lvwerra** [comment]
Should be the following, right?
```python
     train_dataset=dataset["train"],
```

**Comment by neurosageai** [comment]
> I want to use SFFTrain from normal text files. When I try:
> 
> ```
> dataset = load_dataset("text", data_files={"train": "to-train.txt", "test": "to-test.txt"})
> ```
> 
> And I think is loaded good... `dateset` dump:
> 
> ```
> DatasetDict({
>     train: Dataset({
>         features: ['text'],
>         num_rows: 180
>     })
>     test: Dataset({
>         features: ['text'],
>         num_rows: 40
>     })
> })
> ```
> 
> Then when I run:
> 
> ```
> trainer = SFTTrainer(
>     model=model,
>     train_dataset=dataset,
>     dataset_text_field="text",
> )
> ```
> 
> I got error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/xxxxx/zzzzz/train.py", line 88, in <module>
>     trainer = SFTTrainer(
>               ^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 173, in __init__
>     train_dataset = self._prepare_dataset(
>                     ^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 239, in _prepare_dataset
>     return self._prepare_non_packed_dataloader(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 292, in _prepare_non_packed_dataloader
>     tokenized_dataset = dataset.map(tokenize, batched=True, remove_columns=dataset.column_names)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/datasets/dataset_dict.py", line 851, in map
>     {
>   File "/opt/homebrew/lib/python3.11/site-packages/datasets/dataset_dict.py", line 852, in <dictcomp>
>     k: dataset.map(
>        ^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
>     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
>     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2991, in map
>     raise ValueError(
> ValueError: Column to remove ['train', 'test'] not in the dataset. Current columns in the dataset: ['text']
> ```

Did you find any solution to this, please let me know? I am stuck in the same place.

**Comment by G-M-twostay** [comment]
Any solution to this problem? I had the exact same issue.

**Comment by viktor436** [comment]
If you are doing something like: ''' train_dataset = load_dataset('json', data_files='./training_dataset.jsonl' , split='train') '''  or  ''' dataset = load_dataset("text", data_files={"train": "to-train.txt", "test": "to-test.txt"}) '''
after that you shoud do: ''' train_dataset1=train_dataset["train"] ''' and pass ''' train_dataset1 ''' to the SFTTrainer as @lvwerra  stated.

**Comment by difonjohaiv** [comment]
@viktor436 Thanks a lot！！！it works for me
