### ISSUE TITLE
Log Colored Sample to Ensure Collator Correctness

### ISSUE THREAD

**Issue by lapp0** [huggingface/trl#916]
It may be useful to have a helper function which pretty prints a collated sample. I want to ensure the ignore index is working properly with `DataCollatorForCompletionOnlyLM`, so I'm using this function to verify correctness:

```
def print_colored_collated_example(trainer):
    print("Training Sample. Red = ignored (not included in loss calculation)")

    def colorized_decode(tokenizer, input_ids, labels, ignore_index):
        RED = '\033[91m'
        ENDC = '\033[0m'
        words = []
        for token_id, label in zip(input_ids[0], labels[0]):  # Assuming 2D tensors
            decoded_token = tokenizer.decode(token_id, skip_special_tokens=True).strip()
            if label == ignore_index:
                words.append(f'{RED}{decoded_token}{ENDC}')
            else:
                words.append(decoded_token)
        return ' '.join(words)

    example = random.choice(trainer.train_dataset)
    collated_example = trainer.data_collator([example])
    colorized_example = colorized_decode(
        trainer.tokenizer,
        collated_example["input_ids"],
        collated_example["labels"],
        trainer.data_collator.ignore_index
    )
    print(colorized_example)
```

It prints a decoded training sample with every token labelled with the `ignore_index` in red. It has slightly incorrect behavior which should be adjusted (e.g. space joining tokens, using 'print' instead of `logger`), but it's a good starting point.

**Comment by lapp0** [comment]
Thanks for the response. If you think this is out of scope for trl that's understandable.

**Comment by lvwerra** [comment]
I think for now yes, but thanks a lot for outlining a solution, I am sure it will be helpful for others, too!
