### ISSUE TITLE
Using TRL with locally installed models and datasets.

### ISSUE THREAD

**Issue by NickWithBotronics** [huggingface/trl#917]
I tried to use use a local file directory with trl and I get invalid hugging face repo error, is it possible to use locally installed models without having to upload to hugging face and redownload it, or having to use the cache directory? When I was testing it, It even loaded the model fully then told me the repo is invalid.

**Comment by lvwerra** [comment]
It should be possible to load local models, we do this quite often. Can you send the code and exact error message?

**Comment by NickWithBotronics** [comment]
Thank you for the response! I couldn't find any example of it in the Hugging face documentation, or in the example scripts, so I did the best I could, now that you tell me it's possible it's extremally likely I messed up in editing this script I found. 

`from datasets import load_dataset
from trl import SFTTrainer
import transformers
import os

dataset = load_dataset("C:/Users/PC/Documents/text-generation-webui/training/SentimentPrice.json", split="train")

model = transformers.AutoModelForCausalLM.from_pretrained("C:/Users/PC/Documents/text-generation-webui/models/Mistral-Narwhal")
tokenizer = transformers.AutoTokenizer.from_pretrained("C:/User/PC/Documents/text-generation-webui/models/Mistral-Narwhal")

def formatting_prompts_func(examples):
    output_text = []
    for i in range(len(examples["instruction"])):
        instruction = examples["instruction"][i]
        input_text = examples["input"][i]
        response = examples["output"][i]

        if len(input_text) >= 2:
            text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
            
            ### Instruction:
            {instruction}
            
            ### Input:
            {input_text}
            
            ### Response:
            {response}
            '''
        else:
            text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
            
            ### Instruction:
            {instruction}
            
            ### Response:
            {response}
            '''
        output_text.append(text)

    return output_text

trainer = SFTTrainer(
    model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_prompts_func,
    max_seq_length=256,
    packing=False,
    load_in_4bit=True,
    use_flash_attention_2=True,
    neftune_noise_alpha=5,
)

trainer.train()`

Sorry to bother with another question, but I was curious as how NEFT could effect text completion for raw pretraining, is that currently possible with TRL? I only saw mention of SFT, DPO, PPO, reward modeling, and i never saw an example with a large raw dataset.

**Comment by lvwerra** [comment]
I am assuming the error occurs at:
```python
model = transformers.AutoModelForCausalLM.from_pretrained("C:/Users/PC/Documents/text-generation-webui/models/Mistral-Narwhal")
tokenizer = transformers.AutoTokenizer.from_pretrained("C:/User/PC/Documents/text-generation-webui/models/Mistral-Narwhal")
```

Can you post the full stack trace? If that's the case I would open an issue in `transformers` since this is not really a TRL issue then.

Regarding NEFTTune: no, haven't seen people using it for pretraining. It looks a bit like a regularization strategy for the small/noisy instruction datasets.

**Comment by NickWithBotronics** [comment]
I tried multiple versions of the script by editing the one line that gives the error, and i was incorrect the model does not load, just acts like the dataset had loaded.

C:\Users\PC\Desktop\alpaca-qlora-main>py C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py
bin C:\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Python311\Lib\site-packages\trl\trainer\ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
                              ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py", line 6, in <module>
    dataset = load_dataset('json', data_files="C:/Users/PC/Documents/text-generation-webui/training/SentimentPrice.json", split="train", name="SentimentPrice")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

C:\Users\PC\Desktop\alpaca-qlora-main>py C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py
bin C:\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Python311\Lib\site-packages\trl\trainer\ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
                              ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py", line 6, in <module>
    dataset = load_dataset('json', data_files="C:/Users/PC/Documents/text-generation-webui/training/SentimentPrice.json", split="train", name="SentimentPrice")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

C:\Users\PC\Desktop\alpaca-qlora-main>py C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py
bin C:\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Python311\Lib\site-packages\trl\trainer\ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
                              ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py", line 6, in <module>
    dataset = load_dataset('json', data_files="C:/Users/PC/Documents/text-generation-webui/training/SentimentPrice.json", split="train", name="SentimentPrice.json")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

C:\Users\PC\Desktop\alpaca-qlora-main>py C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py
bin C:\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Python311\Lib\site-packages\trl\trainer\ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
                              ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py", line 6, in <module>
    dataset = load_dataset('json', data_files="C:/Users/PC/Documents/text-generation-webui/training/SentimentPrice.json", split="train")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\datasets\load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "C:\Python311\Lib\site-packages\datasets\builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

C:\Users\PC\Desktop\alpaca-qlora-main>py C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py
  File "C:\Users\PC\Desktop\alpaca-qlora-main\MistralFinetuneSFT1.py", line 6
    dataset = load_dataset('json', data_files="C:\Users\PC\Documents\text-generation-webui\training\SentimentPrice.json", split="train")

^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

C:\Users\PC\Desktop\alpaca-qlora-main>

**Comment by lvwerra** [comment]
So it looks like your problem is loading the dataset, not the model, right?
