### ISSUE TITLE
neftune_noise_alpha support removed from SFTTrainer ?

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [huggingface/trl#922]
Please advice.

**Comment by younesbelkada** [comment]
Hi @PrithivirajDamodaran 
Thanks for the issue, neftune is still in SFTTrainer, check out this relevant section of the documentation: https://huggingface.co/docs/trl/main/en/sft_trainer#enhance-models-performances-using-neftune - if you want to use it you need to build TRL from source.

```bash
pip install git+https://github.com/huggingface/trl
```
