### ISSUE TITLE
dpo_llama2.py: peft on top of peft?

### ISSUE THREAD

**Issue by ZHZisZZ** [huggingface/trl#926]
https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L127
https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L186

It looks like the model for DPO training is a PeftModel built upon another PeftModel without weight merging. Is this expected? 

```
(Pdb) PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): PeftModelForCausalLM(
      (base_model): LoraModel(
        (model): LlamaForCausalLM(
          (model): LlamaModel(
            (embed_tokens): Embedding(32000, 4096)
            (layers): ModuleList(
            ......
```

**Comment by lvwerra** [comment]
cc @kashif @younesbelkada

**Comment by younesbelkada** [comment]
Hi @ZHZisZZ 
Indeed this is not expected, all instances of `AutoPeftModelForCausalLM` should be in fact `AutoModelForCausalLM` here. I think what happened is that we first fine-tuned with SFT + PEFT and directly loaded that un-merged peft model for DPO and attached new adapters on top of it.

**Comment by younesbelkada** [comment]
Just made #924 that should fix the issue

**Comment by ZHZisZZ** [comment]
https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/README.md
BTW, I think the README.md for llama2 finetuning should also be updated. 
`accelerate launch examples/stack_llama_2/scripts/dpo_llama2.py --model_name_or_path="sft/final_checkpoint" --output_dir="dpo"`
->
`accelerate launch examples/stack_llama_2/scripts/dpo_llama2.py --model_name_or_path="sft/final_merged_checkpoint" --output_dir="dpo"`
