### ISSUE TITLE
fine tune zephyar with large dataset.

### ISSUE THREAD

**Issue by imrankh46** [huggingface/trl#936]
hi, i am try to SFT( fine tune ) zephyar model with ultrachat200k dataset. but it show cuda out of memory issues.
how to load dataset with streaming and prepare for training for each chank? 
here is the code.

**Comment by lvwerra** [comment]
What kind of GPU are you using for training? If you get Cuda OOM issues then the dataset is not the issue. With `datasets` it should be memory mapped anyway so mostly use storage rather than CPU memory. Can you try reducing the `per_device_train_batch_size=1`?
