### ISSUE TITLE
API - Unconsistant API for `formatting_func` between packed and not packed

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/trl#944]
Currently users need to provide different `formatting_func` depending on if the dataset is `packing=True` or no. In the first case users can pass a method that takes a dict as input and return a simple string, for the non `packing` case users need to write a method that takes a dict and returns a list - API-wise this is very confusing

cc @lvwerra

**Comment by Oxi84** [comment]
what is a packed dataset?

**Comment by younesbelkada** [comment]
Sorry for the confusion, I meant `packing=True` for `packed`. Just changed the description a bit
