### ISSUE TITLE
DPO for T5 problem , error:AttributeError: 'tuple' object has no attribute 'logits'

### ISSUE THREAD

**Issue by Oxi84** [huggingface/trl#947]
I am using official example (https://huggingface.co/blog/dpo-trl) to optimize T5 using DP0. Dataset  format is the same but I still get error: 'tuple' object has no attribute 'logits' 

here is the code. Sorry I have no idea how to format the code. The code button does now work well.

01) Install everything

    
    !pip install transformers --quiet
    !pip install pandas nltk sentencepiece --quiet
    !pip install datasets
    !pip install evaluate
    !pip install rouge_score
    !pip install trl
    from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForSeq2SeqLM, GenerationConfig
    from datasets import load_dataset
    from trl import PPOTrainer, PPOConfig, AutoModelForSeq2SeqLMWithValueHead
    from trl import create_reference_model
    import torch
    import evaluate
    import numpy as np
    import pandas as pd

02) Load model (I am using this paraphrasing model as an example)

    model_name = "humarin/chatgpt_paraphraser_on_T5_base"
    model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(
        model_name, # location of saved SFT model
        low_cpu_mem_usage=True,
        torch_dtype=torch.float32,
        load_in_4bit=False,
        is_trainable=True
    )
    
    model_ref = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(
        model_name,  # same model as the main one
        low_cpu_mem_usage=True,
        torch_dtype=torch.float32,
        load_in_4bit=False
    )

03) Load and process dataset (I am using dataset used to train this paraphrasing model as an example)
   
      def return_prompt_and_responses(samples): #-> Dict[str, str, str]:
        return {
            "prompt": [
                "paraphrase: " + atext
                for atext in samples["text"]
            ],
            "chosen": [
                apara[0]
                for apara in samples["paraphrases"]
            ],
            "rejected": [
                aline
                for aline in samples["text"]
            ]       
        }
    
    dataset = load_dataset(
        "humarin/chatgpt-paraphrases",
        split="train[:1%]",
    )
    
    original_columns = dataset.column_names
    
    dataset = dataset.map(
        return_prompt_and_responses,
        batched=True,
        remove_columns=original_columns
    )
    
04) Train the model
    
    from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments,TrainingArguments
    from trl import DPOTrainer, AutoModelForSeq2SeqLMWithValueHead
    tokenizer = AutoTokenizer.from_pretrained("humarin/chatgpt_paraphraser_on_T5_base")
    output_dir="dpo_model"
    
    training_args = Seq2SeqTrainingArguments(
        output_dir="11",
        learning_rate=3e-4,
        num_train_epochs=1,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        gradient_accumulation_steps=2,
    
    )
    
    dpo_trainer = DPOTrainer(
        model,
        model_ref,
        args=training_args,
        beta=0.1,
        train_dataset=dataset,
        #eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        #peft_config=peft_config,
    )
    
    dpo_trainer.train()
    dpo_trainer.save_model(output_dir)

So the error I get is: **(AttributeError: 'tuple' object has no attribute 'logits')**

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In[20], line 31
         19 #from trl import DPOTrainer, AutoModelForSeq2SeqLMWithValueHead
         20 dpo_trainer = DPOTrainer(
         21     model,
         22     model_ref,
       (...)
         28     #peft_config=peft_config,
         29 )
    ---> 31 dpo_trainer.train()
         32 dpo_trainer.save_model(output_dir)
    
    File /usr/local/lib/python3.10/dist-packages/transformers/trainer.py:1555, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
       1553         hf_hub_utils.enable_progress_bars()
       1554 else:
    -> 1555     return inner_training_loop(
       1556         args=args,
       1557         resume_from_checkpoint=resume_from_checkpoint,
       1558         trial=trial,
       1559         ignore_keys_for_eval=ignore_keys_for_eval,
       1560     )
    
    File /usr/local/lib/python3.10/dist-packages/transformers/trainer.py:1860, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
       1857     self.control = self.callback_handler.on_step_begin(args, self.state, self.control)
       1859 with self.accelerator.accumulate(model):
    -> 1860     tr_loss_step = self.training_step(model, inputs)
       1862 if (
       1863     args.logging_nan_inf_filter
       1864     and not is_torch_tpu_available()
       1865     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
       1866 ):
       1867     # if loss is nan or inf simply add the average of previous logged losses
       1868     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)
    
    File /usr/local/lib/python3.10/dist-packages/transformers/trainer.py:2725, in Trainer.training_step(self, model, inputs)
       2722     return loss_mb.reduce_mean().detach().to(self.args.device)
       2724 with self.compute_loss_context_manager():
    -> 2725     loss = self.compute_loss(model, inputs)
       2727 if self.args.n_gpu > 1:
       2728     loss = loss.mean()  # mean() to average on multi-gpu parallel training
    
    File /usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py:500, in DPOTrainer.compute_loss(self, model, inputs, return_outputs)
        495 if not self.use_dpo_data_collator:
        496     warnings.warn(
        497         "compute_loss is only implemented for DPODataCollatorWithPadding, and you passed a datacollator that is different than "
        498         "DPODataCollatorWithPadding - you might see unexpected behavior. Alternatively, you can implement your own prediction_step method if you are using a custom data collator"
        499     )
    --> 500 loss, metrics = self.get_batch_metrics(model, inputs, train_eval="train")
        502 # force log the metrics
        503 if self.accelerator.is_main_process:
    
    File /usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py:451, in DPOTrainer.get_batch_metrics(self, model, batch, train_eval)
        443 """Compute the DPO loss and other metrics for the given batch of inputs for train or test."""
        444 metrics = {}
        446 (
        447     policy_chosen_logps,
        448     policy_rejected_logps,
        449     policy_chosen_logits,
        450     policy_rejected_logits,
    --> 451 ) = self.concatenated_forward(model, batch)
        452 with torch.no_grad():
        453     if self.ref_model is None:
    
    File /usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_trainer.py:421, in DPOTrainer.concatenated_forward(self, model, batch)
        407 len_chosen = batch["chosen_labels"].shape[0]
        409 model_kwargs = (
        410     {
        411         "labels": concatenated_batch["concatenated_labels"],
       (...)
        415     else {}
        416 )
        417 all_logits = model(
        418     concatenated_batch["concatenated_input_ids"],
        419     attention_mask=concatenated_batch["concatenated_attention_mask"],
        420     **model_kwargs,
    --> 421 ).logits.to(torch.float32)
        423 all_logps = self._get_batch_logps(
        424     all_logits,
        425     concatenated_batch["concatenated_labels"],
        426     average_log_prob=False,
        427 )
        429 chosen_logps = all_logps[:len_chosen]
    
    AttributeError: 'tuple' object has no attribute 'logits'

   ---------------------------------------------------------------------------

@younesbelkada

**Comment by younesbelkada** [comment]
hi @Oxi84 
which version of TRL are you using?

**Comment by Oxi84** [comment]
Latest one. I installed using:

!pip install transformers
!pip install trl

**Comment by younesbelkada** [comment]
Hmm T5 models should be supported for DPO since this PR: https://github.com/huggingface/trl/pull/586 
And we do have tests that correctly test DPO correctness for T5 models: https://github.com/huggingface/trl/blob/main/tests/test_dpo_trainer.py#L78 
Can you double check your TRL version?

```python
>>> import trl
>>> trl.__version__
'0.7.3.dev0'
```

**Comment by Oxi84** [comment]
@younesbelkada

I get trl version: 0.7.2.

Do you any complete example with T5? I was not to find any. Just a few with PPO.

**Comment by Oxi84** [comment]
This is dataset, does not work even with one line so this is not a problem with padding: 

Dataset({
    features: ['chosen', 'rejected', 'prompt'],
    num_rows: 1
})

**Comment by AkashGhosh** [comment]
Same issue,with BART is the issue fixed or anyone  have any solution to this?

**Comment by AkashGhosh** [comment]
Anyone did any model training with BART/T5 with DPO?

**Comment by AkashGhosh** [comment]
@lvwerra  can you please check

**Comment by AkashGhosh** [comment]
@younesbelkada  can you please check,this problem still exists

**Comment by AkashGhosh** [comment]
@Oxi84 is the problem solved at your end?

**Comment by Devy99** [comment]
@Antimony5292 did you try DPO with T5? I found issues in using it ( look at issue #1025 ) ... Do you think that I can fix with this solution?

**Comment by Antimony5292** [comment]
> @Antimony5292 did you try DPO with T5? I has problems in using it ( look at issue #1025 ) ... Do you think that I can fix with this solution?

I've only tested it on the MarianMT, but I think it works just as well on the T5, so you might try it!
