### ISSUE TITLE
DPO Full Fine-tuned Model Too Slow

### ISSUE THREAD

**Issue by kangqi-ni** [huggingface/trl#950]
I have used DPO to fine-tune a vicuna v1.3 based model in bf16 precision without using LoRA. 

However, the fine-tuned model became extremely slow in inference.

This is my inference code:
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    load_in_8bit=False,
    low_cpu_mem_usage=True,
    device_map="auto",
    cache_dir=cache_dir
)
inputs = tokenizer(prompt, return_tensors="pt", return_token_type_ids=False, add_special_tokens=False, truncation=False).to(model.device)

tokens = model.generate(
    **inputs,
    min_new_tokens=2,
    max_new_tokens=2048,
    do_sample=False,
    num_beams=2,
    temperature=float(0.3),
    repetition_penalty=float(1.2),
    renormalize_logits=True,
)[0]
print("Done generating")

tokens = tokens[inputs["input_ids"].shape[1]:]
response = tokenizer.decode(tokens, skip_special_tokens=True)

The model.generate() line takes forever to run. No process seems to be stuck. All CPU and GPU look fine. 
Has anyone run into the same issue? This issue would disappear if I fine-tune using LoRA though.

**Comment by sworddish** [comment]
Yes, I met the same problem, thought it should be the device automap related problem, must be bug somewhere

**Comment by lvwerra** [comment]
Is the issue that you are generating 2048 tokens? can you benchmark against the model before and report input/output lengths? maybe there is just no EOS token generated.

**Comment by alex-ht** [comment]
I experience the opposite situation where EOS often appears too early...

**Comment by raghavgarg97** [comment]
+1 I am experiencing the same issue

**Comment by huiyeruzhou** [comment]
I compare DPO with SFT and log their time spent in inner methods of Trainer. It seems that both DPO and SFT will spend about 30s in  Trainer.training_step (2048 max tokens, 7B codellama, 2*80G A100, deepspeed stage3). However, the VRAM comsumed by ref_model will lead to a maximum batch_size=2 and it is 32 for SFT.
In fact, DPO allow us to compute ref_logps in advance to avoid loading a ref_model:
```
        # if reference_chosen_logps and reference_rejected_logps in batch use them, otherwise use the reference model
        if "reference_chosen_logps" in batch and "reference_rejected_logps" in batch:
            reference_chosen_logps = batch["reference_chosen_logps"]
            reference_rejected_logps = batch["reference_rejected_logps"]
```
If we use DPOTrainer.concatenated_forward mannually for datasets using a batched map, we will be able to save VRAM to use a much larger batch_size.
