### ISSUE TITLE
[DPO] should we refactor to be more in line with Trainer?

### ISSUE THREAD

**Issue by mnoukhov** [huggingface/trl#952]
@kashif is there a reason why the DPO trainer has such a strange setup using `store_metrics` to forcibly store metrics during the prediction step and then delete them whenever `log` is called?  This feels quite brittle and from what I've seen, the regular `Trainer` uses a different setup. `Trainer.evaluate` and `predict` generally returns the metrics and uses `compute_metrics` to calculate things.

Would it make sense to refactor to be more in line with this?

TODO
- change to logging with `compute_metrics` #954 
- make eval use eval_dataloader instead of random batches
- switch to `Seq2SeqTrainer` so we can use `predict_with_generate` instead of `generate_during_eval`

**Comment by mnoukhov** [comment]
I'll get on it and start a draft

**Comment by mnoukhov** [comment]
Still being addressed in a follow-up to #954

**Comment by mnoukhov** [comment]
Still being worked on

**Comment by younesbelkada** [comment]
@mnoukhov let us know with @lvwerra @kashif if you need any help !
