### ISSUE TITLE
[BUG] Gather Stat is not working for DeepSpeed?

### ISSUE THREAD

**Issue by allanj** [huggingface/trl#960]
I guess the issue is mainly caused by this line:

https://github.com/huggingface/trl/blob/6ff0fac2c118250e1a14a0a793e96c5c3f654885/trl/trainer/ppo_trainer.py#L333

The `self.accelerator.distributed_type` is `DEEPSPEED` when I use DeepSpeed Zero stage 2 with `accelerate`.

It works when I change this line to
```python3
self.is_distributed = self.accelerator.distributed_type == "MULTI_GPU"  or self.accelerator.distributed_type == "DEEPSPEED"
```
But I think, to make this more general, we can try something like

```python3
self.is_distributed = self.accelerator.num_process > 1
```

Any suggestions?

**Comment by seanexp** [comment]
looks like a valid fix to me! 👍

**Comment by allanj** [comment]
maybe I will try to make a pull request for this. Also, I feel like there are some redundant for loop that we can avoid in the code

**Comment by younesbelkada** [comment]
Hi everyone, yes this looks like a reasonable change, would you be happy to open a quick PR for it?

**Comment by allanj** [comment]
> Hi everyone, yes this looks like a reasonable change, would you be happy to open a quick PR for it?

I have created the simple PR fix. Please help review: https://github.com/huggingface/trl/pull/997
