### ISSUE TITLE
Report a Small Bug in the Example

### ISSUE THREAD

**Issue by ghzhang233** [huggingface/trl#961]
https://github.com/huggingface/trl/blob/8e9cae8072714cea06bb39e57c692df86b6e2153/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L153C2-L153C2

This line seems a little bit buggy. In my opinion, here one should filter the data samples based on the number of tokens rather than the number of characters. So I would suggest the following modification:

```Python
    def _get_len(x):
        return len(tokenizer(x, return_tensors="pt").input_ids[0])

    # 2. Load the Stack-exchange paired dataset
    train_dataset = get_stack_exchange_paired(data_dir="data/rl", sanity_check=script_args.sanity_check)
    train_dataset = train_dataset.filter(
        lambda x: _get_len(x["prompt"]) + _get_len(x["chosen"]) <= config.max_length
                  and _get_len(x["prompt"]) + _get_len(x["rejected"]) <= config.max_length
    )

    # 3. Load evaluation dataset
    eval_dataset = get_stack_exchange_paired(data_dir="data/evaluation", sanity_check=script_args.sanity_check)
    eval_dataset = eval_dataset.filter(
        lambda x: _get_len(x["prompt"]) + _get_len(x["chosen"]) <= config.max_length
                  and _get_len(x["prompt"]) + _get_len(x["rejected"]) <= config.max_length
    )
```

**Comment by lvwerra** [comment]
I think this is mainly a pragmatic approach since we want to avoid tokenizing the dataset in advance (thus tokenizing it twice effectively) and keeping the code simple. Indeed it's not perfect but usually you can assume a character to token ratio between 3-4.
