### ISSUE TITLE
PPO llama2 7B causing CUDA out of memory OOM

### ISSUE THREAD

**Issue by harrison4ride** [huggingface/trl#963]
Library versions:
```
trl v0.7.2
Accelerate : 0.24.1
```
Problem:
I have 8 GPUs, each one has memory 49152MiB. The `ppo_trainer.step` causes a CUDA memory usage spirk and then CUDA out of memory. But during ppo_trainer.generate the memory usage only takes 10413MiB / 49152MiB. I have tried almost all methods I can think of(using flash attention, small batch size and mini batch size. etc), but I didn't fix it.

My configuration and code:

```
ppo_config: PPOConfig = field(
        default_factory=lambda: PPOConfig(
            steps=10,
            model_name="meta-llama/Llama-2-7b-chat-hf",
            query_dataset=None,
            reward_model=None,
            learning_rate=1e-5,
            log_with=None,
            mini_batch_size=1,
            batch_size=1,
            gradient_accumulation_steps=1,
            early_stopping=False,
            target_kl=0.1,
            kl_penalty="kl",
            ppo_epochs=4,
            seed=0,
            init_kl_coef=0.2,  # Initial KL coefficient.
            adap_kl_ctrl=True,  # Whether to adapt KL control.
            use_score_scaling=False,
            use_score_norm=False,
            score_clip=None,
            optimize_cuda_cache=True,
        )
    )
    peft_config: Optional[LoraConfig] = field(
        default_factory=lambda: LoraConfig(
            r=64,
            lora_alpha=16,
            lora_dropout=0.1,
            bias="none",
            target_modules=[
                "q_proj",
                "down_proj",
                "gate_proj",
                "o_proj",
                "k_proj",
                "v_proj",
                "up_proj",
            ],
            task_type="CAUSAL_LM",
        ),
    )
    trust_remote_code: bool = field(
        default=True, metadata={"help": "Enable `trust_remote_code`"}
    )

tokenizer = AutoTokenizer.from_pretrained(args.ppo_config.model_name, use_fast=True)
tokenizer.pad_token_id = tokenizer.eos_token_id
dataset = build_dataset(tokenizer)

# set seed before initializing value head for deterministic eval
set_seed(args.ppo_config.seed)

# Build the model.
peft_config = args.peft_config
ref_model = None
# Copy the model to each device
device_map = {"": Accelerator().local_process_index}

model = AutoModelForCausalLMWithValueHead.from_pretrained(
    args.ppo_config.model_name,
    trust_remote_code=args.trust_remote_code,
    device_map=device_map,
    peft_config=peft_config,
    load_in_4bit=True,
    torch_dtype=torch.bfloat16,
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    ),
    # use_flash_attention_2=True, Unable to use this feature in current GPU
)
# Whether or not the model should use the past last key/values attentions (if applicable to the model) to speed up decoding.
model.config.use_cache = False
model.config.pretraining_tp = 1
model.gradient_checkpointing_enable()

# We then build the PPOTrainer, passing the model, the reference model, the tokenizer
ppo_trainer = PPOTrainer(
    args.ppo_config,
    model,
    ref_model,
    tokenizer,
    dataset=dataset,
    data_collator=collator,
)
# Define the arguments to pass to the `generate` function.
generation_kwargs = {
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    "pad_token_id": tokenizer.pad_token_id,
}
torch.backends.cuda.sdp_kernel(
    enable_flash=True, enable_math=False, enable_mem_efficient=False
)
for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
    query_tensors = batch["input_ids"]
    print("Start generate")
    # ppo_trainer.accelerator.unwrap_model(model).gradient_checkpointing_disable()
    response_tensors = ppo_trainer.generate(
        query_tensors,
        return_prompt=False,
        # generate_ref_response=False,
        **generation_kwargs,
    )
    print("End generate")
    # ppo_trainer.accelerator.unwrap_model(model).gradient_checkpointing_enable()
    batch["response"] = tokenizer.batch_decode(
        response_tensors, skip_special_tokens=True
    )

    rewards = [torch.tensor(1.0) for i in batch["response"]]

    # Run PPO step
    stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
    ppo_trainer.log_stats(stats, batch, rewards)
    print("Step " + str(epoch) + " finished")
    torch.cuda.empty_cache()

ppo_trainer.save_pretrained(output_dir)
```

**Comment by harrison4ride** [comment]
addition info: GPU takes less util uses more memory.
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 8000                Off | 00000000:1A:00.0 Off |                  Off |
| 34%   38C    P2              90W / 260W |  44559MiB / 49152MiB |     29%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000                Off | 00000000:1C:00.0 Off |                  Off |
| 33%   38C    P2              97W / 260W |  44263MiB / 49152MiB |     35%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Quadro RTX 8000                Off | 00000000:1D:00.0 Off |                  Off |
| 33%   37C    P2              98W / 260W |  44263MiB / 49152MiB |     33%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Quadro RTX 8000                Off | 00000000:1E:00.0 Off |                  Off |
| 33%   42C    P2             117W / 260W |  10389MiB / 49152MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  Quadro RTX 8000                Off | 00000000:3D:00.0 Off |                  Off |
| 33%   40C    P2             106W / 260W |  10389MiB / 49152MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  Quadro RTX 8000                Off | 00000000:3F:00.0 Off |                  Off |
| 33%   40C    P2             111W / 260W |  10413MiB / 49152MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   6  Quadro RTX 8000                Off | 00000000:40:00.0 Off |                  Off |
| 33%   44C    P2             113W / 260W |  10413MiB / 49152MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   7  Quadro RTX 8000                Off | 00000000:41:00.0 Off |                  Off |
| 33%   42C    P2             113W / 260W |  10389MiB / 49152MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by paraGONG** [comment]
Hello, I met the same problem. I load 3 llama 7b on an A100 80G, causing CUDA out of memory. It happened during ppo_trainer.step(). I tried lora and zero but still didn‘t work. Have you solved the problem?Is there any way to save menory?

**Comment by harrison4ride** [comment]
> Hello, I met the same problem. I load 3 llama 7b on an A100 80G, causing CUDA out of memory. It happened during ppo_trainer.step(). I tried lora and zero but still didn‘t work. Have you solved the problem?Is there any way to save menory?

Yes, you can try to reduce the max text length during build dataset.
