### ISSUE TITLE
How does PPO's batch_size affect training? bsz bigger is better or smaller is better?

### ISSUE THREAD

**Issue by noanti** [huggingface/trl#964]
The default value of PPOconfig.batch_size is 265,is it ok to decrease bsz to 1?

**Comment by noanti** [comment]
@lvwerra Thanks for reply! If I set mini_batch=batch_size，and set epoch=1，then it will be totally On-Policy, right？the pg_loss will  always equal advantage？
Is there a problem doing this？
![image](https://github.com/huggingface/trl/assets/6761874/277ea5ad-8081-44b3-9762-91da873deef8)

**Comment by lvwerra** [comment]
Yes, I think you are right!
