### ISSUE TITLE
Batch generation differs from single-instance generation for encoder-decoder models

### ISSUE THREAD

**Issue by imgremlin** [huggingface/trl#975]
I found that batch generation differs from single-instance generation for encoder-decoder models. However, it works for decoder-only models. Here is a reproducible example:
```
import torch
from transformers import AutoTokenizer
from trl import AutoModelForSeq2SeqLMWithValueHead, PPOConfig, PPOTrainer

MODEL = "facebook/bart-base"
device = torch.device('cuda:0')

model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(MODEL).to(device)
tokenizer = AutoTokenizer.from_pretrained(MODEL)

prompts = ['How old is George Bush?', 'What color is the sun?']
prompts_encoded = [tokenizer.encode(i, return_tensors='pt').squeeze().to(device) for i in prompts]
print("prompts_encoded:", prompts_encoded)

config = PPOConfig(batch_size=2)
ppo_trainer = PPOTrainer(config=config, model=model, tokenizer=tokenizer)

batch_generation = ppo_trainer.generate(prompts_encoded, return_prompt=False)
print("batch_generation:", batch_generation)

single_generation = [ppo_trainer.generate(prompt, return_prompt=False) for prompt in prompts_encoded]
print("single_generation:", single_generation)
```
Output:

> prompts_encoded: [tensor([   0, 6179,  793,   16, 1655, 3516,  116,    2], device='cuda:0'), tensor([   0, 2264, 3195,   16,    5, 3778,  116,    2], device='cuda:0')]
> batch_generation: [tensor([2], device='cuda:0'), tensor([2], device='cuda:0')]
> single_generation: [tensor([[   2,    0, 6179,  793,   16, 1655, 3516,  116,    2]], device='cuda:0'), tensor([[   2,    0, 2264, 3195,   16,    5, 3778,  116,    2]], device='cuda:0')]

My libraries:
- torch==2.0.0
- transformers==4.27.4
- trl==0.7.4

**Comment by younesbelkada** [comment]
Hi @imgremlin 
Thanks for the issue, do you face the same issue when using `AutoModelForSeq2SeqLM` from transformers? Not sure it is an issue related with TRL but rather an issue with transformers. Also can you try with transformers==4.35.0 ?

**Comment by imgremlin** [comment]
Yes, it works on the later version. I'm using now '4.36.0.dev0'. Thanks!

**Comment by younesbelkada** [comment]
Awesome ! Closing the issue - thanks for double checking

**Comment by VenkteshV** [comment]
I am facing the same issue with transformers 4.36.2
