### ISSUE TITLE
Guidance with the correct format of the validation dataset 

### ISSUE THREAD

**Issue by Sosycs** [huggingface/trl#981]
Hello every one,

I am in the process of fine-tuning Llama2 using SFT trainer and quantization using Lora.
my dataset is composed of questions structured like:
`<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> Context: Abrasion is another type of mechanical weathering. With abrasion, one rock bumps against another rock. Gravity causes abrasion as a rock tumbles down a slope. Moving water causes abrasion it moves rocks so that they bump against one another (Figure 9.3). Strong winds cause abrasion by blasting sand against rock surfaces. Finally, the ice in glaciers cause abrasion. Pieces of rock embedded in ice at the bottom of a glacier scrape against the rock below. If you have ever collected beach glass or pebbles from a stream, you have witnessed the work of abrasion. Question: Gravity causes erosion by all of the following except Options:(A) glaciers (B) moving air (C) flowing water (D) mass movement Answer: [/INST]`

and the a column 'label' represent the ground truth.
my questions is in my code:
```
trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
)
```

do I provide the "label" column to the model for the validation dataset?
or do I leave it empty? if that so then how can I access the predictions of the validation set of my model?

**Comment by BayesRulez** [comment]
Hi @Sosycs,

Fine-tuning these LLMs is not like training a supervised machine learning model where you have some inputs and a target to compare your prediction with.  Decoder-only transformers like LLaMA2 are simply predicting the next token in a sequence.  

When you are fine-tuning these models, you hand them a complete sequence.  The trainer steps through your input, handing the model them a single extra token at a time and requesting prediction for the next token.  The training loss is calculated across the totality of all predictions vs. the actual next tokens.

What this means for your example is that you need to compile both your questions and your answers into a single string.  You could do it like this:

```
template = """<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> Context: {question} Answer: {answer}[/INST]"""
question = "Abrasion is another type of mechanical weathering..."
answer = "D" # I hope...
prompt = template.replace("{question}", question).replace("{answer}", answer)
```

It's worth noting that it's pretty inefficient to fine-tune a model by scoring it's predictions across the entire prompt.  You don't really care about teaching it that "weathering" is likely to follow "mechanical".  You care much more that it learns to produce "D" (assuming the answer is D...), given the question.

Take a look at the use of the `DataCollatorForCompletionOnlyLM` function here: https://huggingface.co/docs/trl/sft_trainer

It enables you to use only the predictions for tokens that appear to the _right_ of the `response_template` parameter in the trainer's gradient update step.  This is a much more efficient way of getting better, task-specific performance quickly.

Best of luck!

**Comment by Sosycs** [comment]
I am familiar with providing the answer separately and computing the loss depending on the predicted values. But I am currently using what you suggested @BayesRulez. 
In my case this is the instruction structure:
`<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> 
Context: Abrasion is another type of mechanical weathering. With abrasion, one rock bumps against another rock. Gravity causes abrasion as a rock tumbles down a slope. Moving water causes abrasion it moves rocks so that they bump against one another (Figure 9.3). Strong winds cause abrasion by blasting sand against rock surfaces. 
Question: Gravity causes erosion by all of the following except 
Options:(A) glaciers (B) moving air (C) flowing water (D) mass movement 
Answer: [/INST] D </s>`

Do I provide the context, question and options as an instruction_template? 

`
instruction_template = "</SYS>>\n\n Context:"
response_template = "Answer: [/INST]"
collator = DataCollatorForCompletionOnlyLM(instruction_template=instruction_template, response_template=response_template, tokenizer=tokenizer, mlm=False)`
OR
`
response_template = "Answer: [/INST]"
collator = DataCollatorForCompletionOnlyLM(response_template=response_template, tokenizer=tokenizer, mlm=False)
`

**Comment by Sosycs** [comment]
I have tried multiple response templates but always get the error:
`RuntimeError: Could not find response key [835, 4007, 22137, 29901] in token IDs tensor([ 1, 835, ...])`

@BayesRulez Can you please guide me to the correct one?

**Comment by BayesRulez** [comment]
Hi @Sosycs,

I literally just had the same problem when using the Mistral tokenizer and somebody here was kind enough to point out why.

The reason for the error you're seeing is explained [here](https://huggingface.co/docs/trl/sft_trainer#using-tokenids-directly-for-responsetemplate
).

To respond to both of your questions above at the same time, your code should look as follows:

```
response_template = "Answer: [/INST]"

# Work-around for context-sensitive tokenizers
response_template_tokenized = tokenizer.encode(f"\n{response_template}, add_special_tokens=False)[2:]

collator = DataCollatorForCompletionOnlyLM(response_template=response_template_tokenized , tokenizer=tokenizer)
```

Note that you'll only need to use the work-around for context-sensitive tokenizers.  LLaMA and Mistral both use them.  I'm not sure if any other tokenizers do (Mistral was the first I came across).

Hope that helps.

**Comment by Sosycs** [comment]
> Hi @Sosycs,
> 
> I literally just had the same problem when using the Mistral tokenizer and somebody here was kind enough to point out why.
> 
> The reason for the error you're seeing is explained [here](https://huggingface.co/docs/trl/sft_trainer#using-tokenids-directly-for-responsetemplate).
> 
> To respond to both of your questions above at the same time, your code should look as follows:
> 
> ```
> response_template = "Answer: [/INST]"
> 
> # Work-around for context-sensitive tokenizers
> response_template_tokenized = tokenizer.encode(f"\n{response_template}, add_special_tokens=False)[2:]
> 
> collator = DataCollatorForCompletionOnlyLM(response_template=response_template_tokenized , tokenizer=tokenizer)
> ```
> 
> Note that you'll only need to use the work-around for context-sensitive tokenizers. LLaMA and Mistral both use them. I'm not sure if any other tokenizers do (Mistral was the first I came across).
> 
> Hope that helps.

Thank you very much. I have tried this solution in [huggingface](https://huggingface.co/docs/trl/sft_trainer#using-tokenids-directly-for-responsetemplate) but I must have missed something as I used "\nAnswer: [/INST]"

So I tried your exact code and got: 
`TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
`

and according to [this](https://stackoverflow.com/questions/63517293/valueerror-textencodeinput-must-be-uniontextinputsequence-tupleinputsequence/63870843#63870843) it has something with a None value present but I don't know where this come from in my case.

**Comment by Sosycs** [comment]
Hello @younesbelkada,
Thank you very much.
I have tried both "\n[/INST]" and "[/INST]" but with the same error:
`RuntimeError: Could not find response key [835, 4007, 22137, 29901] in token IDs tensor([ 1, 835, ...])
`
regarding the stackoverflow link, I appreciate the link! 
as I understand that this error comes from a value None that presented in my text column but I don't have this value.

**Comment by Sosycs** [comment]
@BayesRulez @younesbelkada  Shall I remove all the white spaces in my dataset in "Answer: [/INST] "?

**Comment by younesbelkada** [comment]
Hi @Sosycs 
Can you try to pass directly the ids instead ? Something like:

```python
response_template_with_context = "[/INST]"  # We added context here: "\n". This is enough for this tokenizer
response_template_ids = tokenizer.encode(response_template_with_context, add_special_tokens=False)

data_collator = DataCollatorForCompletionOnlyLM(response_template_ids, tokenizer=tokenizer)
```

**Comment by Sosycs** [comment]
My format function:

`
import pandas as pd
def format(sample):
    s_prompt="Please select the correct answer from the given multiple Options based on the given Context:"
    system_prompt = f"<s>[INST] <<SYS>>\n {s_prompt}\n<</SYS>>\n\n"
    user_prompt = f"{sample['prompt']}"
    model_answer = f"\n[/INST] {sample['response']} </s>"

    # join all the parts together
    prompt = "".join([i for i in [system_prompt, user_prompt, model_answer] if i is not None])
    return prompt
`

My Code:
`
local_rank = -1
per_device_train_batch_size = 4
per_device_eval_batch_size = 4
gradient_accumulation_steps = 1
learning_rate = 2e-4
max_grad_norm = 0.3
weight_decay = 0.001
lora_alpha = 16
lora_dropout = 0.1
lora_r = 64
max_seq_length = None
model_name = "meta-llama/Llama-2-7b-hf"
use_4bit = True
use_nested_quant = False
bnb_4bit_compute_dtype = "float16"
bnb_4bit_quant_type = "nf4"
num_train_epochs = 2
fp16 = False
bf16 = False
packing = False
gradient_checkpointing = True
optim = "paged_adamw_32bit"
lr_scheduler_type = "cosine"
max_steps = -1
warmup_ratio = 0.03
group_by_length = True
save_steps = 10
logging_steps = 1
output_dir = "/content/drive/MyDrive/finetuning_results"
device_map = {"": 0}
report_to = "tensorboard"
tb_log_dir = "/content/drive/MyDrive/finetuning_results/logs"

def load_model(model_name):
    # Load tokenizer and model with QLoRA configuration
    compute_dtype = getattr(torch, bnb_4bit_compute_dtype)

    # Quantization Config
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=use_4bit,
        bnb_4bit_quant_type=bnb_4bit_quant_type,
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=use_nested_quant,
    )

    if compute_dtype == torch.float16 and use_4bit:
        major, _ = torch.cuda.get_device_capability()
        if major >= 8:
            print("=" * 80)
            print("Your GPU supports bfloat16, you can accelerate training with the argument --bf16")
            print("=" * 80)

    # Model
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map=device_map,
        quantization_config=bnb_config
    )
    model.config.use_cache = False
    model.config.pretraining_tp = 1
    # Load LoRA configuration
    peft_config = LoraConfig(
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        r=lora_r,
        bias="none",
        task_type="CAUSAL_LM",
    )
    # Load Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    return model, tokenizer, peft_config

model, tokenizer, peft_config = load_model(model_name)

training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="tensorboard"
)

response_template_with_context = "[/INST]"  # We added context here: "\n". This is enough for this tokenizer
response_template_ids = tokenizer.encode(response_template_with_context, add_special_tokens=False)
collator = DataCollatorForCompletionOnlyLM(response_template=response_template_tokenized , tokenizer=tokenizer)

# Trainer (Fine-tuning)
trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=packing,
    data_collator=collator,
)

trainer.train()
trainer.model.save_pretrained(output_dir)
`

**Comment by Sosycs** [comment]
> Hi @Sosycs Can you try to pass directly the ids instead ? Something like:
> 
> ```python
> response_template_with_context = "[/INST]"  # We added context here: "\n". This is enough for this tokenizer
> response_template_ids = tokenizer.encode(response_template_with_context, add_special_tokens=False)
> 
> data_collator = DataCollatorForCompletionOnlyLM(response_template_ids, tokenizer=tokenizer)
> ```

    423         )
    424 
--> 425         encodings = self._tokenizer.encode_batch(
    426             batch_text_or_text_pairs,
    427             add_special_tokens=add_special_tokens,

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

**Comment by Sosycs** [comment]
> @Sosycs can you paste your full code here? The following works for me:
> 
> ```
> response_template = "Answer: [/INST]"
> 
> # Work-around for context-sensitive tokenizers
> response_template_tokenized = tokenizer.encode(f"\n{response_template}", add_special_tokens=False)[2:]
> 
> collator = DataCollatorForCompletionOnlyLM(response_template=response_template_tokenized , tokenizer=tokenizer)
> 
> example = """<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> 
> Context: Abrasion is another type of mechanical weathering. With abrasion, one rock bumps against another rock. Gravity causes abrasion as a rock tumbles down a slope. Moving water causes abrasion it moves rocks so that they bump against one another (Figure 9.3). Strong winds cause abrasion by blasting sand against rock surfaces. Finally, the ice in glaciers cause abrasion. Pieces of rock embedded in ice at the bottom of a glacier scrape against the rock below. If you have ever collected beach glass or pebbles from a stream, you have witnessed the work of abrasion. 
> Question: Gravity causes erosion by all of the following except Options:(A) glaciers (B) moving air (C) flowing water (D) mass movement 
> Answer: [/INST]"""
> 
> example_encoded = tokenizer(example)
> 
> collator([example_encoded])
> ```
> 
> It returns a dict of `{input_ids, attention_mask, labels}`. You should see that every value o the `labels` tensor is -100 (cross-entropy loss will ignore this value) except for the final one, which encodes the "D".

When I run your code I get: 
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

**Comment by Sosycs** [comment]
> @Sosycs can you paste your full code here? The following works for me:
> 
> ```
> response_template = "Answer: [/INST]"
> 
> # Work-around for context-sensitive tokenizers
> response_template_tokenized = tokenizer.encode(f"\n{response_template}", add_special_tokens=False)[2:]
> 
> collator = DataCollatorForCompletionOnlyLM(response_template=response_template_tokenized , tokenizer=tokenizer)
> 
> example = """<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> 
> Context: Abrasion is another type of mechanical weathering. With abrasion, one rock bumps against another rock. Gravity causes abrasion as a rock tumbles down a slope. Moving water causes abrasion it moves rocks so that they bump against one another (Figure 9.3). Strong winds cause abrasion by blasting sand against rock surfaces. Finally, the ice in glaciers cause abrasion. Pieces of rock embedded in ice at the bottom of a glacier scrape against the rock below. If you have ever collected beach glass or pebbles from a stream, you have witnessed the work of abrasion. 
> Question: Gravity causes erosion by all of the following except Options:(A) glaciers (B) moving air (C) flowing water (D) mass movement 
> Answer: [/INST]"""
> 
> example_encoded = tokenizer(example)
> 
> collator([example_encoded])
> ```
> 
> It returns a dict of `{input_ids, attention_mask, labels}`. You should see that every value o the `labels` tensor is -100 (cross-entropy loss will ignore this value) except for the final one, which encodes the "D".

@BayesRulez I feel that there is something wrong with my code not the principle of what I send as the response template. When I use your code I get the error:
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

but when I comment the collator line and print both of the encoded response template and example I find the ids of the response template in the example. so is it an error that I make in my code when I use the tokenizer?

**Comment by Sosycs** [comment]
@BayesRulez @younesbelkada 🙏
