### ISSUE TITLE
how to setup epoch number in SFTTrainer?

### ISSUE THREAD

**Issue by KlausikPL** [huggingface/trl#985]
there my example code
from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("IMDB", split="train")

trainer = SFTTrainer(
    "sshleifer/tiny-gpt2",
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)
trainer.train()

**Comment by younesbelkada** [comment]
You need to instantiate a new object of `TrainingArguments` and pass `num_train_epochs` to it. Check out for example what is done here: https://github.com/huggingface/trl/blob/main/examples/scripts/sft.py#L113

**Comment by KlausikPL** [comment]
thanks you for help
