### ISSUE TITLE
Support for Pre-Tokenized Datasets in SFTTrainer

### ISSUE THREAD

**Issue by pritishmishra703** [huggingface/trl#991]
**Problem:**

I have a dataset in the following format:

```python
Dataset({
    features: ['input_ids', 'attention_mask'],
    num_rows: 43471
})
```

The dataset is already tokenized, and I would like to skip the tokenization step in SFTTrainer, as it takes a considerable amount of time (approximately 1 hour on my dataset) to encode each time.

**Feature Request:**

I would like to request a feature that allows users to input pre-tokenized datasets directly into the SFTTrainer, bypassing the need for the 'text' column and the subsequent tokenization step. This would significantly improve the training efficiency for users with large datasets.

**Note:**

I am unsure if this feature already exists, so I am reaching out to the community to clarify and request support for pre-tokenized datasets in SFTTrainer. Thank you!

**Comment by tcapelle** [comment]
I think this should work out of the box, or you could just use the `transformers.Trainer` instead of the SFTTrainer.

**Comment by lvwerra** [comment]
The goal of the SFTTrainer as compared to the `transformers.Trainer` is to make that step obsolete. Otherwise you could use as @tcapelle proposed the original trainer.

**Comment by pritishmishra703** [comment]
Thank you for the suggestion. I am now using the 'text' column from the dataset, and I fixed the slow tokenization by setting dataset_num_proc to 5. Now, it's working fine. Thanks.
